### PR TITLE
LPS-169213 objects-rest-impl - use passed object, avoid instance vari…

### PR DESCRIPTION
**Pull request by igorbeslic**
…able that preserves state in an uncontrolled fashion

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by magjed4289** [comment]
Test failures are not related. OK to forward manually. ✅

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:test:stable

**Comment by igorbeslic** [comment]
ci:forward

**Comment by yanan** [comment]
The pull request has been forwarded manually https://github.com/brianchandotcom/liferay-portal/pull/128701, which has been merged already, closing it now.

**Pull request closed without merging**
