### PR TITLE
LPS-196287 Add integration tests for import of instance scoped Object Entries and Object Definition

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Review by sergiojimcos — APPROVED** [review]
LGTM!!

**Comment by yanan** [comment]
The only failed test need to check is:

- com.liferay.batch.planner.batch.engine.broker.test.BatchEngineBrokerTest - [jenkins console](https://testray.liferay.com/reports/production/logs/2023-09/test-1-29/test-portal-acceptance-pullrequest(master)/8260/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
    - Failed tests: testImportObjectDefinition, testImportCompanyScopeObjectEntry
image

image

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:stop

**Pull request closed without merging**
