### PR TITLE
LPD-32102 Technical Task | test-fix random failure in com.liferay.portal.vulcan.internal.jaxrs.lifecycle.test.SafeReleaseInstanceResourceProviderTest

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-32102

### CODE REVIEW

**Comment by magjed4289** [comment]
@ccorreagg not sure if it's the best approach, but we somehow need to wait for the System to get clean before checking there's no instance. Sometimes on CI the assert occurs to fast and the test is flaky

**Comment by magjed4289** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]
See my changes.

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
