### PR TITLE
LPS-173250 Handle collection property in a complex property

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket [LPS-173250](https://issues.liferay.com/browse/LPS-173250)
____
## Purpose of the PR
Before the PR there was no way to filter by a `multipicklist` field of a related object. This PR is to support that case.
The related ticket example is perfect for explaining this behavior.
Now, with the objects and relationships described on the ticket, when a user types this filter
`(studentSubjects/multi/any(k:k eq 'name3')) and (studentSubjects/multi/any(k:k eq 'name4'))` he should receive the subjects of the students that meet this condition.

_IMPORTANT: Note that the filter differs from the filter used in the ticket at the moment of the creation of this PR_

## How to test it
Deploy the following modules:
* portal-vulcan-impl
* object-rest-impl
* Follow the instructions from the ticket except the last one. Instead of that filter, use the filter above.

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
As we talked, maybe it would be a good option to avoid injecting the Filter from Vulcan as we need to include some functionality that are not supported for Search general purposes, as it is just being validated for no reason. We could create another Feature or just including a property to avoid that injection in the current VulcanFeature and in the future, maybe we could create a ContextProvider for injecting the Predicate

**Comment by LuismiBarcos** [comment]
I've created the new feature to include the FilterContextProvider only in the REST Applications that have not disabled it (like Object REST Applications).

Also, before this PR the filter validation was relying on the FilterContextProvider. Without that, it returns a null predicate and all information was returned in the response. To avoid this bad behavior, I include a commit to handle the exceptions property and throw the proper response to the user.

I tried to explain myself in the commits messages.

I am going to update the PR description because the modules to deploy have changed.

**Review by ccorreagg — APPROVED** [review]
Looks great to me now! Really good job. Maybe we should include tests for this functionality in a future pull request

**Comment by ccorreagg** [comment]
Could we push the code from the other `ExpressionVisitorImpl` somewhere? just in case some day it is necessary, to have something to start working from

**Comment by LuismiBarcos** [comment]
> Looks great to me now! Really good job. Maybe we should include tests for this functionality in a future pull request

Yes, I have a pending ticket to add remaining tests to cover this functionality and I added this to the queue.

> Could we push the code from the other ExpressionVisitorImpl somewhere? just in case some day it is necessary, to have something to start working from

hehehe, that code is now in the [aether](https://en.wikipedia.org/wiki/Aether_(classical_element)) 
It wasn't hard to identify. Also, that was never necessary as it is a really complex case that now we need it because of the complexity to search through object relationships. 

However, if you want fell safer having the code in some place, I can search the commit in my commit history and push the code in a branch of this repo but would be a branch that maybe we forget that we have 😅

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by magjed4289** [comment]
ci:forward:force

**Pull request closed without merging**
