### PR TITLE
LPS-189587 Pass the taskItemDelegateName value to the Batch Engine by using a method of the resource instead of injecting it as query parameter

### PR DESCRIPTION
**Pull request by 4lejandrito**
Rebase of https://github.com/brianchandotcom/liferay-portal/pull/137464

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
@ccorreagg the rebase errors were on the last buildREST commit. I rerun it.

**Comment by ccorreagg** [comment]
rebased with master

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Sent to brian to avoid having conflicts again if someone runs restbuilder. 

https://github.com/brianchandotcom/liferay-portal/pull/137894

**Pull request closed without merging**
