### PR TITLE
LPS-167292 Filter ContentElement by key 

### PR DESCRIPTION
**Pull request by torresvictor100**

### CODE REVIEW

**Comment by torresvictor100** [comment]
@yanan I ran the tests and I think that don't have the errors with my PR, you can see the test results: https://testray.liferay.com/home/-/testray/case_results?testrayComponentId =1509069814&testrayBuildId=2040323136

**Comment by ccorreagg** [comment]
Hi @torresvictor100,

I am reviewing the pull request and also the related Jira task but I don't find any context about the need of this filter, so I would like to know which is the use case you are dealing with.

If you just want to filter by the `articleId` of the Journal Articles, maybe you could use the existing endpoint for Structured Contents instead and include there the `key` field to filter, for example by invoking `http://localhost:8080/o/headless-delivery/v1.0/sites/20121/structured-contents?filter=key eq '45729'`.

**Comment by brunofernandezg** [comment]
cc. @natocesarrego

**Comment by torresvictor100** [comment]
Hi @ccorreag actually this API is implemented in http://localhost:8080/o/headless-delivery/v1.0/sites/{siteId}/structured-contents/by-key/{key}, we don't need this PR, Thank you for your help.

**Pull request closed without merging**
