### PR TITLE
Lps 188142 Add tests for scope object for other virtual instance in import/export center

### PR DESCRIPTION
**Pull request by yanan**
Background:
- Add test for scope object for other virtual instance in import/export center

Test Plan
- Given a new virtual instances www.able.com is created
And Given an object definition Student with a custom field is created and published on virtual instance
When create an export task on default instance
Then C_Student is not in the available Entity Type list

Jira Ticket:
- https://liferay.atlassian.net/browse/LPS-188142

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Review by Hijky — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:test:headless-functional:nocompile

**Comment by magjed4289** [comment]
ci:test:sf

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
