### PR TITLE
LPS-118748

### PR DESCRIPTION
**Pull request by petershin**
@nhpatt

### CODE REVIEW

**Comment by petershin** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by jpince** [comment]
ci:close I already forwarded Javi's commit to Brian https://github.com/brianchandotcom/liferay-portal/pull/92449

@petershin thank you, please send your fix directly to Brian.

**Comment by jpince** [comment]
ci:stop

**Comment by jpince** [comment]
ci:stop

**Pull request closed without merging**
