### PR TITLE
LPD-2571 Widget scopes not correctly applied when staging

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-2571

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:staging

**Comment by magjed4289** [comment]
ci:test:headless-staging

**Comment by magjed4289** [comment]
ci:test:headless-staging

**Comment by vendeltoreki** [comment]
@magjed4289 , we saw that page-scoped blog entries got duplicated when activating staging, even when they are not staged. I'm experimenting with this solution to prevent that: https://github.com/vendeltoreki/liferay-portal/compare/master...vendeltoreki:LPD-2571-headless

**Comment by vendeltoreki** [comment]
@magjed4289 , @ccorreagg ,

It seems like the issue is more complex. I looked at these scenarios as well and we should probably fix them to make sure that `getScopeGroupId()` always returns the right result.
1. Create a new site
2. Activate staging (Blogs not staged)
3. Create a new page "testpage" (can be either content or widget)
4. Add blogs portlet, configure it to have "testpage" scope
5. Go to contents, switch to "testpage" scope and add a Blog entry

Result: this blog entry is created in the page scope that belongs to stating. Remember, we did not publish this page yet, so its scope doesn't exist yet in live, where the blog entry should have been actually created.

The main reason is that we have a portlet, that is not staged (its content should only exist on Live), while it has a page scope, that not necessarily exists in live, if the page is not published yet. I think that's the main source of the problems.

Not sure whether this has a simple solution, but there are a lot of cases we have to consider when fixing this.

Btw, I used these queries to check the group and blog records:
```
select cn.value, g.groupKey, g2.groupKey as parentGroup, g.*
from lportal_master.Group_ g
inner join lportal_master.ClassName_ cn on (cn.classNameId = g.classNameId)
left outer join lportal_master.Group_ g2 on (g2.groupId = g.parentGroupId)
order by g.groupId;


select cn.value, g.groupKey, g2.groupKey as parentGroup, b.*
from lportal_master.BlogsEntry b
inner join lportal_master.Group_ g on (g.groupId = b.groupId)
inner join lportal_master.ClassName_ cn on (cn.classNameId = g.classNameId)
left outer join lportal_master.Group_ g2 on (g2.groupId = g.parentGroupId)
order by g.groupId;

```

**Comment by magjed4289** [comment]
ci:test:headless-staging

**Comment by magjed4289** [comment]
thanks to @vendeltoreki guidance and help, the issue on the content page is entirely solved, however, there are still some test cases that fail. we are moving forward though :) 
cc @4lejandrito

**Comment by ericyanLr** [comment]
Hi @magjed4289 ,

Can you clarify what you mean by moving forward? Will the current proposed fix be submitted with test failures or continued to be worked on to resolve the test failures?

**Comment by magjed4289** [comment]
ci:test:staging

**Comment by magjed4289** [comment]
ci:test:headless-staging

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
@ericyanLr, I have submitted another version of the commit that covers all the test cases. The PR still needs to pass the review and staging test execution analysis.

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:reopen

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:forward:force

**Pull request closed without merging**
