### PR TITLE
LPS-204596 check latest non-expired article, to make assetentry visible

### PR DESCRIPTION
**Pull request by GaborKomaromi**
Hi Team,

Could you please review this pull request?
https://liferay.atlassian.net/browse/LPS-204596
Thank you!

------

**Reproduction Steps:**

1. Add an Asset Publish to the Home page and configure Asset Selection to Dynamic
2. Create a Web Content: MyWC
3. Enable Local Staging
4. Assert that MyWC is visible in both Staging and Live
5. Edit MyWC again in order to to create a newer version of it
6. Go to Version history and expire version 1.0. Version 1.1 is still approved.
7. Go to Publishing > Staging and perform a new Publish Process

**Expected**
MyWC is still visible in the Home page in both Staging and Live

**Actual**
MyWC is not visible anymore in Live site

**Solution:**
As AssetEntry was updated on every version's iteration, I checked if there is any non-expired version, and updated the visible status.

### CODE REVIEW

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
Hey @GaborKomaromi can we write an integration tests for this?

**Comment by GaborKomaromi** [comment]
Hi @4lejandrito,
I reverted the previous changes and created a new solution.

**Comment by GaborKomaromi** [comment]
ci:test:sf

**Comment by GaborKomaromi** [comment]
ci:test:sf

**Comment by GaborKomaromi** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hey @GaborKomaromi we need an integration test for every bug. After that we will send it for review to the echo team.

**Comment by 4lejandrito** [comment]
I will send this to echo for review in the meantime. But @GaborKomaromi please try to write the test when you have time.

**Comment by vendeltoreki** [comment]
Closing this PR, Echo's solution submitted on https://github.com/liferay-echo/liferay-portal/pull/15048

**Pull request closed without merging**
