### PR TITLE
LPS-166102 Adding support for objects in resourceLocator

### PR DESCRIPTION
**Pull request by 4lejandrito**
This adds support for objects in the resourceLocator. Now inside a template we can do:

```
<#assign
    objectResource = resourceLocator.locate("/c/universities", "University")
/>

${objectResource.getObjectEntriesPage(false, null, null, null, null, null)}
```

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
LGTM 👏 👏 👏 
Sorry but I have to say it 😅 
Reviewing this, I found more reasons for the HTTP solution: Anything that we add to the context for `ObjectEntryResourceImpl` must be added in the `ObjectEntryResourceFactoryImpl` (as you did for the `_objectDefinition`) and is something that we could forget easily.

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/125031

**Pull request closed without merging**
