### PR TITLE
LPS-203406 Add Suppliers for each field of the REST API DTOs to postpone the time when the field is set with a value. That happens when deserializing the element by Jackson or calling the getter method

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-203406

---

The purpose of this PR is to optimize the performance of the queries to the REST APIs & GraphQL, based on the `fields` & `restrictFields` query parameter.

For that, we have included in each REST API DTO generated by REST Builder a **private Supplier** that will be filled when the setter method is called with the UnsafeSupplier argument, and it will be executed when the getter method of the field is called. 

With that, we ensure that the code to get the value is only executed when it is needed if the supplier was provided. Once the getter method has been called once, the value is kept in the protected attribute. Jackson will call the getter method by default or if the user included the field based on the `fields` & `restrictFields` values. Whoever that needs the value, it will call the getter method and then, once the field is calculated, it will keep stored in the already existing protected attribute.

That change should not break anything.

Furthermore, the `UserResourceDTOConverter` has been updated, and now all the fields are filled with the `public void set<FieldName>(UnsafeSupplier<<FieldName>[], Exception> <fieldName>UnsafeSupplier)` method in order to avoid getting all the information of the UserAccount if it is not needed.

**TODO**: The idea is to modify the existing `InstanceInitializerCheck` SF rule to force the usage of the setter method with the UnsafeSupplier to improve the performance in every REST API. For that, we will create a new ticket and once it is completed, we will remove the `source-formatter-suppressions.xml` file added in this PR.

---

**Performance tests:**

We have executed some performance tests to check if this change will improve the response time. For that, we have created 500 users in Liferay and we have executed a query to get all the 500 users in the same request without selecting any field (all the fields by default), selecting only 1 field and selecting several fields.

**The results:**

```
curl -X GET -u test@liferay.com:test 'http://localhost:8080/o/headless-admin-user/v1.0/user-accounts?page=-1&pageSize=-1' -o /dev/null -s -w '%{time_total}\n'

** Without filtering fields **
	[1]: 1.310281s
	[2]: 1.127488s
	[3]: 1.075631s
	[4]: 1.204688s
	[5]: 1.043081s
	[6]: 1.017495s
	[7]: 1.000586s
	[8]: 1.062090s
	[9]: 1.099078s
	[10]: 1.011901s
	Avg: 1.0952
```
```
curl -X GET -u test@liferay.com:test 'http://localhost:8080/o/headless-admin-user/v1.0/user-accounts?page=-1&pageSize=-1&fields=id' -o /dev/null -s -w '%{time_total}\n'

** Filtering fields "id" **
	[1]: 0.777610s
	[2]: 0.762412s
	[3]: 0.761128s
	[4]: 0.813661s
	[5]: 0.787481s
	[6]: 0.758365s
	[7]: 0.760169s
	[8]: 0.764353s
	[9]: 0.764770s
	[10]: 0.747721s
	Avg: .7697
```
```
curl -X GET -u test@liferay.com:test 'http://localhost:8080/o/headless-admin-user/v1.0/user-accounts?page=-1&pageSize=-1&fields=additionalName,alternateName,birthDate,dateCreated,emailAddress,familyName,givenName,honorificSuffix,id,image,jobTitle,lastLoginDate,name,roleBriefs' -o /dev/null -s -w '%{time_total}\n'

** Filtering fields "additionalName,alternateName,birthDate,dateCreated,emailAddress,familyName,givenName,honorificSuffix,id,image,jobTitle,lastLoginDate,name,roleBriefs" **
	[1]: 0.768381s
	[2]: 0.809922s
	[3]: 0.772106s
	[4]: 0.791283s
	[5]: 0.783709s
	[6]: 0.778566s
	[7]: 0.940062s
	[8]: 0.988800s
	[9]: 0.988025s
	[10]: 0.915561s
	Avg: .8536
```

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Failures are not related https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2476997516&testrayRunIdA=2476834937&statusB=2
- senmaticVersioningTest caused by other pr
- other failures are also happen on Development master, and one if not start to run because of host problem

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:test:stable

**Comment by ccorreagg** [comment]
Executed buildREST again

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
