### PR TITLE
LPS-197582: RestBuilder doesn't create a body with Content-Type is 0 when there is no body

### PR DESCRIPTION
**Pull request by sergiojimcos**
## Motivation
The aim of this PR is to set Content Length equal to 0 for all the methods that have several several parameter but it doesn't have any Request Schema or no request body.

**What is new?**
- Define an empty List in the `client_resource.ftl`.
- buildREST in all modules.

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPS-197582

### CODE REVIEW

**Comment by 4lejandrito** [comment]
I am not sure if failures may be related... @sergiojimcos can you check with QA?

**Comment by magjed4289** [comment]
Test failures are not related, OK to manually forward ✅

**Comment by sergiojimcos** [comment]
ci:forward:force

**Comment by sergiojimcos** [comment]
Sent to Brian here: https://github.com/brianchandotcom/liferay-portal/pull/141551

**Pull request closed without merging**
