### PR TITLE
LPS-193318 Remove checkPermission handling condition

### PR DESCRIPTION
**Pull request by matijapetanjek**
Please check the [task description](https://liferay.atlassian.net/browse/LPS-193318) for the right context. This obviously isn't a high priority but if we can keep the code cleaner I'm always for it. If this condition is put only to handle a case where a developer forgets to put checkPermissions=false I would remove it, otherwise we can close this PR

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Failures are not related to the pr from qa perspective.

**Comment by 4lejandrito** [comment]
Hey @matijapetanjek we cannot do this because it would break https://liferay.atlassian.net/browse/LPS-190450. We need to disable permission checking for multicompany scenarios because otherwise permission checking will crash. @ccorreagg can give you more context.

**Pull request closed without merging**
