### PR TITLE
LPS-161981

### PR DESCRIPTION
**Pull request by Hijky**
Background:
 Update a testcase to add case about select item actions as field to export with JSONT

Test Plan
CanSelectItemActionsAsFieldToExportWithJSONT
Given Stock object definition created
And Given Stock entries created
When in Import/Export: Export File selected as Entity Type C_Stock (v1_0 - Liferay Object REST) in Export File Format: JSONT
Then actions field is visible to select on the list of fields to include in the export file

Jira ticket:
https://liferay.atlassian.net/browse/LPS-188127

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:headless-functional:nocompile

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:headless-functional:nocompile

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:test:headless-functional:nocompile

**Comment by magjed4289** [comment]
ci:test:headless-functional:nocompile

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
