### PR TITLE
LPD-39011 Add expected externalReferenceCode for the creator to fix failing test

### PR DESCRIPTION
**Pull request by albertojml**
Test is failing since the externalReferenceCode was incorporated to the creator entity in [LPD-32160](https://liferay.atlassian.net/browse/LPD-32160).

This PR adds the missing ERC to fix the test.

See the following Jira ticket: [LPD-39011](https://liferay.atlassian.net/browse/LPD-39011)

### CODE REVIEW

**Comment by albertojml** [comment]
ci:test:relevant

**Comment by albertojml** [comment]
ci:test:headless-playwright

**Review by jaimelr10 — APPROVED** [review]
LGTM!

**Comment by jaimelr10** [comment]
The tests is passing!
image

**Pull request closed without merging**
