### PR TITLE
LPS-175904 Headless API returns [Bad Request Error] when friendlyUrl includes "/"

### PR DESCRIPTION
**Pull request by 4lejandrito**
- Initial solution to allow `/` in path parameters. It is automatic and is only applied to parameters that end with `Path`.
- We should consider applying the OpenAPI `pattern` attribute as described in https://swagger.io/docs/specification/data-models/data-types/. But this would force developers to explicitly add it to their OpenAPI files.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@ruben-pulido can you please test and review?

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
no test failures related to the PR. OK to manually forward ✅

**Comment by magjed4289** [comment]
ci:forward:force

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:close

**Comment by magjed4289** [comment]
ci:reopen

**Comment by ruben-pulido** [comment]
Follow up PR sent [here](https://github.com/liferay-headless/liferay-portal/pull/1089)

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-headless/liferay-portal/pull/1089.

**Pull request closed without merging**
