### PR TITLE
LPS-171970 Update testcase to rename the case name

### PR DESCRIPTION
**Pull request by Hijky**
**Background**
Test Fix to remove typos

**Test Plan**
typo in test names:
GraphQLAPIsExplorer#disableApiEplorer
GraphQLAPIsExplorer#enableApiEplorer

Change to:
GraphQLAPIsExplorer#disableApiExplorer
GraphQLAPIsExplorer#enableApiExplorer

**JIRA Link:**
https://issues.liferay.com/browse/LPS-171970

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:relevant

**Comment by Hijky** [comment]
ci:test:headless-functional

**Review by yanan — APPROVED** [review]

**Comment by Hijky** [comment]
ci:test:headless-functional:nocompile

**Comment by Hijky** [comment]
@magjed4289  @yanan I checked the [Jenkins report](https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/6003/jenkins-report.html) the failures are not related to my PR.

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
