### PR TITLE
LRQA-81533 | Test Fix for ImportExport#GetExportFileAvailableEntityTypes

### PR DESCRIPTION
**Pull request by Hijky**
Background:
Test Fix for ImportExport#GetExportFileAvailableEntityTypes

Jira ticket:
https://liferay.atlassian.net/browse/LRQA-81533

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:headless-functional:nocompile

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:headless-functional:nocompile

**Review by magjed4289 — APPROVED** [review]

**Comment by Hijky** [comment]
The failures are not related to PR.

**Review by yanan — APPROVED** [review]

**Comment by Hijky** [comment]
ci:forward

**Pull request closed without merging**
