### PR TITLE
LPS-162878: Expose permissions for individual object entries

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Add GET and PUT permission endpoints in `rest-openapi.yaml`.
- Update condition in `ObjectDefinitionDeployer` to deploy permissions endpoints for scoped Objects.
- Implement `getPermissionChekerGroupId` and `getPermissionCheckerResourceName` methods.

**NEW ENDPOINTS**
image

**RESPONSE FROM A GET AND PUT REQUEST**
```
{
  "actions": {
    "get": {
      "method": "GET",
      "href": "http://localhost:8080/o/c/testobjects/46735/permissions"
    },
    "replace": {
      "method": "PUT",
      "href": "http://localhost:8080/o/c/testobjects/46735/permissions"
    }
  },
  "facets": [],
  "items": [
    {
      "actionIds": [
        "DELETE",
        "PERMISSIONS",
        "UPDATE",
        "VIEW"
      ],
      "roleName": "Owner"
    },
    {
      "actionIds": [
        "DELETE",
        "PERMISSIONS"
      ],
      "roleName": "Power User"
    }
  ],
  "lastPage": 1,
  "page": 1,
  "pageSize": 2,
  "totalCount": 2
}
```

**How to Reproduce it:**
- Deploy `object-rest-api` and `object-rest-impl`

**JIRA TICKET**
https://issues.liferay.com/browse/LPS-162878

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Review by ccorreagg — APPROVED** [review]
Well done!

**Review by 4lejandrito — APPROVED** [review]

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) 👏 👏 👏

**Comment by sergiojimcos** [comment]
ci:forward

**Pull request closed without merging**
