### PR TITLE
LPS-200643 Create feature flag LPS-174455

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-200231

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
I think you need to run SF to get the FF into portal.properties.

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:sf

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by Hijky** [comment]
The failures are not related to your PR, it's okay to forward.

**Comment by ccorreagg** [comment]
Sent here https://github.com/brianchandotcom/liferay-portal/pull/143188

**Pull request closed without merging**
