### PR TITLE
LPD-39231 [headless] Review PR "Allow using directive script-src-attr 'none' by removing inline handlers"

### PR DESCRIPTION
**Pull request by izaera**
Comes from https://github.com/liferay-frontend/liferay-portal/pull/4476

Please refer to both https://liferay.atlassian.net/browse/LPD-39123 and https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/pages/3245277533/LPD-36188+-+Allow+using+directive+script-src-attr+none+by+removing+inline+handlers to find out the motivation for this PR.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@vendeltoreki @DaniSzimko can you review this?

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Manual checks:
* OK - modules/apps/export-import/export-import-web/src/main/resources/META-INF/resources/export/processes_list/export_layouts_processes.jsp
* OK - modules/apps/export-import/export-import-web/src/main/resources/META-INF/resources/export_import_process.jsp
* OK - modules/apps/staging/staging-bar-web/src/main/resources/META-INF/resources/merge_layout_set_branch.jsp
* OK - modules/apps/staging/staging-bar-web/src/main/resources/META-INF/resources/view_layout_revisions.jsp

**Review by vendeltoreki — APPROVED** [review]

**Comment by vendeltoreki** [comment]
ci:forward:force

**Pull request closed without merging**
