### PR TITLE
LPD-24967: Review & adapt tests using hard-coded test password - integration and POSHI tests

### PR DESCRIPTION
**Pull request by sergiojimcos**
**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPD-24967

### CODE REVIEW

**Comment by sergiojimcos** [comment]
Errors rebased from: https://github.com/liferay-headless/liferay-portal/pull/2016

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by albertojml — APPROVED** [review]
LGTM!

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
Sent to Brian here: https://github.com/brianchandotcom/liferay-portal/pull/150561

**Pull request closed without merging**
