### PR TITLE
LPS-0101 | Automation - Edit an API Application Schema

### PR DESCRIPTION
**Pull request by pedroamarall**
Ticket:
[LPS-197392](https://liferay.atlassian.net/browse/LPS-197392)

Previous pull requests:
[#1682](https://github.com/liferay-headless/liferay-portal/pull/1682)

### CODE REVIEW

**Comment by pedroamarall** [comment]
Hey @magjed4289 Can I forward this pr?
I updated from [here](https://github.com/liferay-headless/liferay-portal/pull/1682#issuecomment-1838247615) with the changes

**Comment by yanan** [comment]
ci:test:headless-builder-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-builder:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
@pedroamarall Thanks for the codes, you can check the commits for the updates I have made including remove duplicate path, thanks again!

**Comment by yanan** [comment]
Test failures are not related

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
