### PR TITLE
LPS-204572 Use set(UnsafeSupplier) method when creating the REST API DTOs to use them only when the user requires the field the first time

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-204572

---

it contains the code of the `LPS-204572` with the source format changes of the `LPS-204735`.

The purpose of this PR is to extend the usage of the `set<Field>(UnsafeSupplier)` method of all REST API DTOs in order to avoid calculating all the fields even though it is possible the user does not require the fields (by using the query parameters `fields` or `restrictFields`).

As in the Objects REST API, a map of properties is used, the modfiication in the setter method of the Map has not been perforrmed yet, as it will be done in a future story, as it is more complex.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by ccorreagg** [comment]
There is a pending test to add from FormatSource team

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by yanan** [comment]
Failure in **sf** is about commit message should not start with whitespace in 6d0373c8b65bf7ef91583d28e3d2255533a42f7b
Failure in **relevant** are not related, here are the [compare run results and more details](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2487149528&testrayRunIdA=2487131938&statusB=2)
- most are not start to run on CI
- the following ones are flaky since they passed locally on an ant all bundle of this pr
    - [LocalFile.CreateNewGETEndpointThatRetrieveSingleEntry#CanSeeGetEndpointPathWithIdParameterInAPIExplorer](https://testray.liferay.com/home/-/testray/case_results/2487132868)
    - [LocalFile.ExposeQueryParametersInAPIExplorerForGeneratedAPI#CanSeeFilterAndSortParametersInComapnyScopedEndpoint](https://testray.liferay.com/home/-/testray/case_results/2487132872)
    - [LocalFile.GeneratePathStructureForEndpoints#CanValidatePathInAPIEndpoint](https://testray.liferay.com/home/-/testray/case_results/2487136215)
    - [LocalFile.AllowUsersToDefinePrefilters#CanApplyPrefilterAndFilter](https://testray.liferay.com/home/-/testray/case_results/2487132864)
    - [LocalFile.AllowUsersToDefineSorts#SortingAndSortParameterReturnTheSameData](https://testray.liferay.com/home/-/testray/case_results/2487132876)

**Comment by ccorreagg** [comment]
> @ccorreagg see commits below:
> 
> ```
> ...
> c884428a22a0d3c778110cb23b33dc23eeba3510 2024-01-11 LPS-204572 Use the proper class to avoid compilation problems, we should use String instead of Object and avoid using an array, we have to pass the item class
> ffa0d285f1076446ee38583022a7ad07fff06243 2024-01-11  LPS-204572 Rest-builder - Make it extends the class as in the TransformUtil class. If the TransformUtil version is older, it still compiles, so it is not a breaking change
> f3e91167217ba9d22bf8c4cbfd41a4c2ddd0dafa 2024-01-11 LPS-204572 Make it extends the class to avoid execution problem when creating the array of elements if the TransformUtil method has been invoked from an inline initializer
> ...
> ```
> 
> But I don't understand why ci showed `6d0373c8b65bf7ef91583d28e3d2255533a42f7b` instead of [ffa0d28](https://github.com/liferay-headless/liferay-portal/commit/ffa0d285f1076446ee38583022a7ad07fff06243), @qz1010 Can you look into it? Thanks @yanan

Oohhhh, I was checking the commit messages by using the `git rebase -i master` command and didn't show the space at the beginning: :facepalm: 

image

Thank you for your help. However as you said, that SHA is not the right one as I wasn't able to find it in the whole PR. I guess it is the new one once the PR is rebased with master by the CI

**Comment by ccorreagg** [comment]
Fixed commit message and rebased with master

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
SF fixes are on the way here: https://github.com/brianchandotcom/liferay-portal/pull/146161 and https://github.com/brianchandotcom/liferay-portal/pull/146181

**Comment by ccorreagg** [comment]
Sent [here](https://github.com/brianchandotcom/liferay-portal/pull/146184). Thank you guys for your help

**Pull request closed without merging**
