### PR TITLE
LPS-189587 Pass the taskItemDelegateName value to the Batch Engine by using a method of the resource instead of injecting it as query parameter

### PR DESCRIPTION
**Pull request by ccorreagg**
Related issue: https://liferay.atlassian.net/browse/LPS-189587

The purpose of this PR is to remove the injection of the `taskItemDelegateName` attribute as query parameter that is performed in the class `ObjectDefinitionIdContainerRequestFilter` and inject it via a resource method.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Review by matijapetanjek — APPROVED** [review]
I am affraid to ask how is this curl

> curl -X 'GET' \
  'http://localhost:8080/o/c/students/scopes/my%20site' \
  -H 'accept: application/json' \
  -u 'test@liferay.com:test'
related to batch engine task item delegate name.

**Comment by ccorreagg** [comment]
Forwarded manually to Brian. See https://github.com/brianchandotcom/liferay-portal/pull/137325

**Pull request closed without merging**
