### PR TITLE
LPS-169912 Only allow operations over an active related Object Definition

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to fix this bug: https://issues.liferay.com/browse/LPS-169912

New validations have been included to avoid inactive related Object Definition. That will avoid the following use cases for inactive Object Definitions:

- Getting the related entries of a System Object that belongs to an inactive Object Definition
- Relate a System Object Entry to a Custom Object whose Object Definition is inactive
- Unrelate a System Object Entry to a Custom Object whose Object Definition is inactive
- Include in the System Object Definition's OpenAPI the endpoints and the schema of the relationships with an inactive Object Definition.
- Include in the System Object Entries returned the related Object Entries if the related Object Definition is inactive

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) 👏 👏 👏 👏

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:forward

**Comment by magjed4289** [comment]
Test failures not related. OK to manually forward. 🌵

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
