### PR TITLE
LPS-167508 Use new instance tables instead of getting the tables from objectFields.

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Fix wrong behavior when the title field is not set manually to a custom field. Tested for custom objects and for many-to-many relationships (both sides) and one-to-many relationships.

More information about how to test it in the related PR -> https://github.com/liferay-headless/liferay-portal/pull/908

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
@ccorreagg I marked you as a reviewer just in case but we have talked about this in the meeting.

I also think that we can create a Base class as you said. I will create a LPS and do it. I don't want to do it in this PR because we are in a hurry to send this and I prefer to unblock other teams and then make the refactor to avoid duplicate code.
Also, as I am working on [the tests](https://github.com/liferay-headless/liferay-portal/pull/937) for this functionality. I think it will be safer to work on the refactor once the tests are ready.

**Review by ccorreagg — APPROVED** [review]
LGTM!

**Comment by ccorreagg** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
Errors don't seem related. Manually forwarded here https://github.com/brianchandotcom/liferay-portal/pull/128050

**Comment by magjed4289** [comment]
ci:reopen

**Comment by magjed4289** [comment]
ci:close

**Pull request closed without merging**
