### PR TITLE
LPS-163446: Inconsistency between the REST APIs and the UI using permissions

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Add new method `getResourcePermissionsByResourceName` that retrieves all Permissions give a `resourceName`, `roleName` and `EntityId`
- Changes in `base_resource_impl.ftl` adding new method `ToPermissionPage`
- Update all `BaseResourceImpls`.

**Note:** This PR also fix another inconsistency, when we retrieved all the Permissions given a `roleName`, it returned all Permissions of all the entities created.

**JIRA Tickets**
https://issues.liferay.com/browse/LPS-163446
https://issues.liferay.com/browse/LPS-162878

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Review by LuismiBarcos — APPROVED** [review]

**Comment by sergiojimcos** [comment]
Rebased with master

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
Rebase with master and baseline

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by yanan** [comment]
Tests failures are unrelated. Here is the [compare run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2017733019&testrayRunIdA=2015982916&statusB=3) results:

Flaky integration tests - exsiting ticket 
- com.liferay.headless.delivery.resource.v1_0.test.DocumentFolderResourceTest
- com.liferay.headless.delivery.resource.v1_0.test.KnowledgeBaseArticleResourceTest

Flaky functional test - test passed locally with a ant all bundle under this pr
- LocalFile.ObjectPortlet#CannotViewOtherUsersEntryWithOnlyAddPermission

**Comment by sergiojimcos** [comment]
Manual forwarding to Brian: https://github.com/brianchandotcom/liferay-portal/pull/125266

**Pull request closed without merging**
