### PR TITLE
[TS] LPS-180389 Continue so we don't overwrite our custom field entry

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-180389

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test

**Comment by 4lejandrito** [comment]
Hi @ChrisKian,

We have 5 other classes that perform the same function. Can you check if this bug could be happening also in those?

```
git ls-files -- "*CustomFieldsUtil*"
```

Thanks!

**Comment by ChrisKian** [comment]
Sure thing @4lejandrito,
 
For the first [CustomFieldsUtil](https://github.com/liferay/liferay-portal/blob/master/modules/apps/headless/headless-delivery/headless-delivery-api/src/main/java/com/liferay/headless/delivery/dto/v1_0/util/CustomFieldsUtil.java) class, we're good [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/headless/headless-delivery/headless-delivery-api/src/main/java/com/liferay/headless/delivery/dto/v1_0/util/CustomFieldsUtil.java#L134-L142) due to the `if/else if` logic.

In [this class](https://github.com/liferay/liferay-portal/blob/master/modules/apps/headless/headless-admin-content/headless-admin-content-impl/src/main/java/com/liferay/headless/admin/content/internal/dto/v1_0/util/CustomFieldsUtil.java) we [directly return the map](https://github.com/liferay/liferay-portal/blob/master/modules/apps/headless/headless-admin-content/headless-admin-content-impl/src/main/java/com/liferay/headless/admin/content/internal/dto/v1_0/util/CustomFieldsUtil.java#L79-L83).

Another [direct return here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-order-impl/src/main/java/com/liferay/headless/commerce/admin/order/internal/dto/v1_0/util/CustomFieldsUtil.java#L154-L155) for [the third class](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-order-impl/src/main/java/com/liferay/headless/commerce/admin/order/internal/dto/v1_0/util/CustomFieldsUtil.java).

Direct return [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/dto/v1_0/util/CustomFieldsUtil.java#L116-L120) and [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/dto/v1_0/util/CustomFieldsUtil.java#L186-L189) for [this class](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-catalog-impl/src/main/java/com/liferay/headless/commerce/admin/catalog/internal/dto/v1_0/util/CustomFieldsUtil.java).

And same for [the final class](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-shipment-impl/src/main/java/com/liferay/headless/commerce/admin/shipment/internal/dto/v1_0/util/CustomFieldsUtil.java), [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-shipment-impl/src/main/java/com/liferay/headless/commerce/admin/shipment/internal/dto/v1_0/util/CustomFieldsUtil.java#L146-L149) and [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-shipment-impl/src/main/java/com/liferay/headless/commerce/admin/shipment/internal/dto/v1_0/util/CustomFieldsUtil.java#L169-L173).

So it looks like we only have the one location to fix.  Please let me know if there is anything else I can help with.

**Comment by 4lejandrito** [comment]
Thanks @ChrisKian. I've created https://issues.liferay.com/browse/LPS-180596 to eventually unify those classes into a single one if possible. But for now this fix is good to go!

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
