### PR TITLE
Using openapitools/openapi-generator-cli for client JS generation

### PR DESCRIPTION
**Pull request by dannielraposo**
@4lejandrito

### CODE REVIEW

**Comment by dannielraposo** [comment]
ci:test:playwright

**Comment by dannielraposo** [comment]
ci:test:help

**Comment by dannielraposo** [comment]
ci:test:playwright

**Comment by ccorreagg** [comment]
ci:test:playwright

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-headless/liferay-portal/pull/2344.

**Pull request closed without merging**
