### PR TITLE
LPS-188999 Using local TransformUtil to fix compatibilityVersions < 2

### PR DESCRIPTION
**Pull request by 4lejandrito**
See https://liferay.atlassian.net/browse/LPS-188999. 

I have copy pasted the whole TransformUtil as a local class. We can probably remove some methods that are not being used.

I've tested this by setting `compatibilityVersion: 0` locally in `headless-site-impl` (could have been any other rest module) and it compiles and works fine (both code and tests). 

Running buildREST in master should not generate any changes since we already have `compatibilityVersion: 2` everywhere.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Test failures are not related, ok to forward manually

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
