### PR TITLE
LPS-189713 Multi company batch units

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPS-189713.

This PR adds support for multi company batch units and applies it to API Builder. This means the object definitions of API Builder will be added to every company, present and future.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Review by matijapetanjek — COMMENTED** [review]
@4lejandrito I'm just sharing my view/understanding of this story:
API Builder uses Objects to create its own persistence model. API Builder should be available for each LR virtual instance. Obviously, we don't want to upload the same Object definition each time a new virtual instance is created and it should be automatized.

The first thing that came to my mind is that will be handled by the Objects framework. I would expect that `ObjectDefinition.scope` can be reused (if not, add new "multiCompany" boolean column) to indicate Objects should be created across all companies.
 `CompanyModelListener#onAfterCreate` would handle newly created companies.

So far, if you wanted to use batch engine to create multi-company data, import file should contain multiple records with different companyId values.
On the other hand, I might not be aware of all the requirements for this story and the limitations of the Objects framework.

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
As discussed internally we will be using this solution until objects implements native support as described by @matijapetanjek.

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/137441

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/137486

**Pull request closed without merging**
