### PR TITLE
LPS-186907: Add validation for http method + path  and must be related whith a APIApplication of an APIEndpoint 

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Create `APIEndpointObjectEntryModelListener` to trigger when a APIEndpoint is going to be created or updated, establishin two validations:

1. The `path` value should be correct
2. The combination of a `httpMethod` and `path` from an Endpoint should be unique in every `APIApplication`.
3. Every APIEndpoint must be related with a APIApplication

- Create some tests cases for APIApplication and APIEndpoint

**How to reproduce it?**

- Deploy `headless-builder-impl`.

**Related JIRA Ticket**
https://liferay.atlassian.net/browse/LPS-186907
https://liferay.atlassian.net/browse/LPS-186913

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
c:stop

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
https://github.com/liferay-headless/liferay-portal/pull/1298

**Pull request closed without merging**
