### PR TITLE
LPS-163262 Unable to parse csv file with field has multiple lines or attachement field during import in import/export center

### PR DESCRIPTION
**Pull request by tototrinh**
Hi guys,
Please help review this PR and leave your comments. Thanks.
Ticket: https://issues.liferay.com/browse/LPS-163262
cc: @ces-huynguyen

### CODE REVIEW

**Comment by tototrinh** [comment]
ci:test:sf

**Comment by tototrinh** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
@tototrinh please if it is possible can you consult us in SLACK t-dxp-headless channel before fixing code. Your work fixes code that we want to delete. Also, even after fixing intermediate UI panel import process does not import aggregated Attachment because importing aggregated objects is not supported if you use CSV. Basically this is not even issue.
I reached PM and our QA representative to see how we can improve communication and collaboration to avoid unnecessary work.
Thank you very much for contribution, I'll forward it for merge, but it is pretty sure that we will remove intermediate UI panel.

**Comment by igorbeslic** [comment]
ci:forward

**Comment by tototrinh** [comment]
@igorbeslic Thank you for your information.

**Pull request closed without merging**
