### PR TITLE
LPD-15576 Use *Service instead of *LocalService

### PR DESCRIPTION
**Pull request by vendeltoreki**
Forwarding from: https://github.com/liferay-headless/liferay-portal/pull/1839

See details: [LPD-15576](https://liferay.atlassian.net/browse/LPD-15576) and [LPD-15802](https://liferay.atlassian.net/browse/LPD-15802)

### CODE REVIEW

**Review by sergiojimcos — APPROVED** [review]
LGTM!!

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-headless/liferay-portal/pull/1861.

**Pull request closed without merging**
