### PR TITLE
LPS-191031: Create new validations for APIProperty and APISchema

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Create new `APIPropertyRelevantModelListener` to add some validations about related `APISchema` and `ObjectFieldERC` property must belong to its `schemaId`.
- Add new validation in `APISchema` where an `Object Definition ERC` must belong to a valid Object Definition.
- Add ObjectDefintionTestUtil for further use in API Builder tests
- Add some test cases to cover this new validations

**NOTE** I think that this PR is not going to pass SF due to there are some changes in the SF rules

**How to deploy it?**
- Deploy `headless-builder-api`
- Deploy `headless-builder-impl`

**JIRA Related Tickets**
https://liferay.atlassian.net/browse/LPS-191031

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Review by 4lejandrito — APPROVED** [review]

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
Possible related failing tests:
* com.liferay.headless.builder.model.listener.test.APISortRelevantObjectEntryModelListenerTest.test
* com.liferay.headless.builder.model.listener.test.APIFilterRelevantObjectEntryModelListenerTest.test

I will take a look

**Comment by LuismiBarcos** [comment]
These tests are failing because they are broken. They are fixed in this PR https://github.com/brianchandotcom/liferay-portal/pull/138397.

Thanks to @yanan to notice this 🙂

**Comment by LuismiBarcos** [comment]
ci:forward:force

**Pull request closed without merging**
