### PR TITLE
LPS-188951 Fixing test by using a valid hostname

### PR DESCRIPTION
**Pull request by 4lejandrito**
The issue is that "myhost" was being rejected by this function:

https://github.com/liferay/liferay-portal/blob/a0adbd0ee3089689565155be61dc8caf47896b5e/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L5977

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
@magjed4289 can you check if the test fixed in this PR (`com.liferay.portal.vulcan.internal.test.ReverseProxyTest`) passed in CI?

**Review by matijapetanjek — APPROVED** [review]
LGMT!

**Comment by magjed4289** [comment]
@4lejandrito the mentioned test passed 
image
Will check if any other failures related now

**Comment by magjed4289** [comment]
No test failures are related to the PR. OK to manually forward ✅

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
