### PR TITLE
LPD-37732 Technical Task | Move tests of object-rest-test to the Headless team

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-37732

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:headless

**Comment by 4lejandrito** [comment]
Hey @magjed4289 these tests were already in our headless suite, right? Why do we need this?

**Comment by magjed4289** [comment]
> Hey @magjed4289 these tests were already in our headless suite, right? Why do we need this?
Right now in Testray these test appear under the team [Business Process Management](https://testray.liferay.com/#/project/35392/routines/994140/build/34794456/case-result/34798862), what we want is to have them in Headless team. Especially having in mind that team suites will be dissappearing soon and we will filter by team when reviewing the global suite.

**Comment by magjed4289** [comment]
headless build running here: https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6849/jenkins-report.html

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:headless

**Comment by magjed4289** [comment]
ci:test:object

**Comment by magjed4289** [comment]
ci:test:object

**Pull request closed without merging**
