### PR TITLE
LPS-175919 Add more tests on open API profile

### PR DESCRIPTION
**Pull request by yanan**
**Background:**
- Add more tests for system APIs in open api profile

**Test Plan:**
- When with get request to retrieve /o/openapi/openapi.json
Then I can see details of all the APIs in the system
- Given navigate to /o/openapi/openapi.json endpoint
When executing HeadlessAdminWorkflow.v1.0.getOpenAPI
Then the shown response code is 200

**Jira Ticket:**
- https://issues.liferay.com/browse/LPS-175919

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
Test failures are unrelated.

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
test failures are not related so I will forward it :)

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
