### PR TITLE
LPS-198510 Prevent ConcurrentModificationException by creating copies of entrySets

### PR DESCRIPTION
**Pull request by jalber786**
What's changed?:
- Both deploy and undeploy methods from the ObjectDefinitionLocalService now use a copy of the same EntrySet in order to prevent the concurrent modification exception by accessing the same reference

See the following **Jira ticket**: [LPS-198510](https://liferay.atlassian.net/browse/LPS-198510)

### CODE REVIEW

**Comment by jalber786** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:forward

**Comment by jalber786** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by jalber786** [comment]
Closing it because the original bug is no longer reproducible.

**Pull request closed without merging**
