### PR TITLE
LPS-184145 Review and fix usages of ObjectDefinition#isSystem

### PR DESCRIPTION
**Pull request by 4lejandrito**
`isSystem` now includes the special custom objects that are provided out of the box. To check for servicebuilder system objects we must check for `isUnmodifiableSystem`. Some places in headless code had not been properly migrated.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
@LuismiBarcos, @ccorreagg can you check if there are more?

**Comment by ccorreagg** [comment]
I guess you are just modifying the usages in the object-rest* modules, right?

I see other usages but in the service modules

https://github.com/liferay/liferay-portal/blob/92ed961a116e46728bf82adce63bb270d5e215e6/modules/apps/object/object-service/src/main/java/com/liferay/object/internal/notification/term/contributor/ObjectDefinitionNotificationTermEvaluator.java#L214

https://github.com/liferay/liferay-portal/blob/92ed961a116e46728bf82adce63bb270d5e215e6/modules/apps/object/object-service/src/main/java/com/liferay/object/internal/notification/term/contributor/ObjectDefinitionNotificationTermEvaluator.java#L299

**Comment by 4lejandrito** [comment]
Yeah but I don't know if those are right... I sent this PR link to @gabrielwas so they review those.

**Comment by ccorreagg** [comment]
Ok, it seems it should be changed but great if they will review it

**Comment by gabrielwas** [comment]
@guilhermedcamacho could you take a look at this PR, please? These are some cases of wrong usages of `isSystem` checking (some leftovers). 

We need to check all the `isSystem` usages. Could you coordinate this with the Alpha squad? Thx!

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
