### PR TITLE
LPD-41431 Remove Batch Engine rows from database when a company is removed

### PR DESCRIPTION
**Pull request by ccorreagg**
Ticket: https://liferay.atlassian.net/browse/LPD-41431

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:help

**Comment by ccorreagg** [comment]
ci:test:upgrade

**Comment by ccorreagg** [comment]
ci:test:db-partition

**Comment by achaparro** [comment]
@ccorreagg the changes fixed the issue. I had to check it locally another issue prevents the failing tests to be completed.

Thanks!

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:upgrade

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Upgrade suite is good, failed are related to two known issues:
https://testray.liferay.com/#/project/35392/routines/45357/build/70877954?filter=%7B%22status%22%3A%5B%22FAILED%22%5D%7D&filterSchema=buildResults&page=1

Example (last two lines):

> 2024-11-18 09:35:26.056 INFO  [main][UpgradeProcess:119] Upgrading com.liferay.batch.engine.internal.upgrade.v4_5_0.util.BatchEngineImportTaskErrorTable$1
> 2024-11-18 09:35:26.066 INFO  [main][UpgradeProcess:137] Completed upgrade process com.liferay.batch.engine.internal.upgrade.v4_5_0.util.BatchEngineImportTaskErrorTable$1 in 10 ms
> 2024-11-18 09:35:26.066 INFO  [main][UpgradeProcess:119] Upgrading com.liferay.batch.engine.internal.upgrade.registry.BatchEngineServiceUpgradeStepRegistrator - Modifying table BatchEngineImportTask to add the columns [importStrategy INTEGER]
> 2024-11-18 09:35:26.075 INFO  [main][UpgradeProcess:137] Completed upgrade process com.liferay.batch.engine.internal.upgrade.registry.BatchEngineServiceUpgradeStepRegistrator - Modifying table BatchEngineImportTask to add the columns [importStrategy INTEGER] in 9 ms
> 2024-11-18 09:35:26.077 INFO  [main][UpgradeProcess:119] Upgrading com.liferay.batch.engine.internal.upgrade.registry.BatchEngineServiceUpgradeStepRegistrator - Modifying table BatchEngineExportTask to add the columns [externalReferenceCode VARCHAR(75) null]
> 2024-11-18 09:35:26.085 INFO  [main][UpgradeProcess:137] Completed upgrade process com.liferay.batch.engine.internal.upgrade.registry.BatchEngineServiceUpgradeStepRegistrator - Modifying table BatchEngineExportTask to add the columns [externalReferenceCode VARCHAR(75) null] in 8 ms
> 2024-11-18 09:35:26.086 INFO  [main][UpgradeProcess:119] Upgrading com.liferay.batch.engine.internal.upgrade.registry.BatchEngineServiceUpgradeStepRegistrator - Modifying table BatchEngineImportTask to add the columns [externalReferenceCode VARCHAR(75) null]
> 2024-11-18 09:35:26.092 INFO  [main][UpgradeProcess:137] Completed upgrade process com.liferay.batch.engine.internal.upgrade.registry.BatchEngineServiceUpgradeStepRegistrator - Modifying table BatchEngineImportTask to add the columns [externalReferenceCode VARCHAR(75) null] in 6 ms
> 2024-11-18 09:35:26.094 INFO  [main][UpgradeProcess:119] Upgrading com.liferay.batch.engine.internal.upgrade.v4_6_1.BatchEngineTaskConfigurationUpgradeProcess
> 2024-11-18 09:35:26.095 INFO  [main][UpgradeProcess:137] Completed upgrade process com.liferay.batch.engine.internal.upgrade.v4_6_1.BatchEngineTaskConfigurationUpgradeProcess in 1 ms
> 2024-11-18 09:35:26.097 INFO  [main][UpgradeProcess:119] Upgrading com.liferay.batch.engine.internal.upgrade.registry.BatchEngineServiceUpgradeStepRegistrator - Modifying table BatchEngineExportTask to alter the type of the column fieldNames to STRING null
> 2024-11-18 09:35:26.105 INFO  [main][UpgradeProcess:137] Completed upgrade process com.liferay.batch.engine.internal.upgrade.registry.BatchEngineServiceUpgradeStepRegistrator - Modifying table BatchEngineExportTask to alter the type of the column fieldNames to STRING null in 8 ms
> 2024-11-18 09:35:26.106 INFO  [main][UpgradeProcess:119] Upgrading com.liferay.batch.engine.internal.upgrade.registry.BatchEngineServiceUpgradeStepRegistrator - Modifying table BatchEngineExportTask to alter the type of the column callbackURL to VARCHAR(255) null
> 2024-11-18 09:35:26.114 INFO  [main][UpgradeProcess:137] Completed upgrade process com.liferay.batch.engine.internal.upgrade.registry.BatchEngineServiceUpgradeStepRegistrator - Modifying table BatchEngineExportTask to alter the type of the column callbackURL to VARCHAR(255) null in 8 ms
> 2024-11-18 09:35:26.114 INFO  [main][UpgradeProcess:119] Upgrading com.liferay.batch.engine.internal.upgrade.registry.BatchEngineServiceUpgradeStepRegistrator - Modifying table BatchEngineImportTask to alter the type of the column callbackURL to VARCHAR(255) null
> 2024-11-18 09:35:26.126 INFO  [main][UpgradeProcess:137] Completed upgrade process com.liferay.batch.engine.internal.upgrade.registry.BatchEngineServiceUpgradeStepRegistrator - Modifying table BatchEngineImportTask to alter the type of the column callbackURL to VARCHAR(255) null in 12 ms
> 2024-11-18 09:35:26.128 INFO  [main][UpgradeProcess:119] Upgrading com.liferay.portal.kernel.upgrade.UpgradeProcessFactory - Modifying schema to run SQL updates
> 2024-11-18 09:35:26.155 INFO  [main][UpgradeProcess:137] Completed upgrade process com.liferay.portal.kernel.upgrade.UpgradeProcessFactory - Modifying schema to run SQL updates in 27 ms

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @ccorreagg , @achaparro ,

I added some minor changes, mainly for the tests. I think they will not affect the upgrade process.

**Review by vendeltoreki — APPROVED** [review]
Approved: added some minor changes but I think these would not significantly affect the already verified test runs.

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
