### PR TITLE
LRQA-79070 Remove companyId and userId from batch engine

### PR DESCRIPTION
**Pull request by yanan**
Background:
- According to the document https://liferay.atlassian.net/wiki/spaces/COMMERCE/pages/1736409287/Batch+Engine, batch engine will get default companyId and userId

Test Plan:
- Remove companyId and userId from batch engine tests since batch engine can read from conf files for default ones

Jira Ticket:
- https://issues.liferay.com/browse/LRQA-79070

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
- Failed tests are unrelated to the pr.
image
- Tried removed the `companyId` but it still fails, I think which is because in CI we create multiple group for testing so it can't use the default `comanyId` reading from config file.

**Review by Hijky — APPROVED** [review]

**Review by magjed4289 — APPROVED** [review]

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
