### PR TITLE
LPS-127777 Consider Integer as possible type for identifiers

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:test:sf

**Review by nhpatt — APPROVED** [review]

**Comment by nhpatt** [comment]
I see that we are mainly using Long (because the auto generated identifier in Liferay is a Long), what is the use case?

**Comment by nhpatt** [comment]
ci:forward

**Comment by javierdearcos** [comment]
> I see that we are mainly using Long (because the auto generated identifier in Liferay is a Long), what is the use case?

Came from the Headless Community Slack channel:
https://liferay-community.slack.com/archives/CUCUYB1EE/p1612973858013400

I preferred to add the logic in case some client runs with the same issue

**Comment by nhpatt** [comment]
Great! Thanks :D

**Pull request closed without merging**
