### PR TITLE
LPD-35430 correcting component name

### PR DESCRIPTION
**Pull request by GaborKomaromi**
Headless component was not used in testray.team.headless.component.names, also title casing REST Infrastructure

### CODE REVIEW

**Comment by GaborKomaromi** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
Reopening as per my comments in https://github.com/brianchandotcom/liferay-portal/pull/153910.

**Comment by 4lejandrito** [comment]
asd

**Pull request closed without merging**
