### PR TITLE
LPS-171173 Call undeploy method of a removed ObjectDefinitionDeployer with all the existing Objects

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR is created to fix this bug: https://issues.liferay.com/browse/LPS-171173

When `portal-vulcan-impl` module is restarted, the `com.liferay.object.rest.internal.deployer.ObjectDefinitionDeployerImpl` class is redeployed as it has dependencies with certain classes of portal-vulcan, causing that all the Objects REST API components that have been registered in OSGi keep unaltered, the references to the registrations are lost as they were kept in private maps, and then, the `_objectDefinitionDeployerServiceTracker` of the class `com.liferay.object.service.impl.ObjectDefinitionLocalServiceImpl` invokes for each ObjectDefinition the method `deploy` once the `ObjectDefinitionDeployerImpl` has been registered, causing that several components are registered as many times as the `ObjectDefinitionDeployerImpl` is redeployed.

To avoid that, apart from calling the `deploy` method for each Object Definition in the Service Tracker of the `ObjectDefinitionLocalServiceImpl` when an `ObjectDefinitionDeployer` has been added, the method `undeploy` will be invoked for each Object Definition in the Service Tracker of the same class when an `ObjectDefinitionDeployer` has been removed.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) Genius!!! 👏 👏 👏 

As we talked, we should send this to the Objects team so they can review the changes in the service.

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]
Awesome!

**Comment by yanan** [comment]
Test failures not related. OK to manually forward.

More details [compared to Acceptance suite](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2204033696&testrayRunIdA=2204305841&statusB=3):
- Failed tests are passed locally
    - LocalFile.CreateObject#CanCreateStringField
    - LocalFile.CreateObject#CanScopeObjectBySite
    - LocalFile.ObjectAutoGeneratedView#CanViewObjectEntriesAfterAddingAttachment
    - LocalFile.ObjectPortlet#StringDisplayedOnAutoGeneratedTable

**Comment by ccorreagg** [comment]
PR sent to Object's team: https://github.com/liferay-objects/liferay-portal/pull/1774

**Pull request closed without merging**
