### PR TITLE
[TS] LPS-157425

### PR DESCRIPTION
**Pull request by ericyanLr**
https://issues.liferay.com/browse/LPS-157425

Hi Team,

**Context**
This PR was created with guidance from [PTR-3915](https://issues.liferay.com/browse/PTR-3915) and the plan is for the Search Team and Headless Team to review.

**Summary of Changes**
- Search
  - Update mapping to introduce multi-field keyword fields to replace the previous **\*_\<languageId>*_sortable** fields
    - As discussed, we will proceed with adding the sub-field: **\*_\<languageId>*_sortable.keyword_lowercase**
  - Also added mappings for Solr
- Headless API
  - For fields that are utilizing **\*_\<languageId>*_sortable** fields for filtering String fields
    - Use the associated sub-field: **\*_\<languageId>*_sortable.keyword_lowercase**
  - Added tests by updating the template: **base_resource_test_case.ftl** in portal-tools-rest-builder
    - Regenerated relevant tests by running gw buildRest

**Game Plan**
1. The Search Team has **tentatively approved** the proposed changes
2. The next step is for for the Headless Team to review the changes. 
3. If everything looks okay, **the plan will be to re-send back to the Search Team for final review**
    - The Search Team would like Bryan to do a final review (Bryan is on PTO and will be back on Friday)

And so, if the proposed changes look okay on the Headless side, we can re-send the PR to the Search Team for final review.

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
Hi @ericyanLr 
Thank you to share with us this PR.
Right now, we are dealing with some high-priority tasks but we will review this as soon as we can.
Sorry for the delay

**Review by LuismiBarcos — APPROVED** [review]
Hi @ericyanLr 

The PR looks good to me :)

According to your description, it is ok to re-send to the Search Team for a final review.

Thanks for opening this PR to us and notifying us about these changes.

**Comment by ericyanLr** [comment]
Hi @LuismiBarcos ,

Thanks so much for reviewing the PR! 

**Question**
I noticed a set of failing tests that may actually need to be addressed, but I'm not sure how we want to handle them.
- The failing tests for AccountResourceTest appear to be an actual issue
- The failing tests for ProductResourceTest and WarehouseResourceTest may be expected to fail? (It looks like it has a lot of Ignore annotations for several test cases)

I left my notes/analysis below.

Can you help take a look to see how we should handle these? I'm guessing we would eventually need to handle these during review.

Please let me know if you have any questions.
Thanks!

----

**Problematic Tests?**
I took a look at the test results and noticed this set of broken tests:
- com.liferay.headless.commerce.admin.account.resource.v1_0.test.AccountResourceTest.testGetAccountsPageWithFilterStringContains
- com.liferay.headless.commerce.admin.account.resource.v1_0.test.AccountResourceTest.testGetAccountsPageWithFilterStringStartsWith
- com.liferay.headless.commerce.admin.catalog.resource.v1_0.test.ProductResourceTest.testGetProductsPageWithFilterStringContains
- com.liferay.headless.commerce.admin.catalog.resource.v1_0.test.ProductResourceTest.testGetProductsPageWithFilterStringStartsWith
- com.liferay.headless.commerce.admin.inventory.resource.v1_0.test.WarehouseResourceTest.testGetWarehousesPageWithFilterStringContains
- com.liferay.headless.commerce.admin.inventory.resource.v1_0.test.WarehouseResourceTest.testGetWarehousesPageWithFilterStringStartsWith

Link to Test Report: https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/540892/testReport/

**Analysis 1: Tests that may be more critical?**
From my analysis, it looks like these two tests may be actual issues:
- com.liferay.headless.commerce.admin.account.resource.v1_0.test.AccountResourceTest.testGetAccountsPageWithFilterStringContains
- com.liferay.headless.commerce.admin.account.resource.v1_0.test.AccountResourceTest.testGetAccountsPageWithFilterStringStartsWith

It looks like these tests may have revealed an inconsistency between the declared field types, that was likely introduced by: [COMMERCE-7498](https://liferay.atlassian.net/browse/COMMERCE-7498) (https://github.com/liferay/liferay-portal/commit/0b90fe383a9bc700327ae8e619bbce2c1e86b0f2)

For example, if we compare the fields declared in the **AccountEntityModel.java** vs **rest-openapi.yaml**, we can see that one declares the field: "type", as a **string** and the other as an **integer**
- Declared as String: [AccountEntityModel.java#L42](https://github.com/liferay/liferay-portal/blob/7.4.3.83-ga83/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-account-impl/src/main/java/com/liferay/headless/commerce/admin/account/internal/odata/entity/v1_0/AccountEntityModel.java#L42)
- Declared as Integer: [rest-openapi.yaml#L206-L211](https://github.com/liferay/liferay-portal/blob/7.4.3.83-ga83/modules/apps/commerce/headless/headless-commerce/headless-commerce-admin-account-impl/rest-openapi.yaml#L206-L211)

This is causing the test to fail, since the mismatching types results in an improper expression.
 
**Analysis 2: Tests that may just be expected to be ignored?**
For the remaining tests, it looks like there are many test cases that have been set to be ignored. 

And so, it would seem that these new tests failing may be "expected" in a sense, due to the current state of these tests.

**Comment by magjed4289** [comment]
hey @ericyanLr thanks for your PR. I have analysed the results of the `ci:test:relevant` run and there are some failures that seem to be related:

- com.liferay.commerce.machine.learning.recommendation.info.collection.provider.test.UserCommerceMLRecommendationRelatedInfoItemCollectionProviderTest 
- com.liferay.headless.commerce.admin.account.resource.v1_0.test.AccountResourceTest
- com.liferay.headless.commerce.admin.catalog.resource.v1_0.test.ProductResourceTest (Failed tests: testGetProductsPageWithFilterStringContains, testGetProductsPageWithFilterStringStartsWith)

Would you mind taking a look? Thanks in advance!

**Comment by ericyanLr** [comment]
Hi @magjed4289 ,

Thanks for taking a look at the tests.

**Regarding:**
> com.liferay.commerce.machine.learning.recommendation.info.collection.provider.test.UserCommerceMLRecommendationRelatedInfoItemCollectionProviderTest

Is there an easy way to verify whether this is a false positive? From a quick glance, it doesn't look like this test would be affected by these changes. 

Would re-running the ci test relevant command be a good way to re-run the test? 

**Regarding:**

> - com.liferay.headless.commerce.admin.account.resource.v1_0.test.AccountResourceTest
> - com.liferay.headless.commerce.admin.catalog.resource.v1_0.test.ProductResourceTest (Failed tests: testGetProductsPageWithFilterStringContains, testGetProductsPageWithFilterStringStartsWith)

Can you see my previous comment above?
https://github.com/liferay-headless/liferay-portal/pull/1323#issuecomment-1613593317

I mentioned these tests and asked for guidance from the Product Team. 

Can you let me know what you think and if you have any suggestions on next steps?
Thanks!

**Comment by magjed4289** [comment]
hey @ericyanLr I'm basing the analysis on the fact that these tests do not fail in any other branches or in the Acceptance routine. The best way to check whether the failures are related is to rerun these specific tests on this specific branch.

**Comment by LuismiBarcos** [comment]
Hey!
I will investigate why are the tests failing as seems weird to me. I hope I will return with some answers as soon as I can

**Comment by LuismiBarcos** [comment]
Hi all!
I've done some research and some tests are related and reproducible in this branch.
The unique test that I couldn't reproduce the error are the tests for the class `com.liferay.commerce.machine.learning.recommendation.info.collection.provider.test.UserCommerceMLRecommendationRelatedInfoItemCollectionProviderTest`

I've created [this PR](https://github.com/liferay-headless/liferay-portal/pull/1333) with an additional commit to fix the rest of the tests.

What I did is what we do in other tests that is ignore the special entity fields that end in the errors that we are having.

I've run the CI, and if the CI says that there are no errors or the errors are not related, it would be ok for me to send this PR to the search team for a final review.

Thanks for your help 

cc/ @ericyanLr

**Comment by LuismiBarcos** [comment]
Continue here https://github.com/liferay-headless/liferay-portal/pull/1333

**Pull request closed without merging**
