### PR TITLE
LPS-176796 Delete isSanitize method because it will be always false

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Delete `isSanitize` method, because there isn't any ExcpetionMapper that uses it.

**JIRA Tikcet**
https://issues.liferay.com/browse/LPS-176796

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
@sergiojimcos semantic version failure seems related.

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward:force

**Pull request closed without merging**
