### PR TITLE
LPS-180229 | Manage categories for object entries

### PR DESCRIPTION
**Pull request by Hijky**
**Background:**
Add a testcase to manage keywords associated to object entries

**Test Plan**
Background
Given taxonomyVocabulary with name 'vocabulary' created
And Given category with name 'category_parent' in 'vocabulary' created
And Given category with name 'category_child' in 'category_parent' created

CanGetTaxonomyCategoryBriefsOfEntriesCollection
And Given Student entry created with taxonomyCategoryId of 'category_parent'
When requesting getStudentsPage
Then I can see 'category_parent' details in the taxonomyCategoryBriefs of the entry with {studentId}

CanEmptyTaxonomyCategoryBriefsOfObjectEntry
And Given Student entry created with taxonomyCategoryId of 'category_parent'
When requesting putStudent with {studentId} and empty  "taxonomyCategoryIds": []
Then 'category_parent' is not visible in the taxonomyCategoryBriefs of the entry

CanUpdateEntryWithExistingTaxonomyCategory
When requesting putStudent with {studentId} to associate 'category_child'
Then 'category_child' is visible in the taxonomyCategoryBriefs of the entry

CanUpdateSiteScopedObjectEntryWithTaxonomyCategoryWithinSameScope
And Given object definition 'Student' with name field and Scope: Site created
And Given Student entry created
When requesting putStudent with {studentId} to associate {category_parentId}
Then I can see 'category_parent' details in the taxonomyCategoryBriefs of the entry with {studentId}

**Jira ticket:**
https://issues.liferay.com/browse/LPS-182485

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:headless-functional:nocompile

**Review by magjed4289 — APPROVED** [review]
Looks good! 👏🏻

**Review by yanan — APPROVED** [review]

**Comment by Hijky** [comment]
ci:forward

**Pull request closed without merging**
