### PR TITLE
LPD-27055 Fix and unignore ManageCategoriesForObjectEntries#CanUpdateSiteScopedObjectEntryWithTaxonomyCategoryOfDifferentSiteScope

### PR DESCRIPTION
**Pull request by albertojml**
**What's changed?:**
- Adapted the way the CURLs of delete by ERC endpoints were generated so that the trailing slash isn't added.
- Fixed test by transforming the Global site name to the `companyId`.
- Unignored the test

See the following Jira Ticket: [LPD-27055](https://liferay.atlassian.net/browse/LPD-27055)

### CODE REVIEW

**Comment by albertojml** [comment]
ci:test:relevant

**Comment by albertojml** [comment]
ci:test:sf

**Comment by albertojml** [comment]
ci:test:relevant

**Review by magjed4289 — APPROVED** [review]
Test is working correctly. Great job! 👏🏻

**Comment by magjed4289** [comment]
ci:forward

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:test:headless-functional:nocompile

**Pull request closed without merging**
