### PR TITLE
LPD-25201 Create an extension point to allow mapping the scopeAlias for certain JAX-RS Applications (and apply the extension point to the Object Entry REST API)

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPD-25201

---

cc/ @stian-sigvartsen @rotty3000

---

The purpose of this ticket is to support the Client Extensions that creates an OAuth2 application in the following situation:

- The scope aliases belong to an Object Entry REST API with the previous/old format (that is, without using lowercase).

This is done by implementing a new extension point

---

**Before the PR:**

When a customer is deploying a Client Extension that contains a `C_Student.everything` scope aliases

- If there is an Object Definition called Student:
  - The OAuth2 application created does not contain the `c_student.everything` scope [Breaking change, in the past we used to set the scope] :x: 
  - If there is **not** an Object Definition called Student: Nothing is done :white_check_mark: 

---

**After the PR:**

When a customer is deploying a Client Extension that contains a `C_Student.everything` scope aliases

- If there is an Object Definition called Student:
  - The OAuth2 application created will contain the `c_student.everything` scope [we are supporting the previous scope aliases format only for Object Definition REST APIs] :white_check_mark: 
  - If there is **not** an Object Definition called Student: Nothing is done :white_check_mark:

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Rebased with master

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
The tests are already failing in master with the same error, so the failures are not related. Those tests should be fixed in a separated task

**Comment by stian-sigvartsen** [comment]
Hi @ccorreagg . Sorry it is taking so long with this review. Here are my thoughts so far...

The method `ScopeLocatorImpl#getScopeAliases` is now broken, because it does not return the final scope aliases. The new scope alias mapping SPI should be applied there also.

But more conceptually I am not sure about adding this new SPI. 
1) We had other things in mind to create a UI for mapping scope aliases at instance level, and this may confuse things. We'd need to review it further from a product perspective.
2) The scope alias mapper is very similar to the existing scope mapper. The only difference is when it is applied in the pipeline. In most cases mapping scopes and controlling the prefix will achieve the same results. I don't know why your approach with the dynamic prefix handler registration was dismissed? liferay-headless/liferay-portal/pull/2026 That might help me better understand the use cases that we need to cover. 

I will unavailable to progress this until next week, but I am wondering if maybe in the short term you would consider your original approach ? liferay-headless/liferay-portal/pull/2013

**Comment by 4lejandrito** [comment]
> Hi @ccorreagg . Sorry it is taking so long with this review. Here are my thoughts so far...
> 
> The method `ScopeLocatorImpl#getScopeAliases` is now broken, because it does not return the final scope aliases. The new scope alias mapping SPI should be applied there also.
> 
> But more conceptually I am not sure about adding this new SPI.
> 
>     1. We had other things in mind to create a UI for mapping scope aliases at instance level, and this may confuse things. We'd need to review it further from a product perspective.
> 
>     2. The scope alias mapper is very similar to the existing scope mapper. The only difference is when it is applied in the pipeline. In most cases mapping scopes and controlling the prefix will achieve the same results. I don't know why your approach with the dynamic prefix handler registration was dismissed? [LPD-25201 Create and register an implementation of PrefixHandlerFactory to provide a scope prefix based on the Object Definition name #2026](https://github.com/liferay-headless/liferay-portal/pull/2026) That might help me better understand the use cases that we need to cover.
> 
> 
> I will unavailable to progress this until next week, but I am wondering if maybe in the short term you would consider your original approach ? [/pull/2013](https://github.com/liferay-headless/liferay-portal/pull/2013)

As per @stian-sigvartsen's suggestion we are going back to the original solution. I also added the test in this PR which also passes. See https://github.com/liferay-headless/liferay-portal/pull/2053.

**Pull request closed without merging**
