### PR TITLE
LPD-15243-15244-15245 Substituting failing Poshi test with Playwright working ones

### PR DESCRIPTION
**Pull request by albertojml**
**What's new?:**
- Added new test class in Playwright related to the single-element GET API Applications.

**What's changed?:**
- Deleted previously failing Poshi tests.

See the following **Jira tickets**: [LPD-15243](https://liferay.atlassian.net/browse/LPD-15243), [LPD-15244](https://liferay.atlassian.net/browse/LPD-15244), [LPD-15245](https://liferay.atlassian.net/browse/LPD-15245)

### CODE REVIEW

**Comment by jalber786** [comment]
ci:test:playwright

**Comment by jalber786** [comment]
ci:test:sf

**Comment by jalber786** [comment]
ci:test:playwright

**Review by 4lejandrito — APPROVED** [review]
@albertojml see my changes.

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
