### PR TITLE
LPS-190497 Fix failure in com.liferay.batch.engine.internal.test.BatchEngineBundleTrackerTest

### PR DESCRIPTION
**Pull request by matijapetanjek**
The root cause of the issue is that `BatchEngineUnitReaderImpl` creates `AdvancedBundleBatchEngineUnit` instead of `ClassicBundleBatchEngineUnit`. By fixing that logic, we are able to rely on `BatchEngineUnit#isValid` method to skip processing invalid units and avoid uncaught exceptions. (if either configuration or data is missing from a classic batch engine bundle, it is [not a valid bundle](https://github.com/liferay-headless/liferay-portal/pull/1380/commits/17b63ef05da655ef96a2b479a9936f31c02c2d62#diff-5cd94a203875f9c01ae5496f862142bbcfdd10824b0e74977e7787c8744cf5e4L89))

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Let's review this together tomorrow. I like the solution but I have some doubts.

**Comment by 4lejandrito** [comment]
As discussed offline we will split this PR in two. 1 to fix the bug (https://github.com/brianchandotcom/liferay-portal/pull/137996) and another one to fix the batch extensions (that I will send later) in a separate ticket.

**Pull request closed without merging**
