### PR TITLE
LPS-194573 Fixed format of error for APIEndpoint validations + fix of some language values that had a dollar character

### PR DESCRIPTION
**Pull request by jalber786**
**What's changed?:**
- Quotation marks used in the "starts with /" validation message used in APIEndpoints is changed to single quotes.
- Adapted tests to follow the new behavior.
- Fixed some language.properties files that were traducted with a dollar character due to an already overwritten commit

**See the following** **[Jira ticket: LPS-194573](https://liferay.atlassian.net/browse/LPS-194573)**

### CODE REVIEW

**Comment by jalber786** [comment]
ci:test:sf

**Comment by jalber786** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Review by sergiojimcos — APPROVED** [review]

**Comment by yanan** [comment]
One test file needs to be updated with this pr, more details on [Compare run results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2413431560&testrayRunIdA=2413979581&statusB=2):
- LocalFile.GeneratePathStructureForEndpoints#CanValidatePathInAPIEndpoint
image

**Comment by jalber786** [comment]
ci:test:sf

**Comment by jalber786** [comment]
ci:test:relevant

**Comment by jalber786** [comment]
ci:test:sf

**Comment by jalber786** [comment]
ci:test:relevant

**Comment by yanan** [comment]
[Failures](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2415805986&testrayRunIdA=2415551434&statusB=2) are not related, ok to forward once we resolve the conflicts.

**Comment by jalber786** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
@jalber786 please fix the conflicts and forward.

**Comment by jalber786** [comment]
ci:forward:force

**Comment by jalber786** [comment]
ci:forward:force

**Comment by jalber786** [comment]
Manually forwarded through https://github.com/brianchandotcom/liferay-portal/pull/140098

**Pull request closed without merging**
