### PR TITLE
Lps 177463 master

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-177463

This pull request changes the callbackURL column of the batchEngineExportTask and batchEngineImportTask tables to be 255 characters in length. To test the changes, please see the steps to reproduce on LPS-177463.

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
cc/ @4lejandrito

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
@igorbeslic fyi.

**Pull request closed without merging**
