### PR TITLE
LPS-186786 Create the structures to read the Api Application of Headless Builder based on Objects

### PR DESCRIPTION
**Pull request by ccorreagg**
The purpose of this PR is to create the interfaces and classes to manage the Headless Builder API Applications, having into account that Objects is the framework to store the entities in the database.

Furthermore, the previous approach of the API Builder has been deleted as we are working in a different approach.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Review by 4lejandrito — APPROVED** [review]

**Comment by ccorreagg** [comment]
Don't worry @magjed4289 , this PR has been sent to Brian here https://github.com/brianchandotcom/liferay-portal/pull/136548 by @4lejandrito .

**Comment by 4lejandrito** [comment]
Sorry guys I was impatient, I wanted brian to review as soon as possible. Now we can keep iterating.

**Pull request closed without merging**
