### PR TITLE
LPD-26960 Disable captcha on tests related to running groovy script

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-26960

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:headless-aaa:nocompile

**Comment by magjed4289** [comment]
ci:test:headless-aaa

**Comment by magjed4289** [comment]
ci:test:headless

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
Test failures are not related. The [layout-set-prototype-web/siteTemplatesWithWebContent.spec.ts](https://testray.liferay.com/home/-/testray/case_results/2573372706?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseTypeId%3D2537899320%26testrayBuildId%3D2573364404%26testrayRunId%3D2573371158%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) runs correctly in the suite. ✅

**Review by jaimelr10 — APPROVED** [review]
Looks good!

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
