### PR TITLE
LPD-22685 LPD-22690 LPD-22689 Fix expressions in Poshi tests

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket 1: https://liferay.atlassian.net/browse/LPD-22685
Related ticket 2: https://liferay.atlassian.net/browse/LPD-22690
Related ticket 3: https://liferay.atlassian.net/browse/LPD-22689

---

The purpose of this ticket is to fix the Poshi tests by updating the Jayway JsonPath expressions

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:headless

**Comment by ccorreagg** [comment]
The tests have passed in the CI:

https://testray.liferay.com/home/-/testray/case_results/2559773861?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F2463450423%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D2463450423%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc

https://testray.liferay.com/home/-/testray/case_results/2559773307?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F2468735878%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D2468735878%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc

https://testray.liferay.com/home/-/testray/case_results/2559773874?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F2463450442%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D2463450442%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/149108

**Pull request closed without merging**
