### PR TITLE
LPS-169820 batch-test

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPS-169820

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:commerce

**Comment by magjed4289** [comment]
ci:help

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:usm

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Pull request closed without merging**
