### PR TITLE
LPS-195203 Add test for export of Object definition 

### PR DESCRIPTION
**Pull request by matijapetanjek**
Run the test with `gw testIntegration --tests BatchEngineBrokerTest.testExportObjectDefinition`

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Review by sergiojimcos — APPROVED** [review]
LGTM!!

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:forward:force

**Pull request closed without merging**
