### PR TITLE
LPD-44872 Ensuring node is downloaded before running buildREST

### PR DESCRIPTION
**Pull request by 4lejandrito**
See https://liferay.atlassian.net/browse/LPD-44872.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/157194

**Comment by ccorreagg** [comment]
As we talked, not sure if this could break customers, as it seems node is a dependency even if we don't want to autogenerate the stubs

**Pull request closed without merging**
