### PR TITLE
LPS-130131 Fix ClassCastException using batch export in API resources

### PR DESCRIPTION
**Pull request by javierdearcos**
Inside the Resources that implements VulcanBatchEngineTaskItemDelegate, the siteId parameter is cast to Long but in the map is passed as a String. Change it to pass it directly as a Long inside the parameters map

### CODE REVIEW

**Review by nhpatt — APPROVED** [review]

**Comment by nhpatt** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
ci:test:sf

**Pull request closed without merging**
