### PR TITLE
LPD-40755 | Failure in DefaultObjectEntryManagerImplTest.testGetObjectEntries

### PR DESCRIPTION
**Pull request by dannielraposo**
See the following Jira Ticket: [LPD-40755](https://liferay.atlassian.net/browse/LPD-40755)

### CODE REVIEW

**Comment by dannielraposo** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Hey @dannielraposo , I have added just a commit, to try to avoid updating the DTO directly and using the real data instead. As the dateCreated and dateModified is the same value when creating an object entry, I have simplified by using just one of them.

By the way, I think we need to update the first commit description, as you mentioned increasing the time but at the end, we decided to decrease the time

**Comment by ccorreagg** [comment]
Please update the first commit message and feel free to forward

**Review by ccorreagg — COMMENTED** [review]
just updating the commit message would be enough to forward IMHO

**Comment by dannielraposo** [comment]
Thank you Carlos, I understand :)

**Comment by dannielraposo** [comment]
ci:forward

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:forward:force

**Comment by ccorreagg** [comment]
The test seems to be fixed

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
