### PR TITLE
LPS-142229 Add contextPath to handle custom context

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you please review my changes?

**Reproduction steps**

1. Change the ROOT folder name (under {LIFERAY_HOME}/tomcat-9.0.17/webapps/ROOT) to 'myportal'.
2. Change the ROOT.xml file name (under {LIFERAY_HOME}
/tomcat-9.0.17/conf/Catalina/localhost/) to 'myportal.xml'.
3. Clear temp and work directories under TOMCAT_HOME.
4. Start the server and log in as admin
5. Try to access: http://localhost:8080/myportal/o/api page

**Expected behaviour:** You should see the REST API test page
**Acutal behaviour:** You will have HTTP 404 errors

**Root cause**
Missing context path from the Urls

**Solution**
Add contextPath to handle custom context

Thanks, Roland

https://issues.liferay.com/browse/LPS-142229

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:sf

**Review by nhpatt — APPROVED** [review]
LGTM, thanks!

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Hi @nhpatt 

could you please push this forward?

Thanks, Roland

**Comment by rolandpakai** [comment]
Hi @nhpatt

could you please take a look on this PR and push it forward?

Thanks, Roland

**Comment by rolandpakai** [comment]
Hi @nhpatt

could you please take a look on this PR and push it forward?

Thanks, Roland

**Comment by javierdearcos** [comment]
Hello Roland,

Sorry for not answering sooner. This user is deprecated as we are now part of the Frontend Infrastructure team, and we handle everything from there @liferay-frontend.

Thank you for taking care of the issue. Makes sense. Try to forward it today in case it is urgent to you, and we will make some additional tests on Monday to check everything is ok with the two configurable routers.

Thanks again and sorry for not answering sooner

**Comment by javierdearcos** [comment]
ci:forward

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
Hi @javierdearcos 

it seems the ci tests are stucked in Pending status.
Can we push this forward?

Thanks, Roland

**Comment by javierdearcos** [comment]
Yeah it seems so... My experience when this happened is that is better to close the PR and create a new one.

Can you create a new PR in the liferay-frontend repo and we try to forward it from there?

**Comment by javierdearcos** [comment]
If you are busy I can doing myself during the morning, when I finish some meetings that I have today

**Comment by javierdearcos** [comment]
Sent here: https://github.com/liferay-frontend/liferay-portal/pull/1693

**Comment by rolandpakai** [comment]
Thank you @javierdearcos

**Pull request closed without merging**
