### PR TITLE
LPS-163942

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by pedro-oliveira446** [comment]
Just starting reviewing :)

**Comment by Hijky** [comment]
The failures are not related to your PR, here are [the compared results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2352935411&testrayRunIdA=2352827236&statusB=2).

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/136547

**Pull request closed without merging**
