### PR TITLE
[TS] LPS-202900 

### PR DESCRIPTION
**Pull request by MirnaGama**
### Steps to reproduce:
1. Create a site template MY_SITE_TPL.
2. Create a TEST site using that template.
3. Add any Design setting to Site Pages (Site Builder → Pages → Three Dots → Configuration).
- For example any string in Custom CSS: “test”.
4. Close this settings section.
5. In MY_SITE_TPL, add any change related to pages, for example add a new Display Page Template.
6. Check TEST’s page design settings. 

_Expected result:_ Custom CSS remains.
_Observed result:_ Custom CSS is now empty

### Results of investigation:
This flow is started by a background task. –[ LayoutSetPrototypeMergeBackgroundTaskExecutor](https://github.com/liferay/liferay-portal-ee/blob/master/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/background/task/LayoutSetPrototypeMergeBackgroundTaskExecutor.java#L68) class will be called whenever the page is loaded after a layout change. After that, the method [doImportStagedModel from StagedLayoutSetStagedModelDataHandler](https://github.com/liferay/liferay-portal-ee/blob/master/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/exportimport/data/handler/StagedLayoutSetStagedModelDataHandler.java#L177) class will be called and within it there is the [_importTheme](https://github.com/liferay/liferay-portal-ee/blob/master/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/exportimport/data/handler/StagedLayoutSetStagedModelDataHandler.java#L794) method -- It is where the css is overwritten:

But the main problem with this merge is that the display page’s layout set will never have the css populated as it is stated that the custom css is disabled because it is using the inherited theme:
template-design-configuration

### CODE REVIEW

**Review by vendeltoreki — CHANGES_REQUESTED** [review]
Hi @MirnaGama ,

Thanks for the PR and the detailed description. I checked the changes and I think there are 2 scenarios that it should also handle properly:
1. When a LayoutSet is imported (Publishing ==> Staging menu) it will not clear the CSS if the imported LayoutSet has an emtpy one. This is easy to handle: just have to check for `MergeLayoutPrototypesThreadLocal.isInProgress() == true` as well.
2. Set a non-empty CSS on the site template, and it will still reset to this one on all sites created from the template, at each propagation. This one is a bit more complicated to fix. Generally, in site templates, when you update a page on the target site, then the propagation will skip that, so it can keep the changes you made. This is detected by comparing the update dates of the Layout records and the last site template propagation times of the pages (in typeSettings of the Layout). I think something similar can be done here as well, just on the LayoutSet level. Probably by adding some update times to the typeSettings of the LayoutSet as well.

Please let me know if you have more questions.

Thanks,
Vendel

**Comment by vendeltoreki** [comment]
Hi @MirnaGama ,

As discussed, these are the reproduction steps for the above use-cases:

### Import use-case:

1. Create a new site "Site1"
2. Export the site data from Publishing ==> Export menu
3. Add the value "TEST" to the CSS field (Site Builder ==> Pages ==> ... button ==> Configuration)
4. Import the previously exported LAR file
5. Check the CSS value of "Site1"

Expected: the CSS value should be empty, as it was in the exported site
Actual: the CSS value is not cleared

### Overwrite use-case:

1. Create a new site template "Temp1"
2. Add the value "TEST" to the CSS field (Site Builder ==> Pages ==> ... button ==> Configuration)
3. Create a new site from "Temp1" template: "Site2"
4. Change the CSS field in "Site2" to "TEST 2"
5. Add a new page to "Temp1" (to trigger the propagation)
6. Check the CSS value of "Site2"

Expected: CSS value should remain "TEST 2", as it has been changed by the user
Actual: CSS value is reset to "TEST"

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:forward:force

**Pull request closed without merging**
