### PR TITLE
LPD-40537 Fixing buildREST TS generation locally

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPD-40537

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
@4lejandrito Should your commit fix the REST Builder issue from the REST Builder tests?

**Comment by ccorreagg** [comment]
It seems the failure you were trying to avoid is still reproducible somehow:

```
     [exec] Execution failed for task ':util:portal-tools-rest-builder-test-impl:buildREST'.
     [exec] > Process 'command '/opt/java/jdk1.8.0_381-x64/bin/java'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] > Run with --info or --debug option to get more log output.
     [exec] > Run with --scan to get full insights.
     [exec] > Get more help at https://help.gradle.org.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':util:portal-tools-rest-builder-test-impl:buildREST'.
```

**Review by ccorreagg — CHANGES_REQUESTED** [review]
A failure in the same module is still reproducible

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-devtools/liferay-portal/pull/290.

**Pull request closed without merging**
