### PR TITLE
LPS-161364 Use new pattern for batch engine

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket [LPS-166128](https://issues.liferay.com/browse/LPS-166128)
____
## Purpose of this PR
In [this PR](https://github.com/brianchandotcom/liferay-portal/pull/124524) we changed the way that we register the new object JAXR applications breaking the import/export center as the taskItemDelegate has a different name.

With this PR we solved it using the new pattern.

## How to deploy it
Deploy de following modules:
* `object-rest-impl`
* `batch-planner-web`
* `batch-planner-rest-impl`

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
WARNING ⚠️ 
This PR solved the problem to find the `batch engine delegate` introduced in the PR mentioned on the description.
BUT, the import/export still failing when trying to export a custom object due to other problems not related to this (the problem is that some properties to export are not declared in the ObjectEntryDTO).

This was happening before changing the pattern.

If you want to review with me the code, we can make a pair-programming session 🙂

**Review by igorbeslic — APPROVED** [review]
Approved

**Review by matijapetanjek — APPROVED** [review]
LGTM :v:

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by magjed4289** [comment]
According to the analysis started by @Hijky, test failures are unrelated. OK to manually forward. ✅

**Comment by LuismiBarcos** [comment]
Manually forward here https://github.com/brianchandotcom/liferay-portal/pull/125197

**Pull request closed without merging**
