### PR TITLE
LRQA-82392 Test fix for EditAPIApplication.testcase

### PR DESCRIPTION
**Pull request by yanan**
Test fix for EditAPIApplication

https://liferay.atlassian.net/browse/LRQA-82392

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
Failures are not related to the pr, there is one new failed test `CreateAPIDefinitionObjectsAsBackendOfAPIBuilder#CanSeeApiEndpointSchemaFields`, which I already run RCA to see more details.

**Comment by yanan** [comment]
The failed test `CreateAPIDefinitionObjectsAsBackendOfAPIBuilder#CanSeeApiEndpointSchemaFields` passed locally and [on RCA ](https://test-1-1.liferay.com/userContent/jobs/root-cause-analysis-tool/builds/11103/jenkins-report.html), block it on testray for the moment

**Review by Hijky — APPROVED** [review]

**Comment by magjed4289** [comment]
@yanan did we create a ticket to investigate `CreateAPIDefinitionObjectsAsBackendOfAPIBuilder#CanSeeApiEndpointSchemaFields`?

**Comment by yanan** [comment]
> @yanan did we create a ticket to investigate `CreateAPIDefinitionObjectsAsBackendOfAPIBuilder#CanSeeApiEndpointSchemaFields`?

I think this may be a bug according to the error in log, but what's strange is that I can't reproduce it locally or on rca, creating a ticket to investigate here [LRQA-82398](https://liferay.atlassian.net/browse/LRQA-82398)
```2023-08-16 04:17:55.337 ERROR [http-nio-8080-exec-6][ExceptionMapper:59] null
java.lang.NullPointerException: null
	at com.liferay.object.rest.internal.vulcan.openapi.contributor.ObjectEntryOpenAPIContributor._setSchemaDescription(ObjectEntryOpenAPIContributor.java:810) ~[?:?]
	at com.liferay.object.rest.internal.vulcan.openapi.contributor.ObjectEntryOpenAPIContributor.contribute(ObjectEntryOpenAPIContributor.java:143) ~[?:?]
	at com.liferay.portal.vulcan.internal.resource.OpenAPIResourceImpl._getOpenAPI(OpenAPIResourceImpl.java:760) ~[?:?]
	at com.liferay.portal.vulcan.internal.resource.OpenAPIResourceImpl.getOpenAPI(OpenAPIResourceImpl.java:130) ~[?:?]

**Comment by yanan** [comment]
ci:forward:force

**Pull request closed without merging**
