### PR TITLE
LPS-200894 

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPS-200894

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:api-builder-functional:nocompile

**Review by yanan — APPROVED** [review]
That's great!

**Review by Hijky — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:test:headless-builder-functional:nocompile

**Comment by magjed4289** [comment]
ci:test:headless-builder-functional:nocompile

**Comment by yanan** [comment]
ci:test:api-builder-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-builder-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-builder-functional:nocompile

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
