### PR TITLE
LPS-177435 Web content field values are lost after editing for ca-ES-VALENCIA

### PR DESCRIPTION
**Pull request by Mikellorza**
Description
-----------
This PR fix the bug :https://issues.liferay.com/browse/LPS-177435.  

When it is used the Locale.filter method, the method is returned the locale of valencia as ca_ES_valencia and this is cause an issue with the ckeditor of the web content edition fields. So, with this fix we are keeping the locale as it is defined in the portal locales, for valencia language : ca_ES_VALENCIA .

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hey @Mikellorza do you think you can add a test for this in https://github.com/liferay-lima/liferay-portal/blob/f6d10ea9c662b8d5408636c2805681d249dd0a1a/modules/apps/portal-vulcan/portal-vulcan-test/src/testIntegration/java/com/liferay/portal/vulcan/internal/jaxrs/context/provider/test/AcceptLanguageContextProviderTest.java#L64?

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
@4lejandrito tests added!

**Comment by 4lejandrito** [comment]
Thanks @Mikellorza! We will review as soon as we can (hopefully this week).

**Comment by ccorreagg** [comment]
@Mikellorza I have created a followed-up PR with a commit to avoid the double loop. Instead, I am using the `TransformUtil`. I think it is more clear

**Comment by Mikellorza** [comment]
@ccorreagg  LGTM!

**Pull request closed without merging**
