### PR TITLE
LPS-160014 | Expose web content articles information in navigation menus APIs

### PR DESCRIPTION
**Pull request by Hijky**
**Background**
Expose web content articles information in navigation menus APIs

**Test Plan**
Given a navigation menu
And Given a web content article is created
And Given a navigation menu use cutom name associate with the created web content through UI
When with get request and siteId to retrieve the navigation menu
Then I can see values of useCustomName equals to true, contentURL equals to webcontent endpoint and type equals to structuredContent

Given a navigation menu
And Given a web content article is created
And Given a navigation menu doesn't use custom name associate with the web content through UI
When with get request and navigationMenuId to retrieve the navigation menu
Then I can see values of useCustomName of false, contentURL equals to webcontent endpoint and type equals to structuredContent

Given a navigation menu
And Given an assetlibrary with connect to site
And Given a content structure created in asset libraryAnd Given a web content article is created in asset Library
And Given a navigation menu use cutom name associate with the created web content through UI
When with get request and siteId to retrieve the navigation menu
Then I can see values of useCustomName equals to true, contentURL equals to wencontent endpoint and type equals to structuredContent

Given a navigation menu
And Given an assetlibrary with connect to site
And Given a content structure created in asset libraryAnd Given a web content article is created in asset Library
And Given a navigation menu doesn't use custom name associate with the web content through UI
When with get request and navigationMenuId to retrieve the navigation menu
Then I can see values of useCustomName of false, contentURL equals to webcontent endpoint and type equals to structuredContent

**JIRA Link:**
https://issues.liferay.com/browse/LPS-160014

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:headless-frontend-functional:nocompile

**Comment by pyoo47** [comment]
ci:test:headless-frontend-functional

**Comment by Hijky** [comment]
@magjed4289 @yanan It seems the failed not related to my PR.

**Comment by yanan** [comment]
I'm looking at this pr and going to make some changes, will force pushed once done. @Hijky and @magjed4289

**Comment by yanan** [comment]
ci:test:headless-frontend-functional

**Comment by yanan** [comment]
ci:test:headless-frontend-functional

**Comment by yanan** [comment]
ci:test:headless-frontend-functional

**Comment by yanan** [comment]
Rebased to latest master.

**Review by magjed4289 — APPROVED** [review]

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:forward

**Pull request closed without merging**
