### PR TITLE
LPD-41388 Add companyId to disable data handlers by companyId

### PR DESCRIPTION
**Pull request by Mikellorza**
Coming from : https://github.com/liferay-headless/liferay-portal/pull/2268/commits

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-41388

# How am I fixing it?

Add companyId to disable data handlers by companyId

# How can you verify that it works?

Run included tests

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:headless-functional

**Comment by DaniSzimko** [comment]
Hello @Mikellorza,

Thank you! The tests are passing, and the code looks good. Let's wait for the CI results, and if there are no related failures, I will forward it.

**Comment by Mikellorza** [comment]
thanks @DaniSzimko :100:

**Comment by DaniSzimko** [comment]
This one seems suspicious to me: https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/972904/testReport/com.liferay.exportimport.test/DummyFolderExportImportTest/testExportImportDeletions/. However, after investigating, I found that this was also failing before this PR, so I believe we can forward this.

**Comment by DaniSzimko** [comment]
What do you think about it @magjed4289 ?

**Comment by Mikellorza** [comment]
@DaniSzimko let me know if you need help from my side

**Comment by magjed4289** [comment]
https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/972904/testReport/com.liferay.exportimport.test/DummyFolderExportImportTest/testExportImportDeletions/ looks not related to the changes, in fact it is a flakiness and we already have a ticket for it :)
The one that worries me is com.liferay.journal.search.test.JournalIndexerTest:
` 2 Failed tests: testRemoveArticleLocale, testUpdateArticleTranslation`
[link to jenkins console](https://ff6962d05a2e111d5850013cb57cd6d53ba13eccdad84caa13507c7-apidata.googleusercontent.com/download/storage/v1/b/testray-results/o/2024-11%2Ftest-1-28%2Ftest-portal-acceptance-pullrequest(master)%2F11632%2Fmodules-integration-mysql57%2F1%2F21%2Fjenkins-console.txt.gz?jk=AXvcXDsNOjmc4N75hPxX0YDU9vaN0Ymp3J_IFAt3HUoYX6bXKFnSudCHXy-mEaBANts4iwUsikY4SCZBVK5G8OD8nUBJbYnrdhyvH5eBQDvgVZ9prdWd3DwXojKQIbDv5cr9NxpJwUbuhvWVW4vI9pbiXHFB6KsKjwgWAHqajZPPi4t9YXAlR4qP8daiN8aQ1GVS8gAf9_UD12WSPdCz70CwkcRz5C6R7AYpWtsW3OqiDAPvKgS6f6K8du2TrYEiHOLol8h59IAvUfvUB6SrvDnlGP6-d4mIvX2uXxoXG0uNaV52ze9ZBJJ6t73jn-XyOzF3xWsANcSkEaxp8Yabbdpen_p1jVZ8C4ef5Tafr4ug3NXvt7hZdO6yrAZKBGVGLaO-lEReZfDVrZ3znroOvlspTNXrceTfa8XgYQ2Qr79C6-vgmDhx85NkVgGkRtdrSaBg7SYn6Irfb0l-p9-FrTuWpD20n41YGYYel_UGNBrxtyaL7lmqAImCAfwqPfOEoVejkITopdFoCN_857cNDydNEWB9LrQIQY0dJgkGBADAH819HXEWmjZJ91etfsGOzTfRgttlITxTF_mT3Ro6RVVbu9_DJLwPEZTKxmdKIo-NUa6sBpfjXuv0O7ZNr2ZYKBi-tEDRGXoQtazLKxlW2j7_AO5aOmvB1otv3MrLfah5nX6JEQvvx6bRVsrgOVmcpCOTz_GyFrA0r8bwx6OI0bLHsQB8lHdq9RUGxHt10N_voFuuAAuFDE6boSzCTgFe1wZlwHUajNmdhl0jtDul-TxZR2LnK7s86Iyp40M-5id9MnNjDq2Vqi0huxIM-qDFF3wf-Hui3QvkpCUaPMVrFgbplS1b9HS3z0ap-u31mKe3LXQE19IydDwdCYisPOD9rnRmNe1ZnRkPkQT8F7GYKBJAWaN8HFVnRP4Zet-oCxHMpeDRHZtQn0DNEBSsCcYvpSDDmdveBx5FEWSXkoXpXjB4LU5H9t4tfNXMn1eBC-aDbW9bj9CTQTHXRBetb_KFtu4O-_vwqGJt1dEUKVBN1Efk1BFD4Lv_CnhNtz3QPhnM7Bo1qcRIccC4s4qP__0GaWSaif1Rqf7CIgnnX2NjZCP8TILERI126VqhyjTpJfETYzMHUaDk8DF_tQ38hbrY51khIc1Z0rWw0DHvU45t15tLY2T56HtZ1tawbh8zfhgItQ7MJJ5jR251kQ6D6vYEPNN_xs5qIdSWWF7a_WmgUx8Fl2ZEY03q-l2LPQHc3G7EJ6uperz5-LwL1Swqb-M68VeVarACZVosNMxxbnSghThgKbRtGlPK0Z7jsgXBYvZ1Rgz5MTLT3KnPuGdhWg&isca=1)
@Mikellorza could you confirm if the tests pass on your branch locally?

**Comment by Mikellorza** [comment]
ci:report:62739970

**Comment by Mikellorza** [comment]
@magjed4289,

I seems that failing tests of  JournalIndexerTest are not related with this PR, and also, I've just tested in my local env and they are working fine. So, we can move forward

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
