### PR TITLE
LPS-166640 Add test for import and export enabled functionality

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains some integration tests to validate the `VulcanBatchEngineTaskItemDelegateRegistry` is providing the expected values of the methods `isBatchPlannerExportEnabled` and `isBatchPlannerImportEnabled` based on some OSGi properties set to the `VulcanBatchEngineTaskItemDelegate` service registered

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
