### PR TITLE
LPS-184123 Update BlogPostingAPI.macro and related test files

### PR DESCRIPTION
**Pull request by yanan**
Background
- [Poshi automation test] Remove duplicate methods in BlogPostingAPI.macro

Test Plan
- getBlogPosting and _getBlogPosting
- remove condition on isSet(testcase) line 67->71
- rename getIdOfUpdatedPostingBatchEngineImportTask to **BlogPosting**
- remove _deleteBlogPosting which is not used anymore
- combine getBlogPostings and getBlogPostingsbyDifferentParameters

Jira Ticket
- https://issues.liferay.com/browse/LPS-184123

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:lima-headless

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:lima-headless

**Comment by yanan** [comment]
Failures in headless tests are unrelated to the pr.

**Review by Hijky — APPROVED** [review]

**Comment by yanan** [comment]
ci:forward

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
