### PR TITLE
LPS-113977 Fix OpenAPI add content application XML transformation

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
Sorry @nhpatt . Found a problem with substitution and I stopped the forward. Can you review it again and if you agree launch the ci:forward?

Thank you!

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
