### PR TITLE
LPS-189580: Add validation when creating an API Endpoint with a valid API Application

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Add two new validations when an API Application is valid and if it exists.
- Add some test cases for that.
- BuildLang for Error messages.

**How to deploy it?**
- Deploy `headless-builder-api` and `headless-builder-impl`

**JIRA Related Tickets**
https://liferay.atlassian.net/browse/LPS-189580

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
Unify all the errors in one method that returns true or false and just have 1 single message for all of them. The difference between the current messages is not big enough to justify having several. 1 is simpler.

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward:force

**Review by 4lejandrito — APPROVED** [review]

**Pull request closed without merging**
