### PR TITLE
LPS-168240 batch-engine - put delegateName to parameters

### PR DESCRIPTION
**Pull request by igorbeslic**
Problem ObjectEntry and ObjectDefinition Resources are common for all Custom Objects. Beside the fact that Batch Engine properly routes execution to this resources, extra configuring is necessary to tell the name of custom object.

Only way for object-rest to know how to resolve correct objectDefinition is to pass batchEngineDelegateName in parameters. REMINDER: in the case of custom object delegate name contains Custom Object technical name and ObjectEntryResourceImpl relies to it to extract DefinitionName

This only reflects Liferay Objects, and presence of delegate name in parameters won't influence other delegates.

In my opinion, Liferay Objects should have dedicated batch module as we are continue pollute code with IFs just to make excellent batch engine code to work with LO.

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:test:sf
ci:test:relevant

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
> In my opinion, Liferay Objects should have dedicated batch module as we are continue pollute code with IFs just to make excellent batch engine code to work with LO.

Can you create a technical debt task for that? That way we will be able to evaluate it more seriously at some point.

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by igorbeslic** [comment]
ci:forward

**Pull request closed without merging**
