### PR TITLE
LRQA-82481 Test fix for ExportTaskResourceTest

### PR DESCRIPTION
**Pull request by yanan**

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
No error on batch.engine.ExportTaskResourceTest now.

**Comment by magjed4289** [comment]
ci:forward:force

**Comment by yanan** [comment]
ci:forward

**Comment by yanan** [comment]
ci:forward:force

**Pull request closed without merging**
