### PR TITLE
LPD-25201 Support previous/old format of Object Definition scope aliases in Client Extensions

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPD-25201

---

cc/ @stian-sigvartsen @rotty3000

---

The purpose of this ticket is to support the Client Extensions that creates an OAuth2 application in the following situation:

- The scope aliases belong to an Object Entry REST API with the previous/old format (that is, without using lowercase).

---

**Before the PR:**

When a customer is deploying a Client Extension that contains a `C_Student.everything` scope aliases

- If there is an Object Definition called Student:
  - The OAuth2 application created does not contain the `c_student.everything` scope [Breaking change, in the past we used to set the scope] :x: 
  - If there is **not** an Object Definition called Student: Nothing is done :white_check_mark: 

---

**After the PR:**

When a customer is deploying a Client Extension that contains a `C_Student.everything` scope aliases

- If there is an Object Definition called Student:
  - The OAuth2 application created will contain the `c_student.everything` scope [we are supporting the previous scope aliases format only for Object Definition REST APIs] :white_check_mark: 
  - If there is **not** an Object Definition called Student: Nothing is done :white_check_mark:

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]
:+1: 

My only concern is the test. I think it is very low level. Is it not possible to make it more high level? Something like:
1. Create the object definition.
2. Create the configuration like the client extensions do.
3. Check the scopes have the right case.

That way we would not have to use a service tracker in the tests, and the test will be more robust to future refactors of the code.

**Comment by stian-sigvartsen** [comment]
Hi @ccorreagg @4lejandrito . I think this change would potentially cause confusing behaviour in relation to scope aliases.
The PR assumes a "belongs" relationship between JAX-RS app and scope alias(es). However, a single scope alias can in fact grant scopes on a number of JAX-RS apps (you can test this if you remove the default "Bundle PrefixHandlerFactory" configuration. Then there are only 2 main scopes "everything.read" and "everything.write".

The confusion would arise if a scope alias contains a mix of Objects scopes and other JAX-RS apps's scopes, and then the Objects scopes are removed. Then suddenly that scope alias becomes case sensitive with the factory configuration. Which means it may not match anything anymore so scopes are lost (much like the original problem you are solving).

I think what we can do is actually register a impl of `PrefixHandlerFactory` using the same approach that you are doing for your `ScopeAliasMapper`, but providing the `osgi.jaxrs.name` of the particular Objects app as a service property on that alongside `companyId`. Then you can add your preferred prefix in `PrefixHandler#addPrefix` .

This has the extra benefit of completely insulating scope aliases from future changes to your JAX-RS apps's `osgi.jaxrs.name` , giving you programmatic control over that relationship.

**Comment by ccorreagg** [comment]
Different approaches:

Test with PrefixHandlerFactory: https://github.com/liferay-headless/liferay-portal/pull/2026 :negative_squared_cross_mark: not valid
current approach: https://github.com/liferay-headless/liferay-portal/pull/2031

**Pull request closed without merging**
