### PR TITLE
LPS-179260 LPS-184854 Include the DELETE method for deleting the KnowledgeBaseAttachment by ERC

### PR DESCRIPTION
**Pull request by ccorreagg**
Related issue: https://issues.liferay.com/browse/LPS-179260
Related bug: https://issues.liferay.com/browse/LPS-184854

---

This PR contains the code to:

- Remove the `POST` and `PUT` endpoints for for knowledge base attachments by external reference code that are associated to a knowledge base article by external reference code and site id.
- Remove the integration tests for `POST` and `PUT` endpoints
- Add the `DELETE` endpoint for knowledge base attachments by external reference code that are associated to a knowledge base article by external reference code and site id.
- Add the integration tests to verify the new `DELETE` endpoint
- Fix the bug and include integration tests to verify the corner case of the related bug.

How to test it:

- Deploy the module `modules/apps/knowledge-base/knowledge-base-api`
- Deploy the module `modules/apps/knowledge-base/knowledge-base-service`
- Deploy the module `modules/apps/headless/headless-delivery/headless-delivery-api`
- Deploy the module `modules/apps/headless/headless-delivery/headless-delivery-impl`
- Launch the Integration tests of the class `KnowledgeBaseAttachmentResourceTest` in the module `modules/apps/headless/headless-delivery/headless-delivery-test`

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:sf

**Review by 4lejandrito — APPROVED** [review]
I think it is good. You can ci:forward. I will look into it a bit more tomorrow just in case we have to send some follow up. But I don't think it will be the case.

**Comment by ccorreagg** [comment]
Rebased due to conflicts

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Rebased again as there is a new conflict

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Hi @ccorreagg , could you help confirm if the failed SemanticVersioningTest on knowledge-base-api related to the pr and help update?
image
Other [failures](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2312808376&testrayRunIdA=2310366383&statusB=2) are unrelated to the pr.

**Comment by ccorreagg** [comment]
> Hi @ccorreagg , could you help confirm if the failed SemanticVersioningTest on knowledge-base-api related to the pr and help update? image Other [failures](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2312808376&testrayRunIdA=2310366383&statusB=2) are unrelated to the pr.

Hey @yanan ,

It seems the error is related. So I will rebase with master and include a new commit to solve that.

Thanks for the review!

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
