### PR TITLE
LPD-35125 Technical Task | Investigate error thrown in com.liferay.exportimport.test.LayoutExportImportTest

### PR DESCRIPTION
**Pull request by DaniSzimko**
from https://github.com/liferay-headless/liferay-portal/pull/2175

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:report:77895254

**Comment by magjed4289** [comment]
test failures are not related ✅

**Comment by magjed4289** [comment]
ci:forward:force

**Pull request closed without merging**
