### PR TITLE
[TS] [Urgent] LPS-188390 Support nested arrays in Liferay REST Builder

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: [LPS-188390](https://liferay.atlassian.net/browse/LPS-188390)

This is a blocker for our client.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @mbowerman we will review this today.

**Comment by mbowerman** [comment]
Hi @4lejandrito Sorry I just realized that I had a mistake in the steps to reproduce LPS description (I accidentally used the yaml where I was testing the 1-dimensional array instead of the 2-dimensional array.) I've fixed the mistake now.

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-headless/liferay-portal/pull/1318.

**Comment by 4lejandrito** [comment]
ci:close

**Pull request closed without merging**
