### PR TITLE
LPS-196493 (Un)Publishing on every node in the cluster

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPS-196493.

This PR makes the publication of apps work across nodes of a cluster.

How to test? I don't know yet.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
@magjed4289 do you guys know how to test on a cluster?

**Review by ccorreagg — APPROVED** [review]
LGTM

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/141012

**Pull request closed without merging**
