### PR TITLE
Milestone 3 | First Iteration: Testing activities [Headless]

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPD-30094.

Every day for the next 2 weeks:
1. Go to https://testray.liferay.com/web/guest#/project/34754/routines/123635.
2. Click on the latest build.
3. Pick its id (last path param).
4. In this PR run `ci:report:<buildid>`.
5. Add the results to [this spreadsheet](https://docs.google.com/spreadsheets/d/1BtGU851eRAkJtM2VoOhCpsMfQ82ZoB7AUTUt1rXPkX4/edit?usp=sharing).

**Daily report**
* Day 1: [Testray](https://testray.liferay.com/web/guest#/project/34754/routines/123635/build/27984841) | [Sheet](https://docs.google.com/spreadsheets/d/1BtGU851eRAkJtM2VoOhCpsMfQ82ZoB7AUTUt1rXPkX4/edit?gid=1435600839#gid=1435600839).
* Day 2: [Testray](https://testray.liferay.com/#/project/34754/routines/123635/build/28705510) | [Comparison](https://testray.liferay.com/#/compare-runs/28731855/27984851/teams) | [Sheet](https://docs.google.com/spreadsheets/d/1BtGU851eRAkJtM2VoOhCpsMfQ82ZoB7AUTUt1rXPkX4/edit?gid=514490985#gid=514490985)
* Day 3: [Testray](https://testray.liferay.com/web/guest#/project/34754/routines/123635/build/29480930) | [Comparison](https://testray.liferay.com/web/guest#/compare-runs/29491987/28731855/teams) | [Sheet](https://docs.google.com/spreadsheets/d/1BtGU851eRAkJtM2VoOhCpsMfQ82ZoB7AUTUt1rXPkX4/edit?gid=1559451333#gid=1559451333)
* Day 4: [Testray](https://testray.liferay.com/web/guest#/project/34754/routines/123635/build/30169421) | [Comparison](https://testray.liferay.com/web/guest#/compare-runs/30197117/29491987/teams) | Sheet

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:report:27984841

**Comment by magjed4289** [comment]
ci:report:28705510

**Comment by magjed4289** [comment]
ci:report:29480930

**Comment by magjed4289** [comment]
ci:report:30169421

**Comment by magjed4289** [comment]
ci:report:31106370

**Comment by magjed4289** [comment]
ci:report:40604138

**Comment by 4lejandrito** [comment]
Closing for now as the initiative was only for the first sprint.

**Pull request closed without merging**
