### PR TITLE
LPD-41373 Adding headless tests to CODEOWNERS

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPD-41373

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@magjed4289 please check if there is anything else we should add regarding tests.

**Comment by magjed4289** [comment]
ci:test:sf

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
