### PR TITLE
LPD-34463 Tests getting an entity by ERC containing $ fail with "Illegal group reference: group index is missing"

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPD-34463

Note that https://github.com/liferay-headless/liferay-portal/pull/2151/commits/2011c96608c19ff343451ab5611d0734dae3152d just exposes the issue. 

Possibly another way to test it (maybe within rest builder project) is preferred.

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:headless

**Comment by magjed4289** [comment]
ci:report:68919082

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
no test failures from headless suite are related to changes ✅

**Review by vendeltoreki — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:report:69190611

**Comment by magjed4289** [comment]
Due to the high priority of the issue, a task to separately work on adding more test coverage has been created: https://liferay.atlassian.net/browse/LPD-34592

**Comment by magjed4289** [comment]
test failures not related with the PR ✅

**Comment by magjed4289** [comment]
ci:forward:force

**Pull request closed without merging**
