### PR TITLE
LPS-201192: Add test cases for Export Object Entries in CSV

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Add test cases for export Object Entries in CSV
- Refactor test cases

**Note:** The original PR starts from this e4947966ce18b06fc4b4dd68088e19955fac4a25 commit

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPS-201192

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]
See my changes.

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
