### PR TITLE
LPD-24170 Rename journal to journal_article

### PR DESCRIPTION
**Pull request by DaniSzimko**
based on this: https://github.com/brianchandotcom/liferay-portal/pull/148740#issuecomment-2063582983

ticket: https://liferay.atlassian.net/browse/LPD-24170

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:headless-staging

**Review by vendeltoreki — APPROVED** [review]

**Comment by DaniSzimko** [comment]
ci:forward

**Pull request closed without merging**
