### PR TITLE
LPD-21541 & LPD-21542 & LPD-21543

### PR DESCRIPTION
**Pull request by ccorreagg**
Created from https://github.com/liferay-headless/liferay-portal/pull/1973 with some extra commits

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Could you please check @dsanz @4lejandrito and tell me what do you think about the changes?

**Comment by ccorreagg** [comment]
@4lejandrito and I had a talk about this PR and we agreed to keep the way you guys decided. It was not possible to check if there is something broken with the changes included in the Base*ResourceImpl in the past, but I suspect it could be. So we agreed it is a good way to have it done

**Review by 4lejandrito — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
Thanks @4lejandrito @ccorreagg I'm going to add some extra suites here, to increase our confidence

**Comment by dsanz** [comment]
ci:test:echo-headless

**Comment by dsanz** [comment]
ci:test:headless-functional

**Comment by dsanz** [comment]
ci:test:relevant

**Comment by dsanz** [comment]
@ccorreagg do you think [these failures](https://github.com/liferay-headless/liferay-portal/pull/1974#issuecomment-2057544459) in `headless-functional` suite can be related to the PR?

**Comment by ccorreagg** [comment]
> @ccorreagg do you think [these failures](https://github.com/liferay-headless/liferay-portal/pull/1974#issuecomment-2057544459) in `headless-functional` suite can be related to the PR?

It seems they are not related with these changes

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:test:stable

**Comment by 4lejandrito** [comment]
@ccorreagg can we close this?

**Comment by ccorreagg** [comment]
Yes, as the latest PR is https://github.com/liferay-frontend/liferay-portal/pull/4149

**Pull request closed without merging**
