### PR TITLE
LPS-160798  Get OpenAPI endpoint does not work for YAML

### PR DESCRIPTION
**Pull request by 4lejandrito**
**Steps to reproduce:** https://issues.liferay.com/browse/LPS-160798.
**Explanation:** Read https://github.com/liferay-headless/liferay-portal/pull/761/commits/f2bc46be90c6c2c99efd4711a22a9dd5a3cb63e6 message.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) 👏 👏 👏 👏 👏 
You unified patterns for the dynamic relationship endpoints. I like that!

**Comment by 4lejandrito** [comment]
ci:reevaluate:1317401_5140

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/123655

**Pull request closed without merging**
