### PR TITLE
LPS-191342 Set a page size limit for the Headless API requests

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-191342

---

The purpose of this PR is to set a page size limit for all the Headless API requests. For that:

- A new configuration parameter has been added into the `Headless API` configuration. The default value is `500`
- The `PaginationContextProvider` has been modified to ensure the page size requested by the user, if applies, is always under the page size limit parameter.
- New language values have been added to the Liferay portal.
- New tests have been created to ensure the values are the expected ones given all the possible use cases.

How to test it:

- By executing the tests of the class `PaginationContextProviderTest` through the command `gw tI --tests PaginationContextProviderTest` in the module `modules/apps/portal-vulcan/portal-vulcan-test`

image

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Rebased with brianchandotcom/master, as it already contains some commits from the Headless Configuration

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
@ccorreagg review my commits. If you like them please forward.

**Review by 4lejandrito — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
OK with the changes @4lejandrito

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
