### PR TITLE
LPS 181729

### PR DESCRIPTION
**Pull request by rotty3000**
- LPS-181729 manually update batch enabled ResourceImpls with VulcanBatchEngineTaskItemDelegate service
- LPS-181729 export rest resource impls with service interface EntityModelResource
- LPS-181729 Refactor BatchEngineTaskItemDelegateRegistry to wait for ResourceImpls to become active

### CODE REVIEW

**Comment by rotty3000** [comment]
@matijapetanjek please see. I've resolved the issue with the component factory pattern.

**Comment by rotty3000** [comment]
ci:test:sf

**Comment by rotty3000** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
ci:reevaluate:1377401_10899

**Comment by matijapetanjek** [comment]
OK great, this works! I just have to add one change related to _validateStrategy method which is still failing in BatchEngineImportTaskLocalSerivce, closing this PR and will send a new one with the new update.

**Comment by matijapetanjek** [comment]
see https://github.com/liferay-headless/liferay-portal/pull/1208

**Pull request closed without merging**
