### PR TITLE
LPD-30049 Fixing default user

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPD-30049

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
@4lejandrito I have seen the pattern even in some User's module, so I think it is right. Regarding the test, I don't fully understand what we are testing when updating the name :thinking: Could you explain to me?

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
> @4lejandrito I have seen the pattern even in some User's module, so I think it is right. Regarding the test, I don't fully understand what we are testing when updating the name 🤔 Could you explain to me?

The test is changing the screename of the admin user in the second company to cause the original code to not find it and break with the same error as the original LPP.

**Review by ccorreagg — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
