### PR TITLE
LPD-42291 Correct export of the ERC of groups

### PR DESCRIPTION
**Pull request by jkappler**
Reviewed here: https://github.com/liferay-content-management/liferay-portal/pull/6101

Correct export of groups in portlet preferences

# What is this trying to solve?

[Link to ticket](https://issues.liferay.com/browse/LPD-42291)

Collections connected to the site and widget preferences that contain groups are not published correctly to remote staging

# How am I fixing it?

For sites (groups), external reference code is different between local and remote staging. For this, if we are publishing, search the correct ERC in the group type settings and replace it accordingly.

# How can you verify that it works?

There are several tests that already cover this:

DepotCollections#CanBePublishedViaRemoteStaging
DMRemoteStaging#CanViewImageInManualCollectionViaAPAfterPublish
DepotRemoteStagingDM#CanViewImageInDynamicCollectionViaAPAfterFriendlyURLIsUpdated

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:staging

**Comment by jkappler** [comment]
ci:test:headless-staging

**Comment by jkappler** [comment]
ci:test:headless-staging

**Comment by vendeltoreki** [comment]
Checked test failures:
```
com.liferay.staging.test.StagingDataPortletPreferencesTest.testDDLDisplayPortletPreferences
com.liferay.segments.test.SegmentsEntryRetrieverTest.testGetSegmentsEntryIdsInSimulationModeWithSegmentsEntry
```
They don't seem to be relevant. Forwarding the PR.

**Review by vendeltoreki — APPROVED** [review]

**Comment by vendeltoreki** [comment]
ci:forward:force

**Comment by jkappler** [comment]
Thanks for the review @vendeltoreki!

**Pull request closed without merging**
