### PR TITLE
LPD-39489 - Investigate failure in LocalFile.StagingUsecase#ActivateStagingForSiteWithTheme

### PR DESCRIPTION
**Pull request by DaniSzimko**
Navigate back to Guest home page after deprecated flag settings

[JIRA ticket](https://liferay.atlassian.net/browse/LPD-39489)

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:headless-functional

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Review by magjed4289 — DISMISSED** [review]

**Comment by DaniSzimko** [comment]
ci:forward

**Comment by DaniSzimko** [comment]
Closing this, because https://github.com/liferay-content-management/liferay-portal/pull/6031 will fix the issue.

**Pull request closed without merging**
