### PR TITLE
LPD-30381 Sort by externalReferenceCode

### PR DESCRIPTION
**Pull request by ling-alan-huang**
Changes:
Removed `userId` and `version`.
Sort items by `externalReferenceCode`.

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@4lejandrito Could your team review this PR? Thanks.

**Comment by 4lejandrito** [comment]
Hey @ling-alan-huang it's on our queue. We will review it as soon as we can.

**Comment by 4lejandrito** [comment]
Hey @ling-alan-huang. Unfortunately these object definitions cannot be sorted by ERC. That file fails to be imported because the order matters due to internal limitations. We would need to solve those first (the objects team) before this can go forward.

**Comment by ling-alan-huang** [comment]
Thanks @4lejandrito Will you let the objects team know about it?

**Pull request closed without merging**
