### PR TITLE
LRQA-84180 Add waitFor and viewSuccessMessage in api builder macro

### PR DESCRIPTION
**Pull request by yanan**
Background:
- Add waitfor to make test run more stable

JIra Ticket
- https://liferay.atlassian.net/browse/LRQA-84180

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-builder-functional:nocompile

**Review by Hijky — APPROVED** [review]
All good!
@magjed4289 FYI, do we need to create a task to remove all the reindex in our all tests? 
cc: @yanan

**Comment by magjed4289** [comment]
> All good! @magjed4289 FYI, do we need to create a task to remove all the reindex in our all tests? cc: @yanan

@Hijky we can try to do it in one pull and see whether all tests pass with no issues. [here's](https://liferay.atlassian.net/browse/LPS-200888) a task you can try it in

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
