### PR TITLE
LPS-194476 Add functional tests on procedure for trigger api generator

### PR DESCRIPTION
**Pull request by yanan**
Background
- Add test for story LPS-191914 procedure for trigger api generator when portal startup

Test Paln
- Given api-application with GET endpoint is published
Given I restart the server
When I navigate to /o/application/openapi.json
Then the openapi.json is available

Jira Ticket:
- https://liferay.atlassian.net/browse/LPS-194476

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Review by Hijky — APPROVED** [review]

**Comment by yanan** [comment]
Failures are not related, added existing ticket on Testray.
Created one test analysis ticket which I will start to investigate next week to see if adding some wait can improve it to run more stably [LRQA-82572](https://liferay.atlassian.net/browse/LRQA-82572).

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
