### PR TITLE
LPD-28139 - React 18 upgrade for liferay-headless modules

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Hey, please check out our changes we made to your module for the React 18 upgrade. Particularly, you only need to check out the [commit specifically for your team](https://github.com/liferay-headless/liferay-portal/pull/2294/commits/b4efcbcafb0125e88abab487702db58c26e695d3). Please verify this doesn't cause any failures/regressions for you and let me know if you have any questions.

[Our full-pr](https://github.com/liferay-frontend/liferay-portal/pull/4507)

[Updates will be applied to this PR](https://github.com/liferay-frontend/liferay-portal/pull/4533)

---------------------

It's finally here! We'v been working on this on and off over the last year and we've finally got green tests. Upgrading to React 18 is a significant milestone for us because it is the first time we have upgraded out React version. We first added official React support into `liferay-portal` in 2019, and previously we used it sparingly in individual projects. The first supported version of React in Liferay was `16.8.6` and before this upgrade we were at `16.12.0`. Now we are at `18.3.1` which is the latest React release(React 19 already has an RC and we will evaluate that after a general release). [See what is new in React 18](https://react.dev/blog/2022/03/29/react-v18)

### Things to note:
- All of `liferay-portal` now uses React@v18. Our importmap for `react` will point to this new version.
- We also provide importmaps pointing to specific versions. This is particularly helpful for client extensions pointing to importmaps.
```json
// Points to version used in liferay-portal
"react-dom": "/o/frontend-js-react-web/__liferay__/exports/react-dom.js",
"react": "/o/frontend-js-react-web/__liferay__/exports/react.js",

// Version specific
"react-16": "/o/frontend-js-react-web/__liferay__/exports/react-16.js",
"react-dom-16": "/o/frontend-js-react-web/__liferay__/exports/react-dom-16.js",
"react-18": "/o/frontend-js-react-web/__liferay__/exports/react-18.js",
"react-dom-18": "/o/frontend-js-react-web/__liferay__/exports/react-dom-18.js",
```
- React now has [automatic batching](https://react.dev/blog/2022/03/29/react-v18#new-feature-automatic-batching) by default. This will reduce re-renders, but can also possibly cause issues in your app if you are dependent on setState's happening synchronously with re-renders.
- Liferay uses React entirely client-side. We don't get any of the server-side goodies because it requires a Node.js server.
- We added two new APIs in our code to accomodate this change and help teams as they upgrade to React 18. Both of these APIs are an "escape hatch", meaning they allow a you to bypass or override certain constraint at a lower level. These are not normative and the aim is to remove them.
	- `USE_REACT_16` environment variable for running unit tests. When updating to 18 we couldn't just blindly get all the JS unit tests to work. To ensure we move forward smoothly, we added this env variable that is added in your package.json's `test` script. 
	- `__reactDOMFlushSync` boolean prop that can be added to `render` from `frontend-js-react-web` or added as a prop to `react:component` tag. This API should RARELY be used, but it can be used to force React to fallback to render with "non-batching" updates. This is only used sparingly and is only used as an intermediary for teams to update. If you think you need to add this to your code, please reach out to me first and let me check your use case.

### Now what?
If your team owns a module, check the `package.json` script for `test`. If your unit tests are using `USE_REACT_16`, we need you to work on updating your tests to be compatible with React 18. To do this, simply remove that environment variable and check your unit test failures.
#### Preparing for React 19
[See the official React guide](https://react.dev/blog/2024/04/25/react-19-upgrade-guide)

Notable Removals:
- [Removed: `propTypes` and `defaultProps`](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops)
- [Removed: string refs](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops)
- [Removed: `ReactDOM.render`](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-reactdom-render)

Lastly, if you regularly are working with React here at Liferay, please refresh yourself with the [Rules of React](https://react.dev/reference/rules). There were lots of instances where we were updating modules and looking at the React code and there were several patterns that were "anti-react". We highly recommend trying to avoid `useEffect` as much as possible and also avoid `querySelector`, `getElementById`, etc. and `addEventListener` in your apps. Those almost always lead to issues down the road as those happen outside of React's virtual DOM and updating.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hey @bryceosterhaus why do we need to add `__reactDOMFlushSync` to all the props? shouldn't this be transparent to us?

**Comment by bryceosterhaus** [comment]
@4lejandrito the reason we had to add that is because of how react's new async rendering works(using this prop forces it to use sync rendering, like react 16). Ideally, we remove this, but I didn't want to modify your code.

In those two files, you have a `<liferay-frontend:component` which is calling some global javascript that updates/modifies nodes that your React components are creating. Because of it now being async rendering, when `<liferay-frontend:component` runs, the react tree hasn't been created yet.

More context: https://liferay.slack.com/archives/CLD39UKM5/p1725352288256779

**Comment by bryceosterhaus** [comment]
If you want to remove `__reactDOMFlushSync `, just need to remove the flag and reconcile how `liferay-frontend:component` is working in those files

**Comment by jaimelr10** [comment]
ci:test:headless-functional

**Comment by jaimelr10** [comment]
ci:test:playwright

**Comment by jaimelr10** [comment]
liferay/ci:test:playwright

**Comment by jaimelr10** [comment]
ci:test:playwright

**Comment by ccorreagg** [comment]
Hey @bryceosterhaus ,

@jaimelr10 is now on PTO but we will continue analyzing the possible related errors. It seems there are some failures that may be related. We will let you know ASAP

**Comment by bryceosterhaus** [comment]
@ccorreagg thanks! If you pinpoint any failures, let me know and I can also investigate in parallel

**Comment by ccorreagg** [comment]
cc/ @magjed4289

**Comment by magjed4289** [comment]
@bryceosterhaus will pass you the list shortly!

**Comment by magjed4289** [comment]
Test failures that seem to be unique:
[LocalFile.ManageCategoriesForObjectEntries#CanUpdateEntryWithExistingTaxonomyCategory](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53681293)
[LocalFile.ManageCategoriesForObjectEntries#CanUpdateSiteScopedObjectEntryWithTaxonomyCategoryWithinSameScope](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53681301)
[LocalFile.StagingUpgrade#PublishArticleCreatedByDeletedUserAfterUpgrade704](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53679813)
[LocalFile.AllowUsersToDefinePrefilters#PrefilterIsLimitedByODataCharacterLimit](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53681469)
[LocalFile.AllowUsersToDefineSorts#SortingIsLimitedByODataCharacterLimit](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53679705)
[LocalFile.ImportExport#CanRecallExportTemplate](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53680397)
[LocalFile.SitetemplatesUsecase#AddPageTemplatesWithDuplicateNameViaSiteTemplate](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53681141)

**Comment by bryceosterhaus** [comment]
[LocalFile.ManageCategoriesForObjectEntries#CanUpdateEntryWithExistingTaxonomyCategory](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53681293) - This one passes locally for me (although if I run it twice in a row it fails).

[LocalFile.ManageCategoriesForObjectEntries#CanUpdateSiteScopedObjectEntryWithTaxonomyCategoryWithinSameScope](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53681301) - This one passes locally for me (although if I run it twice in a row it fails).

[LocalFile.StagingUpgrade#PublishArticleCreatedByDeletedUserAfterUpgrade704](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53679813) - Flakey? I can't seem to see any actual error manually.

[LocalFile.AllowUsersToDefinePrefilters#PrefilterIsLimitedByODataCharacterLimit](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53681469)  - Same as below 
[LocalFile.AllowUsersToDefineSorts#SortingIsLimitedByODataCharacterLimit](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53679705) - It is a JS error, but I might need your team to investigate because the `EditAPIEndpoint` file that this stems from looks like a very suspicious file... All of the useEffects and handlers are concerning.

[LocalFile.ImportExport#CanRecallExportTemplate](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53680397) - This doesn't seem related to my changes, at least from a code perspective, the failure looks legit and comes from some data generated from the backend, I think...

[LocalFile.SitetemplatesUsecase#AddPageTemplatesWithDuplicateNameViaSiteTemplate](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53681141) - Poshi fails locally, but manual testing seems fine?

**Comment by magjed4289** [comment]
@bryceosterhaus I double-checked:
[LocalFile.AllowUsersToDefinePrefilters#PrefilterIsLimitedByODataCharacterLimit](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53681469)
[LocalFile.AllowUsersToDefineSorts#SortingIsLimitedByODataCharacterLimit](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53679705)
It is passing correctly on my master, there is a js error in the console but the test passes. On the branch with your changes, the limitation to 10000 characters is not present and the text is saved being too large.

**Comment by bryceosterhaus** [comment]
@magjed4289 the new results are here https://github.com/liferay-frontend/liferay-portal/pull/4533#issuecomment-2459200620

I think I will need your team to investigate [LocalFile.ImportExport#CanRecallExportTemplate](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53680397), because there is some odd interaction between how the JSP is using both react:component and liferay-frontend:component but also rendering react in the liferay-frontend one...

**Comment by magjed4289** [comment]
thanks @bryceosterhaus, will review the latest results and will let you know!

**Comment by magjed4289** [comment]
Hey, @bryceosterhaus, about the first one - tomorrow I will talk to the team about it, cause we'll probably have to create an investigation task that would theoretically block your PR, so we also have to see when and how can we give it a priority.
About [LocalFile.SitetemplatesUsecase#AddPageTemplatesWithDuplicateNameViaSiteTemplate](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53681141), I'm noticing that the modal Add Page Template is being called twice, not sure if because of the test code or because of the functionality itself, so I'll keep investigating. It happens both on master and on your branch, however the react upgrade seems to make it more sensible :D 
Will keep you posted!

**Comment by magjed4289** [comment]
@bryceosterhaus for the [LocalFile.SitetemplatesUsecase#AddPageTemplatesWithDuplicateNameViaSiteTemplate](https://testray.liferay.com/#/project/35392/routines/45357/build/53677983/case-result/53681141) [this fix](https://github.com/magjed4289/liferay-portal/pull/1297/files) will make the test pass correctly.

**Comment by bryceosterhaus** [comment]
closing as it was approved here https://github.com/liferay-frontend/liferay-portal/pull/4533#issuecomment-2467238529


These changes will be merged with this PR: https://github.com/liferay-frontend/liferay-portal/pull/4507

**Pull request closed without merging**
