### PR TITLE
LPS-200919 Use `post<ParentSchema>ByExternalReferenceCode<Schema>` method when using createStrategy == INSERT in Batch integration

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-200919

---

The purpose of this ticket is to use the `post<ParentSchema>ByExternalReferenceCode<Schema>` method as one of the possible methods when importing data using Batch Engine when `createStrategy == INSERT`.

This is the code of the `create` method of the `VulcanBatchEngineTaskItemDelegate` interface of a REST API:

**Before the PR:**

```java
public void create(
		Collection<ObjectRelationship> objectRelationships,
		Map<String, Serializable> parameters)
	throws Exception {

	UnsafeFunction<ObjectRelationship, ObjectRelationship, Exception>
		objectRelationshipUnsafeFunction = null;

	String createStrategy = (String)parameters.getOrDefault(
		"createStrategy", "INSERT");

	if (StringUtil.equalsIgnoreCase(createStrategy, "INSERT")) {
		if (parameters.containsKey("objectDefinitionId")) {
			objectRelationshipUnsafeFunction =
				objectRelationship ->
					postObjectDefinitionObjectRelationship(
						_parseLong(
							(String)parameters.get("objectDefinitionId")),
						objectRelationship);
		}
		else {
			throw new NotSupportedException(
				"One of the following parameters must be specified: [objectDefinitionId]");
		}
	}
```

**After the PR:**

```java
public void create(
		Collection<ObjectRelationship> objectRelationships,
		Map<String, Serializable> parameters)
	throws Exception {

	UnsafeFunction<ObjectRelationship, ObjectRelationship, Exception>
		objectRelationshipUnsafeFunction = null;

	String createStrategy = (String)parameters.getOrDefault(
		"createStrategy", "INSERT");

	if (StringUtil.equalsIgnoreCase(createStrategy, "INSERT")) {
		if (parameters.containsKey("objectDefinitionId")) {
			objectRelationshipUnsafeFunction =
				objectRelationship ->
					postObjectDefinitionObjectRelationship(
						_parseLong(
							(String)parameters.get("objectDefinitionId")),
						objectRelationship);
		}
		else if (parameters.containsKey("externalReferenceCode")) {
			objectRelationshipUnsafeFunction = objectRelationship ->
				postObjectDefinitionByExternalReferenceCodeObjectRelationship(
					(String)parameters.get("externalReferenceCode"),
					objectRelationship);
		}
		else {
			throw new NotSupportedException(
				"One of the following parameters must be specified: [objectDefinitionId, externalReferenceCode]");
		}
	}
```

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Failures are not related, ok to manually forward. Here are more details on [compare run results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2452837033&testrayRunIdA=2453828133&statusB=2)
- they are flaky failures that sometimes happen on Acceptance master because of `type AccountGroup not found in schema`

**Comment by ccorreagg** [comment]
ci:forward:force

**Comment by ccorreagg** [comment]
> Failures are not related, ok to manually forward. Here are more details on [compare run results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2452837033&testrayRunIdA=2453828133&statusB=2)
> 
> * they are flaky failures that sometimes happen on Acceptance master because of `type AccountGroup not found in schema`

Thanks @yanan !

**Pull request closed without merging**
