### PR TITLE
Igor lps 175559 rest builder has a bug

### PR DESCRIPTION
**Pull request by igorbeslic**
id is not valid parameter for batch (batch code generation seems like someone wanted to do everything in one pass, with minimum code and optimized for million executions - cool)
I regenerated commerce API as it is reported in LPS
Lets regenerate other implementations after this PR lands the eagle nest

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
Thanks for this @igorbeslic!

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward:force

**Pull request closed without merging**
