### PR TITLE
LPD-16467 | LPD-16977: Allow users to import and export Aggregation, Formula, Encrypted and Boolean fields in CSV

### PR DESCRIPTION
**Pull request by sergiojimcos**
## Motivation
The aim of this PR is to allow users to import and export Aggregation, Formula, Encrypted and Boolean fields in CSV. As well as, this implies to import and export using the UI.

**What is new?**
- Restricted some Object Fields under Feature Flag.
- Add integration test case.
- Update functional tests

**JIRA Related Tickets**
https://liferay.atlassian.net/browse/LPD-16467
https://liferay.atlassian.net/browse/LPD-16977
https://liferay.atlassian.net/browse/LPD-17104

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
@sergiojimcos integration tests fail locally:
**Server logs:**
```
java.lang.IllegalArgumentException: Please insert an encryption key or remove the object's encryption field to recover these entries.
```
I fixed it in https://github.com/liferay-headless/liferay-portal/pull/1854/commits/372ab5cadccef5fa2dd898406212048ffc6e1de5. I am still reviewing the rest.

**Comment by 4lejandrito** [comment]
ci:forward

**Review by 4lejandrito — APPROVED** [review]
See my changes.

**Comment by sergiojimcos** [comment]
After comparing the runs in TestRay, all the tests are unrelated :rocket:

**Comment by sergiojimcos** [comment]
ci:forward:force

**Comment by sergiojimcos** [comment]
Sent to Brian here: https://github.com/brianchandotcom/liferay-portal/pull/147111

**Pull request closed without merging**
