### PR TITLE
LPS-163251 - Scroll bar disappears when user finish importing in import/export center

### PR DESCRIPTION
**Pull request by Artartur**
Related Issue: [LPS-163251](https://issues.liferay.com/browse/LPS-163251)

### CODE REVIEW

**Comment by Artartur** [comment]
ci:test

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
Hi @Artartur! I was checking your PR and I don't know if you figured out that with this fix, you will lock all the functionality of the I/E center. Check this:

https://user-images.githubusercontent.com/44723449/213992478-dd699e7d-836f-430f-9ade-d9288ddee6bd.mp4

If you see the scroll bar will appear but the rest of the component will not work. Check it please, thanks :slightly_smiling_face:

**Comment by 4lejandrito** [comment]
The proper fix for this bug would be to redirect to the previous page instead of remaining in the current one.

**Comment by Artartur** [comment]
ci:test:sf

**Comment by Artartur** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-headless/liferay-portal/pull/995.

**Pull request closed without merging**
