### PR TITLE
Lps 166670 Test fix for expose default erc in structured content folder test

### PR DESCRIPTION
**Pull request by yanan**
**Background:**

- Update default erc tests
- Rename test file from ExposeERC... to ExposeErc...

**Test Plan:**

Update tests to run ok no matter database partition is enabled or not. We decide to not read uuid from mysql for this testcase, using erc in response instead

**Jira Ticket:**

https://issues.liferay.com/browse/LPS-166670

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:relevant

**Review by Hijky — APPROVED** [review]

**Review by magjed4289 — COMMENTED** [review]
@yanan we also have some tests that verify that if erc not present in the body, it is assigned as uuid by default. will these tests still be using the SQL method?

**Comment by yanan** [comment]
> 

Yes, the rest tests are still using SQL method to get uuid. The current pr only update the failed tests in LPS-166670 https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2008825538&testrayTeamId=1310752596.

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Hi @magjed4289 , I've updated other related tests and remove the getUuidFromDatabase method, Please help review if anything else needs to be updated when you have time, thanks :smiley:

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
