### PR TITLE
LPD-15576 Security vuln

### PR DESCRIPTION
**Pull request by 4lejandrito**
From https://github.com/liferay-headless/liferay-portal/pull/1875.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Review by vendeltoreki — APPROVED** [review]
The tests look much cleaner now. Thanks, @4lejandrito !

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
