### PR TITLE
LPD-24078: Allow users to sort parent entities with data from the related elements ( Many to One relationship )

### PR DESCRIPTION
**Pull request by vendeltoreki**
[LPD-24078](https://liferay.atlassian.net/browse/LPD-24078)

Forwarding from: https://github.com/liferay-headless/liferay-portal/pull/2006
Modified the test cases, according to https://github.com/liferay-headless/liferay-portal/pull/2006#issuecomment-2120725966

cc: @ccorreagg

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Failing relevant test: `ObjectLayoutLocalServiceTest.testAddObjectLayout`
I checked and it runs successfully in local.

**Comment by ccorreagg** [comment]
ci:forward:force

**Review by ccorreagg — APPROVED** [review]
LGTM @vendeltoreki ! Thanks for the changes!

**Pull request closed without merging**
