### PR TITLE
LPS-119807 Fix creation of questions when specified a root topic

### PR DESCRIPTION
**Pull request by LuismiBarcos**

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:stop

**Comment by LuismiBarcos** [comment]
Forwarded [brianchandotcom#93572](https://github.com/brianchandotcom/liferay-portal/pull/93572)

**Pull request closed without merging**
