### PR TITLE
LPS-200173 Fix regex as we need to allow 1 only alphanumeric character as minimum, not 2

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-200173

----

The purpose of this PR is to fix the related ticket. The problem is the regular expression was accepting a minimum of 2 alphanumeric characters (apart from the initial `/`), making the process fail if the path just contains 1

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by sergiojimcos — APPROVED** [review]
LGTM!!

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:forward

**Comment by Hijky** [comment]
The failures are not related to your PR, It's okay to forward.

**Comment by ccorreagg** [comment]
thanks @Hijky !

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
