### PR TITLE
Lps 192674 Test fix for adding ObjectFolderDto into functional and integration tests

### PR DESCRIPTION
**Pull request by yanan**

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
Test failures are unrelated to the pr. 
- I'm not able to reproduce the failed test locally `PublishAPIApplication#CanGetPublishedStatusInResponse`, mark it as Blocked for now
image

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Comment by yanan** [comment]
ci:forward:force

**Comment by yanan** [comment]
Manually forward: https://github.com/brianchandotcom/liferay-portal/pull/138871

**Pull request closed without merging**
