### PR TITLE
LPD-43285 | Remove feature flag LPD-11036

### PR DESCRIPTION
**Pull request by dannielraposo**
See the following Jira ticket: [LPD-43285](https://liferay.atlassian.net/browse/LPD-43285)

### CODE REVIEW

**Comment by dannielraposo** [comment]
ci:test:relevant

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:test:relevant

**Review by ccorreagg — APPROVED** [review]

**Comment by dannielraposo** [comment]
ci:stop

**Comment by dannielraposo** [comment]
ci:forward

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:test:relevant

**Comment by dannielraposo** [comment]
ci:stop

**Comment by dannielraposo** [comment]
ci:test:relevant

**Comment by dannielraposo** [comment]
c:test:sf

**Comment by dannielraposo** [comment]
ci:test:relevant

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:forward:force

**Pull request closed without merging**
