### PR TITLE
LPS-204334 Investigate failures of DefaultObjectEntryManagerImplTest.testDeleteObjectEntry

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPS-204334

### CODE REVIEW

**Comment by magjed4289** [comment]
[waiting for object response](https://liferay.slack.com/archives/C026NQPV6TV/p1703578388205859) to proceed knowing the expected behaviour

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]
See my changes.

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
