### PR TITLE
LPS-183109 Return the proper Resource class for the GET_RELATIONSHIP operation in GraphQLDTOContributor

### PR DESCRIPTION
**Pull request by ccorreagg**
Related issue: https://issues.liferay.com/browse/LPS-183109

---

This PR contains the code to return the custom objects related to custom objects in GraphQL when the relationship name is included in the GraphQL request. For that, the JAX-RS Resource implementation class that is in charge of returning the related custom objects to a custom object entry must be returned when the operation is GET_RELATIONSHIP.

cc/ @LuismiBarcos

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:forward:force

**Comment by ccorreagg** [comment]
Thanks @magjed4289 !

**Comment by ccorreagg** [comment]
Forwarded manually: https://github.com/brianchandotcom/liferay-portal/pull/134115

**Pull request closed without merging**
