### PR TITLE
LPS-181945 Move UncategorizedObjectFolder creation to a new PortalInstanceLifecycleListener and move Object dependencies out of Batch Engine

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-181945

---

The purpose of this PR is to fix the problems that we are finding when the UncategorizedObjectFolder is being created because of race condition problems.

cc/ @shuyangzhou

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/141610

**Pull request closed without merging**
