### PR TITLE
[TS] LPS-185578 | Sensible information is exposed when API Explorer is disabled

### PR DESCRIPTION
**Pull request by MirnaGama**
**Steps to reproduce:**

1. Navigate to Control Panel > Configuration > System Settings > Platform > Third Party > API Explorer
2. Disable the API Explorer
3. Access the o/api page

_Expected result:_ User-friendly page that suggest that the API Explorer page is disabled
_Actual result:_ Showing internal details

### CODE REVIEW

**Comment by MirnaGama** [comment]
ci:test

**Comment by MirnaGama** [comment]
ci:stop

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:stop

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hey @MirnaGama thanks so much for this. In the case API Explorer is disabled, the `/o/api` url should behave as any other not found url so we simplified your changes in https://github.com/liferay-headless/liferay-portal/pull/1407.

Please let us know your thoughts there.

**Comment by MirnaGama** [comment]
@4lejandrito Got it. 
In this case, I'll update the LPS description so the expected behavior should be returning 404 when API Explorer is disabled. Thanks !

**Pull request closed without merging**
