### PR TITLE
LPS-173905 Add reference in Portlet as the onAfterSave method of the listener is not called until the configuration is saved for the second time

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to fix [this bug](https://issues.liferay.com/browse/LPS-173905).

The point is, for the first time the Configuration is created/saved, the `@Activate` annotated method is executed, but then, the code of the afterSave method is not executed until it is saved for the second time.

With the current code, when the configuration is created, the listener has been already injected, and then, it is ensuring that the listener is already listening for saving events

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
LGTM :)

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
