### PR TITLE
Fix bug LPS-197285

### PR DESCRIPTION
**Pull request by sergiojimcos**
This PR is rebase from master, stable tests are not executing well.

Jira issue: [LPS-197285](https://liferay.atlassian.net/browse/LPS-197285)

cc/ @cgmonte @naraandrade

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:close

**Comment by magjed4289** [comment]
ci:open

**Comment by magjed4289** [comment]
ci:reopen

**Comment by magjed4289** [comment]
ci:close

**Comment by sergiojimcos** [comment]
sent here to Brian: https://github.com/brianchandotcom/liferay-portal/pull/141465

**Pull request closed without merging**
