### PR TITLE
LPS-184027 Refactor of the HTTPTestUtil.invoke to be accessible from any REST API test

### PR DESCRIPTION
**Pull request by jalber786**
**What's changed:**
- HTTPTestUtil was moved from its original Object module to liferay-portal/portal-test
- Swapped the import of the classes that used the old HTTPTestUtil class
- Deleted repetitive invoke methods and swapped it for the HTTPTestUtil.invoke method

**What's deleted:**
- The previous HTTPTestUtil class was deleted

See the following [Jira Ticket](https://issues.liferay.com/browse/LPS-177591)

### CODE REVIEW

**Review by ccorreagg — COMMENTED** [review]
LGTM!

Have you tested locally? If not, I would launch the CI to ensure there is nothing missing to do extra with the movement

**Comment by jalber786** [comment]
ci:test:sf

**Comment by jalber786** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Test failures are not related. OK to manually forward from qa perspective

**Comment by jalber786** [comment]
ci:forward:force

**Pull request closed without merging**
