### PR TITLE
LPD-25811 Added bottom padding for correct visualization of the permissions options in a publish to live modal

### PR DESCRIPTION
**Pull request by albertojml**
**What's changed?:**
- A bottom padding has been added in order to show the permissions options by adding the "cadmin" style class.
- Some changes/improvements in the style has been made to correct some weird behaviors that appeared while introducing the "cadmin" style class.

**_Before the changes:_**
image

**_After the changes:_**
image

See the following  **Jira ticket**: [LPD-25811](https://liferay.atlassian.net/browse/LPD-25811)

### CODE REVIEW

**Comment by albertojml** [comment]
ci:test:relevant

**Comment by albertojml** [comment]
ci:test:sf

**Comment by albertojml** [comment]
ci:test:relevant

**Review by jaimelr10 — APPROVED** [review]
LGTM!

**Comment by jaimelr10** [comment]
ci:forward

**Comment by albertojml** [comment]
ci:forward:force

**Pull request closed without merging**
