### PR TITLE
LPS-169967 Update testcase to fix the steps

### PR DESCRIPTION
**Pull request by Hijky**
**Background**
Update a testcase to fix the steps in test scenarios

**Test Plan**
Given Subject object definition created
And Given oneToMany accountSubjects relationship created
And Given oneToMany subjectAccounts relationship created
When I request PUT to relate Subject entry to the Account entry with /o/c/subjects/{subjectId}/subjectAccounts/{accountId}
Then subject is not associated to the account in GET /o/headless-admin-user/v1.0/accounts/{accountId}/accountSubjects

**JIRA Link:**
https://issues.liferay.com/browse/LPS-169967

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:relevant

**Comment by Hijky** [comment]
ci:test:headless-functional

**Comment by Hijky** [comment]
The failed are not related to my PR and this case has passed "CanCreateMultipleOneToManyRelationshipsBetweenTwoObjects"

**Review by yanan — APPROVED** [review]

**Comment by magjed4289** [comment]
@Hijky can you please double can the tests in the RetrieveTheRelatedElementsOfSystemObject? The error is the same as in the case you have fixed, maybe the root cause is the same.

**Comment by Hijky** [comment]
> @Hijky can you please double can the tests in the RetrieveTheRelatedElementsOfSystemObject? The error is the same as in the case you have fixed, maybe the root cause is the same. Thanks in advance!

Hi Meg, I checked the tests in the RetrieveTheRelatedElementsOfSystemObject and I thought the tests has no errors, we only need to modify the test scenarios in the ticket. And the error is "No ObjectRelationship exists with the name userSecondFoundations".

**Comment by magjed4289** [comment]
> > @Hijky can you please double can the tests in the RetrieveTheRelatedElementsOfSystemObject? The error is the same as in the case you have fixed, maybe the root cause is the same. Thanks in advance!
> 
> Hi Meg, I checked the tests in the RetrieveTheRelatedElementsOfSystemObject and I thought the tests has no errors, we only need to modify the test scenarios in the ticket. And the error is "No ObjectRelationship exists with the name userSecondFoundations".

That is correct, but right after there's an error:
```
[exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.RetrieveTheRelatedElementsOfSystemObject#CanReturnDetailsInOneToManyRelationshipAfterObjectEntryDeletion] STANDARD_ERROR
[exec]     java.lang.Exception: Missing property in path $['items']
```

**Comment by Hijky** [comment]
Hi Meg, I think this question is because:
`var response = UserAccountAPI.getRelationshipByUserAccountId(
			relationshipName = "${relationshipName}",
			userAccountId = "${userAccountId}");`
we can't get the expect response with this method and the reason is with the get method we also have the error 
`"Executing commands: curl -X GET -H 'accept: application/json' -H 'Content-Type: application/json' -u 'test@liferay.com:test' http://test-1-26-15.lax.liferay.com:8080/o/headless-admin-user/v1.0/user-accounts/46550/userSecondFoundations
     [exec]     {
     [exec]       "status" : "NOT_FOUND",
     [exec]       "title" : "No ObjectRelationship exists with the name userSecondFoundations"
     [exec]     }Finished executing commands."`
So we get the error with "Missing property in path $['items']"

**Comment by magjed4289** [comment]
> Hi @magjed4289, I think this question is because:
> `var response = UserAccountAPI.getRelationshipByUserAccountId( relationshipName = "${relationshipName}", userAccountId = "${userAccountId}");`
> we can't get the expect response with this method and the reason is with the get method we also have the error
> `"Executing commands: curl -X GET -H 'accept: application/json' -H 'Content-Type: application/json' -u 'test@liferay.com:test' http://test-1-26-15.lax.liferay.com:8080/o/headless-admin-user/v1.0/user-accounts/46550/userSecondFoundations [exec] { [exec] "status" : "NOT_FOUND", [exec] "title" : "No ObjectRelationship exists with the name userSecondFoundations" [exec] }Finished executing commands."`
> So we get the error with "Missing property in path $['items']"

Then this is what we need to modify, so our test is running as intended.

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:relevant

**Comment by Hijky** [comment]
ci:test:headless-functional

**Comment by magjed4289** [comment]
ci:test:headless-functional

**Comment by magjed4289** [comment]
@Hijky I have made some changes but I have also commented on the problem [in our channel](https://liferay.slack.com/archives/C03U66A6NNN/p1671644037199879). Let's see if anyone will be able to help us 🤞🏻

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
