### PR TITLE
LPS-201360 Add and update tests on api application in other instance

### PR DESCRIPTION
**Pull request by yanan**
Background:
- Add tests `CannotGetAPIApplicationOfOtherInstance` and `CanGetAPIWithSameErcApplicationDeletedOnAnotherInstance` into integration layer

Jira Ticket
- https://liferay.atlassian.net/browse/LPS-201360

Test Plan
- CanGetAPIWithSameErcApplicationDeletedOnAnotherInstance
    - Given an published API application with endpoint and schema created in default instanceAnd Given a virtual instance is created
    - And Given another published API Application on virtual instance with same erc as the one on default instance
    - When with deleteByExternalReferenceCode and externalReferenceCode to delete the application on default instancet
    - Then the application on default instance is deletedAnd Then the application rest api on virtual instance still works
- CannotGetAPIApplicationOfOtherInstance
    - Given an published API application with endpoint and schema created in default instanceAnd Given a virtual instance is created
    - And Given an published API application created in virtual instance
    - When request getAPIApplicationsPage in virtual instance
    - Then only the API in virtual instance is returned

### CODE REVIEW

**Comment by yanan** [comment]
@4lejandrito @magjed4289 We have a scenario to test api application with same ERC on different instances, I have updated the ERC in our existing test and the test passed locally. Please help review if this is ok, thanks!

**Comment by yanan** [comment]
ci:test:headless-builder:nocompile

**Review by 4lejandrito — APPROVED** [review]

**Comment by yanan** [comment]
Failures are not related

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Comment by yanan** [comment]
ci:forward:force

**Comment by yanan** [comment]
Failure is not related, and it is fixed in another ticket
image

**Pull request closed without merging**
