### PR TITLE
LRQA-81577 | Test Fix for updating a path to ImportExport notification

### PR DESCRIPTION
**Pull request by Hijky**
Background:
Test Fix for updating a path to ImportExport notification

Jira ticket:
https://liferay.atlassian.net/browse/LRQA-81577

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:headless-functional:nocompile

**Review by yanan — APPROVED** [review]

**Comment by yanan** [comment]
Kevin has found the root cause is [LPS-189824](https://liferay.atlassian.net/browse/LPS-189824), so we need this test fix.

**Comment by Hijky** [comment]
ci:test:headless-functional:nocompile

**Comment by Hijky** [comment]
The failures are not related to my PR

**Review by magjed4289 — APPROVED** [review]

**Comment by Hijky** [comment]
ci:forward

**Pull request closed without merging**
