### PR TITLE
LPD-36535 Create nestedFields before ObjectEntry

### PR DESCRIPTION
**Pull request by ZakiMiklos**
https://liferay.atlassian.net/browse/LPD-36535

### CODE REVIEW

**Comment by albertojml** [comment]
ci:test:relevant

**Review by albertojml — CHANGES_REQUESTED** [review]
The fix isn't working. Both entities get created but they don't relate properly.

To test it execute the following curls:

`curl -X 'POST' \
  'http://localhost:8080/o/object-admin/v1.0/object-definitions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -u 'test@liferay.com:test' \
  -d '{
    "enableComments": false,
    "objectRelationships": [],
    "objectFolderExternalReferenceCode": "default",
    "enableCategorization": true,
    "accountEntryRestrictedObjectFieldName": "",
    "objectActions": [],
    "enableLocalization": false,
    "accountEntryRestricted": false,
    "externalReferenceCode": "student-definition",
    "objectFields": [
        {
            "indexed": false,
            "localized": false,
            "objectFieldSettings": [],
            "readOnly": "true",
            "DBType": "String",
            "label": {
                "en_US": "Author"
            },
            "type": "String",
            "required": false,
            "externalReferenceCode": "0978adc8-4456-6b1b-12af-024b772f0537",
            "indexedAsKeyword": false,
            "system": true,
            "indexedLanguageId": "",
            "unique": false,
            "name": "creator",
            "state": false,
            "businessType": "Text",
            "readOnlyConditionExpression": ""
        },
        {
            "indexed": false,
            "localized": false,
            "objectFieldSettings": [],
            "readOnly": "true",
            "DBType": "Date",
            "label": {
                "en_US": "Create Date"
            },
            "type": "Date",
            "required": false,
            "externalReferenceCode": "4a32a58f-0015-f32a-2e49-38cb97ce6ad9",
            "indexedAsKeyword": false,
            "system": true,
            "indexedLanguageId": "",
            "unique": false,
            "name": "createDate",
            "state": false,
            "businessType": "Date",
            "readOnlyConditionExpression": ""
        },
        {
            "indexed": false,
            "localized": false,
            "objectFieldSettings": [],
            "readOnly": "false",
            "DBType": "String",
            "label": {
                "en_US": "External Reference Code"
            },
            "type": "String",
            "required": false,
            "externalReferenceCode": "e7f2bc8a-f5e2-fb96-9230-a974f3337802",
            "indexedAsKeyword": false,
            "system": true,
            "indexedLanguageId": "",
            "unique": false,
            "name": "externalReferenceCode",
            "state": false,
            "businessType": "Text",
            "readOnlyConditionExpression": ""
        },
        {
            "indexed": true,
            "localized": false,
            "objectFieldSettings": [],
            "readOnly": "true",
            "DBType": "Long",
            "label": {
                "en_US": "ID"
            },
            "type": "Long",
            "required": false,
            "externalReferenceCode": "6e8843fe-7a3a-8d5b-b997-a80d725ed8ba",
            "indexedAsKeyword": true,
            "system": true,
            "indexedLanguageId": "",
            "unique": false,
            "name": "id",
            "state": false,
            "businessType": "LongInteger",
            "readOnlyConditionExpression": ""
        },
        {
            "indexed": false,
            "localized": false,
            "objectFieldSettings": [],
            "readOnly": "true",
            "DBType": "Date",
            "label": {
                "en_US": "Modified Date"
            },
            "type": "Date",
            "required": false,
            "externalReferenceCode": "2a5071fd-5934-e209-4256-b1153a4b87dd",
            "indexedAsKeyword": false,
            "system": true,
            "indexedLanguageId": "",
            "unique": false,
            "name": "modifiedDate",
            "state": false,
            "businessType": "Date",
            "readOnlyConditionExpression": ""
        },
        {
            "indexed": false,
            "localized": false,
            "objectFieldSettings": [],
            "readOnly": "true",
            "DBType": "String",
            "label": {
                "en_US": "Status"
            },
            "type": "String",
            "required": false,
            "externalReferenceCode": "60f6e1af-797e-d7fd-450b-df4b4c212bf3",
            "indexedAsKeyword": false,
            "system": true,
            "indexedLanguageId": "",
            "unique": false,
            "name": "status",
            "state": false,
            "businessType": "Text",
            "readOnlyConditionExpression": ""
        },
        {
            "indexed": true,
            "localized": false,
            "objectFieldSettings": [],
            "readOnly": "false",
            "DBType": "String",
            "label": {
                "en_US": "Name"
            },
            "type": "String",
            "required": false,
            "externalReferenceCode": "2af3621f-c41e-eb01-43c3-9c32594df964",
            "indexedAsKeyword": false,
            "system": false,
            "indexedLanguageId": "en_US",
            "unique": false,
            "name": "name",
            "state": false,
            "businessType": "Text",
            "readOnlyConditionExpression": ""
        },
        {
            "relationshipType": "oneToMany",
            "indexed": true,
            "localized": false,
            "objectRelationshipExternalReferenceCode": "c5d4b308-7f51-4893-b550-f0658102a24e",
            "objectFieldSettings": [
                {
                    "name": "objectDefinition1ShortName",
                    "value": "University"
                },
                {
                    "name": "objectRelationshipERCObjectFieldName",
                    "value": "r_universityStudents_c_universityERC"
                }
            ],
            "readOnly": "false",
            "DBType": "Long",
            "label": {
                "en_US": "UniversityStudents"
            },
            "type": "Long",
            "required": false,
            "externalReferenceCode": "807f30da-98ac-2567-a7c7-5cdc8273aa8c",
            "indexedAsKeyword": false,
            "system": false,
            "indexedLanguageId": "",
            "unique": false,
            "name": "r_universityStudents_c_universityId",
            "objectDefinitionExternalReferenceCode1": "university-defintion",
            "state": false,
            "businessType": "Relationship",
            "readOnlyConditionExpression": ""
        }
    ],
    "restContextPath": "/o/c/students",
    "scope": "company",
    "portlet": true,
    "modifiable": true,
    "parameterRequired": false,
    "enableObjectEntryHistory": false,
    "titleObjectFieldName": "id",
    "objectValidationRules": [],
    "active": true,
    "defaultLanguageId": "en_US",
    "enableIndexSearch": true,
    "label": {
        "en_US": "Student"
    },
    "panelCategoryKey": "",
    "pluralLabel": {
        "en_US": "Students"
    },
    "objectLayouts": [],
    "system": false,
    "objectViews": [],
    "enableObjectEntryDraft": false,
    "name": "Student",
    "actions": {
        "permissions": {},
        "get": {},
        "update": {},
        "delete": {},
        "exportObjectDefinition": {}
    },
    "status": {
        "label_i18n": "Approved",
        "code": 0,
        "label": "approved"
    }
}'

curl -X 'POST' \
  'http://localhost:8080/o/object-admin/v1.0/object-definitions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -u 'test@liferay.com:test' \
  -d '{
    "enableComments": false,
    "objectRelationships": [
        {
            "objectDefinitionSystem2": false,
            "objectField": {
                "relationshipType": "oneToMany",
                "indexed": true,
                "localized": false,
                "objectRelationshipExternalReferenceCode": "c5d4b308-7f51-4893-b550-f0658102a24e",
                "objectFieldSettings": [
                    {
                        "name": "objectDefinition1ShortName",
                        "value": "University"
                    },
                    {
                        "name": "objectRelationshipERCObjectFieldName",
                        "value": "r_universityStudents_c_universityERC"
                    }
                ],
                "readOnly": "false",
                "DBType": "Long",
                "label": {
                    "en_US": "UniversityStudents"
                },
                "type": "Long",
                "required": false,
                "externalReferenceCode": "807f30da-98ac-2567-a7c7-5cdc8273aa8c",
                "indexedAsKeyword": false,
                "system": false,
                "indexedLanguageId": "",
                "unique": false,
                "name": "r_universityStudents_c_universityId",
                "objectDefinitionExternalReferenceCode1": "university-defintion",
                "state": false,
                "businessType": "Relationship",
                "readOnlyConditionExpression": ""
            },
            "parameterObjectFieldName": "",
            "parameterObjectFieldId": 0,
            "label": {
                "en_US": "UniversityStudents"
            },
            "reverse": false,
            "type": "oneToMany",
            "externalReferenceCode": "c5d4b308-7f51-4893-b550-f0658102a24e",
            "objectDefinitionModifiable2": true,
            "system": false,
            "name": "universityStudents",
            "deletionType": "prevent",
            "objectDefinitionExternalReferenceCode1": "university-defintion",
            "objectDefinitionExternalReferenceCode2": "student-definition",
            "objectDefinitionName2": "Student"
        }
    ],
    "objectFolderExternalReferenceCode": "default",
    "enableCategorization": true,
    "accountEntryRestrictedObjectFieldName": "",
    "objectActions": [],
    "enableLocalization": false,
    "accountEntryRestricted": false,
    "externalReferenceCode": "university-defintion",
    "objectFields": [
        {
            "indexed": false,
            "localized": false,
            "objectFieldSettings": [],
            "readOnly": "true",
            "DBType": "String",
            "label": {
                "en_US": "Author"
            },
            "type": "String",
            "required": false,
            "externalReferenceCode": "269222e8-2849-9483-1248-fdc7a294d1d4",
            "indexedAsKeyword": false,
            "system": true,
            "indexedLanguageId": "",
            "unique": false,
            "name": "creator",
            "state": false,
            "businessType": "Text",
            "readOnlyConditionExpression": ""
        },
        {
            "indexed": false,
            "localized": false,
            "objectFieldSettings": [],
            "readOnly": "true",
            "DBType": "Date",
            "label": {
                "en_US": "Create Date"
            },
            "type": "Date",
            "required": false,
            "externalReferenceCode": "c16740c8-fecc-70a5-d7a0-8763036fc60c",
            "indexedAsKeyword": false,
            "system": true,
            "indexedLanguageId": "",
            "unique": false,
            "name": "createDate",
            "state": false,
            "businessType": "Date",
            "readOnlyConditionExpression": ""
        },
        {
            "indexed": false,
            "localized": false,
            "objectFieldSettings": [],
            "readOnly": "false",
            "DBType": "String",
            "label": {
                "en_US": "External Reference Code"
            },
            "type": "String",
            "required": false,
            "externalReferenceCode": "a07a6825-2913-b8fb-5728-d168b6821887",
            "indexedAsKeyword": false,
            "system": true,
            "indexedLanguageId": "",
            "unique": false,
            "name": "externalReferenceCode",
            "state": false,
            "businessType": "Text",
            "readOnlyConditionExpression": ""
        },
        {
            "indexed": true,
            "localized": false,
            "objectFieldSettings": [],
            "readOnly": "true",
            "DBType": "Long",
            "label": {
                "en_US": "ID"
            },
            "type": "Long",
            "required": false,
            "externalReferenceCode": "976e9153-09e4-93dc-60b9-9ae508d6ffd6",
            "indexedAsKeyword": true,
            "system": true,
            "indexedLanguageId": "",
            "unique": false,
            "name": "id",
            "state": false,
            "businessType": "LongInteger",
            "readOnlyConditionExpression": ""
        },
        {
            "indexed": false,
            "localized": false,
            "objectFieldSettings": [],
            "readOnly": "true",
            "DBType": "Date",
            "label": {
                "en_US": "Modified Date"
            },
            "type": "Date",
            "required": false,
            "externalReferenceCode": "5785775c-c55e-0a84-c692-3f5ba06d4c32",
            "indexedAsKeyword": false,
            "system": true,
            "indexedLanguageId": "",
            "unique": false,
            "name": "modifiedDate",
            "state": false,
            "businessType": "Date",
            "readOnlyConditionExpression": ""
        },
        {
            "indexed": false,
            "localized": false,
            "objectFieldSettings": [],
            "readOnly": "true",
            "DBType": "String",
            "label": {
                "en_US": "Status"
            },
            "type": "String",
            "required": false,
            "externalReferenceCode": "b332cfd7-aa1b-b722-7f12-b1bee80bfada",
            "indexedAsKeyword": false,
            "system": true,
            "indexedLanguageId": "",
            "unique": false,
            "name": "status",
            "state": false,
            "businessType": "Text",
            "readOnlyConditionExpression": ""
        },
        {
            "indexed": true,
            "localized": false,
            "objectFieldSettings": [],
            "readOnly": "false",
            "DBType": "String",
            "label": {
                "en_US": "Name"
            },
            "type": "String",
            "required": false,
            "externalReferenceCode": "8c2f78fb-838f-2cf1-2978-b9c1f3dadee2",
            "indexedAsKeyword": false,
            "system": false,
            "indexedLanguageId": "en_US",
            "unique": false,
            "name": "name",
            "state": false,
            "businessType": "Text",
            "readOnlyConditionExpression": ""
        }
    ],
    "restContextPath": "/o/c/universities",
    "scope": "company",
    "portlet": true,
    "modifiable": true,
    "parameterRequired": false,
    "enableObjectEntryHistory": false,
    "titleObjectFieldName": "id",
    "objectValidationRules": [],
    "active": true,
    "defaultLanguageId": "en_US",
    "enableIndexSearch": true,
    "label": {
        "en_US": "University"
    },
    "panelCategoryKey": "",
    "pluralLabel": {
        "en_US": "Universities"
    },
    "objectLayouts": [],
    "system": false,
    "objectViews": [],
    "enableObjectEntryDraft": false,
    "name": "University",
    "actions": {
        "permissions": {},
        "get": {},
        "update": {},
        "delete": {},
        "exportObjectDefinition": {}
    },
    "status": {
        "label_i18n": "Approved",
        "code": 0,
        "label": "approved"
    }
}'`

Then make the relationship mandatory and make sure both object definitions are published.

Once this is done, execute the following curl:

`curl -X 'POST' \
  'http://localhost:8080/o/c/students/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -u 'test@liferay.com:test' \
  -d '{
  "externalReferenceCode": "Alex",
  "name": "Alex",
  "universityStudents": {
    "externalReferenceCode": "UAM",
    "name": "UAM"
  }
}'`

You will see in the result and in the database that the object entries don't get related properly.

**Comment by albertojml** [comment]
Also, remember to always execute the relevant suite when sending a pull request @ZakiMiklos.

**Comment by ZakiMiklos** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
@ZakiMiklos @albertojml  Is this PR in progress? Should it be reviewed? If not, please close it and open a new one  when you consider it is ready

**Comment by albertojml** [comment]
Closing this PR because its solution is being solved by [LPD-37768](https://liferay.atlassian.net/browse/LPD-37768) and this other PR https://github.com/liferay-headless/liferay-portal/pull/2300

**Pull request closed without merging**
