### PR TITLE
LPD-37768 | Allow creating nested object entries with mandatory one to many relationships

### PR DESCRIPTION
**Pull request by jaimelr10**
**Description**: Fix error where we couldnt create a nested object entry on a mandatory one to many relationship as the curl:
```
curl -X POST \
     -u test@liferay.com:test \
     http://localhost:8080/o/c/students \
     -H 'Content-type: application/json' \
     -d '{"studentName": "student5", "universityStudents": {"universityName": "university", "externalReferenceCode": "entry1_erc"}}'
```
Gave us the error 
```
{
  "status" : "BAD_REQUEST",
  "title" : "No value was provided for required object field \"r_universityStudents_c_universityId\""
}
```

**Jira Ticket**: https://liferay.atlassian.net/browse/LPD-37768

### CODE REVIEW

**Comment by jaimelr10** [comment]
ci:stop

**Comment by jaimelr10** [comment]
ci:test:relevant

**Comment by jaimelr10** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
@albertojml could you have a look at this PR? As it is also related with the PR that Miklos is working on

**Comment by albertojml** [comment]
Closing because it is being reworked on another branch

**Pull request closed without merging**
