### PR TITLE
LPS-196858 Remove readOnly flag from externalReferenceCode ObjectEntry field

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-196857

---

The purpose of this PR is to remove the `readOnly: true` parameter of the ObjectEntry schema of the Custom Objects REST API as the field is not currently read only. Furthermore, the ObjectMapper is not parsing the field when deserializing as it is marked as read only

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by matijapetanjek — APPROVED** [review]
LGTM!!

**Comment by Hijky** [comment]
The failures are not related to your PR, it's okay to forward it.

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
