### PR TITLE
LPS-204377 Update path for OAuth2 client id and client secret

### PR DESCRIPTION
**Pull request by yanan**
Test fix for LocalFile.ScopeObjectAPIsForDifferentInstances test cases because of LPS-200609

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-functional

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Review by magjed4289 — APPROVED** [review]

**Comment by yanan** [comment]
Failures are not related
image

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
