### PR TITLE
LPS-161704 Getting the right definitions and relationships

### PR DESCRIPTION
**Pull request by 4lejandrito**
We were getting the wrong object definition and relationship in some cases.

### CODE REVIEW

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) 👏 👏 👏 
Let's see what Brian thinks about the new method in the object relationship service. For me makes sense.

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/123102

**Comment by 4lejandrito** [comment]
Pushed forced with changes requested by https://github.com/liferay-headless/liferay-portal/pull/735. @LuismiBarcos please review.

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) 👏 👏 👏

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/123344

**Pull request closed without merging**
