### PR TITLE
LPS 114962 Removed questions number in Cards from the Questions' Home.

### PR DESCRIPTION
**Pull request by dgomezg**
@nhpatt

### CODE REVIEW

**Comment by dgomezg** [comment]
I've changed back to 12 columns the search results banner and restored the questions count, but adding a specific class that will allow me to hide that with CSS on the community site.

**Comment by dgomezg** [comment]
@nhpatt

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
Resent here: https://github.com/liferay-headless/liferay-portal/pull/165

**Pull request closed without merging**
