### PR TITLE
LPD-35429 BatchEngineBrokerTest test fix

### PR DESCRIPTION
**Pull request by ZakiMiklos**
https://liferay.atlassian.net/browse/LPD-35381

### CODE REVIEW

**Comment by 4lejandrito** [comment]
I just push forced because I found out the java changes make no difference at all. The change in the CSV alone fixes the test. @magjed4289 @ZakiMiklos can you investigate why? Bear in mind the change is correct because the multiline field was there on purpose before @magjed4289 changed it in the first place. I just wonder why that passed at some point and is now failing.

**Comment by magjed4289** [comment]
Thanks @4lejandrito , I'll try to pass RCA to detect why this happened.

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/154073

**Pull request closed without merging**
