### PR TITLE
LPS-171473 First approach of the APIBuilder by providing a JAX-RS Application to reach the desired operation

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to provide a way to register and invoke an API Builder Operation. For that, several modules have been created:

- **apibuilder-api**: It contains all the interfaces that are involved in the API Builder lifecycle. The most important ones are:
  - `Operation`: is the element that contains all the related elements of an API Builder operation (input, output, type of operation, schemas involved, etc).
  - `OperationContext`: is filled with each invocation.
  - `OperationHandler`: handles an `Operation` with its `OperationContext`
  - `OperationProvider`: provides (if any) an available `Operation` given certain request parameters
  - `OperationRegistrator`: registers/unregisters an `Operation`
  - `OperationHandlerRegistry`: contains a Registry of all the `OperationHandler` interfaces.
- **apibuilder-service**: It contains the implementation of the interfaces.
- **apibuilder-rest-api**: It contains the interface `OpenAPIYAMLOperationsProvider` that will provide a list of Operation from the input OpenAPI YAML object.
- **apibuilder-rest-impl**: It contains the implementation of the interface. Also, it exposes a JAX-RS Application and Resource to attend the request of a given Operation that has previously deployed.
- **apibuilder-rest-test**: It contains several integration tests to check the first approach

**NOTE: All the functionality is under the feature flag **`feature.flag.LPS-171047`****

---

### How the Operation is build:

Everything starts from a OpenAPI v3.0.1 file, by including several Liferay custom fields. See the example of the test module

```
components:
    schemas:
        BlogEntry:
            properties:
                alternativeHeadline:
                    description:
                        The blog post's subtitle.
                    type: string
                    x-field-definition:
                        name: subtitle
                [...]
                id:
                    description:
                        The blog post's identifier.
                    format: int64
                    readOnly: true
                    type: integer
                    x-field-definition:
                        name: entryId
                siteId:
                    description:
                        The ID of the site to which this blog post is scoped.
                    format: int64
                    readOnly: true
                    type: integer
                    x-field-definition:
                        name: groupId
            x-schema-definition:
                entityName: "com.liferay.blogs.model.BlogsEntry"
info:
            [...]
openapi: "3.0.1"
paths:
    "/blogs/{id}":
        get:
            [...]
            parameters:
                - in: path
                  name: id
            [...]
            x-operation-definition:
                type: "getByPrimaryKey"
```
Each pair [path-method] (in this example, [`/blogs/{id}` - `GET`] must contain a parameter `x-operation-definition` that must include a parameter `type` with the type of operation (the `OperationHandler` must be deployed with the same value for the property name `operation.name`).

Each Schema must contain a parameter `x-schema-definition` that must include a parameter `entityName` with the name of the Liferay internal entity that must be managed.

Each single parameter of the Schema must contain a parameter `x-field-definition` that must include a parameter `name` with the name of the field that is returned by the Info Framework for the given entity.

As there were no primary keys identification in Info Framework, a new Field Type has been included for it.

---

### How the data of the Liferay element is returned:

The Info Framework (`info-util` packages) is being used to return in this first approach the data of a given element, in the test example, a BlogEntry. So, for being able to provide certain fields of a given Liferay element, it is necessary to have, by now, at least an implementation of the `InfoItemFormProvider`, `InfoItemObjectProvider` and `InfoItemFieldValuesProvider` (probably in the future more implementations of different interfaces will be necessary).

```
InfoItemObjectProvider<?> infoItemObjectProvider =
	APIBuilderUtil.getInfoItemService(
		objectSchema.getClassName(), InfoItemObjectProvider.class);

long primaryKey = GetterUtil.getLong(attributeValue.getValue());

try {
	Object object = infoItemObjectProvider.getInfoItem(primaryKey);

	InfoItemFieldValuesProvider infoItemFieldValuesProvider =
		APIBuilderUtil.getInfoItemService(
			objectSchema.getClassName(),
			InfoItemFieldValuesProvider.class);

	InfoItemFieldValues infoItemFieldValues =
		infoItemFieldValuesProvider.getInfoItemFieldValues(object);

	return new SuccessfulOperationResponse(
		APIBuilderUtil.toAPIBuilderEntry(
			infoItemFieldValues.getInfoFieldValues(), primaryKey,
			objectSchema.getName()),
		schema);
```

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-headless/liferay-portal/pull/1048.

**Pull request closed without merging**
