### PR TITLE
LPD-37283 Increase 15 seconds to the cronExpression to avoid possible edge cases (in between minutes, etc)

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPD-37283

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:headless

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:headless

**Comment by magjed4289** [comment]
retesting [here](https://test-1-1.liferay.com/job/root-cause-analysis-tool/14196/) to confirm the test is stabilized.

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
