### PR TITLE
LPS-155081 Headless APIs miss error message when fail

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:reevaluate:1297401_5781

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
LGTM :)

We have to take into account what we've talked about in [this thread](https://liferay.slack.com/archives/C03U66A6NNN/p1671448128985359) internally (not posting here for security reasons, just in case 😁 )

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by magjed4289** [comment]
Test failures are not related, OK to manually forward! 👌🏻

**Comment by matijapetanjek** [comment]
Manually sent here https://github.com/brianchandotcom/liferay-portal/pull/127984

**Pull request closed without merging**
