### PR TITLE
LPD-37289 Fix ImportExport#GetImportFileAvailableEntityTypes and ImportExport#GetExportFileAvailableEntityTypes

### PR DESCRIPTION
**Pull request by dannielraposo**
**What's changed?**
The `assertAvailableEntityType` macro was not correctly verifying the presence of the queried option in the select. This update modifies the macro's path to ensure it accurately checks for the inclusion of the specified option.

See the following Jira Ticket: [LPD-37289](https://liferay.atlassian.net/browse/LPD-37289)

### CODE REVIEW

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:test:relevant

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by dannielraposo** [comment]
ci:forward

**Pull request closed without merging**
