### PR TITLE
LPS-193414 Reindex to make sure tests on API Builder more stable

### PR DESCRIPTION
**Pull request by yanan**

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Review by magjed4289 — APPROVED** [review]

**Review by Hijky — APPROVED** [review]

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
