### PR TITLE
LPS-167995 Fix companyId scopes for Custom Objects

### PR DESCRIPTION
**Pull request by ccorreagg**

### CODE REVIEW

**Comment by ccorreagg** [comment]
cc/ @stian-sigvartsen @4lejandrito @LuismiBarcos

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by stian-sigvartsen** [comment]
To update the discussion here based on my offline conversations with @ccorreagg ...

The issue with this PR is that it introduces a new SPI in the OAuth 2 Provider which mostly duplicates the existing `ScopeFinder` SPI which supports company scoping also. This will be confusing, and unnecessary because if Objects registers its JAX-RS `Application` OSGi services with `companyId`(s), this will propagate to the `ScopeFinder` services that get automatically registered by the OAuth 2 provider.

We are collaborating on this approach here at liferay-appsec/liferay-portal/pull/916

**Comment by stian-sigvartsen** [comment]
I have tested the CI bundle locally and the issue with JAX-RS Applications not starting is not reproducible.
There are only minimal `ci:test:relevant` failures. As agreed with @ccorreagg on Friday, we will send this PR for merge.

The OAuth 2 provider test failures might be genuine, but not critical enough to hold this PR back. I will investigate them next week.

**Comment by 4lejandrito** [comment]
@ccorreagg can we close this?

**Comment by ccorreagg** [comment]
Yes! Closing it. Already merged in master, it is possible to follow the PRs from the PR that Stian talked about in his last comment.

Thank you everyone!

**Pull request closed without merging**
