### PR TITLE
LPS-192030 Copy URL of an endpoint doesn't work correctly on a virtual instance

### PR DESCRIPTION
**Pull request by sergiojimcos**
**Purpose**
The main purpose of this PR is to allow users to use the `Copy URL` action in API Endpoint when the instance is in a secure context. Without this changes, the clipboard object is going to be set as `undefined`. If you want to know more information about that you can check it [here](https://stackoverflow.com/questions/51805395/navigator-clipboard-is-undefined). So, when the context is secured, the action will be displayed.

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPS-192030

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by Hijky** [comment]
The failures are not related to your PR, this is the [compared results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2409429027&testrayRunIdA=2409601959&statusB=2), you can forward it

**Comment by sergiojimcos** [comment]
ci:forward:force

**Pull request closed without merging**
