### PR TITLE
LPD-36693 Fixing openapi.json endpoint format

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPD-36693.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Review by LuisOrtiz89 — APPROVED** [review]
Code looks good to me. Let's run the tests and check the results.

**Comment by LuisOrtiz89** [comment]
ci:test:sf

**Comment by LuisOrtiz89** [comment]
ci:help

**Comment by LuisOrtiz89** [comment]
ci:test:headless-acceptance

**Comment by LuisOrtiz89** [comment]
ci:stop

**Comment by LuisOrtiz89** [comment]
ci:test:headless-acceptance

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
