### PR TITLE
LPS-190723: Create a new validation that a Endpoint path should start with "/" 

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Update regular expression to add API Endpoint path, starting with "/".
- Update some test cases applying this change.

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPS-190723

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by 4lejandrito — COMMENTED** [review]
@sergiojimcos will this affect the frontend? Do they have to add the `/` to their POST requests?

**Comment by sergiojimcos** [comment]
> will this affect the frontend?

@4lejandrito I think that UI should catch the exception when an user doesn't insert the `/` in the UI

**Comment by 4lejandrito** [comment]
This has to take that into account. @cgmonte can we force the slash in the frontend? Maybe Sergio can do it.

**Comment by cgmonte** [comment]
> This has to take that into account. @cgmonte can we force the slash in the frontend? Maybe Sergio can do it.

[There is already a function for that](https://github.com/liferay/liferay-portal/blob/master/modules/apps/headless/headless-builder/headless-builder-web/src/main/resources/META-INF/resources/js/components/utils/string.ts#L18).

If a string doesn't start with a forward slash, it adds it. Is that we are looking for, right?

Currently, this is called only when displaying the path cell in FDS, not before sending the POST request. We need to call that function before requesting POST and it will do what we are looking for. We can force at the UI field level, as well, but that can be a little weird to the user (or not, I am not sure).

**Comment by sergiojimcos** [comment]
> > This has to take that into account. @cgmonte can we force the slash in the frontend? Maybe Sergio can do it.
> 
> [There is already a function for that](https://github.com/liferay/liferay-portal/blob/master/modules/apps/headless/headless-builder/headless-builder-web/src/main/resources/META-INF/resources/js/components/utils/string.ts#L18).
> 
> If a string doesn't start with a forward slash, it adds it. Is that we are looking for, right?
> 
> Currently, this is called only when displaying the path cell in FDS, not before sending the POST request. We need to call that function before requesting POST and it will do what we are looking for. We can force at the UI field level, as well, but that can be a little weird to the user (or not, I am not sure).

What we are trying is to add a validation that if an user doesn't introduce the endpoint path starting with a `/` it will throw an error of validation that it should start with it. I think that in the UI part, this could be covered by using the method that @cgmonte  implemented but I'm aware of the API part, because we should have to validate in that part not hardcoding the `/`. What do you think @4lejandrito?

**Comment by 4lejandrito** [comment]
I think the frontend should add the initial `/` automatically so that users don't have to type it.

**Comment by 4lejandrito** [comment]
@cgmonte, @sergiojimcos can you do it as part of this PR so that we send all in one?

**Comment by cgmonte** [comment]
OK, I am not sure if this is what you are looking for, but I sent a PR to myself with the change:

https://github.com/cgmonte/liferay-portal/pull/74

The back-end does not allow a slash character in baseURL string, I get this error:

> Base URL can have a maximum of 255 alphanumeric characters.

Sent to this endpoint: `http://localhost:8080/o/headless-builder/applications/`

Wrong endpoint, I think. Are we talking about `http://localhost:8080/o/headless-builder/endpoints/`?

If so,  there is nothing to do on the front-end, because stories for creating and editing endpoints were not developed yet.

Am I missing something? Let me know. Thanks :)

**Comment by 4lejandrito** [comment]
@cgmonte with the changes on this PR the slash will be allowed as first character. Did you deploy the `-impl` module?

**Comment by 4lejandrito** [comment]
Also, we need to update the input description to indicate the slash is going to be added automatically (the url portion at the top of the input).

**Comment by 4lejandrito** [comment]
For now we will forward this, and @cgmonte you can send a separate pull. If you need to chat about this feel free to ping us on slack.

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
