### PR TITLE
LPS-196277 Throw an IOException instead of a WebApplicationException when an error happens when setting the extended properties to avoid returning a 500 error always

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-196277

---

The purpose of this PR is to avoid returning an Internal Server Error 500 when the `entityExtensionHandler.setExtendedProperties` invocation of the `EntityExtensionContainerResponseFilter` class fails. The http error code is returned as the exception thrown is `WebApplicationException`. As there is a `WebApplicationExceptionMapper` that maps the exception into the 500 code, we need another approach.

As the `filter` method of the `ContainerResponseFilter` throws an IOException, we have encapsulated the caught exception into an IOException and then, the [ExceptionMapper](https://github.com/liferay/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/apps/portal-vulcan/portal-vulcan-impl/src/main/java/com/liferay/portal/vulcan/internal/jaxrs/exception/mapper/ExceptionMapper.java#L20) will manage the exception and based on the cause, it gets the ExceptionMapper that must manage the cause exception and will return the HTTP code and the message body that applies to that case.

In order to make available all the ExceptionMappers Object Entries related, we deploy also the ExceptionMappers, apart from the Custom Object REST APIs, into the Unmodifiable System Object REST APIs. That means the ExceptionMapper will be available for every REST APIs of Objects, not only Custom Objects but also Unmodifiable System Objects.

cc/ @jgarcialr

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Included new commit with the test modified as now the ExceptionMapper is a different one, so we need to catch the log

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by Hijky** [comment]
Test failures are not related. OK to manually forward :white_check_mark:

**Review by 4lejandrito — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
