### PR TITLE
 LPD-37770  Modify export-import/staging infrastructure to support disable data handlers

### PR DESCRIPTION
**Pull request by Mikellorza**
Hi @DaniSzimko ,

I am reseding the PR again in response to [Brian's comment](https://github.com/brianchandotcom/liferay-portal/pull/155037#issuecomment-2405555957). So, for that, I have created the tests in a different way. You can see these changes in the last 3 commits.

# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-37770

Hi team,

Working on deprecating wiki from the portal, we have the need to hide wiki from the export-import/staging process. So, this PR include all necessary changes to support disable data handlers in order to do not import/export staged data models neither portlet data models

# How am I fixing it?

Adding isEnabled method to portlet and staged model data handlers interfaces and use it in base implementations in order to exclude wiki model and portlets from the export-import process.

# How can you verify that it works?

Run included tests.

### CODE REVIEW

**Comment by DaniSzimko** [comment]
Hello @Mikellorza ,
I reviewed the code and ran the integration tests. Everything looks good to me.

**Review by DaniSzimko — APPROVED** [review]

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:headless-staging

**Comment by Mikellorza** [comment]
ci:report:50716099

**Comment by Mikellorza** [comment]
Hi team,

I've  analyzed the issues and there is only  a semantic issue related to this PR. I've just added a [commit](https://github.com/liferay-headless/liferay-portal/pull/2268/commits/0df0254f75d0e05983ecdea7a244fac96dfb43a7) to fix it.

Regards!

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:headless-staging

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
ci:report:52336702

**Comment by Mikellorza** [comment]
There are not related issues with this PR. So, let's move to Brian!

**Comment by Mikellorza** [comment]
ci:forward:force

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
