### PR TITLE
LPD-16008 Add Data Migration Center Lang Keys

### PR DESCRIPTION
**Pull request by matijapetanjek**
Before PR:
image (1)

After PR:
Screenshot from 2024-01-31 15-35-57

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:stop

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:forward:force

**Pull request closed without merging**
