### PR TITLE
LPD-26417 Initial data is not propagated if conflict on friendlyURL when switching to a different site template using `LayoutSetLocalServiceUtil.updateLayoutSetPrototypeLinkEnabled()`

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-26417

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:help

**Comment by magjed4289** [comment]
ci:test:headless-staging

**Comment by magjed4289** [comment]
ci:test:headless-staging

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:playwright

**Comment by magjed4289** [comment]
ci:test:playwright

**Comment by magjed4289** [comment]
ci:test:headless-aaa

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:headless-aaa

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:forward

**Comment by magjed4289** [comment]
ci:forward

**Review by vendeltoreki — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:close

**Comment by magjed4289** [comment]
ci:reopen

**Pull request closed without merging**
