### PR TITLE
LPD-33245 Test for site initializer

### PR DESCRIPTION
**Pull request by LuisOrtiz89**
This test is executed for each available site initializer, and not just for "Masterclass".
The way it works is:
- Create a new site with one of the site initializers.
- Open that new site.
- Enable Local staging with the default configuration.
- Access the Live version of the Home page and take a screenshot.
- Access the Staging version of the Home page and take a screenshot.
- Compare both screenshots. They should have less than 5% pixels different (this value can be easily changed).

The problem is that all tests fails because one of the next reasons:
- The Live and Staging versions of the page have different size. Normally the difference is just 2 pixel height, but it is enough for the comparator to consider them different, even if the number of pixels difference is less than 5% previously configured.
- The Live and Staging versions of the page are different (for example, collections displays do not seem to be working fine).
- There is a timeout when opening the staging window. This does not happen when executing the tests in debug mode... So I am not sure how to solve it.
- Some site initializers fail during site creation. I tested all of them manually and all of they work (activating previously the script execution), but when running the tests, for some reason, they cannot be created.

### CODE REVIEW

**Comment by LuisOrtiz89** [comment]
ci:test:relevant

**Comment by LuisOrtiz89** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
@LuisOrtiz89 see https://github.com/liferay-headless/liferay-portal/pull/2160/commits/c4ac06f0bd561e079d4ad9a918c9f3023ded697a. Using `p_l_mode=preview` renders the page without the menus and removes the position issues. The `welcome` site initializer is now passing, focus on the others. Feel free to go back to the `screenshot` method instead of the snapshots. Snapshots are easier for debugging.

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
See my comment.

**Comment by LuisOrtiz89** [comment]
ci:test:playwright

**Comment by LuisOrtiz89** [comment]
See https://github.com/liferay-headless/liferay-portal/pull/2170

**Pull request closed without merging**
