### PR TITLE
Lps 183986 | Add tests for story  LPS-161981 - Allow developers to export entities in a format that includes the actions

### PR DESCRIPTION
**Pull request by yanan**
Background
- Add test for story LPS-161981 and include https://github.com/liferay-headless/liferay-portal/pull/1223

Jira Ticket:
- https://issues.liferay.com/browse/LPS-183986

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Review by magjed4289 — APPROVED** [review]

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
