### PR TITLE
LPD-1735 The external reference code for schema should be unique

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-1735

see https://github.com/liferay-headless/liferay-portal/pull/1905

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
issue moved to BPM team

**Comment by magjed4289** [comment]
ci:reopen

**Comment by magjed4289** [comment]
discussed [here](https://liferay.slack.com/archives/C03U66A6NNN/p1709133001411229)

**Comment by ccorreagg** [comment]
I think we are not doing the proper approach, as it is just a requirement in the API Builder side, not Object's related. Closing the PR, we will open a new one with a better approach

**Pull request closed without merging**
