### PR TITLE
LPD-26141: Remove ignore annotation in functional test cases

### PR DESCRIPTION
**Pull request by sergiojimcos**
**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPD-26141

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/150721

**Comment by 4lejandrito** [comment]
The 3 tests are passing locally.

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/150722

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/150723.

**Pull request closed without merging**
