### PR TITLE
LPS-140570 Publish link for staging includes unwanted parameters

### PR DESCRIPTION
**Pull request by vendeltoreki**
[LPS-140570](https://liferay.atlassian.net/browse/LPS-140570)

When using remote staging and simple publish, don't use the `remoteAddress` and `remotePort` parameters from the link, but load them from the remote staging site's settings.

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Failures in relevant and stating are not related to the pr, ok to forward
- [relevant compare run results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2469182737&testrayRunIdA=2470085584&statusB=2)
    - com.liferay.redirect.service.test.RedirectNotFoundEntryLocalServiceTest passed on a second run
- [staging compare run results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2469182737&testrayRunIdA=2470068857&statusB=2)
    - testSemanticVersioning[ failed in apps/object/object-api, should be fixed in latest master

**Comment by vendeltoreki** [comment]
ci:forward:force

**Pull request closed without merging**
