### PR TITLE
LPD-28845 Site Admin API with fixes [WIP]

### PR DESCRIPTION
**Pull request by albertojml**
This PR belongs to the Echo team. This includes the fixes/modifications I needed to make in order to make all the API modules compile.

### CODE REVIEW

**Comment by albertojml** [comment]
ci:test:sf

**Comment by albertojml** [comment]
ci:test:sf

**Comment by albertojml** [comment]
New changes based on Brian's suggestions. See [this comment](https://github.com/brianchandotcom/liferay-portal/pull/153098#issuecomment-2284707099) for more information.

**Comment by albertojml** [comment]
ci:test:sf

**Comment by albertojml** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
@ruben-pulido is already working on this with our fixes applied. Closing.

**Pull request closed without merging**
