### PR TITLE
LPS-161704 Fix query including a parenthesis when OR is executed

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to fix the query that gets the object relationship based on the object id and the relationship name

**Before the PR**:

The query returned randomly one of the relationships of the object

```
select * from ObjectRelationship
where ObjectRelationship.reverse = ?
and ObjectRelationship.name = ?
and ObjectRelationship.objectDefinitionId1 = ?
or ObjectRelationship.objectDefinitionId2 = ?
```

**After the PR**:

The query returns the desired relationship

```
select * from ObjectRelationship
where ObjectRelationship.reverse = ?
and ObjectRelationship.name = ?
and (ObjectRelationship.objectDefinitionId1 = ? or ObjectRelationship.objectDefinitionId2 = ?)
```

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Review by 4lejandrito — APPROVED** [review]
Nice catch! Thank you!

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/123580

**Pull request closed without merging**
