### PR TITLE
LPD-35336 Technical Task | Improve OpenAPI schema setting filterable fields

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-35336

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
@ccorreagg I can see some test failures are related to my changes, so I will analyse them

**Comment by ccorreagg** [comment]
Let's close it for now, reopen when we start working on it again

**Pull request closed without merging**
