### PR TITLE
LPS-197392 | Automation - Edit an API Application Schemas

### PR DESCRIPTION
**Pull request by pedroamarall**
Ticket: [LPS-197392](https://liferay.atlassian.net/browse/LPS-197392)

Some points:

- I only considered one test when I came across the BDD of the CanGoBackToSchemasListWithCanelEdit and CanGoBackToSchemasListWithCanelEdit tests. Because there is no "continue" button when you cancel a Schema edit before publishing.

- I will need to run the Headless suite since I have not been able to run the test on my machine, but to avoid delay, I created the tests and sent this pr. I created this [ticket](https://liferay.atlassian.net/browse/LPS-200269) reporting the problem and found this [threed](https://liferay.slack.com/archives/C5E1CRLJY/p1695633513230839?thread_ts=1695633386.372899&cid=C5E1CRLJY) reporting the same thing. I continue to investigate...

### CODE REVIEW

**Comment by pedroamarall** [comment]
ci:test:relevant

**Comment by pedroamarall** [comment]
ci:help

**Comment by pedroamarall** [comment]
ci:test:headless

**Comment by pedroamarall** [comment]
ci:stop

**Comment by pedroamarall** [comment]
ci:test:sf

**Comment by pedroamarall** [comment]
ci:stop:sf

**Comment by pedroamarall** [comment]
ci:stop:relevant

**Comment by pedroamarall** [comment]
ci:test:sf

**Comment by pedroamarall** [comment]
ci:test:relevant

**Comment by pedroamarall** [comment]
ci:test:headless

**Comment by pedroamarall** [comment]
ci:test:sf

**Comment by pedroamarall** [comment]
ci:test:relevant

**Comment by pedroamarall** [comment]
ci:test:sf

**Comment by pedroamarall** [comment]
ci:test:relevant

**Comment by pedroamarall** [comment]
ci:test:headless

**Comment by pedroamarall** [comment]
ci:stop:relevant

**Comment by pedroamarall** [comment]
ci:test:headless

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:test:headless-builder-functional:nocompile

**Comment by magjed4289** [comment]
> ci:test:headless-builder-functional:nocompile

@pedroamarall please use this test suite for running API Builder tests

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
@pedroamarall could you please take a look at the sf errors and modify? thanks!

**Comment by pedroamarall** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:headless-builder-functional:nocompile

**Comment by magjed4289** [comment]
@pedroamarall some of the new tests are failing, could you help take a look? Thanks in advance!

**Comment by pedroamarall** [comment]
ci:test:sf

**Comment by pedroamarall** [comment]
ci:test:headless-builder-functional:nocompile

**Comment by pedroamarall** [comment]
ci:test:sf

**Comment by pedroamarall** [comment]
ci:test:headless-builder-functional:nocompile

**Comment by pedroamarall** [comment]
ci:test:sf

**Comment by pedroamarall** [comment]
ci:test:headless-builder-functional:nocompile

**Pull request closed without merging**
