### PR TITLE
LPS-197907 Removal of the field "parentAPIPropertyERC"

### PR DESCRIPTION
**Pull request by jalber786**
**Purpose of this PR:**
- Delete the field "parentAPIPropertyERC" from the API Property definition and any reference to it

See the following **Jira Tickets**: [LPS-197907](https://liferay.atlassian.net/browse/LPS-197907) / [LPS-197906](https://liferay.atlassian.net/browse/LPS-197906)

### CODE REVIEW

**Comment by jalber786** [comment]
ci:test:sf

**Comment by jalber786** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Review by sergiojimcos — APPROVED** [review]

**Comment by magjed4289** [comment]
Test failures are not related. OK to manually forward ✅

**Comment by jalber786** [comment]
ci:forward:force

**Pull request closed without merging**
