### PR TITLE
LPS-171473 Headless Builder first steps

### PR DESCRIPTION
**Pull request by 4lejandrito**
Simplification of https://github.com/liferay-headless/liferay-portal/pull/1002.

* Removed a lot of code.
* Made tests independent from Blogs (using test info-api implementations).
* Removed functionality not needed for now (XML, permissions...). They'll be handled in their corresponding stories.

We will focus on blogs in the next PRs.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
@magjed4289 I'm sure you're ok with this, RIGHT??

**Comment by magjed4289** [comment]
it still not merged with master, so I will review it just in case 🤣

**Comment by magjed4289** [comment]
Test failures are not related 👏🏻

**Pull request closed without merging**
