### PR TITLE
LPS-125384 runned yarn add highlight.js@10.4.1 --exact

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@wincent, mentioning you since there are other changes in yarn.lock file

cc:// @nhpatt

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by wincent** [comment]
> @wincent, mentioning you since there are other changes in yarn.lock file

They all look fine. 👍  Good to see some duplication go away. The lockfile was supposedly last touched in 09eaa9ba861873f69b18dea771996ed6535dfcfb but despite its name `yarn-deduplicate` isn't necessarily guaranteed to remove _all_ possible duplication in a lockfile, which is why I think you saw `node-fetch` go away when you touched it.

**Comment by jkappler** [comment]
Thanks @wincent!

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
