### PR TITLE
LPS-203406 Ignores the suppliers for serialization

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPS-203406.

Fixes https://liferay.slack.com/archives/C5E1CRLJY/p1703614036684459.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:echo

**Review by ccorreagg — APPROVED** [review]
LGTM

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
> ### ❌ ci:test:echo - 756 out of 850 jobs passed in 2 hours 42 minutes
> Click here for more details.
> ##### Test bundle downloads:
> * [liferay-portal-bundle-tomcat.tar.gz](https://files.liferay.com/private/bundles/test-1-26/jobs/test-portal-acceptance-pullrequest(master)/builds/12422/liferay-portal-bundle-tomcat.tar.gz) (mirrors: [dlc](http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-26/jobs/test-portal-acceptance-pullrequest(master)/builds/12422/liferay-portal-bundle-tomcat.tar.gz), [lax](http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-26/jobs/test-portal-acceptance-pullrequest(master)/builds/12422/liferay-portal-bundle-tomcat.tar.gz))

I [compared](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1703684313305&testrayRunIdA=2479622409&testrayRunIdB=2479803691) the execution with acceptance master and the failures seem to be fixed. 

image

The only test that failed in our execution but not it master seems to be flaky

**Comment by ccorreagg** [comment]
I have seen there is a unit test failing, the REST Builder unit test. We need to include an extra commit to fix it

**Comment by 4lejandrito** [comment]
Thanks @ccorreagg I will do it!

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
