### PR TITLE
LRQA-80863 

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LRQA-80863

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:sf

**Review by matijapetanjek — APPROVED** [review]
LGTM @magjed4289 :+1: .
 BTW can you please format the error output so it is easier to read (e.g. add sb.append("\n"); to a throwable catch block)

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:forward:force

**Pull request closed without merging**
