### PR TITLE
LPS-165823 Add test to sort headless resources inside of widget template

### PR DESCRIPTION
**Pull request by yanan**
**Background:**
- Add test to sort headless resources inside of widget template
  (Check points for poshi tests: 
    1. add widget template through UI since I haven't find a way to add it through headless api
    2. add widget template using exsiting file `adt_blogs_sort.ftl` to avoid autocompletion when set scripts through poshi type.sendKeys
    3. update example to filter by creator name instead of creator id which should not make any differences to the key function)

**Test Plan:**
- Given three blog postings created
  And Given a template that will print the blog postings headlines sorted desc and filtered by creator name
  When adding a template to a widget page
  Then blog posting headlines are visible and in the correct order

**Jira Ticket:**

  - https://issues.liferay.com/browse/LPS-165823

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional

**Comment by yanan** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
Just started reviewing :)

**Review by magjed4289 — COMMENTED** [review]
The test looks good, but there's an error about the filter in the logs 🤔 Could you take a look at it?
image

**Comment by yanan** [comment]
ci:test:headless-functional

**Comment by yanan** [comment]
ci:test:sf

**Review by magjed4289 — APPROVED** [review]
looks great! :) Once the tests passed you can forward it! :)

**Comment by yanan** [comment]
Yeah! Thanks for catching this! I will forward.

**Comment by yanan** [comment]
ci:forward

**Comment by yanan** [comment]
ci:stop

**Comment by yanan** [comment]
ci:forward

**Comment by yanan** [comment]
ci:test:revelant

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Review by Hijky — APPROVED** [review]

**Comment by Hijky** [comment]
@yanan It seems the errors are not related to your PR, you can forward them manually.

**Comment by yanan** [comment]
Manual forward https://github.com/brianchandotcom/liferay-portal/pull/125334

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
Pr https://github.com/brianchandotcom/liferay-portal/pull/125464 has been merged into master.

**Pull request closed without merging**
