### PR TITLE
LPS-181458 | List API Applications

### PR DESCRIPTION
**Pull request by Hijky**
**Background:**
Add a testcase to list API Applications

**Test Plan**
CanListCreatedUnpublishedAPIApplication
Given with postAPIApplication to create an API application with unpublished status
When navigate to API builder
Then the unpublished API application created is shown
And Then no errors in the console

CanListCreatedPublishedAPIApplication
Given with postAPIApplication to create an API application with published status
When navigate to API builder
Then the published API application created is shown

**Jira ticket:**
https://liferay.atlassian.net/browse/LPS-189400

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:headless-functional:nocompile

**Comment by Hijky** [comment]
ci:test:headless-functional:nocompile

**Comment by Hijky** [comment]
The failures are not related to PR. @magjed4289 @yanan

**Review by yanan — APPROVED** [review]

**Comment by magjed4289** [comment]
@Hijky although the test failure is not related do we have any issue for the failing test created in Jira?

**Review by magjed4289 — APPROVED** [review]

**Comment by Hijky** [comment]
> @Hijky although the test failure is not related do we have any issue for the failing test created in Jira?

The failure is not very stable, and can not stably reproduce locally, and it also has a [ticket](https://liferay.atlassian.net/browse/LPS-193414) for it

**Comment by Hijky** [comment]
ci:forward

**Pull request closed without merging**
