### PR TITLE
LPD-23851 Fixing NPE

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPD-23851.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@sergiojimcos please ensure we did not make the same mistake elsewhere.
@magjed4289 can you help us understand why this failure was not catch in [the original PR](https://github.com/liferay-headless/liferay-portal/pull/1944)?

**Comment by 4lejandrito** [comment]
ci:test:commerce-functional

**Comment by ccorreagg** [comment]
> @4lejandrito, after analyzing the test run, it seems that the PR test failure analysis coincided with removing the Poshi tests from the relevant runs. Since this issue was revealed through Automation Functional Tests it was impossible for us to detect at this stage. In my opinion, for the future, what should be considered is: either running functional suites of the teams or requesting a smoke-functional test suite that would run on relevant with some of the Poshi tests included, as it seems that some crucial functionalities are only covered through Poshi layer.

Hey @magjed4289 , do you know which is the way to request the smoke-functional test suite? By opening an LPD ticket? via slack?

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:commerce-functional

**Comment by 4lejandrito** [comment]
> > > @4lejandrito, after analyzing the test run, it seems that the PR test failure analysis coincided with removing the Poshi tests from the relevant runs. Since this issue was revealed through Automation Functional Tests it was impossible for us to detect at this stage. In my opinion, for the future, what should be considered is: either running functional suites of the teams or requesting a smoke-functional test suite that would run on relevant with some of the Poshi tests included, as it seems that some crucial functionalities are only covered through Poshi layer.
> > 
> > 
> > Hey @magjed4289 , do you know which is the way to request the smoke-functional test suite? By opening an LPD ticket? via slack?
> 
> @ccorreagg we need to discuss this with Daldi and the ci guys. This is an example of the downsides of that decission (not saying the upsides are not worth...). I will create a thread on slack.

https://liferay.slack.com/archives/C19PWQ74J/p1713864892386979?thread_ts=1713864650.994539&cid=C19PWQ74J

**Pull request closed without merging**
