### PR TITLE
LPS 197353

### PR DESCRIPTION
**Pull request by 4lejandrito**
- LPS-197353 Making tests context independent
- LPS-197353 buildREST
- LPS-197353 Fixing also manual tests
- LPS-197353 Rename page variable
- LPS-197353 buildREST

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPS-197353

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@4lejandrito, love the changes ❤️

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by Hijky** [comment]
@4lejandrito I checked the failures, there are some failures I can't make sure if it related to your PR, could you take a look at them? Thanks in advance! 
And some tests failed with CI errors or JVM errors, so I think the better way is to re-run it
cc: @magjed4289 @yanan 
[CommerceUnitsOfMeasure#CanOrderManagerViewOrderItemUOMAndQuantity](https://testray.liferay.com/reports/production/logs/2023-10/test-1-38/test-portal-acceptance-pullrequest(master)/9492/functional-tomcat90-mysql57-chrome100-jdk8/6/9/jenkins-console.txt.gz?authuser=0)
[CommerceUnitsOfMeasureBundles#CanOptionValuesHaveLinkedSkuWithDifferentQuantitiesSet](https://testray.liferay.com/reports/production/logs/2023-10/test-1-38/test-portal-acceptance-pullrequest(master)/9492/functional-tomcat90-mysql57-chrome100-jdk8/6/9/jenkins-console.txt.gz?authuser=0)

**Comment by magjed4289** [comment]
[CommerceUnitsOfMeasure#CanOrderManagerViewOrderItemUOMAndQuantity](https://testray.liferay.com/reports/production/logs/2023-10/test-1-38/test-portal-acceptance-pullrequest(master)/9492/functional-tomcat90-mysql57-chrome100-jdk8/6/9/jenkins-console.txt.gz?authuser=0)
[CommerceUnitsOfMeasureBundles#CanOptionValuesHaveLinkedSkuWithDifferentQuantitiesSet](https://testray.liferay.com/reports/production/logs/2023-10/test-1-38/test-portal-acceptance-pullrequest(master)/9492/functional-tomcat90-mysql57-chrome100-jdk8/6/9/jenkins-console.txt.gz?authuser=0)
failures do not seem related either. 

LocalFile.ListAPIApplicationSchemas#CanSearchAPISchema has been ran locally in [liferay-portal-bundle-tomcat.tar.gz](https://files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/9492/liferay-portal-bundle-tomcat.tar.gz) and it passes successfully.
--

 I think it's OK to manually forward. ✅ 
cc @Hijky @yanan

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by magjed4289** [comment]
Test failures are not related to the PR. OK to manually forward! ✅

**Comment by sergiojimcos** [comment]
ci:forward:force

**Comment by sergiojimcos** [comment]
ci:stop

**Comment by sergiojimcos** [comment]
Sent to Brian here: https://github.com/brianchandotcom/liferay-portal/pull/143010

**Pull request closed without merging**
