### PR TITLE
LPS-178850 Added fix to export Content Structure in the Import/Export center

### PR DESCRIPTION
**Pull request by jalber786**
Added a method setGroupLocalService in the file ContentStructureResourceImpl that fixes the problem related to a null pointer exception that popped up while exporting Content Structures in the Import/Export center. This is related to the following [Jira Ticket](https://issues.liferay.com/browse/LPS-178850).

### CODE REVIEW

**Review by igorbeslic — CHANGES_REQUESTED** [review]
Hi @jalber786 I spoke with @4lejandrito - this would be one level harder but this way you would automatically cover all ResourceImpl classes that require groupLocalService injection.

First see this:
com.liferay.portal.vulcan.internal.jaxrs.container.request.filter.ContextContainerRequestFilter
this is how all resourceImpl get their dependencies injected.

Same way goes for BATCH requests. In BATCH that injection is done by Batch Executors.

 Do this:
- discard change you made (it fixes only content structure problem)
- update com.liferay.batch.engine.BatchEngineTaskItemDelegate with new method setGroupLocalService (you will recognise we did similar updates in the past)
- update com.liferay.batch.engine.internal.item.BatchEngineTaskItemDelegateExecutor CONSTRUCTOR to receive GroupLocalService interface as parameter and assign it to private member variable
- update com.liferay.batch.engine.internal.item.BatchEngineTaskItemDelegateExecutor#_setContextFields to call delegate's new setter
- check com.liferay.portal.vulcan.internal.batch.engine.VulcanBatchEngineTaskItemDelegateAdaptor - this is critical - I haven't gone into details, but check if adaptor plays any role in this set-groupLocal-Service phase
- make sure that Java code that instantiates Executor pass groupLocalService to new constructor
My advice (as there are lot of changes) is to do `ant all` to make sure all affected code can be compiled after change.

Send me PR and we would continue. I could also share screen with you during PR review to give you some more insights into batch engine code.

**Comment by jalber786** [comment]
ci:test:relevant

**Comment by jalber786** [comment]
ci:test:sf

**Comment by jalber786** [comment]
ci:test:relevant

**Comment by jalber786** [comment]
ci:test:sf

**Comment by jalber786** [comment]
ci:test:relevant

**Comment by jalber786** [comment]
ci:test:sf

**Comment by jalber786** [comment]
ci:test:relevant

**Comment by jalber786** [comment]
ci:test:sf

**Comment by jalber786** [comment]
ci:test:relevant

**Comment by jalber786** [comment]
ci:test:sf

**Comment by jalber786** [comment]
ci:test:relevant

**Comment by jalber786** [comment]
ci:test:sf

**Comment by jalber786** [comment]
ci:test:relevant

**Comment by jalber786** [comment]
ci:forward

**Pull request closed without merging**
