### PR TITLE
LPD-38287 Apply headless ts stubs for object-admin

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPD-38287

This is on top of https://github.com/liferay-headless/liferay-portal/pull/2242.

### CODE REVIEW

**Comment by jaimelr10** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by jaimelr10** [comment]
ci:test:playwright

**Comment by ccorreagg** [comment]
ci:test:playwright

**Review by jaimelr10 — APPROVED** [review]
Playwright errors don´t seem to be related

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:stop

**Pull request closed without merging**
