### PR TITLE
LPD-3866 removing duplicated creations if they are imported as copy

### PR DESCRIPTION
**Pull request by ZakiMiklos**
https://liferay.atlassian.net/browse/LPD-3866

Test not done yet

### CODE REVIEW

**Comment by ZakiMiklos** [comment]
Updated the PR

**Review by vendeltoreki — COMMENTED** [review]
We discussed with @ZakiMiklos to move the integration test code to the already existing https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-utility-page-test/src/testIntegration/java/com/liferay/layout/utility/page/internal/exportimport/data/handler/test/LayoutUtilityPageEntryStagedModelDataHandlerTest.java class.

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
Forwarding on: https://github.com/liferay-headless/liferay-portal/pull/1946

**Pull request closed without merging**
