### PR TITLE
LPS-196553 Edit an API Application EndPoint (MVP #1)

### PR DESCRIPTION
**Pull request by lhine**
This PR includes:

- Adjustments to enable updating data of created Endpoints;
- Addition of a disabled Select option to display the httpMethod of an Endpoint after its creation (currently, it's a mock to show the default option: GET);
- Other fixes on the application;

### CODE REVIEW

**Comment by lhine** [comment]
@naraandrade @cgmonte, 
Here's the first part for editing endpoints (the basic info). 
Can you review this PR? Thank you🌻

**Review by naraandrade — APPROVED** [review]

**Comment by naraandrade** [comment]
ci:test:sf

**Review by cgmonte — APPROVED** [review]
LGTM!

**Review by cgmonte — APPROVED** [review]

**Comment by cgmonte** [comment]
ci:forward

**Comment by yanan** [comment]
The only related failures are about endpoint path ends without `/`, here are related cases: ([details on compare run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2429962168&testrayRunIdA=2430477690&statusB=2))
- GeneratePathStructureForEndpoints#CanCreateEndpointWithValidPath
- GeneratePathStructureForEndpoints#PathIsPresentInEndpointsWithEditAPIApplication
- ListAPIApplicationEndpoints#CanListCreatedEndpoint
- ListAPIApplicationEndpoints#CanCopyURLOfAPIEndpoint
- ListAPIApplicationEndpoints#CanFilterEndpointAPIByCreationDateAsLastUpdated
- ListAPIApplicationEndpoints#CanOrderEndpointAPI
- ListAPIApplicationEndpoints#CanPaginateAPIEndpoints
- ListAPIApplicationEndpoints#CanSearchEndpointAPI

**Comment by lhine** [comment]
ci:forward

**Comment by cgmonte** [comment]
ci:teste:sf

**Comment by cgmonte** [comment]
ci:test:sf

**Pull request closed without merging**
