### PR TITLE
LPS-182663 Add functional tests on enable export of JSONT format which includes configuration object

### PR DESCRIPTION
**Pull request by yanan**
Background
- Add automation tests which priority to 4 and 5 for story ticket LPS-172470

Jira Ticket
- https://issues.liferay.com/browse/LPS-182663

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
Test failures are unrelated to the new added tests.

**Review by Hijky — APPROVED** [review]

**Review by magjed4289 — APPROVED** [review]
looks good! 👏🏻

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
