### PR TITLE
LPS-191816: Improve the algorithm for endpoint operationId of API Builder

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Try to reproduce the `getOperationId` algorithm of generated by the `RESTBuilder` for Collection endpoints.
- Create an OpenAPIUtil to formar singular words in order to create the endpoint's `operationIds`.

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPS-191816

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:stop

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
Can you add unit tests for the algorithm?

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/139411

**Pull request closed without merging**
