### PR TITLE
LPD-43379 Site Scope Object PUT request fix

### PR DESCRIPTION
**Pull request by ZakiMiklos**
https://liferay.atlassian.net/browse/LPD-43379

### CODE REVIEW

**Comment by ZakiMiklos** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by ZakiMiklos** [comment]
ci:test:sf

**Comment by ZakiMiklos** [comment]
ci:test:relevant

**Comment by ZakiMiklos** [comment]
ci:test:sf

**Comment by ZakiMiklos** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]
Hey @ZakiMiklos,

See my changes. I recommend you read the full commit message for every commit. Let me know if you have any doubts.

The test was good and it reproduced the issue very well. The fix I believe is good too as it does not make sense to use the readonly property `scopeKey`.

Next time make sure you run SF locally first and trigger the sf job on every push.

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
