### PR TITLE
LPD-23087 Fix tests

### PR DESCRIPTION
**Pull request by ccorreagg**
Related issue: https://liferay.atlassian.net/browse/LPD-23087

---

The purpose of this ticket is to fix some poshi acceptance tests, as we should not consider the order when asserting the values from the actions

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:headless

**Comment by ccorreagg** [comment]
The test is still failing. Do not forward yet

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:headless

**Review by 4lejandrito — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:headless

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
