### PR TITLE
LPS-187288 Fix Export template management for Objects

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-187288

---

The purpose of this PR is to fix the Export template management for Objects. For that:

- A new field `internalClassNameKey` has been included in the `Plan` schema of the Batch Planner REST API. The purpose of this field is to have a unique key by concatenating the `internalClassName` and `taskItemDelegateName` (if the `taskItemDelegateName` is not null or `DEFAULT`). This has been included because for Objects, the value of the `internalClassName` is always the same (`com.liferay.object.rest.dto.v1_0.ObjectEntry`).
- Use the new field in the Batch Planner Web module.
- The Simple Class Name calculation has been modified for the Object case; the taskItemDelegateName is returned if it is not null or `DEFAULT`, as it contains the information about the Object Definition that is being managed.

---

### SELECT THE STUDENT (OBJECTS) TEMPLATE

**Before the PR:**

image

**After the PR:**

image

---

### SHOW THE EXPORTS EXECUTED

**Before the PR:**

image

**After the PR:**

image

---

### SHOW THE TEMPLATES

**Before the PR:**

image

**After the PR:**

image

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Failures are not related to the pr :partying_face:

**Comment by ccorreagg** [comment]
> Failures are not related to the pr 🥳

Thank you @yanan !

**Review by matijapetanjek — APPROVED** [review]
LGTM! Really nice work 👏

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
