### PR TITLE
LPS-162964 Refactor to unify the methods to return the Object Entries related to a Object Entry

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to unify the methods that are returning the Object Entries associated to a Object Entry.

As in the current task we are working on returning the related elements to a System Object as a Nested Field, we found the necessity of unifying the methods into one in order to avoid duplicating the current code of the API REST into a component that manages the Nested Fields.

**Before the PR:**

There were two methods, depending on the type of object:

```java
public interface ObjectEntryManager {

        [...]

	public Page<ObjectEntry> getObjectEntryRelatedObjectEntries(
			DTOConverterContext dtoConverterContext,
			ObjectDefinition objectDefinition, Long objectEntryId,
			String objectRelationshipName, Pagination pagination)
		throws Exception;

	public Page<Object> getRelatedSystemObjectEntries(
			ObjectDefinition objectDefinition, Long objectEntryId,
			String objectRelationshipName, Pagination pagination)
		throws Exception;

        [...]
}
```

- getObjectEntryRelatedObjectEntries: Method to return the Page of Object Entries in case the related elements are Custom Objects.
- getRelatedSystemObjectEntries: Method to return the Page of Objects in case the related elements are System Objects.

```java
public class RelatedObjectEntryResourceImpl
	extends BaseRelatedObjectEntryResourceImpl {

	@Override
	public Page<Object> getRelatedObjectEntriesPage(
			String previousPath, Long objectEntryId,
			String objectRelationshipName, Pagination pagination)
		throws Exception {

		[...]

		if (relatedObjectDefinition.isSystem()) {
			return objectEntryManager.getRelatedSystemObjectEntries(
				systemObjectDefinition, objectEntryId, objectRelationshipName,
				pagination);
		}

		return (Page)objectEntryManager.getObjectEntryRelatedObjectEntries(
			_getDefaultDTOConverterContext(
				systemObjectDefinition, objectEntryId, _uriInfo),
			systemObjectDefinition, objectEntryId, objectRelationshipName,
			pagination);

```

**After the PR:**

There is one method, and inside the method based on the type of object, a private method is called.

```java
public interface ObjectEntryManager {

        [...]


	public Page<Object> getObjectEntryRelatedObjectEntries(
			DTOConverterContext dtoConverterContext,
			ObjectDefinition objectDefinition, long objectEntryId,
			String objectRelationshipName, Pagination pagination)
		throws Exception;

        [...]
}
```

The method getObjectEntryRelatedObjectEntries returns the Page of Objects that are related to an Object Entry.

```java
public class RelatedObjectEntryResourceImpl
	extends BaseRelatedObjectEntryResourceImpl {

	@Override
	public Page<Object> getRelatedObjectEntriesPage(
			String previousPath, Long objectEntryId,
			String objectRelationshipName, Pagination pagination)
		throws Exception {

		[...]

		return objectEntryManager.getObjectEntryRelatedObjectEntries(
			_getDefaultDTOConverterContext(
				systemObjectDefinition, objectEntryId, _uriInfo),
			systemObjectDefinition, objectEntryId, objectRelationshipName,
			pagination);

```

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
I reviewed some of the tests that seem to be related but it seems they are related with the cascade type deletion

**Comment by magjed4289** [comment]
failures not related to the PR. OK to manually forward ✅

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) 👏 👏 👏 
It seems like nothing is breaking with the refactor :trollface:

**Comment by LuismiBarcos** [comment]
ci:forward

**Pull request closed without merging**
