### PR TITLE
LPD-25354 Fixing jackson-dataformat-xml vuln

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPD-25354.

I could not update to `2.17.0` because there are compilation errors.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
cc: @peerkar @BryanEngler

**Comment by 4lejandrito** [comment]
@peerkar @BryanEngler @lipusz when you give me the OK I will forward.

**Comment by lipusz** [comment]
@4lejandrito I guess if `ci:test:search` gives OK, I guess it's good to go. You can ping the Bryan if you need help with analyzing the results from that suite.

**Comment by 4lejandrito** [comment]
ci:test:search

**Comment by peerkar** [comment]
@4lejandrito the errors in search suite are not related. Good to go.

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
