### PR TITLE
LPS-186223 Get related objects API returning User must have VIEW permission for ObjectDefinition

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://issues.liferay.com/browse/LPS-186223

These changes use `localService` when getting the relationship object because the `service` checks for permissions at the object definition level. 

I don't think this creates a security hole because the object entries returned are properly permission checked so users will not be able to access anything they could not access before.

### CODE REVIEW

**Review by LuismiBarcos — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by magjed4289** [comment]
ci:reevaluate:1257401_1242

**Comment by magjed4289** [comment]
Failures not related to the PR. OK to manually forward.

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
