### PR TITLE
LPS-175904

### PR DESCRIPTION
**Pull request by ruben-pulido**
This PR builds on top of https://github.com/liferay-headless/liferay-portal/pull/1074

The last  two commits try to address the fact, that path parameters should not be encoded in the URLs added as part of the response, as for example "actions.get.href" or "renderedPage.renderedPageURL".

After the changes a sample response looks like this:

```curl -s -X GET 'http://localhost:8083/o/headless-delivery/v1.0/sites/20119/site-pages/x/y/z?restrictFields=pageDefinition' -H 'Accept-Language: en-US' -u test@liferay.com:test
{
  "actions" : {
    "get-experiences" : {
      "method" : "GET",
      "href" : "http://localhost:8083/o/headless-delivery/v1.0/sites/20119/site-pages/x/y/z/experiences"
    },
    "get" : {
      "method" : "GET",
      "href" : "http://localhost:8083/o/headless-delivery/v1.0/sites/20119/site-pages/x/y/z"
    },
    "get-rendered-page" : {
      "method" : "GET",
      "href" : "http://localhost:8083/o/headless-delivery/v1.0/sites/20119/site-pages/x/y/z/rendered-page"
    }
  },
  "availableLanguages" : [ "en-US" ],
  "creator" : {
    "additionalName" : "",
    "contentType" : "UserAccount",
    "familyName" : "Test",
    "givenName" : "Test",
    "id" : 20123,
    "name" : "Test Test"
  },
  "customFields" : [ ],
  "dateCreated" : "2023-03-13T22:09:58Z",
  "dateModified" : "2023-03-13T22:10:15Z",
  "datePublished" : "2023-03-13T22:09:58Z",
  "friendlyUrlPath" : "/x/y/z",
  "keywords" : [ ],
  "pageSettings" : {
    "hiddenFromNavigation" : false,
    "seoSettings" : {
      "description" : "",
      "htmlTitle" : "",
      "robots" : "",
      "seoKeywords" : ""
    }
  },
  "pageType" : "Content Page",
  "renderedPage" : {
    "renderedPageURL" : "http://localhost:8083/o/headless-delivery/v1.0/sites/20119/site-pages/x/y/z/rendered-page"
  },
  "siteId" : 20119,
  "taxonomyCategoryBriefs" : [ ],
  "title" : "x/y/z",
  "uuid" : "563bc6ef-fde2-b8e8-2382-c8f7c29dae03"
}
```

Before the changes the response looked like this:

```
curl -s -X GET 'http://localhost:8083/o/headless-delivery/v1.0/sites/20119/site-pages/x/y/z?restrictFields=pageDefinition' -H 'Accept-Language: en-US' -u test@liferay.com:test
{
  "actions" : {
    "get-experiences" : {
      "method" : "GET",
      "href" : "http://localhost:8083/o/headless-delivery/v1.0/sites/20119/site-pages/x%2Fy%2Fz/experiences"
    },
    "get" : {
      "method" : "GET",
      "href" : "http://localhost:8083/o/headless-delivery/v1.0/sites/20119/site-pages/x%2Fy%2Fz"
    },
    "get-rendered-page" : {
      "method" : "GET",
      "href" : "http://localhost:8083/o/headless-delivery/v1.0/sites/20119/site-pages/x%2Fy%2Fz/rendered-page"
    }
  },
  "availableLanguages" : [ "en-US" ],
  "creator" : {
    "additionalName" : "",
    "contentType" : "UserAccount",
    "familyName" : "Test",
    "givenName" : "Test",
    "id" : 20123,
    "name" : "Test Test"
  },
  "customFields" : [ ],
  "dateCreated" : "2023-03-13T22:09:58Z",
  "dateModified" : "2023-03-13T22:10:15Z",
  "datePublished" : "2023-03-13T22:09:58Z",
  "friendlyUrlPath" : "/x/y/z",
  "keywords" : [ ],
  "pageSettings" : {
    "hiddenFromNavigation" : false,
    "seoSettings" : {
      "description" : "",
      "htmlTitle" : "",
      "robots" : "",
      "seoKeywords" : ""
    }
  },
  "pageType" : "Content Page",
  "renderedPage" : {
    "renderedPageURL" : "http://localhost:8083/o/headless-delivery/v1.0/sites/20119/site-pages/x%2Fy%2Fz/rendered-page"
  },
  "siteId" : 20119,
  "taxonomyCategoryBriefs" : [ ],
  "title" : "x/y/z",
  "uuid" : "563bc6ef-fde2-b8e8-2382-c8f7c29dae03"
}
```

With the changes added, path parameters would not be encoded regardless of whether parameters end with `Path` when generating links. 

Probably we want to apply a similar logic as the one added in https://github.com/liferay-headless/liferay-portal/pull/1089/commits/dbedc750cde15f0e0c8fd0020124919d2d8e6562 so at least parameters ending with externalReferenceCode are handled similarly, since those may contains slashes as well.

//cc @ealonso @jkappler

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
@4lejandrito This PR is a follow-up of this one https://github.com/liferay-headless/liferay-portal/pull/1074

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) Thanks for the PR Ruben 😊 

I will wait for Alex's review as he has more context than me.

My only concern is if these changes could be considered a breaking change or not, as we are changing an existing property value. I have doubts as the changes are to encode part of the URL, so maybe is not a breaking change

**Comment by 4lejandrito** [comment]
Hi @ruben-pulido,

I have the same concerns as @LuismiBarcos. I think your changes make sense, but I am not sure if they might be breaking in some situations. 

We cannot apply the same `Path` logic because we don't know the name of each parameter at that point. So this would be applied for every path parameter. Which I don't think is too bad, because if someone were using this, it would not be working right now.

Let's see what the tests say.

**Comment by LuismiBarcos** [comment]
ci is ok, can we forward it?

**Comment by 4lejandrito** [comment]
Let's go.

**Comment by 4lejandrito** [comment]
ci:forward

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
Manually forwarded. See https://github.com/brianchandotcom/liferay-portal/pull/131795.

**Pull request closed without merging**
