### PR TITLE
LPD-27908 Organise test components

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-27908

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:headless

**Comment by magjed4289** [comment]
the updated names are not displayed yet correctly in Testray, I asked about it [here](https://liferay.slack.com/archives/C01MVBFRN0K/p1717745831270989?thread_ts=1717745263.469069&cid=C01MVBFRN0K)

**Review by 4lejandrito — COMMENTED** [review]
See my changes and review if needed.

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
