### PR TITLE
LPS-169692 ExposeErcInWikiPageAttachment#CanDeleteAttachmentByExternalReferenceCode

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPS-169692

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:headless-functional:nocompile

**Comment by magjed4289** [comment]
ci:test:data-integration-functional:nocompile

**Review by Hijky — APPROVED** [review]

**Comment by Hijky** [comment]
@magjed4289 The failed ones are not related to your PR.

**Review by yanan — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
