### PR TITLE
LPS-205587: Add feature flag LPS-200135

### PR DESCRIPTION
**Pull request by sergiojimcos**
**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPS-205587

### CODE REVIEW

**Review by 4lejandrito — APPROVED** [review]

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by JoyceWang08211** [comment]
No unique failure was found.

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:forward:force

**Pull request closed without merging**
