### PR TITLE
LPD-19283 Including nested schemas

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPD-19283

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Review by ccorreagg — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/147866

**Pull request closed without merging**
