### PR TITLE
LPS-160013 | Expose blog entries information in navigation menus APIs

### PR DESCRIPTION
**Pull request by Hijky**
**Background**
Expose blog entries information in navigation menus APIs

**Test Plan**
Given a navigation menu
And Given with post request and siteId I create a blog entry
And Given the navigation menu which use custom name associate with the blog entry though UI
When with get request to retrieve the navigation menu with siteId
Then I can see values of useCustomName of true, contentURL equals to blog endpoint and type equals to blogPosting

Given a navigation menu
And Given with post request and siteId I create a blog entry
And Given the navigation menu doesn't use custom name assciate with blog entry through UI
When with get request to retrieve the navigation menu with navigationMenuId
Then I can see values of useCustomName of false, contentURL equals to blog endpoint and type equals to blogPosting

**JIRA Link:**
https://issues.liferay.com/browse/LPS-160013

### CODE REVIEW

**Comment by Hijky** [comment]
Rebased to latest master.

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:headless-frontend-functional:nocompile

**Comment by Hijky** [comment]
@magjed4289 @yanan The failures are not related to PR.

**Review by yanan — APPROVED** [review]
Thanks for the updates!

**Review by magjed4289 — APPROVED** [review]
Looks good ✅

**Comment by Hijky** [comment]
ci:forward

**Pull request closed without merging**
