### PR TITLE
LPS-195195 Add validation to avoid assigning as a request/response schema one that does not belong to the same API Application

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-195195

---

The purpose of this PR is to add a new validation to avoid assigning as a request schema or response schema in an API Endpoint a schema that does belong to another API Application.

---

**How to test it:**

Create an API Application with an endpoint and a schema:

```
curl -X 'POST' \
  'http://localhost:8080/o/headless-builder/applications/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -u 'test@liferay.com:test' \
  -d '{
  "applicationStatus": "published",
  "baseURL": "app",
  "title": "app",
  "apiApplicationToAPIEndpoints": [
    {
      "httpMethod": "get",
      "name": "my-ep",
      "path": "/my-ep"
    }
  ],
  "apiApplicationToAPISchemas": [
    {
      "mainObjectDefinitionERC": "L_API_APPLICATION",
      "name": "my-schema"
    }
  ]
}'
```

Create an API Application with an endpoint and another schema:

```
curl -X 'POST' \
  'http://localhost:8080/o/headless-builder/applications/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -u 'test@liferay.com:test' \
  -d '{
  "applicationStatus": "published",
  "baseURL": "app2",
  "title": "app2",
  "apiApplicationToAPISchemas": [
    {
      "mainObjectDefinitionERC": "L_API_APPLICATION",
      "name": "my-schema2"
    }
  ]}'
```
Try to assign to the schema of the second API Application the endpoint of the first API Application:

```
curl -X 'PUT' \
  'http://localhost:8080/o/headless-builder/schemas/{secondSchemaId}/responseAPISchemaToAPIEndpoints/{endpointId}' \
  -H 'accept: application/json' \
  -u 'test@liferay.com:test'
```

### CODE REVIEW

**Comment by ccorreagg** [comment]
Added this [new commit](https://github.com/liferay-headless/liferay-portal/pull/1481/commits/2d578b78066073a935b07f7ff068f14523f65e50) to simplify

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by sergiojimcos — APPROVED** [review]

**Comment by sergiojimcos** [comment]
LGTM!!

**Comment by 4lejandrito** [comment]
Hey guys, 3 of the 4 failing tests say it is the first time they are failing in 25 times. Can you verify if the failures are related? if not, I approve the changes.

**Review by 4lejandrito — APPROVED** [review]
See my last comment.

**Comment by ccorreagg** [comment]
> 1. [CanSeeApiApplicationSchema](https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/288710//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CreateAPIDefinitionObjectsAsBackendOfAPIBuilder_CanSeeApiApplicationSchema_)

For the first failed test, I have checked it failed in other PRs too, for example: https://testray.liferay.com/home/-/testray/case_results/2419238602?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F2399622972%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D2399622972%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc

Same for the second test:
https://testray.liferay.com/home/-/testray/case_results/2417589505?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F2399622909%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D2399622909%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc

Same for the third test:
https://testray.liferay.com/home/-/testray/case_results/2419544474?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F2401337702%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D2401337702%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc

Same for the fourth test:
https://testray.liferay.com/home/-/testray/case_results/2418594346?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F2398342535%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D2398342535%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc

**Comment by ccorreagg** [comment]
@4lejandrito I think with the analysis I performed, it is safe to forward. What do you think?

**Comment by 4lejandrito** [comment]
ok let's do it.

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
