### PR TITLE
LPD-34304 | Fix batch-planner import tests

### PR DESCRIPTION
**Pull request by jaimelr10**
Description: Change expected richTextField to fix the batch-planner tests

Jira Ticket: https://liferay.atlassian.net/browse/LPD-34305

### CODE REVIEW

**Comment by jaimelr10** [comment]
ci:test:playwright

**Comment by magjed4289** [comment]
the test seem to be still failing 🤔 https://testray.liferay.com/#/project/34754/routines/34756/build/66583581/case-result/66615955

**Review by magjed4289 — CHANGES_REQUESTED** [review]
Could you check why `can export as JSON with all field types mapped`, and  `can export as JSONL with excluded fields` are not passing?

**Comment by jaimelr10** [comment]
Hi @magjed4289, In this task I only corrected the batch-planner import tests, which now seems to be passing. I will go back to the export as soon as I can
https://testray.liferay.com/#/project/34754/routines/34756/build/66583581/case-result/66615969

**Comment by jaimelr10** [comment]
ci:test:playwright

**Review by magjed4289 — APPROVED** [review]
Awesome job! 👏🏻

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
