### PR TITLE
LPD-3866 Removing duplicated creations if they are imported as copy

### PR DESCRIPTION
**Pull request by vendeltoreki**
[LPD-3866](https://liferay.atlassian.net/browse/LPD-3866)

Changing test name as suggested in https://github.com/brianchandotcom/liferay-portal/pull/148760 .

Previous PR: https://github.com/liferay-headless/liferay-portal/pull/1946

cc: @ZakiMiklos

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
Rebased with master and updated some commits by moving the changes in some files to different commits

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:report:2558545670

**Comment by ccorreagg** [comment]
ci:forward

**Review by ccorreagg — APPROVED** [review]

**Comment by vendeltoreki** [comment]
ci:forward:force

**Pull request closed without merging**
