### PR TITLE
LPS-201627 Use the internal name of the EntityField instead of its name for CollectionEntityField

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-201627

---

The purpose of this ticket is to fix the usage of the Collection field for sorting purposes. Previously, the field used is the one given by the `getName` method (that is the field of the REST API). However, we need to use the internal one given by the methods `getSortableName` and `getFilterableName`.

For example, for the Headless Delivery REST API, when using the `taxonomyCategoryIds` field in the sort:

```shell
curl -X GET \
      -u test@liferay.com:test \
      http://localhost:8080/o/headless-delivery/v1.0/sites/20119/structured-contents?sort=taxonomyCategoryIds
```

Being the document in ElasticSearch:

```json
          "assetCategoryIds" : [
            "102506",
            "102509"
          ],
```

See the fragment of the query in ElasticSearch

**Before the PR:**

```json
  "sort": [
    {
      "taxonomyCategoryIds": {
        "order": "asc",
        "unmapped_type": "keyword"
      }
    },
```

**After the PR:**

```json
  "sort": [
    {
      "assetCategoryIds": {
        "order": "asc",
        "unmapped_type": "keyword"
      }
    },
```

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
Is there a way to test this?

**Comment by ccorreagg** [comment]
> Is there a way to test this?

I have included a test in StructuredContentResourceTest (Headless Delivery REST API), I have checked locally that without the change, the test fails:

**Before the change:**
```
com.liferay.headless.delivery.resource.v1_0.test.StructuredContentResourceTest > testGetSiteStructuredContentsPageWithSortInteger STARTED

com.liferay.headless.delivery.resource.v1_0.test.StructuredContentResourceTest > testGetSiteStructuredContentsPageWithSortInteger FAILED
    java.lang.AssertionError: {"actions": {"delete": {"href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125793", "method": "DELETE"}, "get": {"href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125793", "method": "GET"}, "get-rendered-content": {"href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125793/rendered-content/{contentTemplateId}", "method": "GET"}, "get-rendered-content-by-display-page": {"href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125793/rendered-content-by-display-page/{displayPageKey}", "method": "GET"}, "replace": {"href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125793", "method": "PUT"}, "subscribe": {"href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125793/subscribe", "method": "PUT"}, "unsubscribe": {"href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125793/unsubscribe", "method": "PUT"}, "update": {"href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125793", "method": "PATCH"}}, "availableLanguages": ["en-US"], "contentFields": [{"contentFieldValue": {"data": "kREpOmmUWj"}, "dataType": "string", "inputControl": "text", "label": "TextFieldNameLabel", "name": "Foo", "nestedContentFields": [], "repeatable": false}], "contentStructureId": 125724, "creator": {"additionalName": "", "contentType": "UserAccount", "familyName": "Test", "givenName": "Test", "id": 20123, "name": "Test Test"}, "customFields": [], "dateCreated": "2023-11-14T15:51:11Z", "dateModified": "2023-11-14T15:51:11Z", "datePublished": "2023-11-14T15:50:00Z", "description": "y8bvrtud", "externalReferenceCode": "jswjb2ga", "friendlyUrlPath": "185cqs4x", "id": 125793, "key": "125791", "keywords": [], "numberOfComments": 0, "priority": 0.1893681373684697, "relatedContents": [{"contentType": "BlogPosting", "id": 125714, "title": "0uakxNmk"}], "renderedContents": [{"contentTemplateId": "125728", "contentTemplateName": "Test Template", "markedAsDefault": true, "renderedContentURL": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125793/rendered-content/125728"}], "siteId": 125708, "structuredContentFolderId": 0, "subscribed": false, "taxonomyCategoryBriefs": [{"taxonomyCategoryId": 125771, "taxonomyCategoryName": "MNTBuXze"}], "title": "2gjoccri", "uuid": "9d2ddb89-0d60-99cf-6b1f-aebb37447a45"} does not equal {"actions": {"delete": {"href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125779", "method": "DELETE"}, "get": {"href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125779", "method": "GET"}, "get-rendered-content": {"href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125779/rendered-content/{contentTemplateId}", "method": "GET"}, "get-rendered-content-by-display-page": {"href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125779/rendered-content-by-display-page/{displayPageKey}", "method": "GET"}, "replace": {"href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125779", "method": "PUT"}, "subscribe": {"href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125779/subscribe", "method": "PUT"}, "unsubscribe": {"href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125779/unsubscribe", "method": "PUT"}, "update": {"href": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125779", "method": "PATCH"}}, "availableLanguages": ["en-US"], "contentFields": [{"contentFieldValue": {"data": "ywQaVlRPP9"}, "dataType": "string", "inputControl": "text", "label": "TextFieldNameLabel", "name": "Foo", "nestedContentFields": [], "repeatable": false}], "contentStructureId": 125724, "creator": {"additionalName": "", "contentType": "UserAccount", "familyName": "Test", "givenName": "Test", "id": 20123, "name": "Test Test"}, "customFields": [], "dateCreated": "2023-11-14T15:51:09Z", "dateModified": "2023-11-14T15:51:09Z", "datePublished": "2023-11-14T15:50:00Z", "description": "h957qjgn", "externalReferenceCode": "dqefcwn0", "friendlyUrlPath": "ihpzkhtg", "id": 125779, "key": "125777", "keywords": [], "numberOfComments": 0, "priority": 0.15888305151801163, "relatedContents": [{"contentType": "BlogPosting", "id": 125714, "title": "0uakxNmk"}], "renderedContents": [{"contentTemplateId": "125728", "contentTemplateName": "Test Template", "markedAsDefault": true, "renderedContentURL": "http://localhost:8080/o/headless-delivery/v1.0/structured-contents/125779/rendered-content/125728"}], "siteId": 125708, "structuredContentFolderId": 0, "subscribed": false, "taxonomyCategoryBriefs": [{"taxonomyCategoryId": 125774, "taxonomyCategoryName": "GlcgCgYV"}], "title": "x4lu1a0y", "uuid": "e69bc146-c319-d155-7f4f-95595882a6e1"}
    	at org.junit.Assert.fail(Assert.java:89)
    	at org.junit.Assert.assertTrue(Assert.java:42)
    	at com.liferay.headless.delivery.resource.v1_0.test.BaseStructuredContentResourceTestCase.assertEquals(BaseStructuredContentResourceTestCase.java:3475)
    	at com.liferay.headless.delivery.resource.v1_0.test.BaseStructuredContentResourceTestCase.assertEquals(BaseStructuredContentResourceTestCase.java:3491)
    	at com.liferay.headless.delivery.resource.v1_0.test.StructuredContentResourceTest.testGetSiteStructuredContentsPageWithSortInteger(StructuredContentResourceTest.java:384)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)
    	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
    	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)
    	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)
    	at java.lang.Thread.run(Thread.java:750)

1 test completed, 1 failed

```

**After the change:**
```
com.liferay.headless.delivery.resource.v1_0.test.StructuredContentResourceTest > testGetSiteStructuredContentsPageWithSortInteger STARTED

com.liferay.headless.delivery.resource.v1_0.test.StructuredContentResourceTest > testGetSiteStructuredContentsPageWithSortInteger PASSED

```

**Comment by ccorreagg** [comment]
The failure is not related, as I see the same error in different branches. Forwarding...

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
