### PR TITLE
LPD-39351 Technical Task | [ACC] Investigate multiple test failures for different entities in com.liferay.headless.batch.engine.resource.v1_0.test.ExportTaskResourceTest

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-39351

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
test is passing: https://testray.liferay.com/#/project/35392/routines/45357/build/47997826?filter=%7B%22testrayComponentIds%22%3A%5B53038%5D%7D&filterSchema=buildResults&page=1

**Comment by ccorreagg** [comment]
Forwarding to BC!

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
