### PR TITLE
LPS-175821 Create a new paramConverter for Objects to check if the scopeKey is valid

### PR DESCRIPTION
**Pull request by ccorreagg**
Followed-up PR from: https://github.com/liferay-headless/liferay-portal/pull/1028

Thanks @jgarcialr for your pull request!

---

This PR contains the code to fix this bug: https://issues.liferay.com/browse/LPS-175821

As Object REST API contains several mechanisms that register/unregister components in execution time based on the time an `ObjectDefinition` is created/updated/deleted, we have considered to add a new Feature for the Objects API, called `ObjectsFeature`.

The idea of the feature is to provide the Objects API all the JAX-RS resources needed from a common entrypoint instead of deploying them from different places, such as the ObjectApplication, the ObjectDefinitionDeployerImpl, etc. The work of moving the JAX-RS resources (RequestFilters, ResponseFilters, WriterInterceptors, etc) will be doing in the future.

Apart from that, a new `ParamConverter` has been included to verify the path parameter `scopeKey` contains a proper value based on the `ObjectDefinition` related to that API.

By now, as an ObjectDefinition could be scoped by company or site, only for the "site" scope case will be validated; otherwise an exception will be thrown.

---

Given a Object Definition `University` scoped by site and a university created for the site `20121`

**Before the PR:**

```
curl -X 'GET' 'http://localhost:8080/o/c/universities/scopes/11111'  -H 'accept: application/json'  -u 'test@liferay.com:test'
```

The response for a non existing site contains all the universities:

```
{
  [...]
  "items" : [ {
    [...]
    "dateCreated" : "2023-02-16T11:15:54Z",
    "dateModified" : "2023-02-16T11:15:54Z",
    "externalReferenceCode" : "6bbc6524-d555-e800-c4bf-4030ba9d4701",
    "id" : 50986,
    "scopeKey" : "Guest",
    "status" : {
      "code" : 0,
      "label" : "approved",
      "label_i18n" : "Approved"
    },
    "universityName" : "this is the university"
  } ],
  "lastPage" : 1,
  "page" : 1,
  "pageSize" : 20,
  "totalCount" : 1
}
```

**After the PR:**

```
curl -X 'GET' 'http://localhost:8080/o/c/universities/scopes/11111'  -H 'accept: application/json'  -u 'test@liferay.com:test'
```

The response for a non existing site is a HTTP code 404 with the body

```
{
  "status" : "NOT_FOUND",
  "title" : "Unable to get a valid site with ID 11111"
}
```

### CODE REVIEW

**Review by LuismiBarcos — APPROVED** [review]
LGTM :)

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
cc/ @jgarcialr FYI

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
