### PR TITLE
LPS-195622: Validate propertyValues when Data Structure is instance of Collection

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Create new validation for `MULTIPLE_ELEMENT`. If it is an instance of `Collection` it will be validated.

**Related JIRA Ticket**
https://liferay.atlassian.net/browse/LPS-195622

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by yanan** [comment]
Failures are not related, and since the upper forward fails, will forward again with funcational tests(Sorry I pushed tests into this pr)
image

**Comment by yanan** [comment]
ci:forward:force

**Comment by yanan** [comment]
ci:forward:force

**Pull request closed without merging**
