### PR TITLE
LPS-192151 Add support for sorting in API Builder and unify patterns

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket https://liferay.atlassian.net/browse/LPS-192151

## Purpose of the PR
The PR has two different purposes
### Add support for sorting in API Builder
This PR allows users to apply the sorts predefined on the APISort objects when creating an API Builder Application.

This sorting will be ignored when the user adds a custom sort to the request.

For example, a user can create an API Builder Application with a predefined sort like `name:asc`.
This will return the data sorted by name.

But, if the user adds the `sort` param in the request with another value, for example: `date:asc` the data will be sorted by date and will ignore the presorted value.

### Unify pattern
The PR also modifies the existing code to follow the pattern used in the Liferay Headless APIs. This is, inject by context the sorting and filtering parameters needed to calculate the return data.

To do that, the PR creates `ContextProviders` and `ContextResolvers` to be able to calculate the values and inject them directly into the resource.

## How to test it
Deploy the following modules:
* `portal-vulcan-api`
* `portal-vulcan-impl`
* `headless-builder-api`
* `headless-builder-impl`

Execute the following tests under `headless-builder-test`
* `HeadlessBuilderResourceTest.testGetWithAPISortAsc`
* `HeadlessBuilderResourceTest.testGetWithAPISortDesc`

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by yanan** [comment]
The following two tests are failed, @LuismiBarcos could you help take a look when you have time?
- StructuredContentResourceTest.testGetAssetLibraryStructuredContentFolderByExternalReferenceCode
- StructuredContentResourceTest.testGetAssetLibraryStructuredContentByExternalReferenceCode
[More details](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2401875541&testrayRunIdA=2401857094&statusB=2)

**Comment by LuismiBarcos** [comment]
Will take a look. 
Thanks for check it @yanan 🙂

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Rebased, solved conflicts and Auto SF.

**Comment by 4lejandrito** [comment]
Rebased against https://github.com/brianchandotcom/liferay-portal/pull/139494. All integration tests are passing locally.

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by LuismiBarcos** [comment]
Brian has merged https://github.com/brianchandotcom/liferay-portal/pull/139494
It is necessary to rebase and resolve the conflicts before sending this PR. I will handle it tomorrow if you are OK with it.

**Comment by 4lejandrito** [comment]
Rebased against brian's. All integration tests are passing locally.

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/139570

**Pull request closed without merging**
