### PR TITLE
LPS-156004 | Add a testcase to import and export objects

### PR DESCRIPTION
**Pull request by ling-alan-huang**
The previous PR: https://github.com/liferay-headless/liferay-portal/pull/1235

> Background:
> Add a testcase to import and export objects
> 
> Test Plan
> SelectCustomObjectAsEntityType
> Given a custom object is published
> When select the custom object as the entity type to export
> Then no error in server console
> 
> ExportCustomObjectWithObjectEntry
> Given a custom object is published
> And Given object entry is created
> When user export custom object as entity type and map attribute codes
> Then the zip file contains a related file type export successfully
> 
> ExportCustomObjectWithAllFieldTypesMapped
> Given a custom object with all kinds of field type is publushed
> And Given object entry is created
> When user export custom object with all attributes codes selected
> Then the zip file contains a related file type export successfully
> 
> ExportCustomObjectEntryWithOneToManyRelationship
> Given two custom objects published
> And Given oneToMany releationship has been set between them
> And Given one entry related to antoher one
> When user export custom object as entity type
> Then zip file contains related file type export successfully
> 
> ExportCustomObjectEntryWithManyToManyRelationship
> Given two custom objects published
> And Given manyToMany releationship has been set between them
> And Given one entry related to another one
> When user export custom object as entity type
> Then zip file contains related file type export successfully
> 
> Jira ticket:
> https://issues.liferay.com/browse/LPS-176966

### CODE REVIEW

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:relevant

**Comment by Hijky** [comment]
ci:test:relevant

**Comment by Hijky** [comment]
ci:closed

**Comment by Hijky** [comment]
ci:reopen

**Comment by Hijky** [comment]
ci:closed

**Comment by Hijky** [comment]
It will be re-send in this [PR](https://github.com/liferay-headless/liferay-portal/pull/1247)

**Pull request closed without merging**
