### PR TITLE
LPS-104697 Implement endpoint to get the list of content pages

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@javierdearcos, @nhpatt

**Comment by jkappler** [comment]
We have to launch echo suit too, and see that nothing from export is broken (all my manual tests worked)

**Comment by jkappler** [comment]
fixed the wording of the last commit.....

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
Rebased here: https://github.com/liferay-headless/liferay-portal/pull/501

**Pull request closed without merging**
