### PR TITLE
LPD-20706 Avoid adding custom objects to the list of classes to test

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPD-20706

---

The purpose of this PR is to avoid adding the Custom Object classes into the _testableClassNames, as they are being tested in different tests

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
Hey @ccorreagg can you explain in the commit message a bit more why this is needed?

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
> Hey @ccorreagg can you explain in the commit message a bit more why this is needed?

Please @4lejandrito confirm the updated commit message is ok for you

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
