### PR TITLE
LPS-120746 Update checkstyle version in REST Builder due to a known vulnerability

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
Why we need the 
```
	from (configurations.compile) {
		include "checkstyle-*.jar"
	}
```

block?

**Review by nhpatt — APPROVED** [review]

**Comment by nhpatt** [comment]
ci:forward

**Comment by javierdearcos** [comment]
> Why we need the
> 
> ```
> 	from (configurations.compile) {
> 		include "checkstyle-*.jar"
> 	}
> ```
> 
> block?

Just as an anecdote. Without this code it doesn't work. The reason I've found in the commit message of the original code that I had copied:
https://github.com/liferay/liferay-portal/commit/1d735bd14dddd34aa74fb68f5ca499a659d2e13c

I've modify the PR because a new version was needed and send it to Hugo Huijser to check it, as it can affect Service Builder and Source Formatter also:
https://github.com/hhuijser/liferay-portal/pull/5279

**Comment by nhpatt** [comment]
"Add magic from Peter" LOL

**Pull request closed without merging**
