### PR TITLE
LPD-19899 Add upgrade process to transform to lowercase the fields "applicationName" and "scopeAliases"  of the OAuth2ScopeGrant table when it refers to the Object's bundle

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPD-19899

---

The purpose of this PR is to update the database rows of the table `OAuth2ScopeGrant` to transform to lowercase the fields `applicationName` and `scopeAliases`

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
@ccorreagg does that mean we change the data in the DB, but in front the applicationName will remain lowercase?

**Review by 4lejandrito — APPROVED** [review]

**Review by magjed4289 — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
