### PR TITLE
LPD-32898 When scheduled job's status fails to update to "Failed", it will be "In Progress" forever

### PR DESCRIPTION
**Pull request by vendeltoreki**
[LPD-32898](https://liferay.atlassian.net/browse/LPD-32898)

Use the `@Retry` attribute to make sure the status of the scheduled task is set, even when temporary problems, like database deadlocks occur during the update.

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
@vendeltoreki can we close this already since the issue has been solved?

**Comment by vendeltoreki** [comment]
> @vendeltoreki can we close this already since the issue has been solved?

@4lejandrito , yes, I think we can close this PR and [LPD-32898](https://liferay.atlassian.net/browse/LPD-32898) with Won't fix, as there's a DB config solution.

**Comment by ccorreagg** [comment]
As you mentioned, it seems the root issue was caused by a wrong configuration in the database; however, I wonder if merging this code is worth it instead of just closing the PR and the related bug.

I mean, I think other issues are easily reproducible as we haven't configured a retry policy, so the issue of having a forever "in progress" task is easily reproducible too.

What do you think @4lejandrito @vendeltoreki ?

**Comment by 4lejandrito** [comment]
This did not fix the issue @ccorreagg... I think it is better to skip these changes unless we find a good reason in the future.

**Comment by ccorreagg** [comment]
But does it retry in case there is an error in the DB?

**Comment by vendeltoreki** [comment]
In case of MS SQL Server, the retries happened instantly after each other and all of them failed with the same deadlock error, so it did not solve anything in the end. Probably with another DBMS or in another scenario, it would have worked.
Although, the issue is reproducible, but only by artificially putting locks on the table and it's not likely that something like that can happen in a real-life scenario.

**Comment by 4lejandrito** [comment]
Let's just close it.

**Pull request closed without merging**
