### PR TITLE
LPD-17410 Restores creation menu button in site templates

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPD-17410

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
@ealonso this was caused by 68cf6ab420bd4421d6c7ce50f9b8f47cd8061ea7.

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/147110

**Comment by ealonso** [comment]
@4lejandrito sorry about that, 😞

**Pull request closed without merging**
