### PR TITLE
Lps 168806 - Export process fails if the Object Definition name ends with a number

### PR DESCRIPTION
**Pull request by thienquach87**
HI Team,

Here is the PR for fixing https://issues.liferay.com/browse/LPS-168806
Please help to review it
Thanks,
Thien

### CODE REVIEW

**Comment by thienquach87** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
Hey @igorbeslic 
Reviewing the changes of this PR I realized that maybe the method [`fromTechnicalName`](https://github.com/liferay/liferay-portal/blob/201f3d3fec59d2ea77f7773a4ea2a513c779962d/modules/apps/object/object-api/src/main/java/com/liferay/object/entry/util/ObjectEntryNameUtil.java#L25-L33) does not do what we want.
If I understand well, the method is to get the name of an object that comes with the companyId attached to the end, right?
For example, `C_Student1234` where companyId is `1234` we should get `C_Student`

But, in the case that we have an object with the name `C_Object1`, the technical name will be `C_Object11234`. If we pass this technical name to the method, we will get `C_Object` which is incorrect.

For me, we should fix the regular expression used. What do you think?


Also, there was a change in the technical name again 😢 see [this commit ](https://github.com/liferay/liferay-portal/commit/c64f95a9)

Good thing is that as you introduce these util classes, there should be no problem with this (apart from the attached ticket of this PR)

**Review by LuismiBarcos — COMMENTED** [review]
See my comment above.
Thanks for the PR. We really appreciate it 🙂

**Comment by thienquach87** [comment]
@LuismiBarcos,

Thank you for review. I understand your idea and I guess you got @igorbeslic's idea based on comparing between 2 functions  https://github.com/liferay/liferay-portal/blob/201f3d3fec59d2ea77f7773a4ea2a513c779962d/modules/apps/object/object-api/src/main/java/com/liferay/object/entry/util/ObjectEntryNameUtil.java#L25-L33 and [toTechnicalName](https://github.com/liferay/liferay-portal/blob/201f3d3fec59d2ea77f7773a4ea2a513c779962d/modules/apps/object/object-api/src/main/java/com/liferay/object/entry/util/ObjectEntryNameUtil.java#L35-L38). However, in fact, the [toTechnicalName](https://github.com/liferay/liferay-portal/blob/201f3d3fec59d2ea77f7773a4ea2a513c779962d/modules/apps/object/object-api/src/main/java/com/liferay/object/entry/util/ObjectEntryNameUtil.java#L35-L38) function is never used in code. In addition, there are three places where the [fromTechnicalName](https://github.com/liferay/liferay-portal/blob/201f3d3fec59d2ea77f7773a4ea2a513c779962d/modules/apps/object/object-api/src/main/java/com/liferay/object/entry/util/ObjectEntryNameUtil.java#L25-L33) function is called. The parameter passed to function is taskItemDelegateName or internalClassName(not from [toTechnicalName](https://github.com/liferay/liferay-portal/blob/201f3d3fec59d2ea77f7773a4ea2a513c779962d/modules/apps/object/object-api/src/main/java/com/liferay/object/entry/util/ObjectEntryNameUtil.java#L35-L38)), so I think my logic is right, but it really conflicts with [toTechnicalName](https://github.com/liferay/liferay-portal/blob/201f3d3fec59d2ea77f7773a4ea2a513c779962d/modules/apps/object/object-api/src/main/java/com/liferay/object/entry/util/ObjectEntryNameUtil.java#L35-L38)) function, so what do you think if  I can create new function to solve this issue.

**Comment by igorbeslic** [comment]
@LuismiBarcos and @thienquach87 this is not good update.
The change made class method to work the opposite it did before. You have to consider that just weeks ago this was valid code and valid unit test.

@LuismiBarcos is correct with his observations
`fromTechnicalName` extracts C_Student from C_Student1234 where 1234 is companyId

This update made method `fromTechnicalName` to not work anything - it returns C_Student1234 if you pass C_Student1234.

If requirements changed you have to delete both, ObjectEntryNameUtil class, and test - but honestly I have feeling it is not the case.

As Luismi mentioned - you have to provide different implementation - follow Luismi instructions.

**Comment by igorbeslic** [comment]
https://github.com/liferay-headless/liferay-portal/pull/943 this is correct fix

**Pull request closed without merging**
