### PR TITLE
LPS-182705 Use plural name instead of the schema name followed by 's'

### PR DESCRIPTION
**Pull request by ccorreagg**
Issue related: https://issues.liferay.com/browse/LPS-182705

---

This code fix the way the plural of the schema name is being calculated in some Java code and free marker templates of the REST Builder.

* For the `ResourceOpenAPIParser.java` class, the `TextFormatter.formatPlural` is used.
* For the `*.ftl` templates, the `schemaNames` variable is used as it is injected in the context with the result of the `TextFormatter.formatPlural` method.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:forward

**Comment by Hijky** [comment]
Test failures are unrelated. OK to manually forward

**Comment by Hijky** [comment]
ci:forward:force

**Comment by Hijky** [comment]
ci:forward:force

**Comment by ccorreagg** [comment]
Forwarded manually. See [here](https://github.com/brianchandotcom/liferay-portal/pull/133950)

**Pull request closed without merging**
