### PR TITLE
LPS-163284 com.liferay.portal.kernel.model.role.RoleConstants does not exist

### PR DESCRIPTION
**Pull request by 4lejandrito**
Fixes https://issues.liferay.com/browse/LPS-163284.

The new package does not exist in 7.2, but there is still the deprecated original class, so we are using it now. If in the future the class is deleted we will have to inline the constants.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Review by LuismiBarcos — APPROVED** [review]
LGTM :)

**Comment by LuismiBarcos** [comment]
Errors seem not related. Second chance to CI.

**Comment by 4lejandrito** [comment]
https://github.com/liferay-headless/liferay-portal/pull/747

**Comment by 4lejandrito** [comment]
https://github.com/4lejandrito/liferay-portal/pull/563

**Comment by 4lejandrito** [comment]
https://github.com/4lejandrito/liferay-portal/pull/569

**Comment by 4lejandrito** [comment]
https://github.com/4lejandrito/liferay-portal/pull/570

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/123342

**Pull request closed without merging**
