### PR TITLE
LPS-163387 Add test to assert approved status of object definition batch import

### PR DESCRIPTION
**Pull request by yanan**
**Background:**

- Add poshi functional tests for story: Support workflow status in ObjectDefinition batch import

**Test Plan:**

- Given in import and export center I create an import file task
When import objectDefinition with an existing json file in which status is approved
Then the import process completed successfully
And Then the status of the imported objectDefinition is approved
- Given in import and export center I create an import file task
When import objectDefinition with an existing json file in which the status is draft
Then the import process completed successfully
And Then the status of the imported objectDefinition is Draft

**Jira Ticket:**

- https://issues.liferay.com/browse/LPS-163387

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
