### PR TITLE
LPD-23664 Improve performance for publishing pages

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

As this ticket sits on the boundary of echo and headless, I'd like to ask you to review it as well.

The aim of this ticket is to give more control for Admins on which referred Pages are published during a Staging in order to reduce the (possibly unnecessary) data transfer between the staging and the live site

https://liferay.atlassian.net/browse/LPD-23664

Also, please do not ci:forward, I'd like to have this review by @liferay-echo as well

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:headless-staging

**Comment by DaniSzimko** [comment]
Hello @balazssk ,
I found a regression during the review. When I select the 'Selected Only' staging configuration option and then attempt to enable local staging for a blank site, it throws a ConstraintViolationException regarding the Utility Pages. As we discussed, the Utility Pages should be part of the initial staging process. I will re-assing the ticket to you.

**Comment by 4lejandrito** [comment]
@balazssk closing for now. Please reopen if necessary.

**Pull request closed without merging**
