### PR TITLE
LRQA-82574 Ignore to run unit tests in etl project

### PR DESCRIPTION
**Pull request by yanan**

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:relevant

**Review by Hijky — APPROVED** [review]

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
