### PR TITLE
LPS-177592 Test for delete batch actions automatically with REST Builder

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPS-177592

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Looks very nice @magjed4289. Let's see if all the tests pass and we haven't missed any use cases.

**Review by 4lejandrito — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
waiting for[ this task](https://issues.liferay.com/browse/LPS-182692) to be finished

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Closing for now. Will get back to it if needed in the future.

**Pull request closed without merging**
