### PR TITLE
LRQA-84217 

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LRQA-84217
@4lejandrito @sergiojimcos 
The test was failing because there was an invalid "null" value sent as Status of the entry. However in testPutSystemObjectEntryWithNestedCustomObjectEntriesByExternalReferenceCode we use the same UserAccount object (without the status field being set), and the test pases OK. So, I'm wondering what is the difference and whether I'm masking an eventual bug rn 😅

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hey @magjed4289! That's because `testPutSystemObjectEntryWithNestedCustomObjectEntriesByExternalReferenceCode` is calling `UserAccountTestUtil.addUserAccountJSONObject` whereas your fix goes in `UserAccountTestUtil.updateUserAccountJSONObject` (**add** vs **update**). Add calls `POST` and update calls `PUT`. [The failing logic](https://github.com/liferay/liferay-portal/blob/cb77d1144b00b4116061e6aa54b7aa96990c5c15/modules/apps/headless/headless-admin-user/headless-admin-user-impl/src/main/java/com/liferay/headless/admin/user/internal/resource/v1_0/UserAccountResourceImpl.java#L778-L790) is only present in the `PUT` method`.

**Review by 4lejandrito — APPROVED** [review]

**Review by sergiojimcos — APPROVED** [review]
LGTM!!

**Comment by magjed4289** [comment]
> Hey @magjed4289! That's because `testPutSystemObjectEntryWithNestedCustomObjectEntriesByExternalReferenceCode` is calling `UserAccountTestUtil.addUserAccountJSONObject` whereas your fix goes in `UserAccountTestUtil.updateUserAccountJSONObject` (**add** vs **update**).
> 
> Add calls `POST` and update calls `PUT`. [The failing logic](https://github.com/liferay/liferay-portal/blob/cb77d1144b00b4116061e6aa54b7aa96990c5c15/modules/apps/headless/headless-admin-user/headless-admin-user-impl/src/main/java/com/liferay/headless/admin/user/internal/resource/v1_0/UserAccountResourceImpl.java#L778-L790) is only present in the `PUT` method.

oh yeah, that makes sense! Thanks for explaining it! And for the reviews 💟

**Comment by magjed4289** [comment]
ci:forward:force

**Pull request closed without merging**
