### PR TITLE
LPD-21241 Autogenerate GraphQL integration tests for the new namespaces

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPD-21241

---

NOTE: This PR has been created on top of https://github.com/liferay-headless/liferay-portal/pull/1940

---

The purpose of this PR is to autogenerate the GraphQL integration tests for the new available namespaces. The new namespaced queries and mutations were included in this task: https://liferay.atlassian.net/browse/LPD-6667

In that task, some integration tests were created to test the basic functionality. In this PR, some autogenerated tests have been included (in the REST Builder) to test the new namespaced queries, matching the same results as with the previous non-namespaced queries.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by sergiojimcos — APPROVED** [review]
LGTM!!

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:report:2557713945

**Comment by ccorreagg** [comment]
The errors do not seem related

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
