### PR TITLE
LPS-203423 Generate the HttpInvoker#body call taking into account the request body media type defined into the rest-openapi.yaml

### PR DESCRIPTION
**Pull request by rafaprax**
Related issue: https://liferay.atlassian.net/browse/LPS-203423

The purpose of this PR is to fix the generation of the *Resource classes from the rest-client modules. This change fixes the httpInvoker#body calls to take into account the requestBody media type defined in the rest-openapi.yaml instead of using the `application/json` hard coded.

### CODE REVIEW

**Comment by rafaprax** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Hey @rafaprax looks good but we will perform a deeper review on Thursday (tomorrow is public holiday). Is that ok?

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-headless/liferay-portal/pull/1741.

**Pull request closed without merging**
