### PR TITLE
LPS-161982 LO - support for workflow status if submitted by batch engine

### PR DESCRIPTION
**Pull request by igorbeslic**

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]
Hi Igor! I think we can move forward with this, merge it to master and get ray's feedback.

**Comment by igorbeslic** [comment]
ci:reevaluate:1367401_2116

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1367401_2116

**Review by ccorreagg — APPROVED** [review]
LGTM

**Comment by igorbeslic** [comment]
ci:reevaluate:1367401_2116

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:reevaluate:1367401_2116

**Comment by igorbeslic** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
Sent directly https://github.com/brianchandotcom/liferay-portal/pull/124109

**Comment by lucasperj** [comment]
Just started reviewing :)

**Pull request closed without merging**
