### PR TITLE
LPS-102002 Deactive properties of existing endpoints

### PR DESCRIPTION
**Pull request by javierdearcos**
Follow-up of the API Extensibility PR to deactivate properties of existing endpoints.

Prepared PR to be merged after https://github.com/brianchandotcom/liferay-portal/pull/91967

### CODE REVIEW

**Comment by javierdearcos** [comment]
It may cause some conflicts if Brian makes some change in LPS-102001-new when he merges it

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
