### PR TITLE
LPD-35022 Test for site initializer: Welcome

### PR DESCRIPTION
**Pull request by LuisOrtiz89**
https://liferay.atlassian.net/browse/LPD-35022.

This test is executed for each available site initializer, and not just for "Masterclass".
The way it works is:
- Create a new site with one of the site initializers.
- Open that new site.
- Enable Local staging with the default configuration.
- Access the Live version of the Home page and take a screenshot.
- Access the Staging version of the Home page and take a screenshot.
- Compare both screenshots. They should be exactly the same. If not, test fails and a diff image is stored in the Playwright temp folder.

### CODE REVIEW

**Comment by LuisOrtiz89** [comment]
ci:test:playwright

**Comment by LuisOrtiz89** [comment]
ci:stop

**Comment by LuisOrtiz89** [comment]
ci:stop

**Review by 4lejandrito — APPROVED** [review]
See my changes.

**Comment by LuisOrtiz89** [comment]
ci:test:playwright

**Comment by LuisOrtiz89** [comment]
New test executed successfully.

**Comment by LuisOrtiz89** [comment]
ci:forward

**Pull request closed without merging**
