### PR TITLE
LPD-32088 Technical Task | test-fix batch-planner/import.spec.ts

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-32088

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:headless-functional

**Comment by magjed4289** [comment]
ci:help

**Comment by magjed4289** [comment]
ci:test:headless-functional

**Review by jaimelr10 — APPROVED** [review]
Changes are fine, great work! :smile:

**Comment by jaimelr10** [comment]
ci:test:headless-functional

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
