### PR TITLE
LPD-23771 NotificationQueueEntry recipients of Rest Client is parsing recipients wrong

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-23771

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hey @magjed4289 the serdes classes are autogenerated. If the issue is there, the fix must be in rest builder and applied globally.

**Comment by magjed4289** [comment]
thanks @4lejandrito , I'm aware, for now I'm working low level to find a proper solution so that we can apply it through template and autogenerated code. I already talked to Carlos that I need to find a solution that wouldn't involve external libraries 😅

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:test:stop

**Comment by magjed4289** [comment]
ci:close

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:close

**Comment by magjed4289** [comment]
resent https://github.com/liferay-headless/liferay-portal/pull/2027

**Pull request closed without merging**
