### PR TITLE
LPS-192566 Remove $ from x-must-start-with-the-x-character key

### PR DESCRIPTION
**Pull request by yanan**
Background:
- Our existing test APIEndpointRelevantObjectEntryModelListenerTest failed during assert 
Path must start with the $"/" character.

> java.lang.AssertionError: title
> Expected: Path must start with the "/" character.
> got: Path must start with the $"/" character.

Jira Ticket:
- https://liferay.atlassian.net/browse/LPS-192553

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-acceptance

**Review by ccorreagg — APPROVED** [review]
LGTM

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:forward:force

**Pull request closed without merging**
