### PR TITLE
LPS-149787 Talend Components - support for liferay object relation field names

### PR DESCRIPTION
**Pull request by igorbeslic**
PR includes test for LPS-149787

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:test

**Comment by jpince** [comment]
@manoelcyreno is there a smaller set of tests that could be run for talend changes like these? Running ci:test uses a lot of CI resources and would end up with a lot of unrelated failures for the dev to sift through.

Not sure if you are the correct QA contact, but I figured you would know who is :)

**Comment by manoelcyreno** [comment]
ci:test:headless

**Comment by igorbeslic** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/123894

**Pull request closed without merging**
