### PR TITLE
LPD-25034 , LPD-26478 Theme is reset in site created from site template

### PR DESCRIPTION
**Pull request by DaniSzimko**
JIRA ticket: https://liferay.atlassian.net/browse/LPD-25034 , https://liferay.atlassian.net/browse/LPD-26478

Set the imported layoutSet's themeId to the layoutPrototype's layoutSet's themeId during the propagation process

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:headless-staging

**Review by vendeltoreki — CHANGES_REQUESTED** [review]
Thanks @DaniSzimko for the fix! As discussed, can you please add integration test?
This is where I think it could go: https://github.com/liferay/liferay-portal/blob/e06624bcad988c46b7f0a19d55b92d396fadc688/modules/apps/export-import/export-import-test/src/testIntegration/java/com/liferay/exportimport/test/LayoutSetPrototypePropagationTest.java#L677

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:headless-staging

**Comment by DaniSzimko** [comment]
Since these two tickets are related and caused by the same issue, I decided to forward them in the same PR. I'll add the necessary integration tests soon.

cc @vendeltoreki , @4lejandrito

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:headless-staging

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:headless-staging

**Review by vendeltoreki — APPROVED** [review]
Tests added

**Comment by vendeltoreki** [comment]
ci:forward

**Pull request closed without merging**
