### PR TITLE
LPS-163574 Upgrade to graphql-java 17.4

### PR DESCRIPTION
**Pull request by 4lejandrito**
This upgrades graphql libraries to fix [this security vulnerability](https://issues.liferay.com/browse/LPS-163574).

The commits tell the story of the changes needed to migrate to the new libraries. The most important things that had to be changed were:

1. With the new library the request processing was being performed in a separate thread by default which was breaking our thread locals. Fixed in https://github.com/liferay-headless/liferay-portal/pull/779/commits/d6abc1498b396dd26914d4056c9bc2d303eb0b96.
2. The schema is now immutable and we were mutating it via reflection. Fixed in https://github.com/liferay-headless/liferay-portal/pull/779/commits/c270579833a6c7130fa621bc3d8112633daf816d.

The only thing that worries me is this commit: https://github.com/liferay-headless/liferay-portal/pull/779/commits/f3a71124fd74464c96a9ae7e631b74a6db5c7eb8. I am not sure about the implications of that change... I could not find a way to test the directives.

I have tested that the schema is right before & after by comparing the generated JSON. This commit shows the diff: https://github.com/4lejandrito/LPS-163574/commit/0fc7c1e676b9c0f69ddb4c1df8eb8031430a0ada. I corrected all the issues and I believe the rest is just things added by the new library related to directives, and it's ok.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Review by ccorreagg — COMMENTED** [review]
LGTM, but I would really appreciate if we include an extra test to verify the fields that can be recovered in GraphQL but not in REST, for example, the field contentStructure in the structuredContents GraphQL query, what do you think?

**Comment by 4lejandrito** [comment]
> LGTM, but I would really appreciate if we include an extra test to verify the fields that can be recovered in GraphQL but not in REST, for example, the field contentStructure in the structuredContents GraphQL query, what do you think?

What do you think about creating a separate task to add more integration tests to graphql? This PR doesn't change the functionality so adding tests for other things seems unrelated.

**Comment by ccorreagg** [comment]
> > LGTM, but I would really appreciate if we include an extra test to verify the fields that can be recovered in GraphQL but not in REST, for example, the field contentStructure in the structuredContents GraphQL query, what do you think?
> 
> What do you think about creating a separate task to add more integration tests to graphql? This PR doesn't change the functionality so adding tests for other things seems unrelated.

The point is that I am a bit scared of missing some non-common functionality as I guess we are not testing, at least in integration tests

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) 👏 👏 👏 👏

**Comment by 4lejandrito** [comment]
@magjed4289 can you manually test this before merging? We're just upgrading the graphql library version so no functional changes should happen. But we're not 100% sure if something might be broken that we have not tested.

**Comment by ccorreagg** [comment]
Anyway, I am going to test it before forwarding it, ok?

**Comment by ccorreagg** [comment]
> Anyway, I am going to test it before forwarding it, ok?

I made some tests and all of them passed, LGTM from my side

**Comment by 4lejandrito** [comment]
ci:forward

**Review by matijapetanjek — APPROVED** [review]
LGTM :+1:

**Pull request closed without merging**
