### PR TITLE
LPS-178428 Batch engine deploy zip files doesn't work

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:stable

**Comment by magjed4289** [comment]
ci:test:stable

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@magjed4289 @matijapetanjek merged to master and the temp branch. Praying this works!

**Comment by yanan** [comment]
No test failures related to the PR on relevant test suite. @matijapetanjek @magjed4289 
[Comapre run results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2234488769&testrayRunIdA=2235034964&statusB=2):
- PortalSmokeUpgrade#ViewPortalSmokeArchive7310  passed on rca
-  LocalFile.AutoDeployMultipleEntriesZipFile#CanAutoDeployObjectDefinitionZipWithJsonl  Flaky, passed locally
- Other tests in AutoDeployMultipleEntriesZipFile passed

**Pull request closed without merging**
