### PR TITLE
LPS-163251 Scroll bar disappears when user finish importing in import/export center

### PR DESCRIPTION
**Pull request by 4lejandrito**
useModal was being used twice, so there was a ghost modal blocking the
whole page after the import modal was being closed.

Now each modal uses it's own hook so they are properly closed.

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
Failures related. I'll fix and resend.

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by magjed4289** [comment]
Some of the test failures are related. a [[test-fix]](https://issues.liferay.com/browse/LPS-174482) will be provided for failing test cases. OK to manually forward ✅

**Comment by 4lejandrito** [comment]
Hey @magjed4289 let's discuss this tomorrow... I want to understand why tests are failing.

**Comment by magjed4289** [comment]
@4lejandrito it happened because the text in the field is being changed and the text is one of the atributes we're mapping the element with

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/129671

**Pull request closed without merging**
