### PR TITLE
LPS-158259 Set scopes to avoid 401 Unauthorized error when using OAuth 2.0 as the authorization mechanism in GraphQL

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to allow using OAuth 2.0 as the authorization mechanism to interact with GraphQL: https://issues.liferay.com/browse/LPS-158259.

For each companyId, a java Servlet is created to manage the requests through GraphQL. The servlet is generated by using [this external library](https://www.graphql-java.com/), configuring its schema properly.

As the external library uses the `DataFetcher` class to execute the desired code for each request by invocating the method `get(DataFetchingEnvironment var1)`, the necessary operations to control the scope of the request has been included in that method, as in that point, the request body has been properly parsed by the library.

When parsing the following namespaces, the scope context is set based on the JAX-RS Application that will end up managing the request, its bundle  and the Service Access Policy that is set in the JAX-RS request lifecycle too.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]
As discussed:

1. Get this reviewed by appsec.
2. Make sure QA writes functional tests for GraphQL + OAuth2.
3. Investigate if we can reuse the oauth2 code between jaxrs and graphql.

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
cc/ @stian-sigvartsen

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Created this PR https://github.com/liferay-headless/liferay-portal/pull/742 that includes a new interface in Vulcan instead of including the code directly in the base DataFetcher class

**Pull request closed without merging**
