### PR TITLE
LPS-200782 adding a checkbox status to not always publish the DDLRecord

### PR DESCRIPTION
**Pull request by ZakiMiklos**
https://liferay.atlassian.net/browse/LPS-200782

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by 4lejandrito** [comment]
@vendeltoreki I assigned you as reviewer.

**Comment by vendeltoreki** [comment]
Hi @ZakiMiklos ,

Can you please check whether this compile error is relevant or just an issue with the test environment?

https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest(master)/5506/consoleFull

```
     [exec] > Task :apps:dynamic-data-lists:dynamic-data-lists-uad:deploy
     [exec] Files of project ':apps:dynamic-data-lists:dynamic-data-lists-uad' deployed to /opt/dev/projects/github/liferay-portal/bundles/osgi/portal
     [exec] 
     [exec] > Task :apps:dynamic-data-lists:dynamic-data-lists-uad:deployDependencies NO-SOURCE
     [exec] > Task :apps:dynamic-data-lists:dynamic-data-lists-uad:deployConfigs NO-SOURCE
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/dynamic-data-lists/dynamic-data-lists-web/src/main/java/com/liferay/dynamic/data/lists/web/internal/exportimport/portlet/preferences/processor/DDLDisplayExportImportPortletPreferencesProcessor.java:171: error: cannot find symbol
     [exec] 			portletDataContext, className.getValue());
     [exec] 			                    ^
     [exec]   symbol:   variable className
     [exec]   location: class com.liferay.dynamic.data.lists.web.internal.exportimport.portlet.preferences.processor.DDLDisplayExportImportPortletPreferencesProcessor
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/dynamic-data-lists/dynamic-data-lists-web/src/main/java/com/liferay/dynamic/data/lists/web/internal/search/RecordSetSearch.java uses or overrides a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/dynamic-data-lists/dynamic-data-lists-web/src/main/java/com/liferay/dynamic/data/lists/web/internal/exportimport/portlet/preferences/processor/DDLDisplayExportImportPortletPreferencesProcessor.java uses unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 1 error
     [exec] 
     [exec] > Task :apps:dynamic-data-lists:dynamic-data-lists-web:compileJava FAILED
```

Thanks,
Vendel

**Comment by ZakiMiklos** [comment]
Hi @vendeltoreki 

I updated the commit it should be working now.

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Hi @ZakiMiklos ,

I looked at the test case `DDLDisplayExportImportTest.testExportImport`:
```
cd ~/dev/projects/liferay-portal/modules/apps/dynamic-data-lists/dynamic-data-lists-test/
gw :apps:dynamic-data-lists:dynamic-data-lists-test:testIntegration --tests=com.liferay.dynamic.data.lists.internal.exportimport.test.DDLDisplayExportImportTest
```
It fails with your commit in DDLDisplayExportImportPortletPreferencesProcessor, but it seemed to work fine before it.

Can you please check this test as well?

Thanks,
Vendel

**Comment by ZakiMiklos** [comment]
Hi @vendeltoreki Updated the PR. And on local the test passed now.

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
Forwarding on: https://github.com/liferay-headless/liferay-portal/pull/1771

**Pull request closed without merging**
