### PR TITLE
LPS-155809: Allow developers to create a custom object entry and it's related custom objects in a single request

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Update `DefaultObjectEntryManagerImpl` to allow addig a new object entry and theirr related objects.
- Add new Feature Flag.
- Create new test cases for adding related objects entries.

This is the first PR to allow developer to create an object entry (Custom Object) and their related object entries (Custom Object) using nested entities. This implementation allows creating nested entities with a `1-M` (both sides) and `M-M` relationships.

**NOTE**: It is necessary to set the property `feature.flag.LPS-153117=true`

### Example
Let's see an example. Imagine that we have a `M-M` relationship with Subjects and their Students in this way:

- `Student` is a Custom Object. Has a many-to-many relationship (`studentSubject`) with `Subject which is a Custom Object`. To create a new student and their related subjects, we can to this:

```bash
curl --request POST 'http://localhost:8080/o/c/students/' \
--header 'Content-Type: application/json' \
--data-raw '{
    "name": "Bob",
    "externalReferenceCode": "bob",
    "studentSubject": [
        {
            "name": "Physics",
            "externalReferenceCode": "physics"
        },
        {
            "name": "Chemist",
            "externalReferenceCode": "chemist"
        }
    ]
}'
```
This request is going to create a new student `Bob` and their related subjects: `Physics` and `Chemist` and link them because they have a `M-M` relationship (`studentSubject`). 

**NOTE**. In the case that `Students` doesn't have a relationship with `Subjects` a `BAD REQUEST` will be thrown.

### How to deploy it

Deploy the following modules:

- object-rest-impl.
- Don't forget the `feature.flag.LPS-153117=true`

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-168456

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by yanan** [comment]
Hi @sergiojimcos , the test failures are unrelated, here are more details for the [compare run results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2159963556&testrayRunIdA=2160214327&statusB=3):

- Poshi tests passed locally/running single job on jenkins
  - LocalFile.CreateObject#CanCreateStringField
  - LocalFile.CreateObject#CanOnlySeeEntriesFromAccount
  - LocalFile.CreateObject#CanSetDifferentLanguageForObjectLabel
  - LocalFile.CreateObject#CanUpdateRelationship
  - LocalFile.ObjectActions#CanEnableAndDisableCondition
  - LocalFile.ObjectAutoGeneratedView#CanViewObjectEntriesAfterAddingAttachment 	
  - LocalFile.ObjectPortlet#CanDeleteEntry
  - LocalFile.ObjectRelationships#[CannotRelateAnEntryWithItself](https://test-1-1.liferay.com/userContent/jobs/root-cause-analysis-tool/builds/8307/jenkins-report.html)
  - LocalFile.Permissions#[CannotConfigureBlogsPortletAsGuestPG](https://test-1-1.liferay.com/userContent/jobs/root-cause-analysis-tool/builds/8306/jenkins-report.html) 
- com.liferay.portal.security.membership.policy.site.test.SiteMembershipPolicyRolesTest 
  - also occurs on Acceptance master sometimes, existing ticket: [LRQA-73613](https://issues.liferay.com/browse/LRQA-73613)

**Comment by sergiojimcos** [comment]
> Hi @sergiojimcos , the test failures are unrelated, here are more details for the [compare run results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2159963556&testrayRunIdA=2160214327&statusB=3):
> 
> * Poshi tests passed locally/running single job on jenkins
>   
>   * LocalFile.CreateObject#CanCreateStringField
>   * LocalFile.CreateObject#CanOnlySeeEntriesFromAccount
>   * LocalFile.CreateObject#CanSetDifferentLanguageForObjectLabel
>   * LocalFile.CreateObject#CanUpdateRelationship
>   * LocalFile.ObjectActions#CanEnableAndDisableCondition
>   * LocalFile.ObjectAutoGeneratedView#CanViewObjectEntriesAfterAddingAttachment
>   * LocalFile.ObjectPortlet#CanDeleteEntry
>   * LocalFile.ObjectRelationships#[CannotRelateAnEntryWithItself](https://test-1-1.liferay.com/userContent/jobs/root-cause-analysis-tool/builds/8307/jenkins-report.html)
>   * LocalFile.Permissions#[CannotConfigureBlogsPortletAsGuestPG](https://test-1-1.liferay.com/userContent/jobs/root-cause-analysis-tool/builds/8306/jenkins-report.html)
> * com.liferay.portal.security.membership.policy.site.test.SiteMembershipPolicyRolesTest
>   
>   * also occurs on Acceptance master sometimes, existing ticket: [LRQA-73613](https://issues.liferay.com/browse/LRQA-73613)

Thanks a lot @yanan! :heart: Forwarding manually to Brian, just I rebased with master because there was a conflict with `Objectentry ResourceTest`, it was a refactor that was made [here](https://github.com/brianchandotcom/liferay-portal/pull/128652/commits/dc6bf383cc0e95eddca1aed61fd133a42e5fdcfe)

**Comment by sergiojimcos** [comment]
Manual forwarding to Brian: https://github.com/brianchandotcom/liferay-portal/pull/128737

**Pull request closed without merging**
