### PR TITLE
LPD-30390 Fix upgrade test

### PR DESCRIPTION
**Pull request by movaldivia**
https://liferay.atlassian.net/jira/software/c/projects/LPD/boards/626?selectedIssue=LPD-30390

### CODE REVIEW

**Comment by movaldivia** [comment]
ci:test:headless-functional

**Comment by movaldivia** [comment]
ci:test:headless-functional

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by movaldivia** [comment]
ci:forward

**Pull request closed without merging**
