### PR TITLE
LPD-24967 | Review & adapt tests using hard-coded test password - integration and POSHI tests

### PR DESCRIPTION
**Pull request by GaborKomaromi**
Related ticket: https://liferay.atlassian.net/browse/LPD-24967

### CODE REVIEW

**Comment by GaborKomaromi** [comment]
ci:test:sf

**Comment by GaborKomaromi** [comment]
ci:test:relevant

**Review by sergiojimcos — CHANGES_REQUESTED** [review]
Hey @GaborKomaromi!! I was taking a view at this file and we must update it too because it is used in so many TestCase files:
https://github.com/liferay/liferay-portal/blob/04c0268a74a72620e8a6640f9bcbb877e644775d/portal-test/src/com/liferay/portal/kernel/test/util/HTTPTestUtil.java#L151. Could you please check this? After that, I will take another view

**Comment by sergiojimcos** [comment]
As we talked privately, we should make some changes in `batch-planner`, `batch-engine`, `dispatch` and those modules related to Staging.

**Comment by sergiojimcos** [comment]
Rebase errors and new PR sent here: https://github.com/liferay-headless/liferay-portal/pull/2030

**Pull request closed without merging**
