### PR TITLE
LPS-167011 batch-engine - DO NOT TOUCH Batch Engine Code if you dont …

### PR DESCRIPTION
**Pull request by igorbeslic**
…know what are you doing - please. CATCH block still writes to DB and it needs companyId of currently active LXC instance

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
ci:forward

**Pull request closed without merging**
