### PR TITLE
LPD-23664 Improve performance for publishing pages

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

As this ticket sits on the boundary of echo and headless, I'd like to ask you to review it as well.

The aim of this ticket is to give more control for Admins on which referred Pages are published during a Staging in order to reduce the (possibly unnecessary) data transfer between the staging and the live site

https://liferay.atlassian.net/browse/LPD-23664

Also, please do not ci:forward, I'd like to have this reviewed by @liferay-echo as well

previous PR: https://github.com/liferay-headless/liferay-portal/pull/2070

### CODE REVIEW

**Comment by DaniSzimko** [comment]
Hello @balazssk ,
I reviewed your changes again, and I discovered a strange ConstraintViolationException.
Reproduction steps:
1. Go to System Settings -> Infrasrtucture -> Staging, and set the Publish Referred Pages select menu to 'Selected Only'
2. Create a blank site and enable local staging
3. Create a Content Page
4. Create a master page template and place a button on the template. Set the button's link to the page created in the third step.
5. Create a page from the master page template
6. Try to publish with every page selected in the pageTree

I believe the expected behavior here is that the publication is successful, and the master page template + all the selected pages are published on the live site.

image

Could you please review it?

Thank you.

**Comment by balazssk** [comment]
Cheers @DaniSzimko ,
I've fixed the ConstraintViolationException

**Comment by DaniSzimko** [comment]
Hello @balazssk ,
I reviewed your changes, and now I discovered that if I would like to publish only the child page with the 'Selected Only' configuration, it publishes the parent too.
Reproduction steps:

1. Go to System Settings -> Infrasrtucture -> Staging, and set the Publish Referred Pages select menu to 'Selected Only'
2. Uncheck 'Publish Parent Pages by Default' configuration option
3. Create a blank site and enable local staging
4. Create a Content Page named 'PP'
5. Create a Content Page under 'PP' named 'CP'
7. Try to publish with only 'CP' selected in the pageTree

I believe the expected behavior here is that the publication is failed with a MissingReferenceException. 
Currently it publishes the parent page and the child page too.

Could you please review it?

Thank you.

**Comment by 4lejandrito** [comment]
Closing to clean our PR list. @balazssk please reopen if necessary.

**Comment by DaniSzimko** [comment]
Hello @balazssk ,

I've reviewed your improvements once again and discovered an issue. When trying to publish a single page created from a master page template with 'From last publish date' settings, the publication fails with a NullPointerException. This happens because there is no end date in this date mode.

As we discussed in person, I am reassigning the ticket to you to fix this problem.

**Comment by 4lejandrito** [comment]
Closing PR for now.

**Pull request closed without merging**
