### PR TITLE
LPD-31549  Expose ERC in object's attachment fields

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-31549

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:report:55467461

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
@lfbesada I believe we should remove https://github.com/liferay-headless/liferay-portal/pull/2140/commits/e5de8eb521fe617a537600ed3c0a0b7f47ef260b from the PR. We use both type of files to cover both areas of the code. I would not like to change that just for the sake of this PR.

Also, should this PR include support for writing the externalReferenceCode in the same POST that includes the attachment? Can you double check this with product next week? I think at least we should have that story. At the moment if we send a ERC in the payload it will not be persisted (see https://github.com/liferay/liferay-portal/blob/58322ca32e6e52986f8aaad8916a7bbfb96372c5/modules/apps/object/object-api/src/main/java/com/liferay/object/field/attachment/AttachmentManager.java#L19).

For now I believe it is safe to send this PR without that commit.

**Comment by lfbesada** [comment]
@4lejandrito Thanks for your review :heart: I have added your feedback and resent [here](https://github.com/liferay-echo/liferay-portal/pull/16072)

**Pull request closed without merging**
