### PR TITLE
LPS-173132 

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket: [LPS-173132](https://issues.liferay.com/browse/LPS-173132)
___
## Purpose of the PR
Fix the error that appears when trying to get the related elements of a relationship of an object with itself.

Let's see an example:
* Given an Object called Language with a Name field
* Given a relationship with itself called Relationship
* Given the following languages created as object entries:
  * Languages
  * Spanish -> belongs to Languages
  * English -> belongs to Languages
  * Spanish basic -> belongs to Spanish
  * Spanish intermediate -> belongs to Spanish
  * Spanish advanced -> belongs to Spanish
  * English basic -> belongs to English
  * English intermediate -> belongs to English
  * English advanced -> belongs to English

Doing the following request we will receive the immediate child
image

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
