### PR TITLE
Revert "LPD-42653 Use package name under liferay when importing rest …

### PR DESCRIPTION
**Pull request by dannielraposo**
This reverts commit 4d7632032140910fb604e8eace714fb0950dabcd.

### CODE REVIEW

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:test:stable

**Comment by dannielraposo** [comment]
close it since it was to test if reverting the issue got solved but it still fails

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:stable

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-headless/liferay-portal/pull/2379.

**Pull request closed without merging**
