### PR TITLE
COMMERCE-9809 batch-engine - skip collections (we do not support in CSV/XLSX)

### PR DESCRIPTION
**Pull request by igorbeslic**
prevents failures of export process

### CODE REVIEW

**Comment by igorbeslic** [comment]
@matijapetanjek here is commit you have to cherry pick

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:test:stable

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
ci:stable

**Comment by igorbeslic** [comment]
ci:test:stable

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by ccorreagg — APPROVED** [review]
LGTM

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by igorbeslic** [comment]
ci:stop

**Pull request closed without merging**
