### PR TITLE
LPS-203472 Use the encapsulated UploadServletRequest to create the MultipartBody object in MultipartBodyMessageBodyReader

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPS-203472

---

The purpose of this ticket is to modify the way the `MultipartBody` is being built. Before this PR, the `HttpServletRequest` injected by Apache CXF as a context parameter was the request that was being used to build the MultipartBody.

By analyzing the bug, we realised an `UploadServletRequest` was being generated [here](https://github.com/liferay/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/apps/portal/portal-upload-servlet-request-filter/src/main/java/com/liferay/portal/upload/servlet/request/filter/internal/UploadServletRequestFilter.java#L99). That means that request already contains the multiparts, so it is no longer needed to parse it again inside the `MultipartBodyMessageBodyReader` class.

For that, we have modified the `MultipartBodyMessageBodyReader` in order to get the multiparts from the previously created `UploadServletRequest` instead of using the `HttpServletRequest` injected by CXF.

### CODE REVIEW

**Review by 4lejandrito — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Review by ccorreagg — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
Test failures are not related ✅

**Comment by ccorreagg** [comment]
ci:test:stable

**Review by 4lejandrito — APPROVED** [review]
Hey @magjed4289, @ccorreagg, see my commits. I've removed the kb test and tested this in vulcan. That way we do not need rest builder changes.

I verified the test fails without the changes and passes with them.

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
I just added some extra validations to check the expected values have been sent properly and received by the java method

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
> I just added some extra validations to check the expected values have been sent properly and received by the java method for both cases, just simple parameters and also files

Thanks! Feel free to forward.

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
