### PR TITLE
LPS-161981 support technical json - single batch engine import file 

### PR DESCRIPTION
**Pull request by igorbeslic**
This change allows batch engine deployer to process ZIP entries that contain both batch engine configuration and import data in the single file.

What we should review here:
- we named that type of file **technical json file**
- we set extension to that file `.jsont` and deployer implementation would use special reader for it
- proposed structure of technical json file is this
````

{
"configuration":{},
"data": []
}
````
what should be added?
do we miss anything?
@rotty3000

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by rotty3000** [comment]
@igorbeslic I don't think you need to define a new JSON format however, Just use the OpenAPI "collection" format already emitted by the headless APIs, as long as it contains the actions

**Comment by rotty3000** [comment]
in fact I insist that you don't define a new format and use the existing one. This will make batch much more friendly.

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by rotty3000** [comment]
@igorbeslic is the export part coming in a different PR?

**Comment by igorbeslic** [comment]
@rotty3000 yes, correctly - I have to go this way as I'm touching to many modules

**Comment by igorbeslic** [comment]
ci:stop

**Comment by rotty3000** [comment]
@igorbeslic do you plan to have a headless API which produces the JSONT format? My problem with the current design is that no other API will support producing that format which is why I feel the format should make `"configuration": {...}` optional and if not present decipher from `"actions": {...}`. We could use the OpenAPI resource services to figure out the type from a URI of actions.

**Comment by igorbeslic** [comment]
@rotty3000 in this moment with this change one can take Page object produced by any GET request and copy paste it as-is to /batch endpoint and submit. It would import data.
If one goes via ZIP deployer, Page object must be enriched with configuration node to pass necessary details like companyId and userId.
Implementation is quite flexible, and I can make it work any way we decide

**Comment by igorbeslic** [comment]
> 

Configuration node is reqiuired ONLY for ZIP files. Yes if you omit configuration node for ZIP deployer you'll get message that configuration is wrong that companyId or userId is missing. (hm, maybe message would be `configuration is insufficient`)
For API Explorer we obtain companyId/userId from current user session
For Import/Export we obtain companyId/userId from current user session

**Comment by rotty3000** [comment]
before you proceed please let me consider some details of this approach. It's a broken assumption that you need a different file when importing with a ZIP because a client extension on prem is used as a ZIP, while in cloud it's used to call headless API and the JSONT files need to be identical in both cases.

**Comment by igorbeslic** [comment]
This is how batch-engine processes ZIP:
- unzip and collect deployable entries
- create batchEngineImportTask record in DB where rows content is stored in CLOB field
- then BE executes process by obtaining correct batchEngineDelegate using either batchEngineDelegate provided as parameter in configuration node or internalClassName provided as parameter in configuration node
- before execution BE takes companyId and userId and configures contextCompanyId and contextUserId for batchEngineDelegate (it is interface implemented by *ResourceImpl class)

For batch engine ZIP deployer which is not tied to session nor particular companyId only way to direct ZIP entries to correct companyId and to use correct userId permissions is to read it somewhere in zip

We can update Page object OpenAPI schema to declare optional (required=false) configuration node, and document it as special purpose...
OR EVEN BETTER Lets define x-configuration field which is extension field used by tools.
What do you think??

**Pull request closed without merging**
