### PR TITLE
LPS-125312 Take the option label instead of the value string (option …

### PR DESCRIPTION
**Pull request by javierdearcos**
…identifier) as the value of the content field

### CODE REVIEW

**Comment by javierdearcos** [comment]
I'm not sure if this is an old bug or it is caused by a change of behavior of DDM.

If it is a change of behavior we should be careful that this change of behavior is maintain and it is not considered a bug to be fixed, as it could affect this change

**Review by nhpatt — APPROVED** [review]

**Comment by nhpatt** [comment]
Looks like a bug, approving.

**Comment by nhpatt** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
