### PR TITLE
LPS-196412- API Builder relationship fields should be system

### PR DESCRIPTION
**Pull request by G-Sa**
Related to [LPS-196412](https://liferay.atlassian.net/browse/LPS-196412)

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Thanks @G-Sa!

**Review by 4lejandrito — APPROVED** [review]

**Comment by G-Sa** [comment]
ci:test:relevant

**Comment by yanan** [comment]
The following failed tests in relevant seem related, here are more details of [compare run results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2455415030&testrayRunIdA=2454325278&statusB=2): :thinking: 
- integration test failures
    - [com.liferay.headless.builder.application.provider.test.APIApplicationProviderTest](https://testray.liferay.com/reports/production/logs/2023-11/test-1-27/test-portal-acceptance-pullrequest(master)/10666/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)  expected: `com.liferay.headless.builder.internal.application.provider.APIApplicationProviderImpl$4@4286492b` but was `null`
    - [com.liferay.headless.builder.resource.test.HeadlessBuilderOpenAPIResourceTest](https://testray.liferay.com/reports/production/logs/2023-11/test-1-27/test-portal-acceptance-pullrequest(master)/10666/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0) components.schemas Expected: PageSchemaName but none found
    - [com.liferay.headless.builder.resource.test.HeadlessBuilderResourceTest](https://testray.liferay.com/reports/production/logs/2023-11/test-1-27/test-portal-acceptance-pullrequest(master)/10666/modules-integration-mysql57-jdk8/0/2/jenkins-console.txt.gz?authuser=0) 404 in /c/qur8jayk/openapi.json
- functional tests
    - LocalFile.AllowUsersToDefinePrefilters
    - LocalFile.AllowUsersToDefineSorts
    - LocalFile.ChangePublicationStatusOnClusterNodes
    - LocalFile.ExposeQueryParametersInAPIExplorerForGeneratedAPI
    - LocalFile.AllowUsersToDefineEndpointsForObjectsWithSiteScope
    ...
@4lejandrito @G-Sa

**Comment by sergiojimcos** [comment]
New PR here: https://github.com/liferay-headless/liferay-portal/pull/1695

**Pull request closed without merging**
