### PR TITLE
LPS-202530 Ensure the fields from the ZIP are keeping the order

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-202530

---

The purpose of this PR is to ensure the order with the fields/folders inside a ZIP are being kept

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by sergiojimcos — APPROVED** [review]
LGTM!!

**Review by 4lejandrito — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
