### PR TITLE
LPD-40178 Show warning also to the fields that belongs to the single container in the UI

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPD-40178

Given the following API Builder schema instance:

```json
{
  "sender" : {
    "avatar_url" : "https://avatars.githubusercontent.com/u/32699538?v=4",
    "login" : "ccorreagg"
  },
  "action" : "created",
  "starred_at" : "2024-10-16T14:48:59.000Z"
}
```

Before the PR:
image

After the PR:
image

NOTE: The first commits are already in brianchandotom/master. I have included them because otherwise, we should fix the conflicts once this PR is sent to Brian. Please, consider reviewing just the last commit of this PR

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:help

**Comment by ccorreagg** [comment]
ci:test:api-builder

**Comment by magjed4289** [comment]
ci:test:api-builder-functional

**Review by 4lejandrito — APPROVED** [review]

**Pull request closed without merging**
