### PR TITLE
LPS-202545: Check if objectFieldSetting is null or empty to set unique property for ObjectFields

### PR DESCRIPTION
**Pull request by sergiojimcos**
## Motivation
This PR checks if the objectFieldSettings is null or empty. If it is not, it will retrieve the objectFieldSetting value given its key.

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPS-202545

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:object

**Comment by 4lejandrito** [comment]
> Hey @sergiojimcos , would you mind to improve the integration test created by @jaimelr10 [here](https://github.com/brianchandotcom/liferay-portal/pull/143271/commits/c82482fc1d8f2e53fd5c15aeab803624a3803d1c) to cover this scenario?

Hey @guilhermedcamacho, Sergio is on PTO. What if we forward the PR and we improve the test next week when he is back? Otherwise this may get blocked unnecessarily.

**Comment by guilhermedcamacho** [comment]
> > Hey @sergiojimcos , would you mind to improve the integration test created by @jaimelr10 [here](https://github.com/brianchandotcom/liferay-portal/pull/143271/commits/c82482fc1d8f2e53fd5c15aeab803624a3803d1c) to cover this scenario?
> 
> Hey @guilhermedcamacho, Sergio is on PTO. What if we forward the PR and we improve the test next week when he is back? Otherwise this may get blocked unnecessarily.

No problem :smile: I created this [task](https://liferay.atlassian.net/browse/LPS-202744) for him so we can keep track of it. Thanks!

**Comment by 4lejandrito** [comment]
@magjed4289 please verify these failures.

**Comment by Hijky** [comment]
The failures are not related to PR, these are [compared results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2467119922&testrayRunIdA=2465608095&statusB=2), it's okay to forward it.

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/144564

**Comment by sergiojimcos** [comment]
New [PR](https://github.com/liferay-headless/liferay-portal/pull/1751) opened to improve PATCH Object Field

**Pull request closed without merging**
