### PR TITLE
LPD-37447 Upgrade version

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPD-37447

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:help

**Comment by ccorreagg** [comment]
ci:Test:headless

**Comment by ccorreagg** [comment]
ci:test:headless

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
