### PR TITLE
LPD-35125 Technical Task | Investigate error thrown in com.liferay.exportimport.test.LayoutExportImportTest

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-35125

before the PR:
`PortalLogAssertorTest#testScanXMLLog: Unable to get a staged model data handler for a null value because a model was not exported properly`

after the PR:
no ERROR logs and com.liferay.exportimport.test.LayoutExportImportTest > testLayoutExportImportWithChildLayoutReferencedWithButtonAndChildLayoutHasParentLayout passes correctly ✅

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:close

**Comment by magjed4289** [comment]
ci:reopen

**Comment by magjed4289** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
forwarding on https://github.com/liferay-headless/liferay-portal/pull/2181

**Pull request closed without merging**
