### PR TITLE
LPS-171724 Ignore the tests until finding a fix

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPS-171724

### CODE REVIEW

**Review by Hijky — APPROVED** [review]

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:headless-functional

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
