### PR TITLE
LPS-187660 Removing feature flags LPS-165819 & LPS-154672

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by Hijky** [comment]
The failures are not related to your PR. Here are [the comparison results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2351401238&testrayRunIdA=2351894323&statusB=2).

**Comment by Hijky** [comment]
ci:forward:force

**Pull request closed without merging**
