### PR TITLE
LPD-28799 Remove feature flag from LPD-28799

### PR DESCRIPTION
**Pull request by dannielraposo**
https://liferay.atlassian.net/browse/LPD-31945

### CODE REVIEW

**Comment by dannielraposo** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by dannielraposo** [comment]
ci:report:21353022

**Comment by 4lejandrito** [comment]
Test failures seem not related.

**Pull request closed without merging**
