### PR TITLE
LPD-38746 | Change click target to match current page

### PR DESCRIPTION
**Pull request by jaimelr10**
**Description**:  Fix for `Editing global web contents does not trigger site template propagation` test
**Jira Ticket**: https://liferay.atlassian.net/browse/LPD-38703

### CODE REVIEW

**Comment by jaimelr10** [comment]
ci:test:headless-playwright

**Comment by jaimelr10** [comment]
ci:test:headless-playwright

**Comment by jaimelr10** [comment]
ci:test:headless-playwright

**Review by magjed4289 — CHANGES_REQUESTED** [review]
Tests are still not passing. @jaimelr10 could you check and work on the current flakiness? Thank you!

**Comment by jaimelr10** [comment]
ci:test:headless-playwright

**Comment by jaimelr10** [comment]
ci:test:headless-playwright

**Comment by jaimelr10** [comment]
ci:forward

**Pull request closed without merging**
