### PR TITLE
LPS-182365 PATCH requests can cause localized Custom Field data to be deleted if not provided in the request body

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://issues.liferay.com/browse/LPS-182365

When customFields are not passed in PATCH, they are being populated in the existing entity with [acceptAllLanguages = false](https://github.com/liferay/liferay-portal/blob/aae616071f686e01dcc6c8960ae8c2a61947e976/modules/apps/headless/headless-admin-user/headless-admin-user-impl/src/main/java/com/liferay/headless/admin/user/internal/dto/v1_0/converter/UserResourceDTOConverter.java#L135).  This means [the data_i18n map is not being populated](https://github.com/liferay/liferay-portal/blob/22927a43cf8fe787f4c3f61c0ab1d68f96af093c/modules/apps/headless/headless-admin-user/headless-admin-user-impl/src/main/java/com/liferay/headless/admin/user/internal/dto/v1_0/util/CustomFieldsUtil.java#L292-L294) with the existing translations and therefore only the default one ends up being set.

With this fix we ensure `customFields` are set to null if not present in the payload, which makes them being untouched at the end of the operation.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
No related test failures. OK to manually forward ✅

**Review by ccorreagg — COMMENTED** [review]
I forgot to include the approval! LGTM

**Pull request closed without merging**
