### PR TITLE
LRQA-64155 Ignore tests

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@tim-cao

**Comment by nhpatt** [comment]
You can remove the throws Exception... I don't know if sf complains.

**Review by nhpatt — APPROVED** [review]

**Comment by jkappler** [comment]
> You can remove the throws Exception... I don't know if sf complains.

removed

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
