### PR TITLE
LPS-161698 Avoid send "actions" property for system relationships items for now.

### PR DESCRIPTION
**Pull request by LuismiBarcos**
As we need to improve the information returned by the `actions` property, we are sending it as empty for now.
Of course, this is under a feature flag and should not affect the existing endpoints.

An example, the actions property is empty for collection and for each item of the collection returned by the relationship endpoint.
imagen

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]
Nice!

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
Please CI, be nice 🙏

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
@LuismiBarcos, forward manually to brian

**Comment by LuismiBarcos** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/123086

**Pull request closed without merging**
