### PR TITLE
COMMERCE-11747 Headless BigDecimal array support

### PR DESCRIPTION
**Pull request by smottal**
Add support to BigDecimal Array on *SerDes.java generated file.

This PR adds a new method (toBigDecimals) on BaseJSONParser file and use it on *SerDes when managing fieldValues with type BigDecimal[]

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by smottal** [comment]
Hi @4lejandrito: I think the error is "correct" because probably we need to update all the existing BaseJSONParser but I don't know if should be in the scope of this PR or how usually you manage this "massive updates" (and how to do it)

**Review by jalber786 — CHANGES_REQUESTED** [review]
Just a few comments/questions:
1. Every PR that changes something related to restBuilder should be sent with a commit called `buildREST` in which you execute the `buildREST` command both in `liferay-portal/modules/apps and liferay-portal/modules/dxp/apps`
2. I'm seeing by executing buildREST locally that the wanted method is created but never used. Is this because it's usage is present in a different PR?
3. I don't know if generating it in all the modules that have a jsonparser file It's such a good idea. It should probably be created only in those modules that are going to use a BigDecimal. [See this example](https://github.com/liferay-headless/liferay-portal/blob/f81dc316e4f3f1dcfe5e0865f8c92e365e67b9c5/modules/util/portal-tools-rest-builder/src/main/resources/com/liferay/portal/tools/rest/builder/dependencies/base_resource_impl.ftl#L1400C1-L1400C1) for reference of how to only generate this methods in case a specific type needs to be used.

**Comment by jalber786** [comment]
ci:test:sf

**Comment by jalber786** [comment]
ci:test:relevant

**Review by jalber786 — APPROVED** [review]
LGTM!

**Comment by 4lejandrito** [comment]
Hey @smottal, can you add the commits that will be using the new method? We would like to see the final result and send it all in one go.

**Comment by smottal** [comment]
Hi @4lejandrito, unfortunately it's not possible to add here the single commit of the "use of the method" because it's part of a big PR https://github.com/liferay-commerce/liferay-portal/pull/4185 with a lot of other changes

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by Hijky** [comment]
The failures are not related to your PR, there are the [compared results](https://testray.liferay.com/zh/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2418030551&testrayRunIdA=2418491571&statusB=2)

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/140218

**Pull request closed without merging**
