### PR TITLE
LPS-195627 Remove [createDate, modifiedDate] Object Definition internal fields from the OpenAPI

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-195627

---

The purpose of this PR is:

- To remove the internal object fields `createDate` and `modifiedDate` from the OpenAPI, as both fields are translated into the `dateCreated` and `dateModified` fields. This change applies to all the Object Entries, independently of the Object Definition type.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]
It would be great to have a test like the one we have in API Builder that uses [an expected openapi json](https://github.com/liferay/liferay-portal/blob/4458350de684667eac5100e0c73d887589ef19ce/modules/apps/headless/headless-builder/headless-builder-test/src/testIntegration/resources/com/liferay/headless/builder/resource/test/dependencies/expected_openapi.json). But not as part of this PR. We can think about it in the future.

**Comment by ccorreagg** [comment]
> It would be great to have a test like the one we have in API Builder that uses [an expected openapi json](https://github.com/liferay/liferay-portal/blob/4458350de684667eac5100e0c73d887589ef19ce/modules/apps/headless/headless-builder/headless-builder-test/src/testIntegration/resources/com/liferay/headless/builder/resource/test/dependencies/expected_openapi.json). But not as part of this PR. We can think about it in the future.

I totally agree with you

**Comment by yanan** [comment]
Test failures are not related to pr from qa perspective.

**Comment by ccorreagg** [comment]
> Test failures are not related to pr from qa perspective.

Thanks !! :partying_face:

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
