### PR TITLE
LPS-204034 Remove unused @Reference - Part 2

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPS-204034. Part 2. Export/Import.

I am not 100% sure about these ones. Let's wait for the test results.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
The only failing test unique to this PR is `DefaultExportImportContentProcessorTest`. I've tested it locally and it passes most of the time, but I saw it failing several times with and without these changes...

**Comment by 4lejandrito** [comment]
> The only failing test unique to this PR is `DefaultExportImportContentProcessorTest`. I've tested it locally and it passes most of the time, but I saw it failing several times with and without these changes... It seems it is a flaky test.
> 
> It seems suspicious... I'll keep investigating.

It looks like the flakiness is introduced by these changes. I run the whole suite 10 times with and without the changes and without them the 10 times were successful.

**Comment by vendeltoreki** [comment]
Hi @4lejandrito ,

I looked at some of the changes but could not find anything yet that can cause this. I remember we had issues with this before, but usually right after startup. If you remove some dependencies then the load order of the OSGi modules can change, and that can cause some intermittent problems.

**Comment by 4lejandrito** [comment]
I can reproduce the flakiness also in master... So I believe now these changes are not causing it.

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
According to https://test-1-1.liferay.com/job/generate-testray-csv/7681/ the test did not fail this time.

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/146051

**Pull request closed without merging**
