### PR TITLE
LPD-33577 Jobs are not rescheduled in the cluster, when the master node is stopped and a new master is selected

### PR DESCRIPTION
**Pull request by vendeltoreki**
[LPD-33577](https://liferay.atlassian.net/browse/LPD-33577)

Resending https://github.com/liferay-headless/liferay-portal/pull/2150 .

Changed test method names according to https://github.com/brianchandotcom/liferay-portal/pull/153652#issuecomment-2312181631 .

cc: @ccorreagg

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
