### PR TITLE
LPS-179278 Autogenerate tests for export-batch endpoint

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to autogenerate the tests in the `Base*ResourceTestCase.java` class to verify the proper behavior of the `POST` `/export-batch` endpoints generated by REST Builder.

As several tests are being ignored/overriden, some of the export-batch autogenerated tests have been ignored too to avoid failing. The teams that own the components will be notified to manage the autogenerated tests as they consider once this PR is merged.

For the rest, some bugs/technical tasks have been generated as some errors have been detected (see the commit messages). The ignored tests will be available again as soon the bugs are fixed

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) Good job 👏 👏 👏

**Comment by ccorreagg** [comment]
rebased with master

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by yanan** [comment]
No failures related to the pr, ready to forward from qa pespective
- [compare results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2248034738&testrayRunIdA=2248331756&statusB=2) and failed test passed on a second run using rca on jenkins

**Comment by ccorreagg** [comment]
Thank you @yanan !

**Comment by ccorreagg** [comment]
ci:forward:force

**Comment by ccorreagg** [comment]
Forwarded manually: https://github.com/brianchandotcom/liferay-portal/pull/132542

**Pull request closed without merging**
