### PR TITLE
LPD-25633 Batch performance issue

### PR DESCRIPTION
**Pull request by gustavolimav**
https://liferay.atlassian.net/browse/LPD-25633

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hey @gustavolimav,

I just tested this PR and could see great improvements. With this PR the total time to import 1000 items is 40% of the time it took before (32s vs 13s). I could see elastic search calls are now proportional to the number of batches instead of the number of elements.

Thanks a lot!

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]
See my comment. We will do some more tests and forward when ready.

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by gustavolimav** [comment]
@4lejandrito thx for the testing! If you need anything from search side let me know, I will be waiting to create the hotfix requested for this ticket when it is approved.

**Comment by jkappler** [comment]
Also, again, thanks for the changes @gustavolimav 🫶

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
