### PR TITLE
LPS-160015 | Expose documents information in navigation menus APIs

### PR DESCRIPTION
**Pull request by Hijky**
**Background**
Expose documents information in navigation menus APIs

**Test Plan**
Given a navigation menu
And Given a document is uploaded with post request
And Given a navigation menu doesn't use custom name associate with the document through UI
When with get request and siteId to retrieve the navigation menu
Then I can see values of useCustomName of false, contentURL equals to document endpoint and type equals to document

Given a navigation menu
And Given a document is uploaded with post request
And Given a navigation menu use custom name associated with the document through UI
When with get request and navigationMenuId to retrieve the navigation menu
Then I can see values of useCustomName equals to true, contentURL equals to document endpoint and type equals to document

Given a navigation menu
And Given an asset library connect to the site
And Given a document is uploaded with post request in asset library
And Given a navigation menu doesn't use custom name associate with the document through UI
When with get request and siteId to retrieve the navigation menu
Then I can see values of useCustomName of false, contentURL equals to document endpoint and type equals to document 

Given a navigation menu
And Given an asset library connect to the site
And Given a document is uploaded with post request in asset library
And Given a navigation menu use custom name associated with the document through UI
When with get request and navigationMenuId to retrieve the navigation menu
Then I can see values of useCustomName equals to true, contentURL equals to document endpoint and type equals to document

**JIRA Link:**
https://issues.liferay.com/browse/LPS-160015

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:headless-frontend-functional:nocompile

**Comment by Hijky** [comment]
@magjed4289 @yanan I think the failures are not related to my PR.

**Review by yanan — APPROVED** [review]

**Review by magjed4289 — APPROVED** [review]

**Comment by Hijky** [comment]
ci:forward

**Pull request closed without merging**
