### PR TITLE
LPD-44414 Nested fields from the "grandfather" class are not added to the DTO

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-44414

Hi Team,

I've created this fix to address a bug I encountered when testing our nested fields. The fix is straightforward and should unblock our progress.

Could you please review it when you have a chance?

Thank you!

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Hey @lfbesada ,

Could you please indicate which DTOs classes are involved, which are the relationships and which one is not being calculated without the new code?

**Comment by lfbesada** [comment]
Hey @ccorreagg Thanks for the review! :heart: 
The DTO involved is PageTemplate and the nested field that's not working is pageSpecifications, declared on [modules/apps/headless/headless-admin-site/headless-admin-site-impl/rest-openapi.yaml](https://github.com/liferay/liferay-portal/blob/57201ddd261e092462939aaeb22e36c2d3e84350/modules/apps/headless/headless-admin-site/headless-admin-site-impl/rest-openapi.yaml#L2337-L2346)

**Comment by ccorreagg** [comment]
Thanks for your PR and contribution @lfbesada ! :love_letter: 

I have created [this PR](https://github.com/liferay-headless/liferay-portal/pull/2408) with some small changes and also we have fixed our test to verify the nested field has been calculated as expected

**Comment by lfbesada** [comment]
@ccorreagg Thank you very much :heart:

**Pull request closed without merging**
