### PR TITLE
LPS-186055 

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPS-186055

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:test:headless-functional:nocompile

**Comment by magjed4289** [comment]
ci:test:headless-functional:nocompile

**Review by Hijky — APPROVED** [review]

**Review by yanan — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
