### PR TITLE
LPS-198913 Running at the end of the transaction

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPS-198913.

The DB is not ready yet at that point.

### CODE REVIEW

**Review by ccorreagg — APPROVED** [review]
LGTM

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:forward

**Comment by Hijky** [comment]
The failures are not related to your PR, it's okay to forward it.

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
