### PR TITLE
LPD 38548 Add additional parameter restrictedFieldNames to ignore data when import Batch

### PR DESCRIPTION
**Pull request by movaldivia**
Changes with Brian comments.

Previous pr: https://github.com/liferay-headless/liferay-portal/pull/2330

https://liferay.atlassian.net/browse/LPD-38548

What

Added an additional parameter restrictedFieldNames that let clients to ignore data when they are doing an import. For example you can ignore the permissions of your imported data.

### CODE REVIEW

**Comment by movaldivia** [comment]
ci:help

**Comment by movaldivia** [comment]
ci:test:sf

**Comment by movaldivia** [comment]
ci:test:headless

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by movaldivia** [comment]
ci:forward

**Pull request closed without merging**
