### PR TITLE
LPD-37589 Remove beta feature tests from acceptance

### PR DESCRIPTION
**Pull request by GaborKomaromi**
https://liferay.atlassian.net/browse/LPD-37589

### CODE REVIEW

**Comment by GaborKomaromi** [comment]
ci:test:acceptance:dryrun

**Comment by GaborKomaromi** [comment]
ci:test:sf

**Comment by GaborKomaromi** [comment]
ci:test:sf

**Comment by GaborKomaromi** [comment]
ci:test:sf

**Comment by GaborKomaromi** [comment]
ci:test:acceptance:dryrun

**Review by magjed4289 — APPROVED** [review]
Looks good, we just need to confirm the result in [EE Development Acceptance (master)](https://testray.liferay.com/#/project/35392/routines/590307) after it is merged, as we don't have any suite to check it on the PR

**Comment by GaborKomaromi** [comment]
ci:forward

**Comment by GaborKomaromi** [comment]
ci:forward:force

**Pull request closed without merging**
