### PR TITLE
LPS-104697 Adapt tests

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Review by javierdearcos — APPROVED** [review]
great work 😄 👏 🎉

**Comment by javierdearcos** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
ci:stop

**Pull request closed without merging**
