### PR TITLE
LPD 42652 | Use openapitools/openapi-generator-cli for client JS generation. Refactor playwright tests

### PR DESCRIPTION
**Pull request by dannielraposo**
https://liferay.atlassian.net/browse/LPD-42652

### CODE REVIEW

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:test:relevant

**Comment by dannielraposo** [comment]
ci:test:playwright

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:playwright

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by dannielraposo** [comment]
ci:forward

**Pull request closed without merging**
