### PR TITLE
LPS-167050 Creating a job schedule via API with a non existing Type, still creates it normally

### PR DESCRIPTION
**Pull request by nNilton**

### CODE REVIEW

**Comment by nNilton** [comment]
ci:test:sf

**Comment by nNilton** [comment]
ci:test:data-integration

**Review by igorbeslic — COMMENTED** [review]
I'll add commit that updates integration tests. Current tests use arbitrary executor type. Composed using RandomTestUtil :)

**Comment by igorbeslic** [comment]
@nNilton please check commit sequence in https://github.com/liferay-headless/liferay-portal/pull/890
- use service.xml and service builder to auto generate Exception class - https://github.com/liferay-headless/liferay-portal/pull/890/commits/0d751c5721fb7df56557a2388417d53101094ce3
- always run integration tests in dispatch-test or check its execution in CI and fix either code or update test - https://github.com/liferay-headless/liferay-portal/pull/890/commits/09f810b03db3660f5e006af3480041401b924cfc
- provide test for your new feature https://github.com/liferay-headless/liferay-portal/pull/890/commits/84eacc2286f9b2abd49d2ecc1999185c56060592

I'm closing this one - there is updated version here - https://github.com/liferay-headless/liferay-portal/pull/890

cc/ @4lejandrito

**Pull request closed without merging**
