### PR TITLE
LPD-37295 Fix failure in HideOptionsForEntitiesInImportAndExport#CanConfigImportWithOnlyAddImportStrategyAndUpdateChangedRecordFieldsStrategy

### PR DESCRIPTION
**Pull request by dannielraposo**
**What's changed?**
- Fixed test due to change in Catalog that now accepts two different strategies
- The new added test verifies the system's behavior when handling imports with duplicate External Reference Codes (ERCs). 

See the following Jira Ticket: [LPD-37295](https://liferay.atlassian.net/browse/LPD-37295)

### CODE REVIEW

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
