### PR TITLE
LPD-31906 Expose Scope in object's attachment fields ( if needed )

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-31906

This PR is only related to LPD-31906, but it is rebased on [LPD-31549's PR](https://github.com/liferay-headless/liferay-portal/pull/2140 ).
Because of that, this PR should be On Hold waiting for LPD-31549's PR review.
Thanks!

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @lfbesada I think this PR is ok. Nothing to add for now apart from what I said [here](https://github.com/liferay-headless/liferay-portal/pull/2140#pullrequestreview-2230437478).

**Comment by lfbesada** [comment]
@4lejandrito Thanks for your review ❤️ I have added your feedback and resent [here]( https://github.com/liferay-echo/liferay-portal/pull/16072)

**Pull request closed without merging**
