### PR TITLE
LPS-193434 | Test fix for ExportCustomObjectWithAllFieldTypesMapped

### PR DESCRIPTION
**Pull request by Hijky**
Background:
Test fix for ExportCustomObjectWithAllFieldTypesMapped

Jira ticket:
https://liferay.atlassian.net/browse/LPS-193434

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Review by yanan — APPROVED** [review]

**Comment by Hijky** [comment]
ci:test:headless-functional:nocompile

**Comment by Hijky** [comment]
ci:test:sf

**Review by magjed4289 — APPROVED** [review]

**Comment by Hijky** [comment]
ci:forward

**Comment by Hijky** [comment]
ci:forward:force

**Pull request closed without merging**
