### PR TITLE
LPS-169781 Using local services

### PR DESCRIPTION
**Pull request by 4lejandrito**
As in f6187cd26a98099ba86c801436cfa7eb0af961df that fixed this same problem in the old dto converter.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:reevaluate:1317401_6407

**Review by LuismiBarcos — APPROVED** [review]
LGTM :)

I suppose that the reason for the error is the same (reading the comments of the ticket, it seems like the same problem)

So, I assume that we are checking permissions before using this DTO so it is ok to use the local services

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
