### PR TITLE
LPS-111902 Code Editor Inconsistent Styling solved

### PR DESCRIPTION
**Pull request by dgomezg**
The code shown in questions now has the same syntax hightlighting than the one used when Creeating/editing the question.

This has been achieved by using the same CKEEditor (in readonly mode) and tweaking some of the styles to get rid of some toolbars, that is being using in edit mode

### CODE REVIEW

**Comment by dgomezg** [comment]
@nhpatt or @LuismiBarcos

**Comment by nhpatt** [comment]
LGTM, thanks!

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
Rebased here: https://github.com/liferay-headless/liferay-portal/pull/90

**Pull request closed without merging**
