### PR TITLE
LPS-195901 

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPS-195901

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:headless-builder

**Comment by magjed4289** [comment]
ci:test:headless-builder

**Comment by magjed4289** [comment]
ci:test:headless-builder

**Comment by 4lejandrito** [comment]
Thanks @magjed4289!

**Comment by magjed4289** [comment]
ci:test:headless-builder

**Comment by magjed4289** [comment]
ci:forward

**Comment by magjed4289** [comment]
@4lejandrito there are still some tests that belong to Core Infra in this suite, I'll keep investigate further if we can get rid of them, but for now I'll forward the way it is, as it's better than nothing :)

**Pull request closed without merging**
