### PR TITLE
LPS-166665 Extract deployment of swagger libs to a new module

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
Thanks for this PR

**Review by LuismiBarcos — APPROVED** [review]

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
