### PR TITLE
LRQA-83919 Add wait for loading api builder objects

### PR DESCRIPTION
**Pull request by yanan**
Background:

- Sometimes our api builder test will fail because of it hasn't finish loading all objects in object admin page. Add waitfor to avoid this kind of failures

JIra Ticket
- https://liferay.atlassian.net/browse/LRQA-83919

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-builder-functional

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:test:headless-builder-functional:nocompile

**Comment by magjed4289** [comment]
ci:close

**Comment by magjed4289** [comment]
ci:reopen

**Comment by magjed4289** [comment]
ci:test:headless-builder-functional:nocompile

**Comment by yanan** [comment]
ci:test:headless-builder-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
