### PR TITLE
LPS-182093 Remove readonly props handling from patch methods

### PR DESCRIPTION
**Pull request by 4lejandrito**
Ticket: https://issues.liferay.com/browse/LPS-182093.

Removing `useless`? code.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Review by ccorreagg — APPROVED** [review]
I consider a very possitive change; however, I am scared of breaking some customers that were already updating some fields marked as "readOnly" fields and using PATCH method; however, I think it is not very likely.

I wish we could verify all the auto-generated tests for PATCH keep working as before

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
