### PR TITLE
LPS-191340 Test fix for RESTBuilderTest.testCreateRESTBuilder

### PR DESCRIPTION
**Pull request by yanan**

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Test failures unrelated. Current fix passed.
image

**Review by ccorreagg — APPROVED** [review]
LGTM!

**Comment by yanan** [comment]
ci:forward:force

**Review by magjed4289 — APPROVED** [review]

**Comment by yanan** [comment]
ci:forward:force

**Pull request closed without merging**
