### PR TITLE
LRQA-84190 Test fix for HeadlessBuilderOpenAPIResourceTest on attachment fileBase64 desciption

### PR DESCRIPTION
**Pull request by yanan**
Background
- test fix for LPS-200125 to update fileBase64 description

Jira Ticket:
- https://liferay.atlassian.net/browse/LRQA-84190

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-builder

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Comment by yanan** [comment]
ci:forward:force

**Comment by yanan** [comment]
ci:forward:force

**Pull request closed without merging**
