### PR TITLE
LPS-202486 | Remove feature flag LPS-173135

### PR DESCRIPTION
**Pull request by jaimelr10**
**Jira Ticket:** https://liferay.atlassian.net/browse/LPS-202486

**Description**: Remove LPS-173135 Feature Flag

### CODE REVIEW

**Review by 4lejandrito — APPROVED** [review]

**Review by sergiojimcos — APPROVED** [review]

**Comment by jaimelr10** [comment]
ci:forward

**Comment by jaimelr10** [comment]
ci:forward

**Comment by yanan** [comment]
The following failed functional tests in relevant suite are related according to [the compare run results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2476997516&testrayRunIdA=2476695707&statusB=2):
- poshi functional tests
  -  LocalFile.ImportExport#CanDownloadJsonTFormatFileAsJson
  - LocalFile.ImportExport#GetExportFileAvailableEntityTypes
  - LocalFile.SupportExportObjectEntriesAtInstancelevel#AllSystemObjectFieldsAreAvailableToExport
  - LocalFile.SupportExportObjectEntriesAtInstancelevel#CanExportSystemObjectItems
  - LocalFile.SupportExportObjectEntriesAtSiteLevel#CanExportSpecificFieldsWithJSONTConfigurationNode
  - LocalFile.SupportImportObjectEntriesWithSiteScope#CanCreateAndUpdateExistingSiteScopedObjectEntriesWithSameFile
  - LocalFile.ImportExport#CanRecallExportTemplate

**Comment by magjed4289** [comment]
ci:help

**Comment by magjed4289** [comment]
ci:test:headless-functional:nocompile

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:headless-functional

**Comment by magjed4289** [comment]
ci:test:headless-functional

**Comment by jaimelr10** [comment]
ci:test:headless-functional

**Comment by jaimelr10** [comment]
ci:test:headless-functional

**Comment by jaimelr10** [comment]
ci:test:headless-functional

**Comment by jaimelr10** [comment]
ci:test:headless-functional

**Comment by jaimelr10** [comment]
ci:test:headless-functional

**Comment by magjed4289** [comment]
ci:forward

**Comment by magjed4289** [comment]
Test failures are not related. OK to manually forward! ✅

**Comment by magjed4289** [comment]
ci:forward:force

**Comment by jaimelr10** [comment]
ci:forward:force

**Comment by jaimelr10** [comment]
Sent directly in: https://github.com/brianchandotcom/liferay-portal/pull/146452

**Pull request closed without merging**
