### PR TITLE
LPS-190268 Update JSONTBatchEngineExportTaskItemWriterImplTest to include multiCompany

### PR DESCRIPTION
**Pull request by yanan**
Background:
- Update JSONTBatchEngineExportTaskItemWriterImplTest to include multiCompany in batchEngine

Jira Ticket:
- https://liferay.atlassian.net/browse/LPS-190268

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]
Thank so much @yanan.

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
