### PR TITLE
Master lps 169647

### PR DESCRIPTION
**Pull request by yanan**
**Background:**

- Add tests to add relationsihp between custom object and system object
- The second test case is failed when running on CI, haven't found the reason why it works locally while can't passed on CI, ignore it for now

**Test Plan**

- Given University object definition created
And Given manyToMany universitiesAccounts relationship created
And Given University entry created
And Given Account entry created
And Given I request PUT to relate University entry to the Account entry with "/o/c/universities/{universityId}/universitiesAccounts/{accountId}"
When I delete the Account entry
Then GET "/o/c/universities/{universityId}/universitiesAccounts" returns an empty Page
- Given University object definition created
And Given manyToMany accountsUniversities relationship created
And Given manyToMany universitiesAccounts relationship created
When I request PUT to relate University entry to the Account entry with "/o/c/universities/{universityId}/accountsUniversities/{accountId}"
Then university is not associated to the account in GET "/o/headless-admin-user/v1.0/accounts/{accountId}/universitiesAccounts"
- Given University object definition created
And Given oneToMany accountsUniversities relationship created
And Given oneToMany universitiesAccounts relationship created
When I request PUT to relate University entry to the Account entry with "/o/headless-admin-user/v1.0/accounts/{accountId}/universitiesAccounts"
Then Account entry is not associated to the University entry in GET "/o/c/universities/{universityId}/universitiesAccounts"

**JIRA Ticket:**

- https://issues.liferay.com/browse/LPS-169647
- https://issues.liferay.com/browse/LPS-163870

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:headless-functional

**Comment by yanan** [comment]
ci:test:headless-functional

**Comment by yanan** [comment]
ci:test:headless-functional

**Review by Hijky — APPROVED** [review]

**Comment by magjed4289** [comment]
This one as well! 👍🏻

**Review by magjed4289 — APPROVED** [review]

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-functional

**Comment by yanan** [comment]
ci:test:headless-functional

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
