### PR TITLE
LPD-15601

### PR DESCRIPTION
**Pull request by MirnaGama**
https://liferay.atlassian.net/browse/LPD-15601

Applying changes suggested in [PTR-4683](https://liferay.atlassian.net/browse/PTR-4683)

**Commit included:** 
- LPD-15601 Replace recursive multiple selection with just multiple so indeterminate status does not apply (https://github.com/liferay-headless/liferay-portal/pull/1837/commits/d135410a64ec61a2a6357a3a7215b92fbf81dc74)

### CODE REVIEW

**Comment by MirnaGama** [comment]
ci:stop

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Review by jaimelr10 — APPROVED** [review]
Looks good to me! :smile:

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
