### PR TITLE
LPD-44782 Remove Feature Flag

### PR DESCRIPTION
**Pull request by GaborKomaromi**
[LPD-44782](https://liferay.atlassian.net/browse/LPD-44782)

### CODE REVIEW

**Comment by GaborKomaromi** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:stop

**Comment by GaborKomaromi** [comment]
ci:test:relevant

**Comment by GaborKomaromi** [comment]
ci:test:sf

**Comment by GaborKomaromi** [comment]
ci:test:sf

**Comment by GaborKomaromi** [comment]
ci:test:sf

**Comment by GaborKomaromi** [comment]
ci:test:relevant

**Comment by GaborKomaromi** [comment]
@ccorreagg I made required changes after master was synced.

**Comment by GaborKomaromi** [comment]
ci:test:sf

**Comment by GaborKomaromi** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/157391

**Pull request closed without merging**
