### PR TITLE
LPD-34904 Technical Task | [test-fix] LocalStagingPublishParentLayoutsByDefaultTest.testStagingWithUncheckedConfigurationAndModifiedContentAndNonexistingParentAndChildLayoutsOnLive - modify according to the expected behavior

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-34904

Test modified because of https://liferay.atlassian.net/browse/LPD-34369?focusedCommentId=2720508

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:staging

**Comment by magjed4289** [comment]
ci:test:headless-staging

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
test class LocalStagingPublishParentLayoutsByDefaultTest passing correctly ✅

**Comment by DaniSzimko** [comment]
Hello @magjed4289,

I've reviewed your changes, and everything looks good to me. I might suggest adding an **assertNotNull** for **liveChildLayout** before the **Assert.assertNull(liveParentLayout)**, but that's all from my side.

Thank you.

**Comment by magjed4289** [comment]
Thanks @DaniSzimko , good idea, I'll add the change now and forward :)

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
