### PR TITLE
LRQA-84232 Test fix to add unique in objectField in BatchEngineBrokerTest.testImportObjectDefinition

### PR DESCRIPTION
**Pull request by yanan**
Background
- BatchEngineBrokerTest.testImportObjectDefinition integration test failed `testImportObjectDefinition: org.junit.ComparisonFailure: objectFields value mismatch`

Jira Ticket
- https://liferay.atlassian.net/browse/LRQA-84232

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:relevant

**Review by magjed4289 — COMMENTED** [review]
@yanan do we know what PR / Story changed the behavior? Is the unique field required now? Is it a behavior that is intended and have to do with a fix from custom to System or something like that?

**Comment by yanan** [comment]
> @yanan do we know what PR / Story changed the behavior? Is the unique field required now? Is it a behavior that is intended and have to do with a fix from custom to System or something like that?

@magjed4289 This test fix is because [LPS-200105](https://liferay.atlassian.net/browse/LPS-200105) in which the "unique" property is added into objectField

**Comment by 4lejandrito** [comment]
@jaimelr10 @ccorreagg :point_up:

**Review by magjed4289 — APPROVED** [review]

**Comment by yanan** [comment]
Hi @jaimelr10 @ccorreagg , the test passed in the pr, I am going to forward this test fix. Please feel free to update/ping me if there is anything else, thanks.

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
