### PR TITLE
LPD-20288 Sort by 'userId', 'creatorId','objectDefinitionId' or 'siteId' fails in the Object Entry REST API

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-20288

### CODE REVIEW

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Review by ccorreagg — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
It seems there is at least one failing test (ObjectEntryEntityModelTest). Maybe the semantic error also belongs to this PR

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:report:2559793868

**Comment by 4lejandrito** [comment]
Failures not related.

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
