### PR TITLE
LPS-182500 Fixing graphql vuln

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://issues.liferay.com/browse/LPS-182500

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
I would say it is ok 😁 😁 😁
The tests are ok so I assume that there is no problem with the upgrade

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
