### PR TITLE
LPS-113333 Modify solution to minimize Portal Vulcan API growth and to include file info in error

### PR DESCRIPTION
**Pull request by javierdearcos**
Following Brian advice I made some changes in the previous implementation to:
- Minimize Portal Vulcan API growth
- Provide file information in errors

Still one custom exception in Portal Vulcan API is needed because:
- To **extract YAML error information** the exception thrown by the YAML library needs to be processed to improve clarity. This is the main objective of this issue.
- To **isolate YAML library** and avoid spreading the dependency to modules using Portal Vulcan API

Also throwing Runtime exception when a YAML error is produced is needed to cause the gradle task failure (and also to abort executing the rest of the REST Builder flow). It is confusing logging errors and show at the end of the gradle task that it was successful.

The results are shown in the following screenshots
Captura de pantalla 2020-05-19 a las 11 50 46
Captura de pantalla 2020-05-19 a las 11 51 15
Captura de pantalla 2020-05-19 a las 10 35 31

### CODE REVIEW

**Comment by javierdearcos** [comment]
@nhpatt

**Comment by nhpatt** [comment]
ci:forward

**Comment by javierdearcos** [comment]
Updated error description to be closer to Brian suggestion

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:stop

**Pull request closed without merging**
