### PR TITLE
LPD-27473 Addapt tests to match with required code within status

### PR DESCRIPTION
**Pull request by dannielraposo**
This PR is to adapt some test that failed because of changes in https://github.com/liferay-headless/liferay-portal/pull/2203
- OpenAPIResourceTest.OpenAPIResourceTest

### CODE REVIEW

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by dannielraposo** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
