### PR TITLE
LPD-24168 Parent page is not updated when child page is referenced with button fragment

### PR DESCRIPTION
**Pull request by matijapetanjek**
Given the following page structure
- /home
- /parent
    - /child

and a button on /home page that links to a child page
and a StagingConfiguration.publishParentLayoutsByDefault == true
and a Local Staging enabled

When publishing only /home page, through references all 3 pages should be published 

- Child page is published because button fragment references child page
- Parent page is published because StagingConfiguration.publishParentLayoutsByDefault is enabled

The issue was that [StagedLayoutSetStagedModelDataHandler](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/exportimport/data/handler/StagedLayoutSetStagedModelDataHandler.java#L488) would override the action that was set by more specialized [LayoutStagedModelHandler](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/exportimport/data/handler/LayoutStagedModelDataHandler.java#L314).
The naive solution is if detected the action was already defined, skip overwriting the action. @vendeltoreki Please review the change as I'm not sure how this change reflects on other use cases.
Thank you!

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:headless-staging

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:test:stable

**Comment by matijapetanjek** [comment]
ci:forward:force

**Pull request closed without merging**
