### PR TITLE
LPS-163401 | Update functional test on cascade deletion type and sf

### PR DESCRIPTION
**Pull request by yanan**
**Background**:
- Update functional tests on cascade deletion type since object team has improved this

**Test Plan**:
- Test fix and sf on LocalFile.SupportManyToManyRelationships#DeletedObjectDoesNotAppearInManyToManyRelationshipDetailsNestedFields_2

**Ticket**:
- https://issues.liferay.com/browse/LPS-163401

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-frontend-functional:nocompile

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Test failures are unrealted. The only test failure is about prevent deletion type: LocalFile.SupportManyToManyRelationships#ObjectEntryDeletionImpossibleWithPreventDeletionTypeRelationshipCreated, which Kevin is taking a look in [LRQA-77162](https://issues.liferay.com/browse/LRQA-77162).

**Review by Hijky — APPROVED** [review]

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
LGTM! :) Thank you!

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
