### PR TITLE
LPD-43999 | Fix headless-builder-web/schemas.spec.ts > can see all available object definitions on schema creation

### PR DESCRIPTION
**Pull request by jaimelr10**
**Description**: Fill array with object definition and not with promises

**Jira Ticket**: https://liferay.atlassian.net/browse/LPD-43999

### CODE REVIEW

**Comment by jaimelr10** [comment]
ci:test:playwright

**Comment by jaimelr10** [comment]
The test passes in the ci

**Review by ccorreagg — APPROVED** [review]

**Comment by ccorreagg** [comment]
@dannielraposo Feel free to forward if you consider it is ok

**Review by dannielraposo — APPROVED** [review]

**Comment by dannielraposo** [comment]
ci:forward

**Pull request closed without merging**
