### PR TITLE
LPD-28696 Master template's inherited theme doesn't propagate to the site created from site template (Private Pages enabled)

### PR DESCRIPTION
**Pull request by DaniSzimko**
Jira ticket: [LPD-28696](https://liferay.atlassian.net/browse/LPD-28696)
related JIRA links : [LPD-26478](https://liferay.atlassian.net/browse/LPD-26478) , [LPD-25034 ](https://liferay.atlassian.net/browse/LPD-25034), [LPD-27945](https://liferay.atlassian.net/browse/LPD-27945) 

Set the imported layoutSet's themeId to the layoutPrototype's layoutSet's themeId based on link

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:headless-staging

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:headless-staging

**Comment by vendeltoreki** [comment]
Hi @DaniSzimko ,
I checked the repro steps in [LPD-28696](https://liferay.atlassian.net/browse/LPD-28696), and although the LayoutSet themes are updated correctly in the DB, no theme is applied when displaying private pages of the site.
If I create the master page template with a standard button fragment, it has no color when displayed on the site:
2024-06-21_15-20_no_theme
However, it works perfectly with public pages.
2024-06-21_15-23_dialect_theme
Can you please verify whether this is caused by this change?

**Comment by vendeltoreki** [comment]
Checked the rest of the code and test failures and everything seems ok to me.
* We should wait for [LPD-29563](https://liferay.atlassian.net/issues/LPD-29563) to be merged
* We will need some test for this code as well

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:headless-staging

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:stable

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:headless-staging

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
@DaniSzimko , from my side, the code changes and the test changes look OK. I think you can forward it when CI runs successfully.

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:headless-staging

**Pull request closed without merging**
