### PR TITLE
LPS-189041: Improve prompt message when creating an API with existing title/url in API Builder UI

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Delete `Error` tag twice in the toast when creating a API Application
- SF

**Before PR**
image

**After PR**
image

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPS-189041

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:stop

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by cgmonte — APPROVED** [review]
LGTM!

**Comment by cgmonte** [comment]
Hey @sergiojimcos are you rebasing from upstream? This will include lots of unrelated commits in your PR because of the diff between upstream and liferay-headless:master. I always rebase master from liferay-headless:master, so it only appears related commits in PR. It its easier to review.

**Comment by cgmonte** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
> Hey @sergiojimcos are you rebasing from upstream? This will include lots of unrelated commits in your PR because of the diff between upstream and liferay-headless:master. I always rebase master from liferay-headless:master, so it only appears related commits in PR. It its easier to review.

In this case, I rebase from upstream which has got Brian's changes, but I will do it again and forward it :wink:

**Comment by sergiojimcos** [comment]
ci:forward

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
Remove 0e1406aab1d36a85dd94bef18bb7eacd0fff5cea and manually send to Brian. Your changes should not require a baseline, so let that be fixed separately by Brian.

**Pull request closed without merging**
