### PR TITLE
LPS-191929 Fix Predicate.not operator to have a correct generated SQL

### PR DESCRIPTION
**Pull request by ccorreagg**
Related bug: https://liferay.atlassian.net/browse/LPS-191929

---

The purpose of this PR is to fix the `Predicate.not` operator. Before this PR, the `not` method of the `Predicate` interface received one argument, but it does not make sense as the `not` operator must negate the current predicate.

In the `DefaultPredicate.not()` method implemented uses the new `EmptyExpression` as left expression. That causes that the Consumer<String> that contributes to the SQL String is not invoked with the left part, avoiding to include text with invalid SQL syntax.

---

Example:

Given a Predicate (for example, a predicate whose SQL String value would be `O_20096_Student.studentName_ = 'value'`), if we negate the predicate:

**Before the PR**

The SQL String value would be: `O_20096_Student.studentName_ = 'value' not (O_20096_Student.studentName_ = 'value'))` and that causes the following error:

```
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(O_20096_Student.studentName_ = 'value')  limit 20' at line 1
```

**After the PR**

The SQL String value would be: `not (O_20096_Student.studentName_ = 'value'))`

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:stop

**Review by 4lejandrito — APPROVED** [review]
Looks good to me. Send to core infra for review.

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
See https://github.com/liferay-core-infra/liferay-portal/pull/5119

**Pull request closed without merging**
