### PR TITLE
LPS-124650 When we don't have a description do what we normally do in the portal: Use the first 400 characters of the entry content

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Review by javierdearcos — APPROVED** [review]
Elegant! 🙂

**Comment by javierdearcos** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
