### PR TITLE
LPD-19990 Initial data is not propagated when we switch to a different site template using `LayoutSetLocalServiceUtil.updateLayoutSetPrototypeLinkEnabled()`

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-19990

---

NOTE: This PR is LPP related: https://liferay.atlassian.net/browse/LPP-53073

---

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:playwright

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:playwright

**Comment by magjed4289** [comment]
ci:test:playwright:nocompile

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:test:playwright

**Comment by magjed4289** [comment]
ci:test:playwright

**Comment by magjed4289** [comment]
ci:test:playwright

**Comment by magjed4289** [comment]
ci:test:playwright

**Comment by magjed4289** [comment]
ci:test:playwright

**Comment by magjed4289** [comment]
ci:test:playwright

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:report

**Comment by magjed4289** [comment]
ci:help

**Comment by magjed4289** [comment]
ci:report

**Comment by magjed4289** [comment]
ci:report:2554256682

**Comment by magjed4289** [comment]
ci:test:playwright

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:stop:playwright

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:test:playwright

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:sf

**Review by vendeltoreki — COMMENTED** [review]
It seems like there's a problem when both templates use their default Home pages: their friendly URL will collide and the merge will fail. Although, the template swap will be successful. We still need to investigate that scenario.
Otherwise, when there's no friendly URL conflict, the fix works perfectly.

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:sf

**Pull request closed without merging**
