### PR TITLE
[TS] LPS-157425

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Original PR opened by @ericyanLr -> https://github.com/liferay-headless/liferay-portal/pull/1323
Original description:

https://issues.liferay.com/browse/LPS-157425

Hi Team,

**Context**
This PR was created with guidance from [PTR-3915](https://issues.liferay.com/browse/PTR-3915) and the plan is for the Search Team and Headless Team to review.

**Summary of Changes**
- Search
  - Update mapping to introduce multi-field keyword fields to replace the previous **\*_\<languageId>*_sortable** fields
    - As discussed, we will proceed with adding the sub-field: **\*_\<languageId>*_sortable.keyword_lowercase**
  - Also added mappings for Solr
- Headless API
  - For fields that are utilizing **\*_\<languageId>*_sortable** fields for filtering String fields
    - Use the associated sub-field: **\*_\<languageId>*_sortable.keyword_lowercase**
  - Added tests by updating the template: **base_resource_test_case.ftl** in portal-tools-rest-builder
    - Regenerated relevant tests by running gw buildRest

**Game Plan**
1. The Search Team has **tentatively approved** the proposed changes
2. The next step is for for the Headless Team to review the changes. 
3. If everything looks okay, **the plan will be to re-send back to the Search Team for final review**
    - The Search Team would like Bryan to do a final review (Bryan is on PTO and will be back on Friday)

And so, if the proposed changes look okay on the Headless side, we can re-send the PR to the Search Team for final review.

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Thanks @LuismiBarcos!

**Comment by LuismiBarcos** [comment]
Hey @ericyanLr 
The tests are not related, so you can forward this PR to the Search team for a final review.
Thanks for bringing this up to us 🙂

**Comment by ericyanLr** [comment]
Hey @LuismiBarcos ,

Thanks for reviewing and fixing the tests. I have forwarded the PR to the Search Team:
https://github.com/liferay-search/liferay-portal/pull/984

Feel free to close out this PR.

**Additional Note:** I re-ran `gw buildRest` and two additional test classes have been modified:
- modules/apps/headless/headless-site/headless-site-test/src/testIntegration/java/com/liferay/headless/site/resource/v1_0/test/BaseSiteResourceTestCase.java
- modules/apps/portal-search/portal-search-rest-test/src/testIntegration/java/com/liferay/portal/search/rest/resource/v1_0/test/BaseSearchResultResourceTestCase.java

**Comment by lipusz** [comment]
ci:close

**Pull request closed without merging**
