### PR TITLE
LPD-42770 fix test

### PR DESCRIPTION
**Pull request by movaldivia**
Fixed poshi test

https://liferay.atlassian.net/browse/LPD-42770

### CODE REVIEW

**Comment by movaldivia** [comment]
ci:test:relevant

**Comment by movaldivia** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:help

**Comment by ccorreagg** [comment]
ci:test:headless-functional

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
