### PR TITLE
LPD-35332 | Hide the relationship nested field in import

### PR DESCRIPTION
**Pull request by jaimelr10**
**Description**: In this PR we are removing objects relationship nested fields from import, as well as creating validations on the form to manage mandatory anyOf fields.

**Jira Ticket**: https://liferay.atlassian.net/browse/LPD-35332

### CODE REVIEW

**Comment by ccorreagg** [comment]
Rebase error @jaimelr10

**Comment by jaimelr10** [comment]
ci:test:sf

**Comment by jaimelr10** [comment]
ci:test:sf

**Comment by jaimelr10** [comment]
ci:test:relevant

**Comment by jaimelr10** [comment]
ci:test:headless-playwright

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:headless

**Comment by jaimelr10** [comment]
ci:test:headless

**Comment by jaimelr10** [comment]
ci:test:headless-playwright

**Comment by ccorreagg** [comment]
ci:forward

**Comment by jaimelr10** [comment]
ci:test:stable

**Comment by jaimelr10** [comment]
ci:test:relevant

**Comment by jaimelr10** [comment]
ci:stop

**Comment by jaimelr10** [comment]
ci:test:stable

**Review by ccorreagg — APPROVED** [review]
Approved, even though I would prefer a second opinion from the front-part, but according to the TL, let's send to BC

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
