### PR TITLE
Lps 201618 | Add functional tests for export object definition and update exportFile in ImportExport.macro

### PR DESCRIPTION
**Pull request by yanan**
Background
- Add FP4 and FP5 tests for export object definitions
- Rename and update exportFile in ImportExport.macro

Jira Ticket:
- https://liferay.atlassian.net/browse/LPS-197388

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional

**Comment by yanan** [comment]
ci:test:headless-functional

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
Failure is not related
- [PublishAPIApplication#CanGetPublishedStatusInResponse](https://testray.liferay.com/home/-/testray/case_results/2460179315?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2460178620%26testrayRunId%3D2460178644%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) mark the failed test as Flaky since API Builder object is not fully loaded and it is not reproduced locally, will pay attention to it so we can update/fix it if it happens again

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
All good, @yanan , thank you!

**Review by Hijky — APPROVED** [review]

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
