### PR TITLE
Lps 163170 | Add functional tests

### PR DESCRIPTION
**Pull request by yanan**
Background:
- Add test to get blog postings with oauth2 access token using curl and graphql

Jira Ticket
- https://liferay.atlassian.net/browse/LPS-163170

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Review by magjed4289 — APPROVED** [review]
Looks awesome, thanks!

**Review by Hijky — APPROVED** [review]

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
