### PR TITLE
LPS-203043 API Builder cleanup

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPS-203042.

Some small refactor I found while doing something else.

### CODE REVIEW

**Review by ccorreagg — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
