### PR TITLE
LPD-33577 Jobs are not rescheduled in the cluster, when the master node is stopped and a new master is selected

### PR DESCRIPTION
**Pull request by vendeltoreki**
[LPD-33577](https://liferay.atlassian.net/browse/LPD-33577)

Jobs are automatically removed from the scheduler whenever a cluster master token is either acquired or released, so only adding them is required.

Release can happen in a scenario where a connection is lost and restored between cluster nodes: connection loss results in multiple nodes taking the master role and when it's restored, one of the masters has to release its token. In this case, only ALL_NODES jobs will be added on that specific node.

### CODE REVIEW

**Comment by ccorreagg** [comment]
Rebased with master and included two more commits

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Hey @vendeltoreki ,

Do you have any idea of how could I test the invocation to the `doMasterTokenReleased` method?. I have tried by stopping the master's instance but the deactivate method is invoked

**Comment by ccorreagg** [comment]
BTW, great job! I have included a couple of commits to sort and inline some invocations to save some lines of code

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
> Hey @vendeltoreki ,
> 
> Do you have any idea of how could I test the invocation to the `doMasterTokenReleased` method?. I have tried by stopping the master's instance but the deactivate method is invoked

Hey @ccorreagg ,

I used `iptables` to break the connection between the nodes, so both of them became masters. Then re-enabling them would force one of the nodes to release its mater token.

```
iptables -A INPUT -p udp --dport 52807 -j DROP
iptables -A INPUT -p udp --dport 40853 -j DROP
iptables -A INPUT -p udp --dport 33327 -j DROP
iptables -A INPUT -p udp --dport 43898 -j DROP
iptables -A INPUT -p udp --dport 23301 -j DROP
```
To restore the connection:

```
iptables -D INPUT -p udp --dport 52807 -j DROP
iptables -D INPUT -p udp --dport 40853 -j DROP
iptables -D INPUT -p udp --dport 33327 -j DROP
iptables -D INPUT -p udp --dport 43898 -j DROP
iptables -D INPUT -p udp --dport 23301 -j DROP
```

These are the ports that each node displayed in their logs: 
```
-------------------------------------------------------------------
GMS: address=liferay-s5y8i5k5-24143, cluster=liferay-channel-transport-0, physical address=192.168.123.123:43898
-------------------------------------------------------------------
```
 and `23301` was the multicast port (search for mcast_port in the logs).

**Comment by ccorreagg** [comment]
ci:forward

**Review by ccorreagg — APPROVED** [review]

**Pull request closed without merging**
