### PR TITLE
LPD-28044   Remove FF for this epic

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-28129

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:report

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by ccorreagg — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:report:13643520

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:forward

**Comment by magjed4289** [comment]
ci:forward

**Comment by magjed4289** [comment]
ci:report:14508072

**Comment by magjed4289** [comment]
ci:report:14849714

**Comment by magjed4289** [comment]
ci:forward:force

**Pull request closed without merging**
