### PR TITLE
LPS-174410 Add test to load open api profile for all APIs in the system

### PR DESCRIPTION
**Pull request by yanan**
**Background**
Add test to make sure the new openapi load without errors

**Test Plan**
When navigate to /o/openapi/openapi.json endpoint
Then global rest api loaded without errors

**JIRA Link:**
https://issues.liferay.com/browse/LPS-174410

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
Tests failures are unrelated.

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Review by Hijky — APPROVED** [review]

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:test:headless-functional:nocompile

**Comment by magjed4289** [comment]
ci:stop

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
