### PR TITLE
LPD-29154 test-fix for web content related cases

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-29154

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:headless-functional:nocompile

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:headless-functional:nocompile

**Comment by magjed4289** [comment]
ci:test:headless-functional:nocompile

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:headless-functional:nocompile

**Comment by magjed4289** [comment]
change is being reverted for now https://github.com/liferay/liferay-portal/commit/2696ccd6fdec2a57e3a88049e05aa7dc9a59a89d

**Comment by ccorreagg** [comment]
The story has been discarted. Closing PR

**Pull request closed without merging**
