### PR TITLE
LPD-30180 Mitigate flakiness in SitetemplatesUsecase#SiteTemplatePageLinkInWebContentRedirectCorrectly

### PR DESCRIPTION
**Pull request by movaldivia**
https://liferay.atlassian.net/browse/LPD-30180

The link button doesn't load completely when the page loads, so a wait for visible was added.

### CODE REVIEW

**Comment by movaldivia** [comment]
ci:test:functionals

**Comment by movaldivia** [comment]
ci:help

**Comment by movaldivia** [comment]
ci:test:headless-functional

**Comment by movaldivia** [comment]
ci:test:sf

**Comment by movaldivia** [comment]
ci:test:functionals

**Comment by movaldivia** [comment]
ci:test:headless-functional

**Comment by movaldivia** [comment]
ci:test:headless-functional

**Comment by movaldivia** [comment]
ci:test:headless-functional

**Comment by movaldivia** [comment]
ci:test:headless-functional

**Comment by ccorreagg** [comment]
@movaldivia The commit message must contain the LPD of the subtask (if any). So, for the jira task and stories, we need to include the LPD of the subtask. For bugs, as we don't need the subtask, it is the LPD of the bug.

**Comment by ccorreagg** [comment]
I have created this branch in your repo https://github.com/movaldivia/liferay-portal/tree/LPD-33140 renaming the commits to use the subtask LPD. Please create a PR from that branch with the same information. I have created [this commit](https://github.com/liferay/liferay-portal/commit/15cb4747631bd301ea5372740c77dcbabbef4fe1) to define the variable just before being used

**Comment by ccorreagg** [comment]
see https://github.com/liferay-headless/liferay-portal/pull/2276

**Pull request closed without merging**
