### PR TITLE
LPS-173137 Add two unhappy paths in testPatchTaxonomyCategory

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Add two unhappy paths in `testPatchTaxonomyCategory`. Try to patch a `Taxonomy Category` with a nonexistent parent `Taxonomy Vocabulary` and try to patch a `Taxonomy Category` nonexistent parent `Taxonomy Category`

**JIRA Related Ticket**
https://issues.liferay.com/browse/LPS-176425

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
As discussed, add a case for categories with different vocabularies.

**Comment by sergiojimcos** [comment]
ci:forward

**Pull request closed without merging**
