### PR TITLE
LRQA-80341 Test fix for filter custom objects multiple levels relationships

### PR DESCRIPTION
**Pull request by yanan**
Background
- Test fix for filter custom object through multiple levels relationship

Jira Ticket:
- https://issues.liferay.com/browse/LRQA-80341

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Review by Hijky — APPROVED** [review]

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Review by Hijky — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
