### PR TITLE
LPS-198554 Add integration tests

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-198554

---

NOTE: This PR is on top of https://github.com/brianchandotcom/liferay-portal/pull/142009, so please, make sure you don't review those commits.

---

The purpose of this PR is to include:

- Integration test for GraphQL mutation
- Integration test for testing Map complex type within a GraphQL mutation
- Simplify the GraphQL integration tests by removing unused methods in the Base class.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by yanan** [comment]
Failures are not related, ok to forward :partying_face:

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
