### PR TITLE
LPD-17027 Unsafe suppliers on optional fields (Objects)

### PR DESCRIPTION
**Pull request by 4lejandrito**
**Purpose of this PR**
The main objective of this PR is improve the Objects APIs performance by using a new "lazyProperties" mechanism. This is done by adding unsafe suppliers to the properties map so that they are only calculated whenever its needed.

**What's changed?:**
- Now, through Rest-Builder, every Json Map property can accept also UnsafeSuppliers so that the real data is only processed whenever it's needed.
- The ObjectsDTOConverter has been adapted to build the Object Entries DTOs so that this lazy mechanism gets implemented.
- The objects nested fields infrastructure has been changed to take into account the new lazy mechanism.
- Batch Engine is adapted for this new mechanism.

**What's new?:**
- A new serializer for Unsafe Suppliers has been created.
- New tests for checking that the unsafe suppliers are not invoked when they're not needed.

See the following **Jira Ticket**: [LPD-17027](https://liferay.atlassian.net/browse/LPD-17027)

Resent on top of https://github.com/albertojml/liferay-portal/pull/3

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@albertojml please review all the changes from Brian and myself. Test that everything works fine too.

**Comment by albertojml** [comment]
ci:test:sf

**Comment by albertojml** [comment]
ci:test:relevant

**Comment by albertojml** [comment]
ci:test:sf

**Comment by albertojml** [comment]
ci:test:relevant

**Comment by albertojml** [comment]
ci:test:sf

**Comment by albertojml** [comment]
ci:test:relevant

**Comment by albertojml** [comment]
ci:test:sf

**Comment by albertojml** [comment]
ci:test:relevant

**Comment by albertojml** [comment]
ci:test:relevant

**Comment by albertojml** [comment]
ci:test:sf

**Comment by albertojml** [comment]
ci:test:relevant

**Comment by albertojml** [comment]
ci:test:sf

**Comment by albertojml** [comment]
ci:test:relevant

**Comment by albertojml** [comment]
ci:stop

**Comment by albertojml** [comment]
ci:test:sf

**Comment by albertojml** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by albertojml** [comment]
ci:test:sf

**Comment by albertojml** [comment]
ci:test:relevant

**Comment by albertojml** [comment]
ci:test:sf

**Comment by albertojml** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
@ccorreagg please review the last 2 commits. They fix the issue of having `"field": null` in the output JSON when the unsafe supplier returns null.

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:headless

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
@ccorreagg good to go from my side.

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
