### PR TITLE
LPS-189951 Test fix for NestedFieldsContainerRequestFilterTest.testFilter()

### PR DESCRIPTION
**Pull request by yanan**
Background:
- According to [e0d8e617f47fe01b7d66fe84e872a64f8628630dc](https://github.com/liferay/liferay-portal/commit/e0d8e617f47fe01b7d66fe84e872a64f8628630d), the context is not null after created, update to assertNotNull to make the test pass
> The context must be created even if there are no initial field names to
> allow adding new ones when needed.

Jira Ticket:
- https://liferay.atlassian.net/browse/LPS-189951

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]
Thanks @yanan!

**Comment by yanan** [comment]
Test have been passed in this pr and no related failures.

**Comment by yanan** [comment]
ci:forward:force

**Comment by yanan** [comment]
ci:forward:force

**Pull request closed without merging**
