### PR TITLE
LPD-23105 Fix test

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPD-23105

---

The purpose of this ticket is to fix the integration test `DispatchTriggerLocalServiceTest.testUpdateDispatchTrigger`.

As we are generating randomly some data, such as the `DispatchTaskClusterMode` and the `DispatchTaskExecutor`, there is a case with a wrong expected value. In this PR we have updated the expected value just in a possible case based on the randomly combination of both random values.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
Why don't you add the reason in the description to the commit message? that was it will be easier to understand in the future.

**Comment by ccorreagg** [comment]
> Why don't you add the reason in the description to the commit message? that was it will be easier to understand in the future.

Is it not enough with the current description? :

`LPD-23105 Update expected DispatchTaskClusterMode value. When the Dispatch Trigger is updated with Cluster Mode ALL_NODES and the dispatch executor is single cluster mode, the expected mode should be single node memory clustered`

**Comment by 4lejandrito** [comment]
I swear I read "Fix tests" in the commit message. Never mind...

**Review by 4lejandrito — APPROVED** [review]

**Pull request closed without merging**
