### PR TITLE
Lps 201151 Update language key and related integration tests

### PR DESCRIPTION
**Pull request by yanan**
Background
- Test fix because of [LPS-196997](https://liferay.atlassian.net/browse/LPS-196997)
- Typo in language key `the-x-can-only-be-associated-to-api-endpoints-with-a-retrieve-type-of-collection`
- Update `APISortRelevantObjectEntryModelListenerTest.testPostSort` and `APIFilterRelevantObjectEntryModelListenerTest.testPostFilter`

Jira Ticket
- https://liferay.atlassian.net/browse/LPS-201151

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-builder

**Review by magjed4289 — APPROVED** [review]

**Comment by yanan** [comment]
Failures are not related, the updated tests are Passed on CI

**Comment by yanan** [comment]
ci:forward

**Comment by yanan** [comment]
ci:test:stable

**Comment by yanan** [comment]
ci:forward:force

**Pull request closed without merging**
