### PR TITLE
LPS-199304 | Add new GET EndPoint that retrieve a single entry by ID to the UI

### PR DESCRIPTION
**Pull request by sergiojimcos**
**Note**
@jaimelr10 I've opened this PR from https://github.com/liferay-headless/liferay-portal/pull/1662, just to resolve conflicts and send it

**Description:** This PR adds the capability of creating a GET endpoint that retrieves a single element given a path parameter configurable by the UI.
Also, it extracts logic of Filters and Sorts to a component.

**How to test it:**
1. Add API Builder Feature Flags
```
#API BUILDER FEATURE FLAGS
feature.flag.LPS-186757=true
feature.flag.LPS-178642=true
feature.flag.LPS-184413=true
feature.flag.LPS-167253=true
```
2. Create an object
     2.1. Go to Application Menu
     2.2. Create new object called Student (Plural name: students)
     2.3. Go to the newly created object > Fields
     2.4. Create a new field called "carnet" of type text and check "Accept Unique Values Only"
     2.5. Create other field called "Backpack type" of type text
3. Go to Application Menu > API Builder
4. Add New API Application called "Test API"
5. Go to Schemas > Add New Schema > Name: "StudentSchema" Object: "Student" > Create
6. Go to Endpoints > Add API Endpoint > Retrieve Type: "Single Element" > Fill the other fields with mock data
7. Check that the endpoint is created
8. Response Body Schema > "StudentSchema"
     8.1. Check that path parameter property only shows External Reference Code, ID, and Carnet (the "Accept Unique Values Only" field)  > Select one of the three. If here the propertu Carnet is not shown, it may be necesary to reindex elastisearch (Application Menu > Control Panel > Configuration > Search > Index Actions > All Search Indexes > Reindex) 
9. Check that the endpoint can be updated 

**Screenshots:**
image
image
image

**Jira Ticket:** https://liferay.atlassian.net/browse/LPS-199304

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by jaimelr10** [comment]
ci:forward

**Comment by jaimelr10** [comment]
ci:forward

**Comment by jaimelr10** [comment]
ci:forward

**Pull request closed without merging**
