### PR TITLE
LPS-176508 Improve types on headless client getActions method

### PR DESCRIPTION
**Pull request by 4lejandrito**
- LPS-176508 Specifying actions type
- LPS-176508 buildREST

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Review by ccorreagg — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by Hijky** [comment]
The failures are not related to your PR, you can forward it manually.

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130987

**Comment by 4lejandrito** [comment]
ci:stop

**Pull request closed without merging**
