### PR TITLE
LPD-41479 fix flakiness in com.liferay.object.rest.internal.resource.v1_0.test.OpenAPIResourceTest

### PR DESCRIPTION
**Pull request by movaldivia**
https://liferay.atlassian.net/browse/LPD-41479

The test failed (_testGetOpenAPIWithSystemObjectRelationship_) because, as you can see in the picture, there were two system object definitions called 'User'.

object-definition

The second 'User' was created in the previous test, `testGetOpenAPIInDifferentCompany`. To remove this second object definition, I added a final step of removing the company created in that test.

**WARNING**: This wouldn't have happened if the system definition had been fetched by ID here

`		_userSystemObjectDefinition =
			_objectDefinitionLocalService.fetchSystemObjectDefinition(
				userSystemObjectDefinitionManager.getName());`

But I couldn't find a method to do that. This method smells dangerous, and we should implement the fetch by ID or add the company name. What do you think @ccorreagg 

CC: We were talking about this @dannielraposo, @albertojml

### CODE REVIEW

**Comment by movaldivia** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Hey @movaldivia ,

I think we should update that method to include the companyId. I checked and it seems we are only using that method from the tests. Could you double check? Don't be scared of updating the method, it does not make sense to search by the name if it  is possible to have more than one object definition by name (in different companies)

**Comment by movaldivia** [comment]
ci:test:sf

**Comment by movaldivia** [comment]
ci:test:relevant

**Pull request closed without merging**
