### PR TITLE
LPS-194745 Uncomment test

### PR DESCRIPTION
**Pull request by ccorreagg**
Related issue: https://liferay.atlassian.net/browse/LPS-194745

The purpose of this PR is to uncomment the existing test that was commented as I opened a [bug](https://liferay.atlassian.net/browse/LPS-191929). As [the bug](https://liferay.atlassian.net/browse/LPS-191929) has been fixed, the test might be uncommented.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) 👏 👏 👏 
It's really impressive how you removed the comments :trollface:

**Comment by ccorreagg** [comment]
> LGTM :) 👏 👏 👏 It's really impressive how you removed the comments :trollface:

Thanks @LuismiBarcos , I needed your approval, I was not sure about the right solution to the problem

**Comment by ccorreagg** [comment]
Forwarded manually. See https://github.com/brianchandotcom/liferay-portal/pull/139942

**Pull request closed without merging**
