### PR TITLE
LPS-170272 We cannot throw exceptions here

### PR DESCRIPTION
**Pull request by 4lejandrito**
Fixes blocker https://issues.liferay.com/browse/LPS-170272.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:forward

**Comment by igorbeslic** [comment]
@4lejandrito / @magjed4289  I updated CONFLUENCE to match new impl https://liferay.atlassian.net/wiki/spaces/COMMERCE/pages/1736409287/Batch+Engine

**Pull request closed without merging**
