### PR TITLE
LPS-189717: Validation API Schema can not have the same name in the API Application

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Implement two validations:

1. Validate if the `API Application` is valid.
2. Validate that a new `API Schema` can not have the same name in the same `API Application`

- BuildLanguage
- Add test cases for validate these two cases

**How to deploy it?**
- Deploy `headless-builder-api` and `headless-builder-impl`

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPS-189717

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Rebased on top of https://github.com/brianchandotcom/liferay-portal/pull/137461 and https://github.com/brianchandotcom/liferay-portal/pull/137486. Will forward when those are merged.

**Review by 4lejandrito — APPROVED** [review]
See last commit.

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
