### PR TITLE
LPD-39562 Use LinkedHashMap for the Object's properties in the REST DTO to keep the original order

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPD-39562

I have updated the functional tests to perform the whole creation of the API Application within the same request. But for that, we need to add the schema before the endpoint

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:object

**Comment by ccorreagg** [comment]
ci:test:headless

**Comment by ccorreagg** [comment]
In the ci:test:object suite, the comparison with the latest execution of its suite shows 2 errors, but none of them are uniques https://testray.liferay.com/#/compare-runs/44429969/44047732/details?filter=%7B%22testrayCaseResultStatus1%22%3A%5B%22FAILED%22%5D%2C%22testrayCaseResultStatus2%22%3A%5B%22PASSED%22%5D%7D&filterSchema=compareRunsCases

**Comment by ccorreagg** [comment]
With ci:test:headless 8 failures are in the CI execution compared to the latest ci:test:headless. https://testray.liferay.com/#/compare-runs/44449697/44280716/teams

Same with the previous case, none of them seem unique

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:help

**Comment by ccorreagg** [comment]
ci:test:api-builder

**Comment by ccorreagg** [comment]
The error https://testray.liferay.com/#/project/35392/cases/40289630 could be related. Relaunching to double-check before analyzing again

**Comment by ccorreagg** [comment]
ci:test:api-builder

**Comment by ccorreagg** [comment]
ci:test:api-builder

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/155522

**Pull request closed without merging**
