### PR TITLE
LPS-201866 | Test fix for clicking the download button more stable

### PR DESCRIPTION
**Pull request by Hijky**
**Background**
Update a macro to click the download button more stable

**Jira Ticket:**
https://liferay.atlassian.net/browse/LPS-201866

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:headless-functional:nocompile

**Review by yanan — APPROVED** [review]

**Comment by Hijky** [comment]
ci:test:headless-functional

**Comment by Hijky** [comment]
The failure is about the inability to find the dependency file flaky error and is not related to the PR

**Comment by Hijky** [comment]
ci:forward

**Pull request closed without merging**
