### PR TITLE
Lrqa 82613 | Update filter endpoint and schema tests

### PR DESCRIPTION
**Pull request by yanan**
Unignore tests and Update to correct date format to run headless builder filter UI related test

-  https://liferay.atlassian.net/browse/LRQA-82613

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
Failures are not related, and linked test fix ticket on Testray.

**Review by Hijky — APPROVED** [review]

**Pull request closed without merging**
