### PR TITLE
LPS-174611 Add createBatch action in getListTypeDefinitionListTypeEntriesPage method

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Add `createBatch` action in `getListTypeDefinitionListTypeEntriesPage` method from `headless-admin-list-type`

image

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-174611

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by yanan** [comment]
Tests failures are unrelated, ok to forward manually.

**Comment by sergiojimcos** [comment]
Manual forwarding to Brian: https://github.com/brianchandotcom/liferay-portal/pull/130072

**Pull request closed without merging**
