### PR TITLE
LRQA-82817 Update to pauseClickAt to publish api application

### PR DESCRIPTION
**Pull request by yanan**
- https://liferay.atlassian.net/browse/LRQA-82817
- update to make PublishAPIApplication.testcase more stable

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Review by Hijky — APPROVED** [review]

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
All tests are not start to run because of compile error. And this is a samll testfix which run ok locally, I'll forward this one.

**Comment by yanan** [comment]
ci:forward

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
