### PR TITLE
LPD-17716 Investigate warning code="404"

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-17716

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:stable

**Review by 4lejandrito — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward:force

**Pull request closed without merging**
