### PR TITLE
LRQA-77262 | Update case to run correctly

### PR DESCRIPTION
**Pull request by Hijky**
**Background**
Update case to run correctly

**Test Plan**
Add a parameter value in the test case.

**JIRA Link:**
https://issues.liferay.com/browse/LRQA-77262

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:headless-frontend-functional:nocompile

**Comment by Hijky** [comment]
@magjed4289 @yanan It seems the failed not related to my PR.

**Review by magjed4289 — APPROVED** [review]
Looks good! 👍🏻

**Comment by Hijky** [comment]
ci:forward

**Pull request closed without merging**
