### PR TITLE
LPD-30463 | Can't sort by object nestedField of type boolean when using Oracle

### PR DESCRIPTION
**Pull request by ccorreagg**
From: https://github.com/brianchandotcom/liferay-portal/pull/156371

---

**What's changed?**

The method `getValuesList` has been replaced with `getPrimaryKeys` to improve query construction when sorting is applied. Previously, dslQuery grouped by all fields in the object, causing SQL errors in Oracle when any field was of type CLOB, even if that field was not part of the sorting criteria. Since Oracle does not support grouping by CLOB fields, the updated approach **retrieves only the primary key** (PK) column in the initial query. A subsequent query is then executed to retrieve the remaining fields.

This two-step approach does not reduce efficiency, as the second query was already present, meaning it was unnecessary to retrieve all fields in the initial query when only the PK was ultimately used.

See the following Jira Ticket: [LPD-30463](https://liferay.atlassian.net/browse/LPD-30463)

cc/ @dannielraposo 

TODO: https://github.com/brianchandotcom/liferay-portal/pull/156371#issuecomment-2493705284 keep the initial method

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:headless

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:headless

**Comment by ccorreagg** [comment]
ci:test:objects

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:test:help

**Comment by dannielraposo** [comment]
ci:test:stop

**Comment by dannielraposo** [comment]
ci:stop

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:test:relevant

**Comment by dannielraposo** [comment]
ci:forward:force

**Pull request closed without merging**
