### PR TITLE
LPS-111236 Adapt ResourceNotFound tests

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by javierdearcos** [comment]
@nhpatt

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
I guess he will try to change 
```
JSONObject extensionsJSONObject = errorJSONObject.getJSONObject("extensions");

					Assert.assertEquals("Not Found", extensionsJSONObject.getString("code"));
```
but let's hope

**Comment by javierdearcos** [comment]
> extensionsJSONObject

Which name do you think is more correct? I'd prefer to change it and pass the review at once

**Comment by javierdearcos** [comment]
Also not sure if with the new mechanism it is possible to chain paths with JSONUtil getting the first element of a JSONArray. I checked and I think it has no infrastructure to this kind of operations.

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
Yeah, I meant the extensions/code part

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
As I was extending JSONUtil to support getting an item in an array I found out that the option already existed.

Refactored to use this option.

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
ci:stop

**Pull request closed without merging**
