### PR TITLE
LPS-190849 Use the proper file extension for advanced batch engine tasks

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPS-190849

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
`com.liferay.batch.engine.internal.test.BatchEngineBundleTrackerTest` is expected to fail in this PR and will no longer fail when https://github.com/brianchandotcom/liferay-portal/pull/137997 is merged (which will be merged first).

**Review by matijapetanjek — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
