### PR TITLE
LPS-127775 allow new lines in descriptions

### PR DESCRIPTION
**Pull request by nhpatt**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
@javierdearcos @LuismiBarcos 

I've added it for descriptions but it's probable that it makes sense everywhere.

**Comment by javierdearcos** [comment]
Nice to know that FreeMarker has a built-in function for this case

**Comment by javierdearcos** [comment]
Forwarding again as it completely seems like a CI problem

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
