### PR TITLE
LPS-163446: Inconsistency between the REST APIs and the UI using permissions 

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Add new method `getResourcePermissionsByResourceName` that retrieves all Permissions give a `resourceName`, `roleName` and `EntityId`
- Changes in `base_resource_impl.ftl` adding new method `getResourcePermissionsByResourceName` and update `toPermissionPage`
- `buildREST` in `modules/apps` and `modules/dxp/apps` to update all BaseResourceImpls
- This new changes comes from: https://github.com/brianchandotcom/liferay-portal/pull/125266

**Note:** This PR also fix another inconsistency, when we retrieved all the Permissions given a `roleName`, it returned all Permissions of all the entities created.

**JIRA Tickets**
https://issues.liferay.com/browse/LPS-163446
https://issues.liferay.com/browse/LPS-162878

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by sergiojimcos** [comment]
I've made some changes in the `base_resource_impl.ftl` because, there was a conflict between the Role internal model with `dto.Role`

**Comment by Hijky** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:reevaluate:1397401_1503

**Comment by Hijky** [comment]
@sergiojimcos I checked the failed, and I think the failures are not related to your PR, this is the compare [results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2041279452&testrayRunIdA=2040291510&statusB=2), you can forward it manually.

**Comment by sergiojimcos** [comment]
Manual forwarding to Brian: https://github.com/brianchandotcom/liferay-portal/pull/125976

**Pull request closed without merging**
