### PR TITLE
LPS-127858 portal-tools-rest-builder Deserialise BigDecimals

### PR DESCRIPTION
**Pull request by riccardo-ferrari**

### CODE REVIEW

**Comment by riccardo-ferrari** [comment]
ci:test:sf

**Comment by riccardo-ferrari** [comment]
cc: @javierdearcos

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
Thanks! Hopefully tests are fixed here: https://github.com/liferay-headless/liferay-portal/pull/576

**Pull request closed without merging**
