### PR TITLE
LPS-181149 Fix feature flag annotation

### PR DESCRIPTION
**Pull request by 4lejandrito**
From https://github.com/liferay-headless/liferay-portal/pull/1160.

## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-181149)

Dear Team, this PR fixes an issue introduced in https://issues.liferay.com/browse/LPS-179576. If we use PropsTestUtil, we are overriding the complete properties map, so the idea is to use PropsUtil like we traditionally do for feature flags.

Also, we leave the feature flags in the state before the tests are executed. The steps would be:

- Store the value that the FF has before the test
- Store the value that the FF has before the method (it will take the class value if set)
- Restore the value after the method (leaving it as the class value in any case if set)
- Restore the value after the class

## Test Scenario

* Run fragment-test suite twice, and no errors in "company not found" will be shown when creating an omni admin user

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
SF Not related.

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by jkappler** [comment]
Thanks a lot @4lejandrito ❤️

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
