### PR TITLE
LPS-172590 Generate default methods when it is not clear the parameter belongs to the current entity schema

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to modify REST Builder for the following case:

When in the path, there is a path parameter which name matches with a parameter of the entity schema but it is not clear that the parameter must belong to the entity schema, then a Getter method is auto-generated and invoked from the test with a default implementation returning the parameter of the entity schema.

---

**When the getter method is NOT being autogenerated and the parameter of the entity schema is being directy used as before?**

Given a parameter, for example `externalReferenceCode`

1. When the substring of the path after the parameter that is being analyzed is empty.

    For example, for a schema called `MySchema`: `/random-path/{externalReferenceCode}` 

2. When there is an evidence that the substring before the path is related to the entity schema

    For example, for a schema called `MySchema`:

  -  `/my-schemas/{externalReferenceCode}/[...]` 
  -  `/mySchemas/{externalReferenceCode}/[...]` 
 
---

**NOTE:** The default implementation will not cause a breaking change as it is executing the same code than before, and it is a decission of the API developer to override the getter method with the desired behaviour

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by matijapetanjek — APPROVED** [review]
This was educational review for me :D

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Failures could be related? @magjed4289 can you check?

**Comment by magjed4289** [comment]
The following failures look unique:

1. [LocalFile.ExposeErcFromAssetLibraryForStructuredContentFolders#StructuredContentFolderIsCreatedInAssetLibraryWithErcByDefault](https://testray.liferay.com/home/-/testray/case_results/2195090524?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1902759375%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1902759375%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc) - UNRELATED: run on the PR bundle locally with no failures

2. [com.liferay.headless.delivery.resource.v1_0.test.StructuredContentFolderResourceTest > testGetStructuredContentFolderStructuredContentFoldersPageWithFilterDateTimeEquals ](https://testray.liferay.com/home/-/testray/case_results/2195092215?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1518350312%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1518350312%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc)
@ccorreagg can you run this one on your branch and check whether it passes?

`   [exec] com.liferay.headless.delivery.resource.v1_0.test.StructuredContentFolderResourceTest > testGetStructuredContentFolderStructuredContentFoldersPageWithFilterDateTimeEquals STARTED
     [exec] 
     [exec] com.liferay.headless.delivery.resource.v1_0.test.StructuredContentFolderResourceTest > testGetStructuredContentFolderStructuredContentFoldersPageWithFilterDateTimeEquals FAILED
     [exec]     com.liferay.portal.kernel.exception.GroupKeyException
     [exec]     	at com.liferay.portal.service.impl.GroupLocalServiceImpl.validateGroupKey(GroupLocalServiceImpl.java:4931)
     [exec]     	at com.liferay.portal.service.impl.GroupLocalServiceImpl.addGroup(GroupLocalServiceImpl.java:435)
     [exec]     	at sun.reflect.GeneratedMethodAccessor1911.invoke(Unknown Source)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
     [exec]     	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
     [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec]     	at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:60)
     [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec]     	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
     [exec]     	at com.sun.proxy.$Proxy108.addGroup(Unknown Source)
     [exec]     	at com.liferay.depot.service.impl.DepotEntryLocalServiceImpl.addDepotEntry(DepotEntryLocalServiceImpl.java:116)
     [exec]     	at sun.reflect.GeneratedMethodAccessor1910.invoke(Unknown Source)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
     [exec]     	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
     [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec]     	at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:60)
     [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec]     	at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:79)
     [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec]     	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
     [exec]     	at com.sun.proxy.$Proxy758.addDepotEntry(Unknown Source)
     [exec]     	at com.liferay.depot.service.DepotEntryLocalServiceUtil.addDepotEntry(DepotEntryLocalServiceUtil.java:77)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseStructuredContentFolderResourceTestCase.setUp(BaseStructuredContentFolderResourceTestCase.java:121)
     [exec]     	at sun.reflect.GeneratedMethodAccessor2153.invoke(Unknown Source)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
     [exec]     	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     [exec]     	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec] `

**Comment by ccorreagg** [comment]
Hi

> The following failures look unique:
> 
> 1. [LocalFile.ExposeErcFromAssetLibraryForStructuredContentFolders#StructuredContentFolderIsCreatedInAssetLibraryWithErcByDefault](https://testray.liferay.com/home/-/testray/case_results/2195090524?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1902759375%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1902759375%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc) - UNRELATED: run on the PR bundle locally with no failures
> 2. [com.liferay.headless.delivery.resource.v1_0.test.StructuredContentFolderResourceTest > testGetStructuredContentFolderStructuredContentFoldersPageWithFilterDateTimeEquals ](https://testray.liferay.com/home/-/testray/case_results/2195092215?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F1518350312%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D1518350312%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc)
>    @ccorreagg can you run this one on your branch and check whether it passes?
> 
> ` [exec] com.liferay.headless.delivery.resource.v1_0.test.StructuredContentFolderResourceTest > testGetStructuredContentFolderStructuredContentFoldersPageWithFilterDateTimeEquals STARTED [exec] [exec] com.liferay.headless.delivery.resource.v1_0.test.StructuredContentFolderResourceTest > testGetStructuredContentFolderStructuredContentFoldersPageWithFilterDateTimeEquals FAILED [exec] com.liferay.portal.kernel.exception.GroupKeyException [exec] at com.liferay.portal.service.impl.GroupLocalServiceImpl.validateGroupKey(GroupLocalServiceImpl.java:4931) [exec] at com.liferay.portal.service.impl.GroupLocalServiceImpl.addGroup(GroupLocalServiceImpl.java:435) [exec] at sun.reflect.GeneratedMethodAccessor1911.invoke(Unknown Source) [exec] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [exec] at java.lang.reflect.Method.invoke(Method.java:498) [exec] at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) [exec] at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) [exec] at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) [exec] at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:60) [exec] at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) [exec] at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) [exec] at com.sun.proxy.$Proxy108.addGroup(Unknown Source) [exec] at com.liferay.depot.service.impl.DepotEntryLocalServiceImpl.addDepotEntry(DepotEntryLocalServiceImpl.java:116) [exec] at sun.reflect.GeneratedMethodAccessor1910.invoke(Unknown Source) [exec] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [exec] at java.lang.reflect.Method.invoke(Method.java:498) [exec] at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) [exec] at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) [exec] at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) [exec] at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:60) [exec] at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) [exec] at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:79) [exec] at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) [exec] at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) [exec] at com.sun.proxy.$Proxy758.addDepotEntry(Unknown Source) [exec] at com.liferay.depot.service.DepotEntryLocalServiceUtil.addDepotEntry(DepotEntryLocalServiceUtil.java:77) [exec] at com.liferay.headless.delivery.resource.v1_0.test.BaseStructuredContentFolderResourceTestCase.setUp(BaseStructuredContentFolderResourceTestCase.java:121) [exec] at sun.reflect.GeneratedMethodAccessor2153.invoke(Unknown Source) [exec] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [exec] at java.lang.reflect.Method.invoke(Method.java:498) [exec] at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) [exec] at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [exec] at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) [exec] at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33) [exec] at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24) [exec] at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99) [exec] at org.junit.rules.RunRules.evaluate(RunRules.java:20) [exec] at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237) [exec] at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59) [exec] at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59) [exec] at org.junit.rules.RunRules.evaluate(RunRules.java:20) [exec] at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316) [exec] at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95) [exec] at java.lang.Thread.run(Thread.java:745) [exec]`

Hi @magjed4289 ,

Thanks for your review!

I ran that test locally and it passed:

```
com.liferay.headless.delivery.resource.v1_0.test.StructuredContentFolderResourceTest STANDARD_OUT
    Loading jar:file:/home/carloscorrea/Liferay/Proyecto/bundles/tomcat-9.0.71/webapps/ROOT/WEB-INF/shielded-container-lib/portal-impl.jar!/system.properties

com.liferay.headless.delivery.resource.v1_0.test.StructuredContentFolderResourceTest > testGetStructuredContentFolderStructuredContentFoldersPageWithFilterDateTimeEquals STARTED

com.liferay.headless.delivery.resource.v1_0.test.StructuredContentFolderResourceTest > testGetStructuredContentFolderStructuredContentFoldersPageWithFilterDateTimeEquals PASSED

> Task :apps:headless:headless-delivery:headless-delivery-test:stopTestableTomcat


BUILD SUCCESSFUL in 52s
267 actionable tasks: 136 executed, 1 from cache, 130 up-to-date

```

**Comment by magjed4289** [comment]
OK, in that cases it's safe to be manually forwarded :) ✅

**Comment by ccorreagg** [comment]
> OK, in that cases it's safe to be manually forwarded :) white_check_mark

Perfect! Thank you! :heart:

**Pull request closed without merging**
