### PR TITLE
LRQA-80580 Test fix for ImportExport since AccountGroups has been removed

### PR DESCRIPTION
**Pull request by yanan**
Background
- Test fix for ImportExport#GetExportFileAvailableEntityTypes and ImportExport#GetImportFileAvailableEntityTypes

Test Plan
- Remove AccountGroup from available Entity Type list in Import/Export

Jira Ticket
- https://issues.liferay.com/browse/LRQA-80580

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Review by Hijky — APPROVED** [review]

**Review by magjed4289 — APPROVED** [review]
I think we need to refactor and make a list of Strings from these elements in the future, changing whole text this many times must be annoying 😅

**Comment by yanan** [comment]
> I think we need to refactor and make a list of Strings from these elements in the future, changing whole text this many times must be annoying sweat_smile

Yeah, the list updated kind of frequently since it belongs to different teams :smile: , I'm not totally clear how to implement the list of String, but not changing this so frequently sounds really nice! Anyway, I'm going to forward this now :smiley:

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
