### PR TITLE
LPD-26257: Avoid NPE when try to import Object Definition without Object Fields

### PR DESCRIPTION
**Pull request by sergiojimcos**
## Motivation
The aim of this PR is to fix a functional test case case: ImportExport#CanImportObjectDefinitionWithDraftStatus that was caused by this df3d1033

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPD-26257

### CODE REVIEW

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
Please add an integration test.

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
Please indicate in the commit message that this fixes an existing test.

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward:force

**Pull request closed without merging**
