### PR TITLE
LPS-109844 Implementation to create structured contents drafts

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Applied changes requested [here](https://github.com/brianchandotcom/liferay-portal/pull/101309#issuecomment-831480830)

This is the second pull related to the changes mentioned above and contains the new endpoint to allow the creation of structured contents drafts with its implementation. 

It depends on [this PR](https://github.com/brianchandotcom/liferay-portal/pull/101375)

### CODE REVIEW

**Comment by nhpatt** [comment]
No need to review IMHO. Just ci:forward when the other passes or rebase if not.

**Comment by LuismiBarcos** [comment]
When you say "passes" means when Brian merges it?

**Comment by nhpatt** [comment]
Or not :trollface:

**Comment by LuismiBarcos** [comment]
😒

**Comment by LuismiBarcos** [comment]
Sent [here](https://github.com/liferay-headless/liferay-portal/pull/706)

**Pull request closed without merging**
