### PR TITLE
LPD-38638 Use the correct host in the request

### PR DESCRIPTION
**Pull request by vngoliveira**
[LPD-38541](https://liferay.atlassian.net/browse/LPD-38541)

### CODE REVIEW

**Comment by ccorreagg** [comment]
hey @vngoliveira 

I think that test belongs to the Object's team (BPM). What is the purpose of creating this PR in the Headless repo?

**Comment by carolmariaabb** [comment]
@ccorreagg it's related to this [thread](https://liferay.slack.com/archives/C03S91MJG6L/p1730295689213049?thread_ts=1729533607.118569&cid=C03S91MJG6L)

**Comment by vngoliveira** [comment]
Sorry @ccorreagg, I forgot to link the thread

**Comment by 4lejandrito** [comment]
Thanks @vngoliveira! See https://github.com/liferay-headless/liferay-portal/pull/2319.

**Pull request closed without merging**
