### PR TITLE
Lps 170027 Add functional tests on break relationship between system object and custom object

### PR DESCRIPTION
**Pull request by yanan**
**Background:**
- Add functional tests on break relationship between system object and custom object(Stroy )

**Test Plan**
- Given a foundation object
Given oneToMany relationship usersFoundations created
Given one foundation entry created
Given the userAccount entry created
Given I relate all the foundation entries with the userAccount entry through the userAccount PUT endpoint
When using the delete request deleteUserAccount{relationshipName}
Then I can see no one entry correctly related in GET request response with the relationshipName=usersFoundations
- Given a foundation object
Given oneToMany relationship usersFoundations created
Given two foundation entries created
Given one userAccount entry created
Given all foundation is related to userAccount through userAccounts PUT endpoint
When deleting one of the foundation entries with deleteUserAccount{relationshipName} request
Then I can see only one entry correctly related in GET request response
- Given a foundation object
Given manyToMany relationship usersFoundations created
Given one foundation entry created
Given one userAccount entry created
Given I relate the foundation entry with the userAccount entry through the userAccount PUT endpoint
When using the delete request deleteUserAccount{relationshipName}
Then I can see no one entry correctly related in GET request response with the relationshipName=usersFoundations

**JIRA Ticket:**
- https://issues.liferay.com/browse/LPS-169885

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
Tests failures are unrelated, all about ImportExport.testcase.

**Review by Hijky — APPROVED** [review]

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
Looks good! Thank you! ☺️

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
