### PR TITLE
LPS-184046 Handle object extended fields in Batch Engine Import tasks

### PR DESCRIPTION
**Pull request by ccorreagg**
Related issue: https://liferay.atlassian.net/browse/LPS-184046

---

This PR has been created to handle the extended fields of the System Objects. With the changes included in this pull request, it is possible to Import any Liferay entity considered System Object with its custom fields defined. For that, the following changes have been performed:

- New interface `ItemReaderPostAction` with an implementation in order to validate the extended properties included in each item that is going to be imported.
- New interface `ImportTaskPostAction` with an implementation in order to set the extended properties included in each item that is going to be imported.
- As it is necessary for setting the extended properties the persisted item (in order to access, for example, to the identifier), a new method has been created apart from the existing `VulcanBatchEngineTaskItemDelegate.setContextBatchUnsafeConsumer`. The new method `VulcanBatchEngineTaskItemDelegate.setContextBatchUnsafeBiConsumer` has been created to set the context that will be in charge of managing the Function that will return the persisted element, as it is necessary by Batch Engine. For that, new changes have been included in the REST Builder.
- Keeping both methods have been developed that way to maintain backwards compatibility

---

How to test it:

- Have a portal built from this branch rebased with the latest master
- Execute the test `BatchEngineImportTaskExecutorTest.testImportAccountJSONWithObjectExtendedFields` of the `batch-engine/batch-engine-test` module

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
> ###  ci:test:relevant - 0 out of 1 jobs passed in 30 minutes
> Click here for more details.
> ##### Test bundle downloads:
> * [liferay-portal-bundle-tomcat.tar.gz](https://files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/3830/liferay-portal-bundle-tomcat.tar.gz) (mirrors: [dlc](http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/3830/liferay-portal-bundle-tomcat.tar.gz), [lax](http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-40/jobs/test-portal-acceptance-pullrequest(master)/builds/3830/liferay-portal-bundle-tomcat.tar.gz))

The error is related, because some JAX-RS resources have been added into master, so latest REST Builder changes are not included in the current branch. I am rebasing with latest master

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by matijapetanjek — APPROVED** [review]
LGTM :partying_face:

**Comment by ccorreagg** [comment]
ci:reevaluate:1407401_3832

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
test failures are not related with the PR. OK to manually forward ✅

**Review by 4lejandrito — APPROVED** [review]
See my commits.

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:forward:force

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
Forwarded manually. See https://github.com/brianchandotcom/liferay-portal/pull/137373

**Pull request closed without merging**
