### PR TITLE
LPS-166641 Add tests to list available entities in the import/export center

### PR DESCRIPTION
**Pull request by yanan**
**Background:**

list of entities in the Import/Export center functionality contains the correct entities available for batch operations

**Test Plan:**
- Given navigate to import and export center
When new export file
Then I can see all available entity types to export
- Given navigate to import and export center
When new import file
Then I can see all available entity types to import

**Jira Ticket:**

https://issues.liferay.com/browse/LPS-166641

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
