### PR TITLE
LPS-174373 Process batch engine files found in DXP modules

### PR DESCRIPTION
**Pull request by matijapetanjek**
Hi @rotty3000 here is the rebased PR for processing batch files from OSGI bundles. 
I have just extracted the BatchEngineUnit processing logic from AutoDeployListener to a BatchEngineUnitProcessor class and updated tests accordingly.

Thank you very much for the work! 
/cc @igorbeslic

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by rotty3000** [comment]
:100:

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by rotty3000** [comment]
ci:reevaluate:1257401_6274

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:forward:force

**Pull request closed without merging**
