### PR TITLE
LPS-125794 Not assume path parameters order is the same as Java method signature

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by javierdearcos** [comment]
I'm concern about this change as it will affect every API and all versions... But I think it will make no harm as the changes are in the client implementation and will remain inside the client modules without affecting other modules

**Comment by javierdearcos** [comment]
Sometimes I've had problems with PMD in the generated code after a REST Builder change but I'm not sure how to check this locally... I've made a `gw build` in one of the affected modules (headless-delivery) and PMD fails but with a medium priority warning but is something that was already in the old generated code

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
It should be by running pmdMain but it doesn't work right now in my PC :(

**Review by nhpatt — APPROVED** [review]

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
