### PR TITLE
LPS-118970 Include Questions in the bundle for 7.3

### PR DESCRIPTION
**Pull request by LuismiBarcos**

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
According to the documentation:

- Liferay-Releng-Restart-Required: to set it to false is required a POSHI test ([More info in LPS-110344](https://issues.liferay.com/browse/LPS-110344)) and we don't have a POSHI test, right?
- Liferay-Releng-Fix-Delivery-Method: Questions is inside of the Collaboration Suite, marked in "Liferay-Releng-Suite". This force to set as "core" the field "Liferay-Releng-Fix-Delivery-Method". 

> If the app suite is specified, then Liferay-Releng-Portal-Required: true, Liferay-Releng-Marketplace: true, and Liferay-Releng-Bundle: true, Liferay-Releng-Fix-Delivery-Method: core

Anyway, "Liferay-Releng-Dix-Delivery-Method" has 2 values:
> core: fixed through FPs/SPs
empty: fixed through Marketplace releases
 
And I think we are interested in fix this app through FPs/SPs :)

My unique doubt is if Questions should be part of the Collaboration Suite or be a standalone app.

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
Collab :)

**Comment by nhpatt** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
Didn't know about de `build.gradle` Thanks!

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
