### PR TITLE
LPS-127869 Check data limit quotas at persistence level instead of local service level

### PR DESCRIPTION
**Pull request by javierdearcos**
Check the data limit quotas at BasePersistenceImpl class.

Remove the old code that check data limit quotas at LocalServiceImpl classes

Deprecate old properties at PropsValues and PropsKeys

Remove old properties from portal.properties file

cc @nhpatt

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:reevaluate:1077401_6747

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by javierdearcos** [comment]
Last try to forward it, and if not I will rebase and send it in a new pull

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
