### PR TITLE
LPS-168806 remove company id detector after last object update

### PR DESCRIPTION
**Pull request by igorbeslic**
This PR removes code that was added as a part of wrong initiative.
After changes introduced by:
https://issues.liferay.com/browse/LPS-167995
this code is not needed at all.

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by yanan** [comment]
Hello @igorbeslic , the test failures are unrelated, the pr can be forwarded manually from qa perspective. 

Here are more details for the [compare run results](https://testray.liferay.com/zh/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2143738562&testrayRunIdA=2145101474&statusB=3):

Passed locally using an ant all bundle with the current pr
- LocalFile.PortalSmoke#Smoke
- LocalFile.CreateObject#CannotAddObjectWithoutAddPermission 
- LocalFile.CreateObject#CannotUpdateObjectNameAfterPublished 

Test fix which already merged into master yesterday(LPS-171267):
-  LocalFile.ObjectRelationships#CanCreateObjectWithRelationshipParameter
- LocalFile.ObjectRelationships#CannotRelateAnEntryWithItself

**Comment by yanan** [comment]
Seem there is a conflict in the bnd file, please help resolve the conflicts before forward, thanks!

**Comment by igorbeslic** [comment]
ci:forward

**Comment by igorbeslic** [comment]
forwarded manually https://github.com/brianchandotcom/liferay-portal/pull/128174 thank you @yanan

**Pull request closed without merging**
