### PR TITLE
LPS-174482 Update the macro to the correct element

### PR DESCRIPTION
**Pull request by Hijky**
**Background**
[test-fix] Update ImportExport test cases with new element path

**Related PR** 
https://github.com/liferay-headless/liferay-portal/pull/995

**JIRA Link:**
https://issues.liferay.com/browse/LPS-174482

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:relevant

**Comment by Hijky** [comment]
ci:test:headless-functional

**Comment by Hijky** [comment]
@magjed4289, all of the failures are related to the updated element, no else related failures.

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:relevant

**Comment by Hijky** [comment]
ci:test:headless-functional

**Comment by Hijky** [comment]
ci:test:headless-functional

**Comment by Hijky** [comment]
ci:test:headless-functional

**Review by magjed4289 — APPROVED** [review]

**Comment by Hijky** [comment]
ci:forward

**Pull request closed without merging**
