### PR TITLE
LPS-146160 use correct field to check if template stageing is allowed

### PR DESCRIPTION
**Pull request by ZakiMiklos**
https://liferay.atlassian.net/browse/LPS-146160

### CODE REVIEW

**Comment by ZakiMiklos** [comment]
ci:test:sf

**Comment by ZakiMiklos** [comment]
ci:test:sf

**Comment by ZakiMiklos** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:staging

**Comment by vendeltoreki** [comment]
Forwarding on: https://github.com/liferay-headless/liferay-portal/pull/1806

**Pull request closed without merging**
