### PR TITLE
Lrqa 77282 | update integration tests

### PR DESCRIPTION
**Pull request by yanan**
Background:

- fix AssertionError by updating add method in testDeleteAssetLibraryStructuredContentByExternalReferenceCode 
- fix AssertionError by updating add method in testDeleteAssetLibraryDocumentByExternalReferenceCode

JIRA Ticket:

- https://issues.liferay.com/browse/LRQA-77281
- https://issues.liferay.com/browse/LRQA-77282

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
@sergiojimcos can you please check whether it is okay? To me it looks okay, but I don't feel comfortable with giving an OK to the integreation test myself 😅

**Review by sergiojimcos — APPROVED** [review]

**Comment by sergiojimcos** [comment]
Good job @yanan!! :clap::clap::clap::clap:

**Comment by yanan** [comment]
Thank you guys for the review, I will forward this one :smile:

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
