### PR TITLE
LPD-25480: Remove Feature Flags for Group III, Group IV and Group V

### PR DESCRIPTION
**Pull request by sergiojimcos**
**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPD-25480

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by vendeltoreki — APPROVED** [review]
I've tested the changes and the feature flag removal worked correctly

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
One test is related, fixing it

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward:force

**Comment by sergiojimcos** [comment]
ci:forward:force

**Pull request closed without merging**
