### PR TITLE
LPD-26392: Migrate aui:link taglib using a clay:button taglib

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Use `clay:button` taglib instead of `aui:link` which doesn't contain all the frontend states.
- Add new functional test to cover that `Change` button works as expect.

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPD-26392

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by jaimelr10** [comment]
ci:test:relevant

**Comment by jaimelr10** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by jaimelr10 — APPROVED** [review]
LGTM!

**Comment by jaimelr10** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
