### PR TITLE
LPS-107899 Expose permissions for all roles through APIS without having to send the roleNames param

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
looks awesome @javierdearcos 💯

**Comment by jkappler** [comment]
ci:forward

**Comment by javierdearcos** [comment]
Checking the problem. It is a problem of the PR. I know what it is happening but I'm not sure the best way to solve it

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
