### PR TITLE
LPS-204786 It is not possible to make entries in custom objects that have a relationship field

### PR DESCRIPTION
**Pull request by pedro-oliveira446**
[LPS-204786](https://liferay.atlassian.net/browse/LPS-204786)

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
Failures in relevant are not related from qa perspective
image

**Review by sergiojimcos — APPROVED** [review]
LGTM!!

**Comment by sergiojimcos** [comment]
ci:forward:force

**Pull request closed without merging**
