### PR TITLE
 LPS-113978 Allow generation of methods correspondent to GET operation…

### PR DESCRIPTION
**Pull request by javierdearcos**
… with return types different from Schema type, Response or String in REST Builder

### CODE REVIEW

**Comment by javierdearcos** [comment]
cc/ @inacionery

We made a fix to allow returning different types depending on the OpenAPI specification that causes a breaking change in Workflow API. Changes are in a separate commit.

Please check if you agree with this change. Other option would be to change OpenAPI specification to keep returning a String.

Thank you

**Comment by nhpatt** [comment]
@javierdearcos can you test GraphQL? there were some issues returning booleans or other different things

**Comment by inacionery** [comment]
Hi @javierdearcos,

That's fine, let me run the workflow tests to make sure everything is working.

Thanks!

**Comment by inacionery** [comment]
ci:test:workflow

**Comment by inacionery** [comment]
Hey @rodrigocunhaa,

Could you please check the CI results?

Thanks!

**Comment by rodrigocunhaa** [comment]
Hey @inacionery , It's all good. All the failed tests are flaky.

**Comment by javierdearcos** [comment]
Thank you very much @inacionery @rodrigocunhaa !

Have you reviewed the implementation @nhpatt ? Can we execute the CI forward?

**Comment by nhpatt** [comment]
@javierdearcos yes, go with ci:forward

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:stop

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
