### PR TITLE
LPS-194865 Fixing race condition

### PR DESCRIPTION
**Pull request by 4lejandrito**
This fixes this error:

https://testray.liferay.com/reports/production/logs/2023-09/test-1-36/test-portal-acceptance-pullrequest(master)/4146/functional-tomcat90-mysql57-jdk8/0/20/liferay-log.txt.gz?authuser=0

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
@yanan can you verify the failures?

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by yanan** [comment]
> @yanan can you verify the failures?

There is no failure about the API Builder 404 error on this pr! :+1:  I will run tests multiple times with the merged updates, thanks so much!

**Pull request closed without merging**
