### PR TITLE
LPD-24966: Review & adapt tests using hard-coded test password - REST Builder autogenerated tests

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Changes in `base_resource_test_case.ftl` in order to use `PropsUtil` and `PropsKey` instead of hardcoded password
- BuildREST

**Related JIRA Ticket**
https://liferay.atlassian.net/browse/LPD-24966

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
The REST builder changes in autogenerated tests are applied correctly when checking on 7.1.x, 7.2.x, 7.3.x branches ✅

**Review by magjed4289 — APPROVED** [review]

**Comment by sergiojimcos** [comment]
ci:forward

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
@sergiojimcos I think we should only use that value if it is set, if not, default to `test` to avoid breaking previous versions.

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by sergiojimcos** [comment]
No related test cases. Forwarding to Brian

**Comment by sergiojimcos** [comment]
ci:forward:force

**Pull request closed without merging**
