### PR TITLE
LPS-201065 & LPS-201092: Replace AUI() usages

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket LPS-201065](https://liferay.atlassian.net/browse/LPS-201065)
[Link to ticket LPS-201092](https://liferay.atlassian.net/browse/LPS-201092)

## Motivation

In Echo team we are replacing the AUI() usages with js, for this task I have replaced it in dispatch-talend-web, and in dispatch-web, I think the code is not used anymore, so I have removed it.

## Steps for dispatch-talend-web

- Go to Control Panel > Configuration > Job Scheduler
- Click on add button > Talend > create a job
- Edit the job created > go to Talend tab and import a job from your computer
- NOTE: I have downloaded the job here: https://repository.liferay.com/nexus/index.html#nexus-search;quick~com/liferay/etl 

https://github.com/DiegoHu97/liferay-portal/assets/91208451/f2c0a3f4-196e-40d3-a9a6-f4d797bc7ce8

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@jaimelr10 can you review?

**Review by jaimelr10 — APPROVED** [review]
LGTM!

**Comment by jaimelr10** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
ci:test:stable

**Comment by magjed4289** [comment]
Test failures are not related. OK to manually forward ✅

**Comment by jaimelr10** [comment]
ci:forward:force

**Pull request closed without merging**
