### PR TITLE
PD-17696 - Move all Staging related components to Headless team in Testray

### PR DESCRIPTION
**Pull request by joshchong**
https://liferay.atlassian.net/browse/LPD-17696

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:headless

**Comment by magjed4289** [comment]
ci:test:staging

**Review by magjed4289 — CHANGES_REQUESTED** [review]
@joshchong in the ci:test:staging [there are still some tests](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2539146823&testrayTeamId=1310752596&testrayComponentId=1310723285&testrayRunId=2539148767) that keep being assigned to the Staging team, could you take a look?
Also, I think there's one more modification missing when it comes to the ci:test:headless suite, we need to add the Staging components to the suite. 
Also, could you make the change in the staging suite name to be headless-staging, as @4lejandrito suggested?

**Comment by joshchong** [comment]
hey @magjed4289, in your link I'm seeing the team is correctly assigned to Headless, but the component is Staging, which seems correct to me. was there something else you were seeing?

I did notice some tests that are still assigned to Staging team [here.](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2539146823&testrayTeamId=1310723283&testrayRunId=2539148767) even though I updated that component to be under Headless. I believe what's happening is that because those tests are running elsewhere (like upstream or other PRs) they are reverting the value bac. So until the PR is merged upstream, we are going to see inconsistent results in PR runs made here.

As for modifying the test suites themselves, this ticket and PR was just to update the team the tests belong to. I was going to make changes to the test suite separately. I created a ticket for that here: https://liferay.atlassian.net/browse/LPD-17897

**Comment by magjed4289** [comment]
@joshchong in the Team column of Testray I believe we should see Headless, however I tried to filter by Headless team and those tests appear there as well, so I guess it's okay... Still a bit confusing though 😅

**Comment by magjed4289** [comment]
ci:formward:force

**Comment by magjed4289** [comment]
ci:forward:force

**Review by magjed4289 — APPROVED** [review]

**Pull request closed without merging**
