### PR TITLE
LPD-30106 - Add automated test for LPD-18477

### PR DESCRIPTION
**Pull request by DaniSzimko**
https://liferay.atlassian.net/browse/LPD-30106

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:test:headless-playwright

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:close

**Comment by magjed4289** [comment]
test looks good, although it's missing in headless-playwright test suite. to include, you need to modify the main test.properties:
`headless-playwright-projects=\
     (...)
        staging-configuration-web`

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:headless-playwright

**Comment by DaniSzimko** [comment]
ci:test:headless-functional

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:forward:force

**Pull request closed without merging**
