### PR TITLE
LPS-202744: Improve integration test for PATCH Object Fields Unique value

### PR DESCRIPTION
**Pull request by sergiojimcos**
**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPS-202744

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/145385

**Comment by 4lejandrito** [comment]
@sergiojimcos see my changes.

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/145387

**Pull request closed without merging**
