### PR TITLE
LPS-178368 Fix error when patching a site scoped object

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket -> [LPS-178368](https://issues.liferay.com/browse/LPS-178368)
____
## Purpose of the PR
Fix an error when doing patch over an object entry of a site scoped object.
## How to test it
Deploy the following modules:
* `object-rest-impl`
* The steps to reproduce the bug are described on the ticket

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Review by ccorreagg — APPROVED** [review]
LGTM! Well done including the test!

**Comment by LuismiBarcos** [comment]
ci:forward

**Pull request closed without merging**
