### PR TITLE
LPD-18487 [test-fix] changing 'indexed' value for Aggregation and Formula ObjectFields in ObjectDefinition

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-18487

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:playwright

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:test:playwright

**Review by 4lejandrito — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
