### PR TITLE
LPS-166866 Removing feature flag for epics LPS-153316, LPS-149282 and LPS-161363

### PR DESCRIPTION
**Pull request by 4lejandrito**
Do not forward until all the linked tickets in https://issues.liferay.com/browse/LPS-166866 have been closed.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
LGTM :)
Let's see what the CI says 😁

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
Closed in favor of https://github.com/liferay-headless/liferay-portal/pull/1112

**Pull request closed without merging**
