### PR TITLE
LPS-169292 Update to using \& to combine two parameters to batch create blog tests

### PR DESCRIPTION
**Pull request by yanan**
**Background:**
- HeadlessDeliveryBatchMode.testcase functional tests failed on CI 

**Test Plan**
- It is because we need to use `\&` to combine multiple parameters

**JIRA Ticket:**
- https://issues.liferay.com/browse/LPS-169292

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
All functional tests work now. Convert to Draft and will rebase and resend once this pr https://github.com/brianchandotcom/liferay-portal/pull/126736 merged.

**Review by magjed4289 — APPROVED** [review]
Looks good, thank you! :)

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
