### PR TITLE
LPS-123502 Fix the browser back button for Forum Redirector

### PR DESCRIPTION
**Pull request by LuismiBarcos**

### CODE REVIEW

**Comment by nhpatt** [comment]
Did you manage to test it?

**Review by nhpatt — APPROVED** [review]

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
Yes, I tested it by adding a rule to my urlrewrite.xml, and works as I expect.

**Review by nhpatt — APPROVED** [review]

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
