### PR TITLE
LPS-194342 Adding scopeKey path param to the OpenAPI

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPS-194342

Adds the scopeKey to the OpenAPI:

image

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Review by sergiojimcos — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
