### PR TITLE
LPD-34772 & LPD-31166 Patch with query parameters

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPD-34772

This also includes extra commits for https://liferay.atlassian.net/browse/LPD-31166 to fix an issue with the patch tests.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
@4lejandrito I have included extra commits

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by ccorreagg — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
