### PR TITLE
LPS-92033 Segments list API improvements

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

* Ticket: [Improvements in segments list API](https://issues.liferay.com/browse/LPS-92033)

Updated the segments list endpoint form a site to:

* Render `criteria` field in JSON format instead of String: change to `type: object` in `rest-openapi.yaml`
* Not render the internal information in `source` field: 
   - SOURCE_ASAH_FARO_BACKEND = Analytics Cloud
   - SOURCE_DEFAULT = Liferay
   - SOURCE_REFERRED = Liferay (Compound) 

The endpoint is:

```
http://localhost:8080/o/headless-admin-user/v1.0/sites/{siteId}/segments
```

**Screenshot**

Screenshot 2020-10-02 at 12 59 54

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Hey @liferay-headless, I applied suggested changes from https://github.com/liferay-headless/liferay-portal/pull/426. Let me know if you have more feedback for this old story :) Thanks!

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Hey @liferay-headless, do you have any more feedback here? Let me know! Thanks! :)

**Comment by nhpatt** [comment]
Hi @dgarciasarai!

Did you see the last comment about changing the name of the property to avoid a breaking change? https://github.com/liferay-headless/liferay-portal/pull/426#issuecomment-718569321

**Comment by dgarciasarai** [comment]
Hey @nhpatt, sorry, I don't need the same name for the property (`criteria`), so for me it's a good idea to create another property name to display the criteria as JSON. Any idea or suggestion for the new property name? Thanks!

**Comment by nhpatt** [comment]
Mmm... I don't know... maybe CriteriaObject? there is a previous example (although coming from schema.org with MediaObject and also an ObjectReviewed).

**Comment by dgarciasarai** [comment]
Sorry for the delay @nhpatt, so many things to do 😓    If I'm understanding you, your proposal is to add a new attribute with a new Schema?

**Comment by nhpatt** [comment]
Yes :)

**Comment by dgarciasarai** [comment]
Hey @nhpatt, I created a new attribute called `criteriaValue` to display the criteria as JSONObject but I'm having trouble with `JSONFactoryUtil.createJSONObject(segmentsEntry.getCriteria())`. When debugging I see that the conversion is ok:

Screenshot 2021-03-10 at 12 49 02

But in the response of the API I have:

```
"criteriaValue": {
            "jsonobject": {
                "empty": false
            }
        },
```

Example criteria:

```
{"criteria":{"user":{"conjunction":"and","filterString":"(firstName eq 'test')","typeValue":"model"}},"filterStrings":{"model":"(firstName eq 'test')"}}
```

Can you take a look and help me? I don't know what is happening now 😞 

Thanks!

**Comment by nhpatt** [comment]
Looks like JSONObject does not serialize well (internal problem with JSONObject) so we have to convert to a map.

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
Ohhh, because headless-admin-content now includes a lot of external schemas of admin-user and delivery we need to regenerate it when we touch those modules /@javier.dearcos

**Comment by nhpatt** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
Thank you @nhpatt!

**Pull request closed without merging**
