### PR TITLE
LPS-128008 SiteId can be null, so control it to avoid possible NPE

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@javierdearcos, @nhpatt

**Comment by jkappler** [comment]
ci:test:commerce

**Comment by jkappler** [comment]
@marco-leo

**Comment by brianchandotcom** [comment]
@jkappler see bc6169a5b412ce28eb44c10053e8219335634173

I backported this to 7.1.x so I can start publishing 7.3.x.

If there are test errors, send me another pull.

**Comment by jpince** [comment]
ci:close since this was fetched and merged by Brian Chan (see [comment](https://github.com/liferay-headless/liferay-portal/pull/595#issuecomment-782119553))

**Pull request closed without merging**
