### PR TITLE
LPS-163008: Service Builder automate and validate for duplicate ERC

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- This is a continuation of https://github.com/sergiojimcos/liferay-portal/pull/3.
- Update some templates in Service Builder tool to validate ERC.
- Creates `Duplicate<Entity>ExternalReferenceCodeExceptions` just executing the Service Builder. It doesn't need to indicate in the `service.xml`
- Update naming from `findByG_ERC` to `findByERC_G`.
- Execute `buildService` in:
- [x] Account Entry
- [x] Batch-Engine
- [x] Blogs
- [x] ClientExtensions
- [x] Commerce
- [x] Commerce Account
- [x] Commerce Disccount
- [x] Commerce Order Rule
- [x] Commerce Pricing
- [x] Commerce Term
- [x] Dispatch
- [x] Journal
- [x] KnowledgeBase
- [x] Layout Util Page
- [x] List Type
- [x] MessageBoard
- [x] OAuth2
- [x] Objects
- [x] Wiki
- Manual changes in other modules that are related to the previous. 

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-163008

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
CI tests fails related because I have to update a lot of services due to they need to use a new recommend bundle version. Working on that :muscle:

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by 4lejandrito — COMMENTED** [review]
@sergiojimcos I think you can squash all the autogenerated commits in a single one like we do with rest builder to simplify the PR. What do you think?

**Comment by sergiojimcos** [comment]
> @sergiojimcos I think you can squash all the autogenerated commits in a single one like we do with rest builder to simplify the PR. What do you think?

Yeah, you are right. I didn't squash all generated code because first of all I want how CI behaves with the changes and see if there is any module that fails

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Hi @sergiojimcos , here is a summary of relevant tests [compare run results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2055034196&testrayRunIdA=2055267945&statusB=3):

- Integration tests might be related
  - com.liferay.blogs.service.test.BlogsEntryLocalServiceTest 
  - com.liferay.knowledge.base.service.test.KBArticleLocalServiceTest 
  - com.liferay.message.boards.service.test.MBMessageLocalServiceTest 
  - com.liferay.oauth2.provider.client.test.HttpMethodApplicationClientTest 
  - com.liferay.wiki.service.test.WikiNodeLocalServiceTest 
  - com.liferay.wiki.service.test.WikiPageLocalServiceTest 
```testAddBlogsEntryWithExistingExternalReferenceCode: java.lang.Exception: Unexpected exception, expected<com.liferay.blogs.exception.DuplicateEntryExternalReferenceCodeException> but was<com.liferay.friendly.url.exception.DuplicateFriendlyURLEntryException>```
- Functional tests related 
  - LocalFile.ExposeErcFromAssetLibraryForComments#CannotCreateTwoCommentsWithSameCustomExternalReferenceCode
- The other failed tests are not started

And I've send you a pr to update the functional tests if this is expected https://github.com/sergiojimcos/liferay-portal/pull/4, and I can close https://github.com/sergiojimcos/liferay-portal/pull/4 if this is not necessary. Sorry for any troubles :smile:

**Comment by sergiojimcos** [comment]
> 

Thanks a lot @yanan!! :heart: I'll take a look of it each test. As well as, I realized that the semantic version is due to there was an update in `CommerAccount`. As well as, I will take a look at the change that you have made in the functional test

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:stop

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:stop

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
Manual forwarding to Brian: https://github.com/brianchandotcom/liferay-portal/pull/126661

**Pull request closed without merging**
