### PR TITLE
LRQA-82482 | Test fix for Element is not present

### PR DESCRIPTION
**Pull request by Hijky**
**Background:**
Test fix for Element is not present

**Jira ticket:**
https://liferay.atlassian.net/browse/LRQA-82482

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:headless-functional:nocompile

**Comment by Hijky** [comment]
The failures 
LocalFile.CreateAPIApplication#CanCreateAPIOnVirtualInstance
LocalFile.UnpublishAPIApplication#CanPromptUnpublishAPIApplicationDialog
report in this [ticket](https://liferay.atlassian.net/browse/LPS-193414)

the other failures are analyzing and not related to PR

**Review by yanan — APPROVED** [review]

**Review by magjed4289 — APPROVED** [review]

**Comment by Hijky** [comment]
ci:forward

**Comment by Hijky** [comment]
ci:forward:force

**Pull request closed without merging**
