### PR TITLE
LPS-163728 Register a unique application for each object and company

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket -> [LPS-163728](https://issues.liferay.com/browse/LPS-163728)
____

### Purpose of this PR
The main idea of this PR is to register a unique JAXRs application for each object, solving the problem of Objects with the same name in different virtual instances.

### How to deploy the solution
Deploy the following modules
* `object-rest-impl`
* `batch-planner-rest-impl`
* `object-rest-api`

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
cc/ @4lejandrito

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by magjed4289** [comment]
Test failures that were detected with the test run on #794 were retriggered locally on the current branch. All related tests are passing succesfully. Ok to manually forward ✅

**Comment by LuismiBarcos** [comment]
Manually forward https://github.com/brianchandotcom/liferay-portal/pull/124382

**Pull request closed without merging**
