### PR TITLE
LPS-173430

### PR DESCRIPTION
**Pull request by Hijky**
**Background:**
Update testcase to add case for filter multiple levels with comparison if multiple relationships between two objects

**Test Plan**
CanFilterMultipleLevelsWithComparisonIfMultipleRelationshipsBetweenTwoObjects
Given Student, Subject and University object definitions with field 'name' created
And Given one-to-many relaltionships:studentSubjects, subjectUniversities, universityStudents created
And Given many-to-many relationships: studentsUniversities, subjectsStudents, universitiesSubjects created
And Given created subject 'Calculus' related to created student 'Pearl' with studentSubjects
And Given student 'Pearl' related to the created university 'Oxford' with universityStudents
When in GetSubjectsPage filtering by 'studentSubjects/universityStudents/dateCreated lt 2030-04-10T15:04:51Z'
Then 'Calculus' entry details are returned

**Jira ticket:**
https://issues.liferay.com/browse/LPS-187462

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:headless-functional:nocompile

**Review by yanan — APPROVED** [review]

**Comment by Hijky** [comment]
The failures are not related to my PR.

**Review by magjed4289 — APPROVED** [review]

**Comment by Hijky** [comment]
ci:forward

**Pull request closed without merging**
