### PR TITLE
LPS-166071 Add tests for more batch actions in object admin api and update related macro file

### PR DESCRIPTION
**Pull request by yanan**
**Background:**

- Add poshi functional tests for story: Expose updateBatch/deleteBatch action in the Object headless APIs

**Test Plan:**
- When invoking object admin GET "/v1.0/object-definitions"
Then the actions block include the information for the updateBatch, deleteBatch action endpoint
- Given an object definition is created
When with get request and objectDefinitionId to retrieve objectAction, objectField, objectLayout, objectRelationship, objectValidationRule and objectView
Then the actions block include the information for the updateBatch,deleteBatch action endpoint
- Given student object definition is created
And Given student entry is created
When invoking getStudentsPage in c/student
Then the actions block include the information for the updateBatch,deleteBatch action endpoint

**Jira Ticket:**

- https://issues.liferay.com/browse/LPS-166071

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Hi @magjed4289 , yes, the existing tests are for this expose createBatch story, Jira ticket: https://issues.liferay.com/browse/LPS-163169, which is in the same epic of the current [updateBatch, deleteBatch story](https://issues.liferay.com/browse/LPS-164290).

**Review by Hijky — APPROVED** [review]

**Comment by magjed4289** [comment]
Maybe we can modify the tests then, but let's not switch one test for another. Those are already in the Test Map, documented in Jira as well, and check one acceptance criteria related to the story LPS-163169. If we want to save some time and resources maybe we could work on putting more preconditions in common into the setUp step, but let's try not to remove the tests that already existed.

**Comment by yanan** [comment]
> Maybe we can modify the tests then, but let's not switch one test for another. Those are already in the Test Map, documented in Jira as well, and check one acceptance criteria related to the story LPS-163169. If we want to save some time and resources maybe we could work on putting more preconditions in common into the setUp step, but let's try not to remove the tests that already existed.

Got it, updating.

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
