### PR TITLE
LPD-15350 stubs in headless

### PR DESCRIPTION
**Pull request by ccorreagg**

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:help

**Comment by ccorreagg** [comment]
ci:test:headless-playwright

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:headless-playwright

**Comment by ccorreagg** [comment]
ci:test:playwright

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:playwright

**Comment by ccorreagg** [comment]
ci:test:playwright

**Comment by ccorreagg** [comment]
ci:test:playwright

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:playwright

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by jaimelr10** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:playwright

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:playwright

**Comment by ccorreagg** [comment]
ci:test:playwright

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:playwright

**Comment by ccorreagg** [comment]
ci:test:playwright

**Pull request closed without merging**
