### PR TITLE
LPD-21420 don't delete display page just cause it is not referenced in import

### PR DESCRIPTION
**Pull request by ZakiMiklos**
https://liferay.atlassian.net/browse/LPD-21420

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hey @ZakiMiklos please forward this PR to the `liferay-echo` team.

**Review by 4lejandrito — COMMENTED** [review]
See my comment.

**Comment by ZakiMiklos** [comment]
Fowarded to https://github.com/liferay-echo/liferay-portal/pull/15457

**Comment by ZakiMiklos** [comment]
Fowarded to CM: 
https://github.com/liferay-content-management/liferay-portal/pull/5313

**Pull request closed without merging**
