### PR TITLE
LPS-174616: Add createBatch action on all missing endpoints of Headless Delivery

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Add `createBatch` action in all missing endpoints of Headless Delivery
- Changes in: `getMessageBoardThreadMessageBoardMessagesPage`, `getMessageBoardSectionMessageBoardThreadsPage`, `getSiteBlogPostingImagesPage`, `getMessageBoardThreadMessageBoardAttachmentsPage`, `getMessageBoardMessageMessageBoardAttachmentsPage`, `getKnowledgeBaseFolderKnowledgeBaseArticlesPage`, `getStructuredContentFolderStructuredContentsPage`, `getDocumentFolderDocumentsPage`, `getWikiPageWikiPageAttachmentsPage`.

**JIRA Tickets:**
https://issues.liferay.com/browse/LPS-175143
https://issues.liferay.com/browse/LPS-175144
https://issues.liferay.com/browse/LPS-174617
https://issues.liferay.com/browse/LPS-174614
https://issues.liferay.com/browse/LPS-174615
https://issues.liferay.com/browse/LPS-174613
https://issues.liferay.com/browse/LPS-175135
https://issues.liferay.com/browse/LPS-174612
https://issues.liferay.com/browse/LPS-174616
https://issues.liferay.com/browse/LPS-174610

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:close

**Comment by sergiojimcos** [comment]
ci:stop

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
LGTM :)

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
Manual forwarding to Brian: https://github.com/brianchandotcom/liferay-portal/pull/130067

**Pull request closed without merging**
