### PR TITLE
LPS-129055 Add tests

### PR DESCRIPTION
**Pull request by jesseyeh-liferay**
Previous pull requests:
1. https://github.com/ChrisKian/liferay-portal/pull/286
1. https://github.com/ChrisKian/liferay-portal/pull/288
1. https://github.com/ChrisKian/liferay-portal/pull/291

Resending tests for [LPS-129055](https://issues.liferay.com/browse/LPS-129055) with SF changes per [Brian's request](https://github.com/brianchandotcom/liferay-portal/pull/100199#issuecomment-805353831).

### CODE REVIEW

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by jesseyeh-liferay** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:reevaluate:1047401_7820

**Comment by nhpatt** [comment]
Resending here: https://github.com/liferay-headless/liferay-portal/pull/672

**Pull request closed without merging**
