### PR TITLE
LPS-204247 Remove unused @Reference in MultiCompanyBatchEngineUnitPortalInstanceLifecycleListener.java

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-204247

---

The purpose of this PR is to remove the unused `@Reference` in the `MultiCompanyBatchEngineUnitPortalInstanceLifecycleListener` java class. That reference was included to ensure `MultiCompanyBatchEngineUnitPortalInstanceLifecycleListener` is registered after `DefaultObjectFolderPortalInstanceLifecycleListener`. With that, in the moment it was included we were ensuring the method `DefaultObjectFolderPortalInstanceLifecycleListener.portalInstanceRegistered` should be executed before the `MultiCompanyBatchEngineUnitPortalInstanceLifecycleListener.portalInstanceRegistered` for each existing company, as the execution is done inside an addingService method of a service tracker.

However, after trying to reproduce the initial issue, we have not been able to. Now, with the `completableFuture.get();`, the execution will not continue until there is a component that is able to manage the import, that means the `object-rest-impl` module (the ones that contains the component that will be in charge of the import) will not be deployed until `object-service` is deployed properly, and that means the `DefaultObjectFolderPortalInstanceLifecycleListener` will be deployed and its method executed too.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:help

**Comment by ccorreagg** [comment]
ci:test:help

**Comment by ccorreagg** [comment]
ci:test:headless-builder

**Comment by ccorreagg** [comment]
> ### ❌ ci:test:headless-builder - 103 out of 108 jobs passed in 2 hours 18 minutes
> Click here for more details.
> 
> This pull is eligible for [reevaluation](https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands). When this [upstream build](https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/310) has completed, using the following CI command will compare this pull request result against a more recent upstream result:
> 
> ci:reevaluate:1327401_3402
> #### Base Branch:
> Branch Name: [master](https://github.com/liferay/liferay-portal/tree/master)Branch GIT ID: [3710a8f0d816394652434e548cc8f65b80efc8a8](https://github.com/liferay/liferay-portal/commit/3710a8f0d816394652434e548cc8f65b80efc8a8)
> 
> #### Upstream Comparison:
> Branch GIT ID: [33567827e93b2980f70f1b3ae1be8ba7cf28ef77](https://github.com/liferay/liferay-portal/commit/33567827e93b2980f70f1b3ae1be8ba7cf28ef77)Jenkins Build URL: [EE Development Acceptance (master) - 309 - 2024-01-16[20:43:36]](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2488689009)
> 
> **ci:test:headless-builder - 103 out of 108 jobs PASSED**
> ##### For more details click [here](https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3402/jenkins-report.html).
> #### Failures unique to this pull:
> 1. [functional-tomcat90-mysql57-jdk8/4/7](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/768440//consoleText)[beanshell] Total duration: 225
>    [beanshell] Remote execution completed in 226ms.
>    [beanshell] Remote execution starting with 1 threads.
>    [beanshell] Executing commands: ssh -o NumberOfPasswordPrompts=0 root@test-1-39 'mkdir -p "/mnt/mfs-hdd1-10.0.10/jenkins/testray-results/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/4/7"'
>    [beanshell] Average thread duration: 225ms
>    [beanshell] Busy slaves:0
>    [beanshell] Finished slaves:1
>    [beanshell] Target slaves:1
>    [beanshell] Total duration: 226
>    [beanshell] Remote execution completed in 226ms.
>    [beanshell] Executing commands: rsync -aqz --chmod=go=rx "/opt/dev/projects/github/liferay-jenkins-ee/testray/prepared_rsync_logs"/* "test-1-39::testray-results/production/logs/"
>    [beanshell] Uploaded https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/4/7/jenkins-console.txt.gz
>    [beanshell] INFO: Using GOOGLE_APPLICATION_CREDENTIALS=/root/.gcloud/ci-testray.json
>    [beanshell] Unable to delete because file does not exist /opt/dev/projects/github/liferay-jenkins-ee/testray/prepared_s3_logs
>    [beanshell] Created S3 Object https://storage.cloud.google.com/testray-results/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/4/7/jenkins-console.txt.gz in 241 ms
>    [stopwatch] [run.current.job: 7:47.648 sec]
>    [beanshell] Created cache file in /tmp/jenkins-cached-files/-1913520426.txt
>    BUILD FAILED
>    /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:15098: The following error occurred while executing this line:
>    /opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:15971: Sourced file: inline evaluation of: `               import com.liferay.jenkins.results.parser.BuildDatabase;         import com . . . '' : TargetError : at Line: 149 : in file: inline evaluation of:`                import com.liferay.jenkins.results.parser.BuildDatabase;         import com . . . '' : throw exception ;
>    Target exception: com.liferay.jenkins.results.parser.GitWorkingDirectory$GitWorkingDirectoryRuntimeException: Runtime exception  occurred in liferay-portal
>    Unable to fetch remote Git ref LPS-204247 after 3 minutes
>    error: object file .git/objects/37/245965fe1ac194790ec0c2271d7c615f1508ea is empty
>    fatal: cannot read existing object info 37245965fe1ac194790ec0c2271d7c615f1508ea
>    fatal: fetch-pack: invalid index-pack output1. [LocalFile.ListAPIApplicationSchemas#CanPaginateAPISchemas](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/768440//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ListAPIApplicationSchemas_CanPaginateAPISchemas_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/4/7/LocalFile.ListAPIApplicationSchemas_CanPaginateAPISchemas/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/4/7/LocalFile.ListAPIApplicationSchemas_CanPaginateAPISchemas/summary.html.gz) - [Poshi Console](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/4/7/LocalFile.ListAPIApplicationSchemas_CanPaginateAPISchemas/console.txt.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/4/7/jenkins-console.txt.gz)
> 2. [functional-tomcat90-mysql57-jdk8/1/2](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/768437//consoleText)1. [LocalFile.EditGETEndpointThatRetrieveSingleEntryWithCompanyObject#CanSeeUniqueFieldAsPathParameterPropertiesInRelatedSchema](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/768437//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EditGETEndpointThatRetrieveSingleEntryWithCompanyObject_CanSeeUniqueFieldAsPathParameterPropertiesInRelatedSchema_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.EditGETEndpointThatRetrieveSingleEntryWithCompanyObject_CanSeeUniqueFieldAsPathParameterPropertiesInRelatedSchema/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.EditGETEndpointThatRetrieveSingleEntryWithCompanyObject_CanSeeUniqueFieldAsPathParameterPropertiesInRelatedSchema/summary.html.gz) - [Poshi Console](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.EditGETEndpointThatRetrieveSingleEntryWithCompanyObject_CanSeeUniqueFieldAsPathParameterPropertiesInRelatedSchema/console.txt.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/1/2/jenkins-console.txt.gz)2. [LocalFile.EditGETEndpointThatRetrieveSingleEntryWithSiteObject#CanListSiteScopedEndpoint](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/768437//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EditGETEndpointThatRetrieveSingleEntryWithSiteObject_CanListSiteScopedEndpoint_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.EditGETEndpointThatRetrieveSingleEntryWithSiteObject_CanListSiteScopedEndpoint/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.EditGETEndpointThatRetrieveSingleEntryWithSiteObject_CanListSiteScopedEndpoint/summary.html.gz) - [Poshi Console](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.EditGETEndpointThatRetrieveSingleEntryWithSiteObject_CanListSiteScopedEndpoint/console.txt.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/1/2/jenkins-console.txt.gz)
> 3. [functional-tomcat90-mysql57-jdk8/1/5](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/807457//consoleText)1. [LocalFile.CreateAPIApplicationSchema#AllObjectDefinitionsAreAvailableInTheObjectMenu](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/807457//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_CreateAPIApplicationSchema_AllObjectDefinitionsAreAvailableInTheObjectMenu_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/1/5/LocalFile.CreateAPIApplicationSchema_AllObjectDefinitionsAreAvailableInTheObjectMenu/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/1/5/LocalFile.CreateAPIApplicationSchema_AllObjectDefinitionsAreAvailableInTheObjectMenu/summary.html.gz) - [Poshi Console](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/1/5/LocalFile.CreateAPIApplicationSchema_AllObjectDefinitionsAreAvailableInTheObjectMenu/console.txt.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2024-01/test-1-32/test-portal-acceptance-pullrequest(master)/3402/functional-tomcat90-mysql57-jdk8/1/5/jenkins-console.txt.gz)
> 4. [modules-integration-mysql57-jdk8/0/0](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/873412//consoleText)1. [com.liferay.headless.builder.model.listener.test.APISortRelevantObjectEntryModelListenerTest](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/873412/testReport/com.liferay.headless.builder.model.listener.test/APISortRelevantObjectEntryModelListenerTest) - [Failed 23 of last 25](https://testray.liferay.com/home/-/testray/case_results/2487686210/history)1. [testPostSort](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/873412//testReport/com.liferay.headless.builder.model.listener.test/APISortRelevantObjectEntryModelListenerTest/testPostSort)
> 
> **Failures in common with [acceptance upstream results](https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)) at [3356782](https://github.com/liferay-headless/liferay-portal/commit/33567827e93b2980f70f1b3ae1be8ba7cf28ef77):**
> ##### Test bundle downloads:
> * [liferay-portal-bundle-tomcat.tar.gz](https://files.liferay.com/private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/3402/liferay-portal-bundle-tomcat.tar.gz) (mirrors: [dlc](http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/3402/liferay-portal-bundle-tomcat.tar.gz), [lax](http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/3402/liferay-portal-bundle-tomcat.tar.gz))

It seems the errors are not related. This is the [comparison matrix](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2488689052&testrayRunIdA=2488753523&statusB=2):

image

The two failed tests:

image

The first seems to be a flaky test:

image

The second one has not been executed due to an external error

**Comment by ccorreagg** [comment]
ci:test:headless-builder

**Comment by ccorreagg** [comment]
ci:test:headless-builder

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
Rebased on top of https://github.com/liferay-headless/liferay-portal/pull/1826 and https://github.com/liferay-headless/liferay-portal/pull/1827 that fixes the API Builder tests

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:headless-builder

**Comment by ccorreagg** [comment]
Rebased with master

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:headless-builder

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:headless-builder

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:headless-builder

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
The CI seems to be broken. It is failing all the time with the relevant suite. It also happens in different PRs.

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:report:2488753470

**Comment by ccorreagg** [comment]
ci:report:2488110052

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:report:2538148588

**Comment by ccorreagg** [comment]
ci:test:headless-builder

**Comment by ccorreagg** [comment]
ci:test:stable

**Comment by ccorreagg** [comment]
It seems none of the errors are related. I have been trying to reproduce the error that could happen when removing the dependency but wasn't able either locally. Forwarding the PR

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
