### PR TITLE
LPD-17716 Remove DeleteAfterTestRun that duplicates actions of DataGuard

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-17716

The purpose of this PR is to resolve issues with trying to remove an ObjectDefinition that is already deleted. 
DataGuard takes care of removing the data, so DeleteAfterTestRun is unnecessary and leads to issues when running tests:

`PortalLogAssertorTest#testScanXMLLog: null com.liferay.object.exception.NoSuchObjectDefinitionException: No ObjectDefinition exists with the primary key 73199  at com.liferay.object.service.persistence.impl.ObjectDefinitionPersistenceImpl.findByPrimaryKey(ObjectDefinitionPersistenceImpl.java:11878)  at com.liferay.object.service.persistence.impl.ObjectDefinitionPersistenceImpl.findByPrimaryKey(ObjectDefinitionPersistenceImpl.java:11896)  at com.liferay.object.service.impl.ObjectEntryLocalServiceImpl.getValues(ObjectEntryLocalServiceImpl.java:1090)  at sun.reflect.GeneratedMethodAccessor2577.invoke(Unknown Source)  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)  at java.lang.reflect.Method.invoke(Method.java:498)  at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41)  at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60)  at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMe...`

DataGuard is enough and removes all the ObjectDefinitions from the DataBase leaving the instance clean.

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hey @magjed4289, @ccorreagg,

I am not sure if this is safe. I think at some point we removed those annotations and DataGuard still failed... I like the changes, but we have to be pretty sure it works reliably.

**Comment by ccorreagg** [comment]
I think the problem comes when an object definition is removed before the object entries, in some cases, the object entries are removed again, and then, it fails, but don't remember the use cases where the error is reproducible

**Review by 4lejandrito — APPROVED** [review]
Let's forward and if we see new issues we can roll it back.

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
