### PR TITLE
LPS-173450 Fix the auto-generated PATCH method when the GET by externalReferenceCode method has more than one parameter

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to fix this bug: https://issues.liferay.com/browse/LPS-173450

Now, the `get` and `put` methods name come from the `patch` method name just by replacing the substring `patch` for `get` or `put` instead of calculating it based on the `forcePredictableOperationId` configuration parameter.

Furthermore, instead of just adding the first java method parameter name, all of them except the last one are used.

cc/ @4lejandrito as I rollback part of the code that was included in [this commit](https://github.com/liferay/liferay-portal/commit/ba509dfe7c4274565b27076e82b887b576d65f33)

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:forward:force

**Pull request closed without merging**
