### PR TITLE
LPD-39971 Import attachments from URL

### PR DESCRIPTION
**Pull request by marco-leo**
**Problem**:

Currently, Liferay object entries require attachments to be uploaded as base64 or link it with an existing Document in the document library. This can be cumbersome, especially when dealing with large files or when attachments are stored remotely.

**Solution**:

Introduce a new property to the attachment field type schema: attachmentURL. (we can discuss on the name)

When importing an object entry, if the attachmentURL property is filled, Liferay will:

Fetch the document from the specified URL.

Store the downloaded document in the document library.

Associate the downloaded document with the object entry.

The new mechanism supports both batch imports and individual object entry creation through the POST endpoint.

### CODE REVIEW

**Comment by marco-leo** [comment]
@4lejandrito I know is missing tests, but I would like to validate the pattern and name with you first, than I will complete the PR

**Comment by marco-leo** [comment]
ci:test:relevant

**Comment by marco-leo** [comment]
ci:test:stable

**Comment by 4lejandrito** [comment]
Hey @marco-leo I think this looks good. Some questions:

1. Should we mark the property as write only? Or do we want to store the original url somewhere in the DB?
2. Should the headless product guys take a look to identify potential missing usecases? 

We can polish this with proper testing if needed, let us know if you want us to move this forward.

**Comment by 4lejandrito** [comment]
As discussed, this goes in the right direction. Send us the final PR when it's ready.

**Comment by 4lejandrito** [comment]
@jaimelr10 please also add a feature flag.

**Pull request closed without merging**
