### PR TITLE
Commerce 9949 | update functional tests

### PR DESCRIPTION
**Pull request by yanan**
**Background:**
- Include https://github.com/liferay-headless/liferay-portal/pull/722
- Test fix for functional test on Job Scheduler Trigger

**Test Plan:**
- ImportExport#CanScheduleImport

**JIRA Ticket:**
- https://issues.liferay.com/browse/COMMERCE-9949

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:data-integration

**Comment by yanan** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:data-integration

**Comment by yanan** [comment]
ci:test:data-integration

**Comment by yanan** [comment]
The failed test is not related. All tests in ImportExport.testcase working.
And the only failure is on top-level, [com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/225386/testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog/) batch test. 
image

**Comment by yanan** [comment]
Hello @igorbeslic , just a heads up that I'm going to forward this one since Meg and I think the test failure is unrelated. Please feel free to let know if there is anything :smile:

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
