### PR TITLE
LPS-197939 Update BatchEngineBroker tests to correctly handle 2nd company

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
stopping the ci as there will be more changes to come
cc @matijapetanjek

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:stop

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by yanan** [comment]
Failures in relevant tests are not related, and BatchEngineBrokerTest passed in this pr :partying_face: 
image

**Comment by matijapetanjek** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/142189

**Pull request closed without merging**
