### PR TITLE
LPS-194572: Actions node missing in JSONL and JSON formats

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Include actions when export a Custom Object Definition for `JSON` and `JSONL`.
- Create new test case validation to determine that actions property is not empty.
- Fix Company init when creating a new one.

**JIRA Related Ticke**
https://liferay.atlassian.net/browse/LPS-194572

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by matijapetanjek — APPROVED** [review]
LGTM!!

**Comment by sergiojimcos** [comment]
ci:forward

**Pull request closed without merging**
