### PR TITLE
LPS-202692 NoSuchLayoutException occurs when going to staging configuration via Portlet

### PR DESCRIPTION
**Pull request by DaniSzimko**
https://liferay.atlassian.net/browse/LPS-202692

from: https://github.com/liferay-headless/liferay-portal/pull/1712

cc @vendeltoreki , @4lejandrito

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:staging

**Review by 4lejandrito — APPROVED** [review]
Hey @DaniSzimko I reviewed and tested it. The test fails without the changes and passed with them so :+1: 

Good to go from my side.

**Comment by vendeltoreki** [comment]
ci:forward

**Comment by vendeltoreki** [comment]
ci:forward:force

**Pull request closed without merging**
