### PR TITLE
LPS-195526 Avoid to unrelate elements in the UPSERT strategy when those elements were already related and must keep being related

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-195526

---

The purpose of this PR is to modify the existing flow in which, when receiving a request for an element and its related elements in the same body, when processing the related elements, all the related elements were first unrelated and then related those that traveled in the body of the message.

This prevents `ObjectEntry` modification events from being generated/invoked with the relationship field empty when the request has not requested to unrelate those elements.

The new interface `ExternalReferenceCodeModel` has been added to the kernel. All the entities created with Service Builder will implement the interface in case the `externalReferenceCode` field exists and the Liferay version is greater or equals to 7.4. That will allow to get the external reference code of a model without using reflection.

---

How to test it:

Follow [the instruccions in the jira ticket](https://liferay.atlassian.net/browse/LPS-195526)

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Rebased with master, relaunched the `ant build-services` command and included a commit with the portal-kernel baseline

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
See my changes and if possible add a test that fails without these changes in `headless-builder-test`.

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Rebased with master to fix the conflicts

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Added commit to fix the [ReturnRelatedObjectEntriesInResponse#CanReturnUpdatedCustomObjectsWithPatchSubjectInOneToManyRelationshipWithItself](https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/262358//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ReturnRelatedObjectEntriesInResponse_CanReturnUpdatedCustomObjectsWithPatchSubjectInOneToManyRelationshipWithItself_) test

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Carlos is helping to look into the issue, here is more details on the [compare run results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2424478530&testrayRunIdA=2424370460&statusB=2)
- SystemObjectRelatedObjectEntriesTest.testPostSystemObjectEntryWithNestedCustomObjectEntries
- APIPropertyRelevantObjectEntryModelListenerTest.testAddAPIProperty
- OperateSystemObjectAndRelatedCustomObjectsWithinSingleRequest (Error is same with the first one)

**Comment by ccorreagg** [comment]
Fixed tests and rebased with master

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Rebased with master

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Failures are not related from qa perspective :partying_face:

**Comment by ccorreagg** [comment]
ci:forward:force

**Comment by ccorreagg** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140835

**Pull request closed without merging**
