### PR TITLE
LPS-183903 Allow developers to retrieve different levels of the many/one to many related elements of a system object as nestedFields

### PR DESCRIPTION
**Pull request by ccorreagg**
Related issue: https://issues.liferay.com/browse/LPS-183903

---

This PR contains the code to allow developers to retrieve different levels of the many to many and one to many related elements of a System Object.

Currently, it is already possible to retrieve the MtoM and 1toM of a System Object, as the functionality was included previously in [this other PR](https://github.com/brianchandotcom/liferay-portal/pull/133972). The reason is because when developing it in the Custom Objects side, when related to a System Object, some code was necessary to be included.

For that, the following changes have been included:

- A commit to modify the method used to check if the object definition is a system object, from `isSystem` to `isUnmodifiableSystemObject`, as the new method must be used when service builder system objects are involved.
- New integration "sub-tests" have been included in the `SystemObjectRelatedObjectEntriesTest` class over the tests `testGetManyToManySystemObjectRelatedObjectEntries` and `testGetOneToManySystemObjectRelatedObjectEntries`

**How to test it:**

- Set the feature flag `LPS-165819`
- Deploy the module `modules/apps/object/object-rest-impl`
- Launch the integration tests over the directory `modules/apps/object/object-rest-test`:
  - `gw tI --tests SystemObjectRelatedObjectEntriesTest.testGetManyToManySystemObjectRelatedObjectEntries`
  - `gw tI --tests SystemObjectRelatedObjectEntriesTest.testGetOneToManySystemObjectRelatedObjectEntries`

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
It is only necessary to review the commits who description starts with LPS-183903 (as the previous commits belong to another PR that will be merged soon and whose changes are used in this PR)

**Review by LuismiBarcos — APPROVED** [review]
What an amazing PR 👏 👏 👏 👏

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
The tests have been moved to a different class, to it is necessary this PR to be reviewed again

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Weird, as the test SystemObjectRelatedObjectEntriesTest.testGetManyToManySystemObjectRelatedObjectEntries works properly in local :thinking:

**Comment by ccorreagg** [comment]
> Weird, as the test `SystemObjectRelatedObjectEntriesTest.testGetManyToManySystemObjectRelatedObjectEntries` works properly in local thinking

Well, finally detected. There was a feature flag missing in the test

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) 👏 👏 👏 👏

**Comment by yanan** [comment]
Failures are unrelated to the current pr.

**Comment by ccorreagg** [comment]
Thanks @yanan !

**Comment by ccorreagg** [comment]
Forwarded manually. See https://github.com/brianchandotcom/liferay-portal/pull/134681

**Pull request closed without merging**
