### PR TITLE
LPD-20366: Enable to delete multiple job scheduler triggers created

### PR DESCRIPTION
**Pull request by sergiojimcos**
## Motivation
The idea of this PR is to fix the management toolbar logic where an user can delete several job schedulers created and it can show all the total job schedulers triggers when a job scheduler is selected.

**What is new?**
- Get all selected `dispatchTriggersIds` from a Long Array instead of getting all the parameter as String and split it because it will always return the first one.
- Fix `management toolbar` total numbers of Job Schedulers created.
- Add new module in `playwright` to test these two cases.

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPD-20366

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward:force

**Comment by sergiojimcos** [comment]
Sent here to Brian: https://github.com/brianchandotcom/liferay-portal/pull/148181

**Pull request closed without merging**
