### PR TITLE
LPS-131550 Move TransformUtil from portal-vulcan to petra-function

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:stop

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by yanan** [comment]
Hello @matijapetanjek , the test failures are unrelated from qa perspective.
 
Here is the [compare run](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2011185867&testrayRunIdA=2010848033&statusB=3), the only unique integration failures seem flaky, I also see it on other Acceptance tests. cc @magjed4289 

- com.liferay.oauth2.provider.client.test.DisabledUserClientTest
- com.liferay.oauth2.provider.token.endpoint.test.RefreshTokenAuthorizationGrantTest
- com.liferay.segments.configuration.provider.test.SegmentsConfigurationProviderTest

**Comment by matijapetanjek** [comment]
Thank you very much @yanan for the analysis!

**Comment by matijapetanjek** [comment]
@4lejandrito  if you think everything is OK with this PR I will send it to Brian directly, looks like there are too many flaky tests triggered with this PR to be forwarded by CI.

**Review by 4lejandrito — APPROVED** [review]

**Comment by matijapetanjek** [comment]
ci:forward

**Pull request closed without merging**
