### PR TITLE
LPS-156004 | Add a testcase to import and export objects

### PR DESCRIPTION
**Pull request by Hijky**
Background:
Add a testcase to import and export objects

Test Plan
SelectCustomObjectAsEntityType
Given a custom object is published
When select the custom object as the entity type to export
Then no error in server console

ExportCustomObjectWithObjectEntry
Given a custom object is published
And Given object entry is created
When user export custom object as entity type and map attribute codes
Then the zip file contains a related file type export successfully

ExportCustomObjectWithAllFieldTypesMapped
Given a custom object with all kinds of field type is publushed
And Given object entry is created
When user export custom object with all attributes codes selected
Then the zip file contains a related file type export successfully

ExportCustomObjectEntryWithOneToManyRelationship
Given two custom objects published
And Given oneToMany releationship has been set between them
And Given one entry related to antoher one
When user export custom object as entity type
Then zip file contains related file type export successfully

ExportCustomObjectEntryWithManyToManyRelationship
Given two custom objects published
And Given manyToMany releationship has been set between them
And Given one entry related to another one
When user export custom object as entity type
Then zip file contains related file type export successfully

Jira ticket:
https://issues.liferay.com/browse/LPS-176966

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:reopen

**Comment by Hijky** [comment]
@ling-alan-huang Hi Alan, this is an SF error it didn't appear last Friday but failed this Monday, and when I finished commit locally and then run 'ant format-source-current-branch', the 'feature.flag.LPS-153478=false' will be deleted in portal.properties

**Comment by ling-alan-huang** [comment]
@Hijky I fixed it in this PR: https://github.com/ling-alan-huang/liferay-portal/pull/1865

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:headless-functional:nocompile

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:forward

**Comment by Hijky** [comment]
ci:test:headless-functional:nocompile

**Comment by Hijky** [comment]
@magjed4289 @yanan I checked the failures of ci:test:relevant and ci:test:headless-functional, some related failures were caused by the error 'Unable to update batch engine export task', it may be related to the last commit for SF, and I think it doesn't relate to my changes, and if the failures are not related to the changes could you help me ci:forwrad:force it?
Screenshot from 2023-05-16 17-38-19

**Comment by yanan** [comment]
> @magjed4289 @yanan I checked the failures of ci:test:relevant and ci:test:headless-functional, some related failures were caused by the error 'Unable to update batch engine export task', it may be related to the last commit for SF, and I think it doesn't relate to my changes, and if the failures are not related to the changes could you help me ci:forwrad:force it? Screenshot from 2023-05-16 17-38-19

I don't think the error is because of the last commit of SF, which is only disable sf on PropertiesFeatureFlagsCheck, the problem is NullPointerException when export Custom object, we need to check if it happens on master so that we can make sure if this is a regression bug or not. 
And yes, the failures should not because of your files. Let's see if Meg would like to forward this :smiley:

**Comment by magjed4289** [comment]
> @magjed4289 @yanan I checked the failures of ci:test:relevant and ci:test:headless-functional, some related failures were caused by the error 'Unable to update batch engine export task', it may be related to the last commit for SF, and I think it doesn't relate to my changes, and if the failures are not related to the changes could you help me ci:forwrad:force it? Screenshot from 2023-05-16 17-38-19

hmm, this error looks familiar, did you look in Jira whether we already have reported something similar? 🤔 Some of the errors appear in [EE Development Acceptance (master) routine](https://testray.liferay.com/home/-/testray/case_results/2305693512?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcases%2F2299538611%2Fview%3Fcur%3D1%26delta%3D200%26testrayCaseId%3D2299538611%26orderByCol%3DcreateDate_sortable%26orderByType%3Ddesc)

**Comment by ling-alan-huang** [comment]
@magjed4289 Give me 10 mins, I will check the SF changes again.

**Comment by ling-alan-huang** [comment]
Resent https://github.com/liferay-headless/liferay-portal/pull/1239

**Comment by ling-alan-huang** [comment]
ci:close

**Pull request closed without merging**
