### PR TITLE
LPD-35339 OBJECT_DEFAULT potential security vulnerability

### PR DESCRIPTION
**Pull request by LuisOrtiz89**

### CODE REVIEW

**Comment by LuisOrtiz89** [comment]
ci:test:relevant

**Comment by LuisOrtiz89** [comment]
ci:report:11617966

**Review by 4lejandrito — APPROVED** [review]
See my changes. Please review the test results.

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by LuisOrtiz89** [comment]
@4lejandrito I force pushed some very small changes to fix some failing tests as we discussed in Slack. If Testray report is OK, we can forward it.

**Comment by LuisOrtiz89** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/154331

**Pull request closed without merging**
