### PR TITLE
Lrqa 78630

### PR DESCRIPTION
**Pull request by yanan**
Background:
- Update tests on erc message related since changes on LPS-163008

Test Plan
- LocalFile.ExposeErcFromAssetLibraryForComments#CannotCreateTwoCommentsWithSameCustomExternalReferenceCode
- LocalFile.ExposeErcForCategories#CanDeleteCategoryByErc
- LocalFile.ExposeErcForCategories#CanRecieveErrorMessageByNotExistErcInCategory

JIRA Ticket:
- https://issues.liferay.com/browse/LRQA-78630
- https://issues.liferay.com/browse/LRQA-78623

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
Tests failures are unrelated, all about ImportExport.testcase now.

**Review by Hijky — APPROVED** [review]

**Review by magjed4289 — APPROVED** [review]

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
