### PR TITLE
LRQA-78917 Test Fix Expected text does not match with Actual text

### PR DESCRIPTION
**Pull request by Hijky**
Background
Expected text does not match with Actual text

JIRA Link:
https://issues.liferay.com/browse/LRQA-78917

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:relevant

**Comment by Hijky** [comment]
ci:test:headless-functional

**Comment by Hijky** [comment]
@magjed4289 @yanan The failures are not related to my PR.
The test cases ImportExport#GetImportFileAvailableEntityTypes and ImportExport#GetExportFileAvailableEntityTypes are run successfully.
Screenshot from 2022-12-27 08-38-41

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Review by yanan — APPROVED** [review]

**Comment by yanan** [comment]
Test failures are unrelated to the current pr, we can investigate and send new updates for other failures.

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
