### PR TITLE
LPS-204388: Delete previous Job Scheduler when it is updated

### PR DESCRIPTION
**Pull request by sergiojimcos**
## Motivation
The idea of this PR is to delete the previous `dispatchTaskClusterMode`'s Job Scheduler created and set the new one. Before it always add new ones instead of delete the previous one.

**What is new?**
- Recover previous 	`dispatchTaskClusterMode` in order to delete the previous one and update the new one.
- Add test case to represent this use case

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPS-204388

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
