### PR TITLE
LPS-125032 Add exception mapper to AssetCategoryException to map it to a Bad Request response

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by javierdearcos** [comment]
We were throwing a 500 without any information in the server's log.

This way we give a Bad Request response with some information about the error but not very detailed as it is not a specific exception of the underlying service and have no exception message written by the service.

Other solution could be to catch the exception in the ResourceImpl and throw another one with a more specific message related with the entity and action executed, but the code get messier...

I think this approach is better to not mess the ResourceImpl code

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
LGTM :)

**Review by nhpatt — APPROVED** [review]

**Pull request closed without merging**
