### PR TITLE
LPD-42640 Add file to launch the relevant tests if there is any change

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPD-42640

The purpose of this PR is to add the `build.gradle` file as one of the files that, if it is changed, the `portal-vulcan` tests will be launched inside the relevant suite. For example, we did some changes in [this other PR](https://github.com/liferay-headless/liferay-portal/pull/2346) and the portal-vulcan tests were not launched the first execution of the relevant suite

---

cc/ @GaborKomaromi

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant:dryrun

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant:dryrun

**Comment by magjed4289** [comment]
@ccorreagg could you explain what we want to achieve here?

**Comment by magjed4289** [comment]
ci:test:relevant:dryrun

**Comment by ccorreagg** [comment]
> @ccorreagg could you explain what we want to achieve here?

Hey @magjed4289 , I have included a more descriptive description. Please let me know if that is enough

**Comment by magjed4289** [comment]
closing as will be tested first on my personal repo, will resed if possible to modify

**Pull request closed without merging**
