### PR TITLE
LPS-201676

### PR DESCRIPTION
**Pull request by Youness-ELMO**
[LPS-190596](https://liferay.atlassian.net/browse/LPS-201676) - Automation to Allow users to define sorts

### CODE REVIEW

**Comment by Youness-ELMO** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:headless-builder-functional:nocompile

**Comment by magjed4289** [comment]
ci:forward

**Comment by magjed4289** [comment]
LGTM! Thank you @Youness-ELMO! 🥳

**Pull request closed without merging**
