### PR TITLE
LPD-37770 Modify export-import/staging infrastructure to support disable data handlers

### PR DESCRIPTION
**Pull request by Mikellorza**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-37770

Hi team,

Working on deprecating wiki from the portal, we have the need to hide wiki from the export-import/staging process. So, this PR include all necessary changes to support disable data handlers in order to do not import/export staged data models neither portlet data models

# How am I fixing it?

Adding isEnabled method to portlet and staged model data handlers interfaces and use it in base implementations in order to exclude wiki model and portlets from the export-import process.

# How can you verify that it works?

Run included tests.

### CODE REVIEW

**Comment by Mikellorza** [comment]
Hi @DaniSzimko ,

Only to clarify that we will need some customers using wiki and import/export or staging functionality, so for that reason we can not delete data handlers components because there will be some customers using wiki normally  and for new companies we will hide wiki.

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:headless-staging

**Comment by DaniSzimko** [comment]
Hello @Mikellorza 

Thank you for submitting the PR. I reviewed it, and the only issue I noticed is that if I disable the Wiki with your modifications, the WikiAdminPortlet is still visible in the UI. I think we should add an isEnabled method to the MVCPortlet as well to prevent scenarios where the WikiAdmin and WikiDisplay portlets remain active in the UI, but their data handlers are not functioning.

Please let me know what you think.

**Comment by Mikellorza** [comment]
Hi @DaniSzimko ,

Thanks for your feedback. Don't worry about more changes about wiki deprecation. There are some PR's about it like[ this one](https://github.com/liferay-content-management/liferay-portal/pull/5917) already merged in brian , [this another one](https://github.com/liferay-core-infra/liferay-portal/pull/7491) in core infra team and some more that I am working on.  If you want you can see the subtask created[ on the story](https://liferay.atlassian.net/browse/LPD-36851). 

Regards!

**Comment by Mikellorza** [comment]
@DaniSzimko ,

The change you comment is already on master as you can see [here](https://github.com/liferay/liferay-portal/blob/6b1dddaf95b1e77c92fc29de69cf7f81c0564dc1/modules/apps/wiki/wiki-web/src/main/java/com/liferay/wiki/web/internal/portlet/WikiAdminPortlet.java#L63)

Regards!

**Comment by Mikellorza** [comment]
ci:report:34225320

**Comment by Mikellorza** [comment]
ci:report:34225320

**Comment by Mikellorza** [comment]
There is a semantic related issue  : https://testray.liferay.com/#/project/35392/routines/45357/build/34225320/case-result/34228275. I am working to fix it.

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:headless-staging

**Comment by DaniSzimko** [comment]
Hello @Mikellorza ,

Thank you for the response. Could you please fix the versioning in export-import-test?
If it is done, I believe we can forward this.

**Comment by Mikellorza** [comment]
ci:report:34327394

**Comment by Mikellorza** [comment]
@DaniSzimko ,

yes, it is done yes. I am trying to see why stable suite is nos passing. I will keep you posted.

Thanks !

**Comment by Mikellorza** [comment]
ci:report:34462644

**Comment by Mikellorza** [comment]
ci:report:34327394

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:headless-staging

**Comment by Mikellorza** [comment]
ci:report:35421022

**Comment by Mikellorza** [comment]
ci:report:35562116

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:report:36462358

**Comment by Mikellorza** [comment]
ci:report:36462358

**Comment by Mikellorza** [comment]
There is an error in stable suite and I have to add a translation for the created portlet in the tests: https://testray.liferay.com/#/project/35392/routines/45357/build/36462358/case-result/36467642

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
This is the [only test that could be related](https://testray.liferay.com/#/project/35392/routines/45357/build/36807208/case-result/36821799) but I added [this commit](https://github.com/liferay-headless/liferay-portal/pull/2235/commits/d3ea9f32dd67513b047993e06d6fa8f23edeaa8d) and [this commit](https://github.com/liferay-headless/liferay-portal/pull/2235/commits/34ceb5dca0dcee4b290ec9d672e20acc28f05eb8) to fix it.

**Comment by Mikellorza** [comment]
So, let's move to brian.

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
