### PR TITLE
LPS-125672 Modify Service Builder to allow adding an scoped external reference code

### PR DESCRIPTION
**Pull request by javierdearcos**
(Change LPS to refer to a new technical task to track better this changes)

Added example of usage in portal-tools-service-builder-test-service

The changes in scope are noticeable in:

- The Persistence files where `... findByG_ERC(long groupId, String externalReferenceCode)` signature is generated instead of `... findByC_ERC(long companyId, String externalReferenceCode)`
- The LocalService files where `... fetchGroupScopedEntryByReferenceCode(long groupId, String externalReferenceCode)` signature is generated instead of `fetchCompanyScopedEntryByReferenceCode(long companyId, String externalReferenceCode)`

### CODE REVIEW

**Comment by javierdearcos** [comment]
cc/ @nhpatt

**Comment by javierdearcos** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by javierdearcos** [comment]
Don't know what Brian was referring to with the comment in the closed PR: 
```
I think the current toUpperCase may be wrong vs. using TextFormatter.
```
I've checked the class but I think it is better with the current implementation and the output is correct

https://github.com/brianchandotcom/liferay-portal/pull/97554

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:forward

**Pull request closed without merging**
