### PR TITLE
LPS-195543 Delete when disassociating API Properties from an API Schema

### PR DESCRIPTION
**Pull request by ccorreagg**
Related issue: https://liferay.atlassian.net/browse/LPS-195543

---

The purpose of this PR is to delete the API property (ObjectEntry) that is being disassociated from an API Schema automatically, as we don't want to keep API Properties without any schema associated.

A new Registrar Helper has been created, so the registration of the `ObjectRelatedModelsProvider` interface is delegated to simplify it, as now we are registering with some properties that makes easier to find them and override the functionality of certain methods.

---

How to test it:

A new integration test has been added. It is possible to test by executing the command `gw tI --tests APIPropertyRelevantObjectEntryModelListenerTest.testRemoveAPIProperty` in the `headless/headless-builder/headless-builder-test` module

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Added last 2 commits.

**Comment by 4lejandrito** [comment]
ci:forward

**Review by 4lejandrito — APPROVED** [review]

**Comment by yanan** [comment]
Except for the conflict, here is one failure needs double check:
- LocalFile.ListAPIApplicationSchemas#CanFilterSchemaByCreationDateAsLastUpdated
    - Failed to create an API application with POST request, [error log](https://testray.liferay.com/reports/production/logs/2023-09/test-1-36/test-portal-acceptance-pullrequest(master)/4218/functional-tomcat90-mysql57-chrome100-jdk8/4/1/liferay-log.txt.gz?authuser=0)
image

image

**Comment by ccorreagg** [comment]
Included a new commit to avoid the NPE, as the service tracker had been closed already

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
Test fixes needed:
[LPS-197335](https://liferay.atlassian.net/browse/LPS-197335)

Other test failures are not related.
OK to manually forward. ✅

**Comment by ccorreagg** [comment]
Thank you @meg!

Sent [here](https://github.com/brianchandotcom/liferay-portal/pull/141310)

**Comment by magjed4289** [comment]
Test failures are not related. I removed earlier comment by mismatch of PRs, but all good :) ✅

**Pull request closed without merging**
