### PR TITLE
LPD-18212 Autogenerate namespaces for GraphQL queries/mutations to make the queries/mutations unique

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: [LPD-18212](https://liferay.atlassian.net/browse/LPD-18212)

See https://github.com/liferay-headless/liferay-portal/pull/1888

---

The purpose of this PR is to provide queries and mutations namespaced by a namespace (calculated based on the JAX-RS REST API application path). For example, those queries/mutations from the Headless Delivery REST API v1.0, will be now encapsulated within the `headlessDelivery_v1_0` namespace.

This calculation uses the REST API path:

`/headless-delivery/v1.0` -> `headlessDelivery_v1_0`

By now, it will be necessary to set the feature flag `LPD-10789`

In order to maintain backwards compatibility, the non-namespaced queries and mutations and the ones with a static namespace based on the `rest-config.yaml` file will keep working, but in the GraphQL schema it will be marked as deprecated.

cc/ @albertojml 

---

**Examples:**

**New namespaced queries:**

```graphql
query {
    headlessAdminContent_v1_0 {
        structuredContents(siteKey: "20117") {
            items {
                contentStructure {
                    name
                }
                title
                version {
                    number
                    status {
                        code
                    }
                }
            }
        }
    }
    headlessDelivery_v1_0 {
        structuredContents(siteKey: "20117") {
            items {
                title
            }
        }
    }
}
```

**Deprecated queries:**

(with namespace (from the `rest-config.yaml` file), for example the Headless Admin Content REST API)

```graphql
query {
    admin {
        structuredContents(siteKey: "20117") {
            items {
                contentStructure {
                    name
                }
                title
                version {
                    number
                    status {
                        code
                    }
                }
            }
        }
    }
}
```
(without namespace, for example the Headless Delivery REST API)

```graphql
query {
    structuredContents(siteKey: "20117") {
        items {
            title
        }
    }
}
```

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:report:2543874761

**Comment by ccorreagg** [comment]
No related errors found in the CSV. Relaunching the ci:test:relevant just in case

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:report:2544593759

**Comment by ccorreagg** [comment]
No related errors have been found. Let's wait @4lejandrito ' review to forward to Brian

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:report:2547783924

**Comment by ccorreagg** [comment]
ci:report:2548092784

**Comment by ccorreagg** [comment]
The test failures are not related. Forwarding to Brian

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
