### PR TITLE
LPD-20733 Fix the macro to align with the new appearance of the content section

### PR DESCRIPTION
**Pull request by DaniSzimko**
Issue: https://liferay.atlassian.net/browse/LPD-20733

Fix the macro to align with the new appearance of the content section

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:headless

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
Hey @DaniSzimko. We cannot send PRs directly to task tickets. You need to create a subtask and send it to that ticket.

**Review by 4lejandrito — APPROVED** [review]

**Comment by DaniSzimko** [comment]
ci:stop

**Comment by DaniSzimko** [comment]
ci:forward:force

**Pull request closed without merging**
