### PR TITLE
LPD-22778 Fix flakiness of the BatchEngineExportTaskExecutorTest.testExportBlogPostingsToJSONLFileWithFieldNames test

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPD-22778

---

The purpose of this ticket is to fix the flakiness of the `BatchEngineExportTaskExecutorTest.testExportBlogPostingsToJSONLFileWithFieldNames` test.

I have detected the flakiness comes from the usages of the service layer because we are filtering by some workflow statuses. However, as it is not needed, I have created this PR to stop using those filters and always returning all the Blog Postings, independently of the status (it is not relevant for this use case).

Furthermore, I have detected some assertions that were not being performed and some optimizations have been included too.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by matijapetanjek — APPROVED** [review]
Looks good to me!

**Comment by matijapetanjek** [comment]
I wanted to fix the failing [com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/377681/testReport/com.liferay.batch.engine.internal.writer/XLSBatchEngineExportTaskItemWriterImplTest) but I cannot reproduce the fails locally:

```
com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest STANDARD_OUT
    Loading jar:file:/Users/matijap/git/liferay/liferay-portal-master/.m2/com/liferay/portal/com.liferay.portal.impl/101.1.0-SNAPSHOT/com.liferay.portal.impl-101.1.0-SNAPSHOT.jar!/system.properties
    Loading jar:file:/Users/matijap/git/liferay/bundles/tomcat-9.0.87/webapps/ROOT/WEB-INF/shielded-container-lib/portal-impl.jar!/system.properties
    Loading jar:file:/Users/matijap/git/liferay/liferay-portal-master/.m2/com/liferay/portal/com.liferay.portal.impl/101.1.0-SNAPSHOT/com.liferay.portal.impl-101.1.0-SNAPSHOT.jar!/portal.properties

com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest > testWriteRowsWithDefinedFieldNames1 STARTED

com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest > testWriteRowsWithDefinedFieldNames1 PASSED

com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest > testWriteRowsWithDefinedFieldNames2 STARTED

com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest > testWriteRowsWithDefinedFieldNames2 PASSED

com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest > testWriteRowsWithDefinedFieldNames3 STARTED

com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest > testWriteRowsWithDefinedFieldNames3 PASSED

com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest > testWriteRowsWithDefinedFieldNames4 STARTED

com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest > testWriteRowsWithDefinedFieldNames4 PASSED

com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest > testWriteRowsWithEmptyFieldNames STARTED

com.liferay.batch.engine.internal.writer.XLSBatchEngineExportTaskItemWriterImplTest > testWriteRowsWithEmptyFieldNames PASSED


BUILD SUCCESSFUL in 18s
```
Forwarding PR.

**Comment by matijapetanjek** [comment]
ci:forward

**Pull request closed without merging**
