### PR TITLE
LPS-166739 Respect reverse proxy URL in REST actions

### PR DESCRIPTION
**Pull request by matijapetanjek**
The main question was how to have HttpServletRequest(or header info) in ActionUtil to build correct href values. 

1. Adding a new method in ActionUtil which accepts HttpServletRequest parameter would help but is not an option since it would require changes on rest builder method signatures. 
2. Serving custom UriInfo object created in a ContextContainerRequestFilter and configured with correct URL values didn't work because UriInfo relies on HttpServletRequest internally when determining URL, and only if HttpServletRequest is not present it uses our manually configured values. Removing HttpServletRequest from UriInfo caused issues in other parts of Vulcan infra 
3. This solution uses a ThreadLocal approach to store a relevant HttpServletRequest.

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hey @matijapetanjek, I've created https://github.com/liferay-headless/liferay-portal/pull/1008 which just overrides the uriinfo. The test you wrote is passing. Can you review and make sure I didn't break anything else? 

If you think is OK feel free to forward, I won't have time until Monday. Tomorrow I'm on PTO.

Thanks!

**Pull request closed without merging**
