### PR TITLE
LPS-193316 It's possible to download a file in Export when none of the entity field selected

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
Hey @matijapetanjek, 

I think the Export button should not be clickable if there are no selected fields. If we change the message at the top to say:
```
Info:Select at least one field to include in the exported file.
```
And only enable the button if there are fields selected, it will be a much better solution. 

What do you think?

**Comment by 4lejandrito** [comment]
> @4lejandrito As a "not-a-UX-expert" I can only agree :D, in that case I would apply the same behavior to the Import flow.
> 
> Btw I would still keep the toast and error message that will tell the user what is wrong (in import and export flow), what do you think?

If we disable the button, the user will not be able to click it so there is no chance to show the toast. So I would get rid of the toast. Just make sure the UI says that at least 1 field should be selected.

**Comment by ugeortiz** [comment]
Hello 👋🏼 and thanks for bring me to the conversation. 

It depends. The solution proposed by @4lejandrito is enough good. We could use the toast informing about a required action and also disabling the button until at least one field is selected. 

Another way to do it could be to leave the button enabled and alert the user with an alert when she or he is trying to export without selecting at least one field. Sometimes disabled buttons can create some kind of confusion due they are disabled, and some users couldn't notice it and press them without getting any result. 

In these cases, I always try to be more consistent with the others examples in portal as I can. There are other examples like Objects where they use disable buttons to do it. 


Hope this help ;)

**Comment by matijapetanjek** [comment]
@ugeortiz I completely agree with a disabled button for the import form in your screenshot.

That being said, this is an import form in Import/Export center
Screenshot from 2023-09-13 16-38-09
Aside from the fact that this screen is probably a UX nightmare :yum:, I strongly feel that error messages are helpful in order to correctly fill out the form, with just a disabled button I would be lost.

Here is the export form we're talking about.

Screenshot from 2023-09-13 16-54-07

 Admittedly, it is simpler than the import form but also similar in some ways. As a part of the same Import/Export "product" I wouldn't introduce different behavior on it and I believe it would do much more damage to introduce disabled button on the Import form than to keep an error message on the Export form. Or maybe I'm looking at this wrong and it's ok to have a disabled button on Export form and error messages on Import form?

I hope I managed to explain my reasonings clearly, let me know what you think or if there are further questions.

Also thank you for taking the time to help us on this!

**Comment by ugeortiz** [comment]
Hey @matijapetanjek, thanks for your input ;) 

Sometimes disabled buttons can't express too much the need of doing something. I was looking how we do in both export and import. In terms of accessibility it is very important to provide information about what do needs the user to complete a task. 

At 'import' we are showing an error alerting to the user about the need to map the fields. 

Screenshot 2023-09-15 at 11 33 20

Why don't do the same for 'export'? This could be an example 👇🏽 

https://github.com/liferay-headless/liferay-portal/assets/98747059/33635bb7-f81f-4741-ab01-ed4f82c6fe9f

In this case we will have consistency between both. Please let me know what do you think guys. 

Thanks in advance!

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:forward:force

**Pull request closed without merging**
