### PR TITLE
Lps 172437 Add more tests on expose erc for wikiPageAttachement

### PR DESCRIPTION
**Pull request by yanan**
**Background**
- Add more tests for story: expose ERC in WikiPageAttachment

**Test Plan**
- Given WikiPage with attachment created
  When requesting getWikiPageAttachment
  Then the attachment object contains externalReferenceCode
- Given WikiPage with attachment created
  When requesting getWikiPageWikiPageAttachmentsPage
  Then the attachment object contains externalReferenceCode | PASSED
- Given WikiPage with attachment created
  When requesting getSiteWikiPageByExternalReferenceCodeWikiPageExternalReferenceCodeWikiPageAttachmentByExternalReferenceCode
  Then the payload contains externalReferenceCode

**Jira Ticket**
- https://issues.liferay.com/browse/LPS-172437

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
Functional tests failures are unrelated.

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Review by Hijky — APPROVED** [review]

**Review by magjed4289 — COMMENTED** [review]
Looks good! :) The only thing I would change is removing the property portal.acceptance = "true"; as we only need to add the FP4 and FP5 to the acceptance suite.

**Comment by yanan** [comment]
ci:test:headless-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Comment by yanan** [comment]
Removed test cases with priority 3 from acceptance suite, tests failures are unrelated.

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
