### PR TITLE
LPS-127858 Deserialize Big Decimals in REST Builder

### PR DESCRIPTION
**Pull request by javierdearcos**

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:commerce

**Comment by javierdearcos** [comment]
I'm gonna forward the PR as all commerce tests are in green @riccardo-ferrari @marco-leo.

Feel free to stop it if you see any possible problem and I will check deeper

**Comment by javierdearcos** [comment]
ci:forward

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
