### PR TITLE
LPS-188315 Invoke the getPersistedModel method before invoking to the delete method of the LocalService to verify the baseModel exists before hand

### PR DESCRIPTION
**Pull request by ccorreagg**
The purpose of this PR is to avoid invoking the `delete` method of the Local Service if the element does not exist. That is causing some problems as printing error traces in the Liferay log when trying to delete already deleted elements from the Integration Tests.

For that, a previous invocation has been performed to the `getPersistedModel` method. If the persisted model exists (most of the cases), the persisted model will be deleted via `delete` method of the Local Service. Otherwise, an exception will be thrown, avoiding the invocation to the Service Layer.

The `catch` block will be in charge of managing the rest of the deletions as before (such as resource permissions, etc)

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Thanks @ccorreagg!

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
