### PR TITLE
COMMERCE-9949 DI - Batch Planner -  fix poshi test - use correct executor type

### PR DESCRIPTION
**Pull request by igorbeslic**

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:test:data-integration

**Comment by igorbeslic** [comment]
ci:test:data-integration

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:reevaluate:1377401_4872

**Comment by 4lejandrito** [comment]
@igorbeslic are those failures related?

**Comment by yanan** [comment]
Hello @igorbeslic , I've updated the functional tests and send a new pr here https://github.com/liferay-headless/liferay-portal/pull/738, (sorry for sending a new pr since I don't have permission to append commits in the current pr :smile: ) cc @4lejandrito

**Pull request closed without merging**
