### PR TITLE
LPS-197531 | master

### PR DESCRIPTION
**Pull request by JoyceWang08211**
https://liferay.atlassian.net/browse/LPS-197531

### CODE REVIEW

**Comment by JoyceWang08211** [comment]
ci:test:headless-functional:nocompile

**Comment by Hijky** [comment]
@JoyceWang08211 Could you include [these PR changes](https://github.com/liferay-headless/liferay-portal/pull/1745) and modify your current PR? thanks in advance!

**Comment by JoyceWang08211** [comment]
> @JoyceWang08211 Could you include [these PR changes](https://github.com/liferay-headless/liferay-portal/pull/1745) and modify your current PR? thanks in advance!

Thanks for the reminder. I will rebase the current PR after https://github.com/liferay-headless/liferay-portal/pull/1745 is merged.

**Comment by JoyceWang08211** [comment]
ci:test:headless-functional:nocompile

**Comment by JoyceWang08211** [comment]
ci:forward

**Pull request closed without merging**
