### PR TITLE
LPS-199836 API Builder should not be displayed in the Category Sample porlet

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Delete property `"com.liferay.portlet.display-category=category.sample"` to not show this porlet in the Content Sample as a Widget

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPS-199836

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:forward

**Comment by yanan** [comment]
ci:test:headless-builder-functional

**Comment by sergiojimcos** [comment]
ci:help

**Comment by sergiojimcos** [comment]
ci:test:headless-builder-functional

**Comment by yanan** [comment]
Failures are not related, ok to forward

**Comment by sergiojimcos** [comment]
ci:forward:force

**Comment by sergiojimcos** [comment]
Sent to Brian here: https://github.com/brianchandotcom/liferay-portal/pull/142692

**Pull request closed without merging**
