### PR TITLE
LPS-161983

### PR DESCRIPTION
**Pull request by rotty3000**

### CODE REVIEW

**Comment by rotty3000** [comment]
ci:test:sf

**Review by igorbeslic — APPROVED** [review]
All ok

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by ccorreagg** [comment]
What about this case:

batch1
├── batch-engine.json
└── foo.json
batch2
├── batch-engine.json* ERR: companyId < 0
└── foo.json


I think the "batch2" batch engine entry should not be generated in that case, but AFAIK, it seems to be generated as well. Maybe we should include the validations (companyId > 0, userId > 0, etc) should be also included when validating the batchEngineImportConfiguration in the `deploy` method

**Comment by ccorreagg** [comment]
I mean, if we include those validations to know if the zip file is deployable, we should filter those invalid deployable entries when trying to process them

**Comment by rotty3000** [comment]
sure that makes sense!

**Comment by rotty3000** [comment]
You should note however that the whole concept of embedded companyId and/or userId is flawed. One should never store those details with raw data since they may not make sense. CompanyId and userId should be sensitive at the moment they are imported only.

**Comment by rotty3000** [comment]
.. but I will grant that from the deploy directory you have a problem to pass such parameters but the deploy dir is also a flawed model in terms of supporting virtual instances from the start.

**Comment by igorbeslic** [comment]
@rotty3000 and @ccorreagg  companyId or userId must not be validated at all in batch engine deployer.
Some APIs (like ObjectDefinition) resolve companyId via given userId, and some APIs require only companyId. Forcing validation in deployer you may break some regular use cases.
With missing relevant companyId or userId particular module or even batch engine would notify with exception visible only in logs.
It is good to know that this deployment is reserved for professionals that understands details under-the-hood. Otherwise, there is Import/Export module that targets Dummy non-tech users where UI guides the through process.

**Pull request closed without merging**
