### PR TITLE
LPS-193109 - Hide related object fields from the field mapping UI

### PR DESCRIPTION
**Pull request by matijapetanjek**

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:stop

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by yanan** [comment]
There is one related baseline failure [compare run result](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2405917817&testrayRunIdA=2405535179&statusB=2), 
Added one more commit on baseline into the pr

**Comment by yanan** [comment]
ci:forward

**Comment by yanan** [comment]
Failures are not related from qa perspective,[ compare run results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2406460563&testrayRunIdA=2406808899&statusB=2)
- lpkg-controller-mysql57-jdk8/0/0 -> failed to publish JUnit test result report
- Failed prior to running test -> run again on some of the tests, and they passed
    - ObjectCustomLayouts#CanSelectExistingEntriesOnRelationshipTab
    - ListAPIApplicationSchemas#CanOrderSchemasByName
    - ObjectActions#CanTriggerStandaloneActionWithPermission

**Comment by 4lejandrito** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/139599.

**Comment by 4lejandrito** [comment]
Hey @matijapetanjek,

After deploying these changes and creating an object definition related to itself I still see the fields:

Screenshot from 2023-08-23 12-13-19

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
See my previous comment.

**Comment by 4lejandrito** [comment]
[@matijapetanjek I ahttps://github.com/liferay-headless/liferay-portal/pull/1482m closing this](https://github.com/liferay-headless/liferay-portal/pull/1482).

**Pull request closed without merging**
