### PR TITLE
LPD-37290 Access just the external reference code from the user to fix prevously failing test 

### PR DESCRIPTION
**Pull request by albertojml**
Test started failing since the [incorporation of new external reference codes in entities related to users](https://github.com/liferay/liferay-portal/compare/d548429213ad34626cdf90a0da189876dcfaa537...bf6b2caab2813f04907e10f9e0d36ce370b08595).

This PR purpose fixes the issue by making sure only the ERC from the user is used to create the put/patch requests.

See the following Jira ticket: [LPD-37290](https://liferay.atlassian.net/browse/LPD-37166)

### CODE REVIEW

**Comment by albertojml** [comment]
ci:help

**Comment by albertojml** [comment]
ci:test:headless-functional

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
Better to send it soon to have them in the next suite, we will have the opportunity to fix them in case we broke anything

**Pull request closed without merging**
