### PR TITLE
LPD-38638 Using the testCompany user and hostname for headless tests

### PR DESCRIPTION
**Pull request by 4lejandrito**
From https://github.com/liferay-headless/liferay-portal/pull/2314. https://liferay.atlassian.net/browse/LPD-38638.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
@4lejandrito It seems the failures are related

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:reevaluate:1347401_6895

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
