### PR TITLE
LPS-166172 Add query params to API Explorer for custom objects

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to expose (for the `GET` operations) the following query parameters:

- fields
- nestedFields
- restrictFields

in OpenAPI specification file of any Custom Object Definition.

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by sergiojimcos — APPROVED** [review]
LGTM!! :clap:

**Comment by Hijky** [comment]
The failures are not related to your PR, you can forward it manually.

**Review by 4lejandrito — APPROVED** [review]

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
