### PR TITLE
LPD-18347: Update tool tip text for unsupported types when exporting in CSV

### PR DESCRIPTION
**Pull request by sergiojimcos**
## Motivation
The idea of this PR is to update the `ClayTootipProvider` message when an user wants to export an Object Entry in CSV format.

**After PR**
Screenshot from 2024-02-21 13-51-08

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPD-18347

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
> @sergiojimcos @jaimelr10 Should we include/update a test?

Maybe a test where the locator is present?

**Comment by jaimelr10** [comment]
Hi @sergiojimcos @ccorreagg 
I don't see necessary to add a test here, the tooltip should be tested by clay.
Also, eventually we will support all the fields, so this will be removed :)

**Review by jaimelr10 — APPROVED** [review]
LGTM! :rocket:

**Comment by jaimelr10** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
One Poshi test fails and it is related. I will update it:
- [EnableOnlySupportedFieldTypesForCSVExportViaUI#CanSeeDisabledFieldsDetailsWithExportObjectCsv](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358084//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EnableOnlySupportedFieldTypesForCSVExportViaUI_CanSeeDisabledFieldsDetailsWithExportObjectCsv_)

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by ccorreagg** [comment]
> One Poshi test fails and it is related. I will update it:
> 
> * [EnableOnlySupportedFieldTypesForCSVExportViaUI#CanSeeDisabledFieldsDetailsWithExportObjectCsv](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/358084//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_EnableOnlySupportedFieldTypesForCSVExportViaUI_CanSeeDisabledFieldsDetailsWithExportObjectCsv_)

That supports my theory of adding the test ^^

**Comment by sergiojimcos** [comment]
After analyzing Testray results, I've seen that test are unrelated! Sending to Brian

**Comment by sergiojimcos** [comment]
Sent here: https://github.com/brianchandotcom/liferay-portal/pull/147459

**Pull request closed without merging**
