### PR TITLE
LPS-196412- API Builder relationship fields should be system

### PR DESCRIPTION
**Pull request by sergiojimcos**
Hi @G-Sa, this PR contains the changes in order to set ObjectRelationship field names to system. The commit added, retrieves all the object fields that could be system or custom.

**What is new?**
- Changes in ObjectEntryLocalService to retrieve all the object fields
- Set ObjectRelationships to system.

**Related JIRA Ticket**
[LPS-196412](https://liferay.atlassian.net/browse/LPS-196412)

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:objects

**Comment by sergiojimcos** [comment]
ci:test:object

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
