### PR TITLE
LPS-202023 Replace AUI() usages in push-notifications-web

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-202023)

## Motivation 
In Echo team we are replacing AUI() with js

I have not test this case, I have not been able to find how to test it in UI, but the changes are easy and it should work as before.

### CODE REVIEW

**Review by jaimelr10 — APPROVED** [review]
LGTM!

**Comment by jaimelr10** [comment]
ci:forward

**Comment by yanan** [comment]
Failures in relevant are not related, ok to forward :partying_face:

**Comment by jaimelr10** [comment]
ci:forward:force

**Pull request closed without merging**
