### PR TITLE
LPS-175235 "fields" query parameter does not work when it is executedover a System Object 

### PR DESCRIPTION
**Pull request by TaiPhamLR**
Motivation
=======

This work solves the problem reported in the ticket https://issues.liferay.com/browse/LPS-175235 .
Previous PR: https://github.com/liferay-core-infra/liferay-portal/pull/3547

Proposed Solution
========

- Cause:
   When we perform any request GET (by id) any objects are considered a System Object, the entry will be put into an ExtendedEntity instance (see [EntityExtensionWriterInterceptor#_extendEntity](https://github.com/liferay-core-infra/liferay-portal/blob/master/modules/apps/portal-vulcan/portal-vulcan-impl/src/main/java/com/liferay/portal/vulcan/internal/jaxrs/writer/interceptor/EntityExtensionWriterInterceptor.java#L55))
as field  `entity`. If we perform request Get with `filter` (ex: ?filter=externalReferenceCode), the VulcanPropertyFilter#serializeAsField would ignore `entity` property and cound not "see" `externalReferenceCode`
The result would be empty json: `{}`

- What we did to solve this problem:
At class EntityExtensionWriterInterceptor, we get Fields Query Param and Restrict Fields Query Param from the context and pass them to ExtendedEntity.
And we process them, then put field name and field value of the entity to `_extendedProperties`

Steps to Verify
========

- Perform the following request (replace the id 20124 with an existing one): 
`curl -X GET -u 'test@liferay.com:test' http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/20124`
- The response should be something like:
<details>
<summary>
Json string:
</summary>
<p>

```yaml
{
  "accountBriefs" : [ ],
  "actions" : {
    "get-user-account-by-external-reference-code" : {
      "method" : "GET",
      "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/by-external-reference-code/20124"
    },
    "put-user-account" : {
      "method" : "PUT",
      "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/20124"
    },
    "delete-user-account" : {
      "method" : "DELETE",
      "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/20124"
    },
    "get-user-account" : {
      "method" : "GET",
      "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/20124"
    },
    "delete-user-account-by-external-reference-code" : {
      "method" : "DELETE",
      "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/by-external-reference-code/20124"
    },
    "put-user-account-by-external-reference-code" : {
      "method" : "PUT",
      "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/by-external-reference-code/20124"
    },
    "get-my-user-account" : {
      "method" : "GET",
      "href" : "http://localhost:8080/o/headless-admin-user/v1.0/my-user-account"
    },
    "patch-user-account" : {
      "method" : "PATCH",
      "href" : "http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/20124"
    }
  },
  "additionalName" : "",
  "alternateName" : "test",
  "birthDate" : "1970-01-01T00:00:00Z",
  "customFields" : [ ],
  "dashboardURL" : "/user/test",
  "dateCreated" : "2023-02-08T10:01:13Z",
  "dateModified" : "2023-02-09T08:22:45Z",
  "emailAddress" : "test@liferay.com",
  "externalReferenceCode" : "8b8b59b0-0362-70e1-3b2d-98fd3454ed84",
  "familyName" : "Test",
  "givenName" : "Test",
  "id" : 20124,
  "jobTitle" : "",
  "keywords" : [ ],
  "lastLoginDate" : "2023-02-08T16:08:12Z",
  "name" : "Test Test",
  "organizationBriefs" : [ ],
  "profileURL" : "/web/test",
  "roleBriefs" : [ {
    "id" : 20102,
    "name" : "Administrator"
  }, {
    "id" : 20106,
    "name" : "Power User"
  }, {
    "id" : 20108,
    "name" : "User"
  } ],
  "siteBriefs" : [ {
    "descriptiveName" : "Global",
    "id" : 20122,
    "name" : "Global"
  }, {
    "descriptiveName" : "Liferay DXP",
    "id" : 20120,
    "name" : "Guest"
  } ],
  "userAccountContactInformation" : {
    "emailAddresses" : [ ],
    "facebook" : "",
    "jabber" : "",
    "postalAddresses" : [ ],
    "skype" : "",
    "sms" : "",
    "telephones" : [ ],
    "twitter" : "",
    "webUrls" : [ ]
  },
  "userGroupBriefs" : [ ]
}
```

</p>
</details>

- Perform the following request including the `fields` query parameter with an existing field:
`curl -X GET -u 'test@liferay.com:test' http://localhost:8080/o/headless-admin-user/v1.0/user-accounts/20124?fields=externalReferenceCode`

** Expected behaviour:
- The response should contain only the `externalReferenceCode` field:
`{
  "externalReferenceCode" : "8b8b59b0-0362-70e1-3b2d-98fd3454ed84"
}`

** Current behaviour:

- The response is an empty JSON:
`{ }`

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
Hi @TaiPhamLR 
Sorry for the late response. We will take a look at this PR. Thanks for sharing it with us 🙂 

/cc @ccorreagg Pinging you as you have context on this

**Review by LuismiBarcos — COMMENTED** [review]
Hi @TaiPhamLR 
The solution proposed was really good and you discover the problem.

Thanks to that, made me think about the origin of the problem I could find a less invasive solution that we didn't see at the beginning. 

So thank you for the PR because helped us to found a solution.

The PR with the solution is this one https://github.com/liferay-headless/liferay-portal/pull/1094

_NOTE: I couldn't mark you as a co-author of the commit because I didn't find your email. If you want to be part of the commit, let me know._

**Comment by LuismiBarcos** [comment]
Follow-up PR: https://github.com/liferay-headless/liferay-portal/pull/1094

**Comment by TaiPhamLR** [comment]
Thanks for your review and sharing @LuismiBarcos. 
 _"I couldn't mark you as a co-author of the commit because I didn't find your email. If you want to be part of the commit, let me know"_ - Not a problem. The simple solution is the best thing for us. :clap:
Regards,
Tai.

**Pull request closed without merging**
