### PR TITLE
LPS-130901 Add externalReferenceCode infrastructure to WikiPage

### PR DESCRIPTION
**Pull request by LuismiBarcos**

### CODE REVIEW

**Review by nhpatt — COMMENTED** [review]
you have 2 commits with the same message :) the last one looks like it should be tests something

**Review by javierdearcos — APPROVED** [review]

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
Sent here https://github.com/liferay-headless/liferay-portal/pull/696

**Pull request closed without merging**
