### PR TITLE
LPD-23771 NotificationQueueEntry recipients of Rest Client is parsing recipients wrong

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-23771

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
Test failures are not related with the PR ✅

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
Rebased with master and squashed the REST Builder changes. For any reason, the changes are not being generated in the Meg's computer. We are analyzing the reason

**Comment by ccorreagg** [comment]
ci:test:stop

**Comment by ccorreagg** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
@magjed4289 When the tests finish, we need to get rid of that commit:

image

As the code is autogenerated. We should not have commits in autogenerated classes

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:close

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:stop

**Comment by magjed4289** [comment]
ci:close

**Comment by magjed4289** [comment]
ci:reopen

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
It seems the errors could be caused by the CI and not related, but I will relaunch again the revelant suite

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
This test https://testray.liferay.com/home/-/testray/case_results/2571641493 could be related, as it has failed three times and all of them seem to belong to this pull request. Let's see what happens with this new execution

**Comment by ccorreagg** [comment]
Rebased with master

**Comment by ccorreagg** [comment]
The tests pass locally:

```
> Task :apps:portal-search:portal-search-admin-web-test:testIntegration

com.liferay.portal.search.admin.web.internal.portlet.action.test.EditMVCActionCommandTest STANDARD_OUT
    Loading jar:file:/home/carlos/Liferay/Proyecto/bundles/tomcat-9.0.87/webapps/ROOT/WEB-INF/shielded-container-lib/portal-impl.jar!/system.properties

com.liferay.portal.search.admin.web.internal.portlet.action.test.EditMVCActionCommandTest > testPermissionToReindexAsCompanyAdmin STARTED

com.liferay.portal.search.admin.web.internal.portlet.action.test.EditMVCActionCommandTest > testPermissionToReindexAsCompanyAdmin PASSED

com.liferay.portal.search.admin.web.internal.portlet.action.test.EditMVCActionCommandTest > testPermissionToReindexAsOmniadmin STARTED

com.liferay.portal.search.admin.web.internal.portlet.action.test.EditMVCActionCommandTest > testPermissionToReindexAsOmniadmin PASSED

com.liferay.portal.search.admin.web.internal.portlet.action.test.EditMVCActionCommandTest > testPermissionToReindexAsUser STARTED

com.liferay.portal.search.admin.web.internal.portlet.action.test.EditMVCActionCommandTest > testPermissionToReindexAsUser PASSED

com.liferay.portal.search.admin.web.internal.portlet.action.test.EditMVCActionCommandTest > testPermissionToReindexMultipleCompaniesAsCompanyAdmin STARTED

com.liferay.portal.search.admin.web.internal.portlet.action.test.EditMVCActionCommandTest > testPermissionToReindexMultipleCompaniesAsCompanyAdmin PASSED

com.liferay.portal.search.admin.web.internal.portlet.action.test.EditMVCActionCommandTest > testPermissionToReindexMultipleCompaniesAsOmniadmin STARTED

com.liferay.portal.search.admin.web.internal.portlet.action.test.EditMVCActionCommandTest > testPermissionToReindexMultipleCompaniesAsOmniadmin PASSED

> Task :apps:portal-search:portal-search-admin-web-test:stopTestableTomcat

```

**Comment by ccorreagg** [comment]
ci:forward

**Comment by magjed4289** [comment]
running a uniquely looking test failure [here](https://test-1-1.liferay.com/job/root-cause-analysis-tool/13935/)

**Comment by magjed4289** [comment]
Test class **/search/admin/**/EditMVCActionCommandTest passes on the [rerun](https://test-1-2.liferay.com/job/root-cause-analysis-tool-batch/919/)
image

**Comment by ccorreagg** [comment]
ci:forward:force

**Review by ccorreagg — APPROVED** [review]

**Pull request closed without merging**
