### PR TITLE
LPD-31813 Add the ERC to the Creator data returned from REST calls for Custom Objects

### PR DESCRIPTION
**Pull request by DaniSzimko**
https://liferay.atlassian.net/browse/LPD-31813

### CODE REVIEW

**Comment by DaniSzimko** [comment]
ci:test:sf

**Comment by DaniSzimko** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:forward:force

**Pull request closed without merging**
