### PR TITLE
LPD-15576 Additional commits to remove the unnecessary getBatchEngineImportTaskErrors() method

### PR DESCRIPTION
**Pull request by vendeltoreki**
Changes based on Brian's comment: https://github.com/brianchandotcom/liferay-portal/pull/147245#issuecomment-1952938206

We can query the list of errors this way: https://github.com/liferay-headless/liferay-portal/commit/63bea1b509ff2cc2bfc6c05d517d0e622eb6751e , see [example](https://github.com/liferay/liferay-portal/blob/7202f9fc4d80c3ee4a008b9d0d61f7764f80431e/modules/apps/headless/headless-batch-engine/headless-batch-engine-impl/src/main/java/com/liferay/headless/batch/engine/internal/resource/v1_0/ImportTaskResourceImpl.java#L530) in the same class. Also, `BatchEngineImportTaskErrorService` is not created yet and it would have to replicate the same permission checks, invoking `batchEngineImportTaskService.getBatchEngineImportTask(..)` anyways to check for the owner.

cc: @4lejandrito

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by vendeltoreki** [comment]
None of these tests are filing locally, seems safe to forward.

com.liferay.batch.engine.internal.test.BatchEngineExportTaskExecutorTest
 - testExportBlogPostingsToJSONFileWithFieldNames
com.liferay.batch.engine.internal.test.BatchEngineImportTaskExecutorTest
 - testUpdateBlogPostingsFromJSONLFile
com.liferay.headless.batch.engine.resource.v1_0.test.ExportTaskResourceTest -- already fails
 - testPostExportTask

**Comment by vendeltoreki** [comment]
ci:forward:force

**Comment by vendeltoreki** [comment]
ci:forward:force

**Pull request closed without merging**
