### PR TITLE
LPD 44180 | Localized Document URLs in Fragment Editables Are Not Transformed When Publishing from Staging to Live

### PR DESCRIPTION
**Pull request by dannielraposo**
See the following Jira ticket: [LPD-44180](https://liferay.atlassian.net/browse/LPD-44180)

### CODE REVIEW

**Comment by dannielraposo** [comment]
ci:test:relevant

**Comment by dannielraposo** [comment]
ci:test:relevant

**Comment by DaniSzimko** [comment]
ci:test:headless-functional

**Comment by dannielraposo** [comment]
ci:test:headless-functional

**Comment by dannielraposo** [comment]
test failures are not related, see [here](https://testray.liferay.com/#/compare-runs/92268492/91694705/details?filter=%7B%22testrayCaseResultStatus1%22%3A%5B%22PASSED%22%5D%2C%22testrayCaseResultStatus2%22%3A%5B%22FAILED%22%5D%7D&filterSchema=compareRunsCases)

**Comment by dannielraposo** [comment]
ci:forward

**Comment by dannielraposo** [comment]
ci:reopen

**Pull request closed without merging**
