### PR TITLE
LPS-195045 Fix the Import CSV Template returned for Custom Objects

### PR DESCRIPTION
**Pull request by ccorreagg**
Related bug: https://liferay.atlassian.net/browse/LPS-195045

---

The purpose of this PR is to fix the CSV template file returned by the `/plans/{internalClassName}/template` endpoint for Custom Objects.

---

**How to test it:**

Create a Custom Object Definition:

```
curl -X "POST" "http://localhost:8080/o/object-admin/v1.0/object-definitions" \
     -H 'Content-Type: application/json' \
     -u 'test@liferay.com:test' \
     -d $'{
  "active": true,
  "status": {
    "code": 0
  },
  "objectFields": [
    {
      "DBType": "String",
      "indexed": true,
      "indexedLanguageId": "",
      "externalReferenceCode": "university-name",
      "listTypeDefinitionId": 0,
      "label": {
        "en_US": "University name"
      },
      "type": "String",
      "required": true,
      "name": "universityName",
      "indexedAsKeyword": false
    }
  ],
  "pluralLabel": {
    "en-US": "Universities"
  },
  "portlet": true,
  "scope": "company",
  "label": {
    "en-US": "University"
  },
  "externalReferenceCode": "University",
  "name": "University"
}'
```

Perform the following request:

```
curl -X "GET" "http://localhost:8080/o/batch-planner/v1.0/plans/com.liferay.object.rest.dto.v1_0.ObjectEntry%23C_University/template" \
     -u 'test@liferay.com:test'
```

**Before this PR:**

The response is empty:

```

```

**After this PR:**

The response contains an example in CSV format containing an example:

```
universityName,keywords,externalReferenceCode,taxonomyCategoryIds
string,array,string,array
```

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Rebased with master and the test has been fixed

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by matijapetanjek — APPROVED** [review]
LGTM!!

**Comment by ccorreagg** [comment]
ci:forward

**Comment by ccorreagg** [comment]
ci:forward

**Comment by yanan** [comment]
Failures are not related :champagne:

**Comment by ccorreagg** [comment]
Forwarded manually here: https://github.com/brianchandotcom/liferay-portal/pull/140456

**Pull request closed without merging**
