### PR TITLE
LPD-23089 Bumping to graphql-java@17.6 to address security issue concerning guava

### PR DESCRIPTION
**Pull request by GaborKomaromi**
https://liferay.atlassian.net/browse/LPD-23089

### CODE REVIEW

**Comment by GaborKomaromi** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
@GaborKomaromi that bump seems a breaking change. Have you verified it compiles and works fine with a sample graphql query?

**Comment by GaborKomaromi** [comment]
@4lejandrito it compiled, but I have not tested it with the graphql example. Getting back to you with its results soon.

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
The bump to the next minor version is not solving the security issue, as the guava version is the same:

#Generated by org.apache.felix.bundleplugin
#Fri Oct 16 16:40:25 EDT 2020
groupId=com.google.guava
artifactId=guava
version=30.0-jre

**Comment by ccorreagg** [comment]
image

**Review by ccorreagg — CHANGES_REQUESTED** [review]
The 17.6 version seems not to be enough to solve the vulnerability

**Pull request closed without merging**
