### PR TITLE
Lps 139343 master

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-139343

This pull changes PortalInstanceResourceImpl to no longer use CompanyLocalService and instead use CompanyService for permission checking.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Review by javierdearcos — APPROVED** [review]
Great. Thank you for your contribution.

As you did, the rest layer always has to use the Services to check permissions. The only exception is if you are completely sure that the permission check would be redundant because it was checked before.

Forwarding

**Comment by javierdearcos** [comment]
Just for future PRs. The Headless team is now part of the Frontend Infrastructure team, so this user and repo are "deprecated". We are using the @liferay-frontend user and repo to review and accept PRs.

We will work to make clearer this fact.

**Comment by javierdearcos** [comment]
ci:forward

**Comment by SamZiemer** [comment]
Thanks @javierdearcos I will make note to send any future headless pulls to the frontend team.

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
Thanks to you 🙂 

Let's make another try with the CI and if it is not successful I will rebase and send it from the @liferay-frontend repo and put you in copy

**Comment by javierdearcos** [comment]
I will rebase it and send it to liferay-frontend to fix semver and try again. Put you in copy so you are aware of the progress

**Comment by javierdearcos** [comment]
Sending from https://github.com/liferay-frontend/liferay-portal/pull/1743

**Pull request closed without merging**
