### PR TITLE
LPS-170415 Add integration test for filter parent custom entities with data from the related elements

### PR DESCRIPTION
**Pull request by LuismiBarcos**
Related ticket [LPS-170415](https://issues.liferay.com/browse/LPS-170415)
____
In this PR, I include many tests to cover the filtering by related elements.

The custom objects have a particular condition when saving the data. They store it in two different tables depending if the custom object was or was not published. For example, if a custom object is already published and updated with a new object field. The information of that field will be stored in a different table of the fields created before the publication of the custom object.

This condition also affects the relationships information. 

So, the tests created try to cover all the possibilities and ensure that the filtering is working when filtering by one of the operations supported.

### How to test it
Just execute the tests of the class `ObjectEntryResourceTest`

The business code is in master.

### CODE REVIEW

**Comment by LuismiBarcos** [comment]
ci:test:sf

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by LuismiBarcos** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
@LuismiBarcos will resend soon.

**Pull request closed without merging**
