### PR TITLE
LPS-186732: Manage "previous relationship" in related elements on PUT method

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Manage previous related elements in the Many-to-One relationships between Custom Object Definition with System Object Defintion.
- Delete `@Ignore` annotation and update test cases.

**How to deploy it?**
- Deploy `object-rest-api` and `object-rest-impl`

**JIRA Related Ticket**
https://liferay.atlassian.net/browse/LPS-186732

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by Hijky** [comment]
The failures are not related to your PR, there are [the compared results.](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1687765011855&testrayRunIdA=2358541169&testrayRunIdB=2360743895)

**Comment by sergiojimcos** [comment]
ci:forward:foce

**Comment by sergiojimcos** [comment]
ci:forward:force

**Pull request closed without merging**
