### PR TITLE
Lrqa 77318 | Update functional tests to use & only in curl command to combine multiple parameters

### PR DESCRIPTION
**Pull request by yanan**
**Background:**
- Update to make functional tests work. And I think the root cause might be [LPS-162331](https://issues.liferay.com/browse/LPS-162331) Convert method references to field references in Elasticsearch impl, we can't combine two parameters with `/&`, only `&` works. For example  curl...?filter=xxx&sort=xxx, 

**Test Plan:**
- Test fix in StructuredContentFilteringAndSorting.testcase
- Test fix in HeadlessDeliveryBatchMode.testcase

**Ticket:**
- https://issues.liferay.com/browse/LRQA-77318
- https://issues.liferay.com/browse/LRQA-77319

### CODE REVIEW

**Comment by yanan** [comment]
ci:test:headless-frontend-functional:nocompile

**Comment by yanan** [comment]
ci:test:sf

**Comment by yanan** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
@yanan can you please check [this thread](https://liferay.slack.com/archives/CD7939WBE/p1656574819888569) and see if your solution is compatible?

**Comment by yanan** [comment]
Hi @magjed4289 , thanks for the infos. The related headless tests failed on the CI server using CentOS, and I've run the failed tests locally on Ubuntu, `/&` is no longer working.
I tried to run an RCA since `/&` is working before, here is the [rca result](https://test-1-1.liferay.com/userContent/jobs/root-cause-analysis-tool/builds/7186/jenkins-report.html), not very sure if this is correct root cause :smile:
After CI runs in this pr, the tests in StructuredContentFilteringAndSorting.testcase and HeadlessDeliveryBatchMode.testcase are no longer failed.

**Comment by magjed4289** [comment]
> Hi @magjed4289 , thanks for the infos. The related headless tests failed on the CI server using CentOS, and I've run the failed tests locally on Ubuntu, `/&` is no longer working. I tried to run an RCA since `/&` is working before, here is the [rca result](https://test-1-1.liferay.com/userContent/jobs/root-cause-analysis-tool/builds/7186/jenkins-report.html), not very sure if this is correct root cause 😄 After CI runs in this pr, the tests in StructuredContentFilteringAndSorting.testcase and HeadlessDeliveryBatchMode.testcase are no longer failed.

What about `\&` - is it the same as `/&`? 🤔 Have this stopped working either?

**Comment by yanan** [comment]
Hi @magjed4289 , the `/&` returns a {"status" : "BAD_REQUEST"} since `/` is meanful in curl I think. I will try on Windows later tonight, but not able to try on Macos for now.
image

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by magjed4289** [comment]
checked on Mac, looks like it works okay! :)

**Review by magjed4289 — APPROVED** [review]

**Comment by yanan** [comment]
Thank you for the confirmation! Same situation on windows, `&` is working. I'll go forward :smile:

**Comment by yanan** [comment]
ci:forward

**Pull request closed without merging**
