### PR TITLE
[TS] [Urgent] LPS-188390 Support nested arrays in Liferay REST Builder

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://github.com/liferay-headless/liferay-portal/pull/1311

Hey @mbowerman I added a test please review it matches what you want. If it does, you can do ci:forward.

Thanks!

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Failures seem related...

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Errors fixed. @mbowerman see https://github.com/liferay-headless/liferay-portal/pull/1318/commits/1d972561b83cb96ae9a03a6c2ad6f2296c43eddd.

**Comment by mbowerman** [comment]
Thanks @4lejandrito this looks good! I will ci:forward when the ci testing completes.

**Comment by mbowerman** [comment]
ci:forward

**Comment by mbowerman** [comment]
ci:forward:force

**Pull request closed without merging**
