### PR TITLE
LPS-121087 Disable rating buttons to guest users

### PR DESCRIPTION
**Pull request by LuismiBarcos**

### CODE REVIEW

**Review by javierdearcos — APPROVED** [review]

**Comment by javierdearcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:stop

**Review by javierdearcos — APPROVED** [review]

**Comment by javierdearcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
ci:forward

**Comment by LuismiBarcos** [comment]
Sent here #417

**Pull request closed without merging**
