### PR TITLE
LPD-45155 Technical Task | [test-fix] OpenAPI: new property fileSourceURL in "FileEntry" schema

### PR DESCRIPTION
**Pull request by magjed4289**
https://issues.liferay.com/browse/LPD-45155

Root cause: https://liferay.atlassian.net/browse/LPD-40575

### CODE REVIEW

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
tests are passing correctly now ✅

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
