### PR TITLE
LPS-179806 Rest builder generates non-existent resource methods

### PR DESCRIPTION
**Pull request by matijapetanjek**
Jira link: https://issues.liferay.com/browse/LPS-179806

### CODE REVIEW

**Comment by matijapetanjek** [comment]
ci:test:sf

**Comment by matijapetanjek** [comment]
ci:test:relevant

**Review by LuismiBarcos — APPROVED** [review]
LGTM :) 👏 👏 👏 

Although, I miss a buildREST-generating commit. AFAIK, each time we make changes on the rest builder, we should run the rest builder on the Liferay APIs to ensure that we have the latest version (and to ensure that we are not breaking anything 😁 )

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
ci:forward

**Comment by matijapetanjek** [comment]
You're right, this way we can only test that the PUT method returns the updated entity. I'm not sure how can we fetch the data from the database if there is no GET method available in the resource? Make a convention every endpoint must have GET method? Ask Commerce team to re-implement their patch methods to actually do partial update, instead of redirecting patch to put implementation, in which case [this PR would be obsolete](https://github.com/liferay-commerce/liferay-portal/pull/3520)? Not to mention their tests are under Ignore annotation and fail if you remove it, this approach seemed the least painful in order to unblock them and make the code compilable.

**Comment by ccorreagg** [comment]
> You're right, this way we can only test that the PUT method returns the updated entity. I'm not sure how can we fetch the data from the database if there is no GET method available in the resource? Make a convention every endpoint must have GET method? Ask Commerce team to re-implement their patch methods to actually do partial update, instead of redirecting patch to put implementation, in which case [this PR would be obsolete](https://github.com/liferay-commerce/liferay-portal/pull/3520)? Not to mention their tests are under Ignore annotation and fail if you remove it, this approach seemed the least painful in order to unblock them and make the code compilable.

Well, I don't know if we should set that the GET method must be mandatory as a convention. I don't know what you think about that @4lejandrito 

Maybe generating a default method returning an exception would be a good approach as we are already following that pattern when it is not possible to find something.

In this case, it would be something like:

```
test${javaMethodSignature.methodName?cap_first}_${javaMethodSignature.methodName?replace("put", "get")}
```

**Comment by matijapetanjek** [comment]
OK I'll generate the stub method with Unsupported operation exception, it will be the fastest update.

**Comment by 4lejandrito** [comment]
I agree with @ccorreagg. That's the cleanest way.

**Comment by ccorreagg** [comment]
Hey @matijapetanjek ,

I have created this draft: https://github.com/liferay-headless/liferay-portal/pull/1139

I have included an extra commit with a use case that is failing for the changes of this PR.

Please have a look at it because we probably need to include more changes

**Review by ccorreagg — CHANGES_REQUESTED** [review]
We need to include more changes as there are more generated code in the test when the ExternalReferenceCode is involved

**Comment by ccorreagg** [comment]
See this: https://github.com/liferay-headless/liferay-portal/pull/1141

**Pull request closed without merging**
