### PR TITLE
LPD-40828 | Hide object relationship on API builder schema editor

### PR DESCRIPTION
**Pull request by jaimelr10**
**Desciption:** We are creating a whitelist with properties that are supported on the API Builder schema editor according to their bussines types.
image

**Jira Ticket:** https://liferay.atlassian.net/browse/LPD-40828

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:help

**Comment by ccorreagg** [comment]
ci:test:api-builder

**Comment by jaimelr10** [comment]
ci:test:sf

**Comment by jaimelr10** [comment]
ci:test:sf

**Comment by jaimelr10** [comment]
ci:test:api-builder

**Comment by jaimelr10** [comment]
Hey @ccorreagg! If the test passes I'm ok with forwarding it!

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
