### PR TITLE
LPD-32158 Make PUT permissions endpoint override existing permissions

### PR DESCRIPTION
**Pull request by 4lejandrito**
From: https://github.com/liferay-headless/liferay-portal/pull/2188.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Thank you @4lejandrito for reviewing and improving it! :smile:

**Comment by marcelabc** [comment]
ci:test:sf

**Comment by marcelabc** [comment]
ci:test:relevant

**Comment by marcelabc** [comment]
Hey @4lejandrito @ccorreagg
Can we forward this PR? :smile:

**Comment by 4lejandrito** [comment]
@marcelabc we want to perform further review. We were too busy this week. We’ll do it on Monday.

**Comment by ccorreagg** [comment]
Hey @marcelabc ,

I am reviewing the PR but I don't understand why we are overriding the whole `putObjectEntryPermissionsPage` method. Does it mean the endpoint prior this PR is not working as expected?. I am asking in order to understand the whole Object's solution for permissions

**Comment by ccorreagg** [comment]
BTW, force-pushed in order to solve the conflicts with master's branch (just a bnd.bnd version file)

**Comment by p-albuquerque** [comment]
@ccorreagg The endpoint prior this PR is not working as expected in the [AC3](https://liferay.atlassian.net/browse/LPD-31946) scenario.

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
Test failures are not related to the PR. ✅

**Review by vendeltoreki — APPROVED** [review]

**Comment by vendeltoreki** [comment]
ci:forward:force

**Pull request closed without merging**
