### PR TITLE
LPD-43570 Declaring the right dependencies

### PR DESCRIPTION
**Pull request by 4lejandrito**
https://liferay.atlassian.net/browse/LPD-43569

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by dannielraposo** [comment]
ci:test:stable

**Comment by dannielraposo** [comment]
ci:test:stable

**Comment by dannielraposo** [comment]
ci:test:stable

**Comment by dannielraposo** [comment]
ci:stop

**Comment by dannielraposo** [comment]
ci:test:stable

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:test:sf

**Comment by dannielraposo** [comment]
ci:test:stable

**Comment by dannielraposo** [comment]
ci:test:relevant

**Comment by dannielraposo** [comment]
@4lejandrito can you check the relevant test failures? I don´t know about the [modules-semantic-versioning](https://testray.liferay.com/#/project/35392/routines/45357/build/87970308/case-result/87998380).
Locally it builds well.

**Comment by dannielraposo** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
@dannielraposo the semantic versioning issue is not related. We did not change object-api in this PR.

**Review by dannielraposo — APPROVED** [review]
Based on [this run](https://github.com/liferay-headless/liferay-portal/pull/2379#issuecomment-2529937527) I think we can forward it

**Comment by dannielraposo** [comment]
ci:test:relevant

**Comment by dannielraposo** [comment]
Forwarding this PR. The issue arises because the CI is using JDK 8 for the rest-builder task, while the openapi-generator requires JDK 11 or higher. This issue was introduced with [this PR](https://github.com/brianchandotcom/liferay-portal/pull/156416), but it wasn’t noticed earlier because that PR didn’t fail. The logs show that the openapi-generator wasn’t executed due to the JDK version. We are currently working with the responsible team to ensure the rest-builder task uses JDK 11 or higher.

**Comment by dannielraposo** [comment]
ci:forward:force

**Pull request closed without merging**
