### PR TITLE
LPS-184728 Register the companyId for the Object's VulcanBatchEngineItemDelegate implementation (ObjectEntryResource) when creating/activating a new Object Definition

### PR DESCRIPTION
**Pull request by ccorreagg**
Followed-up PR from: https://github.com/liferay-headless/liferay-portal/pull/1264

Ticket: [LPS-184728](https://issues.liferay.com/browse/LPS-184728).

The purpose of this PR is to register the `companyId` of the implementations of the `VulcanBatchEngineItemDelegate` interface in Objects.

Apart from that, the interface `VulcanBatchEngineTaskItemDelegateRegistry` and its implementation `VulcanBatchEngineTaskItemDelegateRegistryImpl` has been updated to include the `companyId` for each method. The classes that were using those methods have been updated to provide the companyId in the request too

cc/ @mbowerman

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by matijapetanjek — APPROVED** [review]
LGTM :D

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by magjed4289** [comment]
test failures are not related, OK to manually forward ✅

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
