### PR TITLE
LPS-195543: Manage unrelated API Properties that are going to be patched from an API Schema

### PR DESCRIPTION
**Pull request by sergiojimcos**
Workaround of this [issue](https://liferay.atlassian.net/browse/LPS-195543)

### CODE REVIEW

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:objects

**Comment by sergiojimcos** [comment]
ci:test:object

**Comment by ccorreagg** [comment]
Closed as we found another solution. See https://github.com/liferay-headless/liferay-portal/pull/1532

**Pull request closed without merging**
