### PR TITLE
LPS-125480 We have already an exception mapper for tags, but in a different application. So copy it over and adapt it for our application

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@javierdearcos, @nhpatt

**Comment by jkappler** [comment]
ci:test:relevant

**Review by javierdearcos — APPROVED** [review]

**Comment by nhpatt** [comment]
LGTM :)

**Comment by nhpatt** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
