### PR TITLE
LPS-168808 Information Template ERROR in the Edition Mode

### PR DESCRIPTION
**Pull request by 4lejandrito**
Read the commit messages. With these changes we avoid using the original request cookies.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
@magjed4289 can you test this before it gets forwarded just in case you find other issues?

**Comment by magjed4289** [comment]
Just started reviewing :)

**Comment by magjed4289** [comment]
ci:forward

**Pull request closed without merging**
