### PR TITLE
LPS-202102 Throw an IllegalArgumentException if the base64 encoding sent via REST API is invalid

### PR DESCRIPTION
**Pull request by ccorreagg**
Related ticket: https://liferay.atlassian.net/browse/LPS-202102

---

The purpose of this PR is to throw an exception that is mapped into a Bad Request error code in the REST API. For that, all the exception thrown is caught when decoding the base64 encoding and if any error happened, an IllegalArgumentException is thrown.

How to reproduce it:

Follow the steps of the ticket

NOTE: A test will be added in a followed-up PR

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:test:relevant

**Review by sergiojimcos — APPROVED** [review]
LGTM!!

**Comment by magjed4289** [comment]
Test failures are not related to the PR. OK to manually forward. ✅

**Comment by ccorreagg** [comment]
ci:forward:force

**Pull request closed without merging**
