### PR TITLE
LPS-124237 Retrieve the parameters from uriInfo and replace the template values where we can

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@javierdearcos

**Review by javierdearcos — APPROVED** [review]
👏 👏 👏 

The first of many! 😉

**Comment by javierdearcos** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
