### PR TITLE
LPS-165428 asset library folder issue

### PR DESCRIPTION
**Pull request by igorbeslic**
See https://issues.liferay.com/browse/LPS-165428
If caller wants to organize structured content into folder, structuredContentFolderId given by API data is ignored and content is being placed always in parent folder.
This PR fixes affected calls (PUT/POST) and content is being correctly organized to desired folder

### CODE REVIEW

**Comment by igorbeslic** [comment]
ci:test:sf

**Comment by igorbeslic** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Review by sergiojimcos — COMMENTED** [review]
LGTM!! :clap: :clap: :clap:

**Pull request closed without merging**
