### PR TITLE
LPD-38287 Fix tearDown

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR fixes partially some of the tests that fails from this PR: https://github.com/brianchandotcom/liferay-portal/pull/155601

### CODE REVIEW

**Comment by ccorreagg** [comment]
ci:help

**Comment by ccorreagg** [comment]
ci:test:playwright

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
ci:stop

**Comment by ccorreagg** [comment]
ci:test:playwright

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:playwright

**Comment by ccorreagg** [comment]
Most of the playwright tests have failed because of timeouts. We are relaunching the tests again and see the results

**Comment by ccorreagg** [comment]
ci:forward

**Pull request closed without merging**
