### PR TITLE
LPS-195115 Don't throw exception if exportImportPortletPreferencesProcessor is null

### PR DESCRIPTION
**Pull request by ZakiMiklos**
https://liferay.atlassian.net/browse/LPS-195115

### CODE REVIEW

**Comment by ZakiMiklos** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Hi @ZakiMiklos!

* is it possible to write a test for this? (either unit, integration or functional). 
* can you improve the title of the PR with a more meaningful description (null check)?

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
See my latest comment.

**Comment by ZakiMiklos** [comment]
Hi @4lejandrito 

-Not sure if it is possible since it not causes a staging problem just a console message. The process goes as intented
- Yes updated the title

**Review by 4lejandrito — APPROVED** [review]
Ok it seems good to go then.

**Comment by 4lejandrito** [comment]
ci:forward:force

**Comment by 4lejandrito** [comment]
ci:reevaluate:1317401_10302

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward:force

**Pull request closed without merging**
